'use client';

import { Suspense, useCallback, useEffect, useMemo, useState } from 'react';
import Image from 'next/image';
import { useRouter, useSearchParams } from 'next/navigation';
import { ArrowLeft, Printer } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';
import { useLanguage } from '@/hooks/useLanguage';
import { formatMoney } from '@/lib/formatMoney';

type Lang = 'ar' | 'en' | 'fr';

type Project = {
  id: string;
  name: string;
  category: string | null;
  status: string | null;
  target_amount: number | null;
  collected_amount: number | null;
  currency: string | null;
  start_date: string | null;
  end_date: string | null;
  organization_name: string | null;
  notes: string | null;
};

type Donation = {
  id: string;
  project_id: string | null;
  project_name?: string;
  amount: number | null;
  currency: string | null;
  donation_date: string | null;
  donation_type: string | null;
  notes: string | null;
  created_at: string | null;
};

type ZakatAsset = {
  id: string;
  asset_name: string;
  asset_type: string | null;
  amount: number | null;
  currency: string | null;
  ownership_date: string | null;
  zakat_due_date: string | null;
  is_zakatable: boolean | null;
};

type Commitment = {
  id: string;
  name: string;
  amount: number | null;
  currency: string | null;
  frequency: string | null;
  next_due_date: string | null;
  category: string | null;
  status: string | null;
};

type Beneficiary = {
  id: string;
  category: string | null;
  status: string | null;
  monthly_support_amount: number | null;
};

type ImpactMetric = {
  id: string;
  project_id: string;
  metric_name: string;
  metric_value: number | null;
  metric_unit: string | null;
};

const LEGACY_CHARITY_PREFIX = '\u062e\u064a\u0631\u064a\u0629';

const TEXT = {
  ar: {
    title: 'تقرير الأعمال الخيرية السنوي',
    preview: 'معاينة التقرير',
    print: 'طباعة / حفظ PDF',
    back: 'رجوع للمشاريع الخيرية',
    generatedOn: 'تم الإنشاء في',
    year: 'السنة',
    user: 'المستخدم',
    executive: 'الملخص التنفيذي',
    zakat: 'ملخص الزكاة',
    projects: 'ملخص المشاريع الخيرية',
    donations: 'سجل التبرعات',
    commitments: 'الالتزامات الخيرية المتوقعة',
    impact: 'ملخص الأثر',
    totalDonations: 'إجمالي التبرعات هذا العام',
    projectCount: 'عدد المشاريع الخيرية',
    completedProjects: 'المشاريع المكتملة',
    expectedCommitments: 'الالتزامات المتوقعة',
    estimatedZakat: 'زكاة المال المتوقعة',
    linkedDonations: 'عدد التبرعات المرتبطة',
    zakatableAmount: 'المبلغ الخاضع للزكاة',
    zakatAssets: 'عدد أصول الزكاة',
    upcomingDue: 'مواعيد الزكاة القادمة',
    noData: 'لا توجد بيانات',
    target: 'الهدف',
    collected: 'المحصّل',
    progress: 'التقدم',
    organization: 'الجهة',
    dates: 'التواريخ',
    date: 'التاريخ',
    amount: 'المبلغ',
    type: 'النوع',
    project: 'المشروع',
    notes: 'ملاحظات',
    monthlyAnnualized: 'الالتزامات الشهرية × 12',
    annualCommitments: 'الالتزامات السنوية',
    totalExpected: 'إجمالي الالتزامات الخيرية المتوقعة',
    impactEmpty: 'لا توجد بيانات أثر كافية حتى الآن.',
    beneficiaries: 'المستفيدون',
    customMetrics: 'مؤشرات الأثر المخصصة',
    disclaimer: 'هذا التقرير تم إنشاؤه من THE SFM لأغراض التنظيم والمتابعة الشخصية، ولا يُعد فتوى شرعية أو تقريراً مالياً معتمداً إلا بعد مراجعته من جهة مختصة.',
  },
  en: {
    title: 'Annual Charity Report',
    preview: 'Report Preview',
    print: 'Print / Save PDF',
    back: 'Back to Charity Projects',
    generatedOn: 'Generated on',
    year: 'Year',
    user: 'User',
    executive: 'Executive Summary',
    zakat: 'Zakat Summary',
    projects: 'Charity Projects Summary',
    donations: 'Donation Records',
    commitments: 'Expected Charity Commitments',
    impact: 'Impact Summary',
    totalDonations: 'Total donations this year',
    projectCount: 'Number of charity projects',
    completedProjects: 'Completed projects',
    expectedCommitments: 'Expected commitments',
    estimatedZakat: 'Estimated zakat',
    linkedDonations: 'Linked donations',
    zakatableAmount: 'Zakatable amount',
    zakatAssets: 'Zakat assets count',
    upcomingDue: 'Upcoming zakat due dates',
    noData: 'No data available',
    target: 'Target',
    collected: 'Collected',
    progress: 'Progress',
    organization: 'Organization',
    dates: 'Dates',
    date: 'Date',
    amount: 'Amount',
    type: 'Type',
    project: 'Project',
    notes: 'Notes',
    monthlyAnnualized: 'Monthly commitments x 12',
    annualCommitments: 'Annual commitments',
    totalExpected: 'Total expected charity obligations',
    impactEmpty: 'Not enough impact data yet.',
    beneficiaries: 'Beneficiaries',
    customMetrics: 'Custom impact indicators',
    disclaimer: 'This report was generated by THE SFM for personal organization and tracking. It is not a religious ruling or official financial report unless reviewed by a qualified authority.',
  },
  fr: {
    title: 'Rapport annuel caritatif',
    preview: 'Aperçu du rapport',
    print: 'Imprimer / Enregistrer PDF',
    back: 'Retour aux projets caritatifs',
    generatedOn: 'Généré le',
    year: 'Année',
    user: 'Utilisateur',
    executive: 'Résumé exécutif',
    zakat: 'Résumé de la zakat',
    projects: 'Résumé des projets caritatifs',
    donations: 'Historique des dons',
    commitments: 'Engagements caritatifs prévus',
    impact: "Résumé de l'impact",
    totalDonations: 'Total des dons cette année',
    projectCount: 'Nombre de projets caritatifs',
    completedProjects: 'Projets terminés',
    expectedCommitments: 'Engagements prévus',
    estimatedZakat: 'Zakat estimée',
    linkedDonations: 'Dons liés',
    zakatableAmount: 'Montant soumis à la zakat',
    zakatAssets: 'Nombre d’actifs de zakat',
    upcomingDue: 'Prochaines dates de zakat',
    noData: 'Aucune donnée disponible',
    target: 'Objectif',
    collected: 'Collecté',
    progress: 'Progression',
    organization: 'Organisation',
    dates: 'Dates',
    date: 'Date',
    amount: 'Montant',
    type: 'Type',
    project: 'Projet',
    notes: 'Notes',
    monthlyAnnualized: 'Engagements mensuels x 12',
    annualCommitments: 'Engagements annuels',
    totalExpected: 'Total des obligations caritatives prévues',
    impactEmpty: 'Données d’impact insuffisantes pour le moment.',
    beneficiaries: 'Bénéficiaires',
    customMetrics: 'Indicateurs d’impact personnalisés',
    disclaimer: 'Ce rapport a été généré par THE SFM à des fins d’organisation et de suivi personnel. Il ne constitue pas un avis religieux ni un rapport financier officiel sauf validation par une autorité compétente.',
  },
} as const;

function safeNumber(value: unknown) {
  const number = Number(value);
  return Number.isFinite(number) ? number : 0;
}

function yearOf(value?: string | null) {
  if (!value) return null;
  const year = new Date(`${value.slice(0, 10)}T00:00:00`).getFullYear();
  return Number.isFinite(year) ? year : null;
}

function ReportContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const { user } = useAuth();
  const { lang, dir } = useLanguage();
  const tr = TEXT[lang as Lang] ?? TEXT.ar;
  const db = supabase as any;
  const selectedYear = Number(searchParams?.get('year')) || new Date().getFullYear();

  const [projects, setProjects] = useState<Project[]>([]);
  const [donations, setDonations] = useState<Donation[]>([]);
  const [assets, setAssets] = useState<ZakatAsset[]>([]);
  const [commitments, setCommitments] = useState<Commitment[]>([]);
  const [beneficiaries, setBeneficiaries] = useState<Beneficiary[]>([]);
  const [impactMetrics, setImpactMetrics] = useState<ImpactMetric[]>([]);
  const [loading, setLoading] = useState(true);

  const money = useCallback((amount: number, currency = 'KWD') => formatMoney(amount, currency, lang as Lang), [lang]);
  const dateLabel = useCallback((value?: string | null) => {
    if (!value) return '-';
    return new Date(`${value.slice(0, 10)}T00:00:00`).toLocaleDateString(lang === 'ar' ? 'ar-KW-u-nu-latn' : lang === 'fr' ? 'fr-FR' : 'en-US');
  }, [lang]);

  useEffect(() => {
    let cancelled = false;
    async function load() {
      if (!user) return;
      setLoading(true);
      const [projectRes, donationRes, assetRes, commitmentRes, beneficiaryRes, metricRes, legacyRes] = await Promise.all([
        db.from('charity_projects').select('*').eq('user_id', user.id),
        db.from('charity_project_donations').select('*').eq('user_id', user.id),
        db.from('zakat_assets').select('*').eq('user_id', user.id),
        db.from('charity_commitments').select('*').eq('user_id', user.id),
        db.from('charity_beneficiaries').select('*').eq('user_id', user.id),
        db.from('charity_project_impact_metrics').select('*').eq('user_id', user.id),
        db.from('expense_items').select('id,name,amount,created_at').eq('user_id', user.id).like('name', `${LEGACY_CHARITY_PREFIX}:%`),
      ]);
      if (cancelled) return;
      const loadedProjects = projectRes.error ? [] : (projectRes.data ?? []) as Project[];
      const projectNames = new Map(loadedProjects.map(project => [project.id, project.name]));
      const linked = donationRes.error ? [] : ((donationRes.data ?? []) as Donation[]).map(donation => ({
        ...donation,
        project_name: donation.project_id ? projectNames.get(donation.project_id) : undefined,
      }));
      const legacy = legacyRes.error ? [] : (legacyRes.data ?? []).map((row: any): Donation => {
        const parts = String(row.name || '').split(':');
        return {
          id: row.id,
          project_id: null,
          project_name: '',
          amount: safeNumber(row.amount),
          currency: 'KWD',
          donation_date: row.created_at,
          donation_type: parts[2] || 'charity',
          notes: parts[2] || '',
          created_at: row.created_at,
        };
      });
      setProjects(loadedProjects.filter(project => [yearOf(project.start_date), yearOf(project.end_date), yearOf((project as any).created_at)].includes(selectedYear)));
      setDonations([...linked, ...legacy].filter(donation => yearOf(donation.donation_date || donation.created_at) === selectedYear));
      setAssets((assetRes.error ? [] : (assetRes.data ?? []) as ZakatAsset[]).filter(asset => yearOf(asset.zakat_due_date || asset.ownership_date) === selectedYear || asset.is_zakatable));
      setCommitments((commitmentRes.error ? [] : (commitmentRes.data ?? []) as Commitment[]).filter(commitment => !commitment.next_due_date || yearOf(commitment.next_due_date) === selectedYear));
      setBeneficiaries(beneficiaryRes.error ? [] : (beneficiaryRes.data ?? []) as Beneficiary[]);
      setImpactMetrics(metricRes.error ? [] : (metricRes.data ?? []) as ImpactMetric[]);
      setLoading(false);
    }
    load();
    return () => { cancelled = true; };
  }, [db, selectedYear, user]);

  const totals = useMemo(() => {
    const totalDonations = donations.reduce((sum, donation) => sum + safeNumber(donation.amount), 0);
    const zakatableAmount = assets.filter(asset => asset.is_zakatable !== false).reduce((sum, asset) => sum + safeNumber(asset.amount), 0);
    const estimatedZakat = zakatableAmount * 0.025;
    const monthlyCommitments = commitments.filter(item => item.frequency === 'monthly').reduce((sum, item) => sum + safeNumber(item.amount) * 12, 0);
    const annualCommitments = commitments.filter(item => item.frequency !== 'monthly').reduce((sum, item) => sum + safeNumber(item.amount), 0);
    const expectedCommitments = monthlyCommitments + annualCommitments + estimatedZakat;
    const monthlySupport = beneficiaries.filter(item => item.status === 'active').reduce((sum, item) => sum + safeNumber(item.monthly_support_amount), 0);
    return { totalDonations, zakatableAmount, estimatedZakat, monthlyCommitments, annualCommitments, expectedCommitments, monthlySupport };
  }, [assets, beneficiaries, commitments, donations]);

  const generatedDate = new Date().toLocaleDateString(lang === 'ar' ? 'ar-KW-u-nu-latn' : lang === 'fr' ? 'fr-FR' : 'en-US');
  const userName = user?.user_metadata?.full_name || user?.email || '-';

  return (
    <main className="report-page" dir={dir}>
      <div className="report-actions no-print">
        <button onClick={() => router.push('/charity-projects')} aria-label={tr.back}><ArrowLeft size={16} /> {tr.back}</button>
        <button onClick={() => window.print()} aria-label={tr.print}><Printer size={16} /> {tr.print}</button>
      </div>

      <article className="report-sheet">
        <header className="cover">
          <div className="brand">
            <Image src="/sfm-logo.png" alt="THE SFM" width={54} height={54} priority className="sfm-brand-mark sfm-brand-mark--report" />
            <div><strong>THE SFM</strong><span>{tr.preview}</span></div>
          </div>
          <h1>{tr.title}</h1>
          <div className="cover-meta">
            <span>{tr.year}: <b>{selectedYear}</b></span>
            <span>{tr.generatedOn}: <b>{generatedDate}</b></span>
            <span>{tr.user}: <b>{userName}</b></span>
          </div>
        </header>

        {loading ? <section className="section"><p>{tr.noData}</p></section> : (
          <>
            <section className="section">
              <h2>{tr.executive}</h2>
              <div className="summary-grid">
                <Metric label={tr.totalDonations} value={money(totals.totalDonations)} />
                <Metric label={tr.projectCount} value={String(projects.length)} />
                <Metric label={tr.completedProjects} value={String(projects.filter(project => project.status === 'completed').length)} />
                <Metric label={tr.expectedCommitments} value={money(totals.expectedCommitments)} />
                <Metric label={tr.estimatedZakat} value={money(totals.estimatedZakat)} />
                <Metric label={tr.linkedDonations} value={String(donations.length)} />
              </div>
            </section>

            <section className="section">
              <h2>{tr.zakat}</h2>
              <div className="summary-grid three">
                <Metric label={tr.zakatableAmount} value={money(totals.zakatableAmount)} />
                <Metric label={tr.estimatedZakat} value={money(totals.estimatedZakat)} />
                <Metric label={tr.zakatAssets} value={String(assets.length)} />
              </div>
              <h3>{tr.upcomingDue}</h3>
              {assets.filter(asset => asset.zakat_due_date).length ? (
                <ul>{assets.filter(asset => asset.zakat_due_date).map(asset => <li key={asset.id}>{asset.asset_name} - {dateLabel(asset.zakat_due_date)}</li>)}</ul>
              ) : <p className="empty">{tr.noData}</p>}
            </section>

            <section className="section">
              <h2>{tr.projects}</h2>
              {projects.length ? (
                <div className="table-wrap">
                  <table><thead><tr><th>{tr.project}</th><th>{tr.type}</th><th>{tr.target}</th><th>{tr.collected}</th><th>{tr.progress}</th><th>{tr.organization}</th><th>{tr.dates}</th></tr></thead>
                    <tbody>{projects.map(project => {
                      const target = safeNumber(project.target_amount);
                      const collected = safeNumber(project.collected_amount);
                      const progress = target > 0 ? Math.min(100, (collected / target) * 100) : 0;
                      return <tr key={project.id}><td>{project.name}</td><td>{project.category || '-'}</td><td>{money(target, project.currency || 'KWD')}</td><td>{money(collected, project.currency || 'KWD')}</td><td>{progress.toFixed(1)}%</td><td>{project.organization_name || '-'}</td><td>{dateLabel(project.start_date)} - {dateLabel(project.end_date)}</td></tr>;
                    })}</tbody></table>
                </div>
              ) : <p className="empty">{tr.noData}</p>}
            </section>

            <section className="section">
              <h2>{tr.donations}</h2>
              {donations.length ? (
                <div className="table-wrap">
                  <table><thead><tr><th>{tr.date}</th><th>{tr.amount}</th><th>{tr.type}</th><th>{tr.project}</th><th>{tr.notes}</th></tr></thead>
                    <tbody>{donations.map(donation => <tr key={donation.id}><td>{dateLabel(donation.donation_date || donation.created_at)}</td><td>{money(safeNumber(donation.amount), donation.currency || 'KWD')}</td><td>{donation.donation_type || '-'}</td><td>{donation.project_name || '-'}</td><td>{donation.notes || '-'}</td></tr>)}</tbody></table>
                </div>
              ) : <p className="empty">{tr.noData}</p>}
            </section>

            <section className="section">
              <h2>{tr.commitments}</h2>
              <div className="summary-grid three">
                <Metric label={tr.monthlyAnnualized} value={money(totals.monthlyCommitments)} />
                <Metric label={tr.annualCommitments} value={money(totals.annualCommitments)} />
                <Metric label={tr.totalExpected} value={money(totals.expectedCommitments)} />
              </div>
            </section>

            <section className="section">
              <h2>{tr.impact}</h2>
              {projects.length || beneficiaries.length || impactMetrics.length ? (
                <>
                  <div className="summary-grid three">
                    <Metric label={tr.totalDonations} value={money(totals.totalDonations)} />
                    <Metric label={tr.beneficiaries} value={String(beneficiaries.length)} />
                    <Metric label={tr.monthlyAnnualized} value={money(totals.monthlySupport * 12)} />
                  </div>
                  {impactMetrics.length > 0 && (
                    <>
                      <h3>{tr.customMetrics}</h3>
                      <div className="table-wrap">
                        <table><thead><tr><th>{tr.project}</th><th>{tr.type}</th><th>{tr.amount}</th><th>{tr.notes}</th></tr></thead>
                          <tbody>{impactMetrics.map(metric => <tr key={metric.id}><td>{projects.find(project => project.id === metric.project_id)?.name || '-'}</td><td>{metric.metric_name}</td><td>{safeNumber(metric.metric_value).toLocaleString(lang === 'ar' ? 'ar-KW-u-nu-latn' : lang === 'fr' ? 'fr-FR' : 'en-US')} {metric.metric_unit || ''}</td><td>-</td></tr>)}</tbody></table>
                      </div>
                    </>
                  )}
                </>
              ) : <p className="empty">{tr.impactEmpty}</p>}
            </section>
          </>
        )}

        <footer>
          <p>{tr.disclaimer}</p>
          <span>THE SFM - {tr.generatedOn} {generatedDate}</span>
        </footer>
      </article>

      <style jsx global>{`
        .report-page{min-height:100vh;background:var(--sfm-background);color:var(--sfm-primary-dark);font-family:Tajawal,Arial,sans-serif;padding:24px}
        .report-actions{max-width:1040px;margin:0 auto 16px;display:flex;justify-content:space-between;gap:10px}.report-actions button{height:var(--control-h);border-radius:var(--r-md);border:1px solid rgba(29,140,255,.22);background:var(--sfm-card);color:var(--sfm-midnight);padding:0 14px;display:inline-flex;align-items:center;gap:7px;font:900 13px Tajawal,Arial,sans-serif;cursor:pointer}
        .report-sheet{max-width:1040px;margin:0 auto;background:var(--sfm-card);border:1px solid rgba(29,140,255,.18);border-radius:var(--r-2xl);box-shadow:0 18px 54px rgba(3,18,37,.12);overflow:hidden}.cover{background:linear-gradient(135deg,var(--sfm-deep-navy),var(--sfm-primary-dark) 62%,var(--sfm-card-dark) 145%);color:var(--sfm-card);padding:34px}.brand{display:flex;align-items:center;gap:12px}.brand img{border-radius:var(--r-md)}.brand strong{display:block;color:var(--sfm-soft-cyan);font-size:18px}.brand span{display:block;color:rgba(234,246,255,.58);font-size:12px}.cover h1{margin:28px 0 14px;font-size:42px}.cover-meta{display:flex;gap:12px;flex-wrap:wrap}.cover-meta span{border:1px solid rgba(255,255,255,.16);background:rgba(255,255,255,.08);border-radius:999px;padding:7px 12px;color:rgba(234,246,255,.75)}
        .section{padding:24px 30px;border-bottom:1px solid rgba(29,140,255,.12)}.section h2{margin:0 0 14px;color:var(--sfm-midnight);font-size:23px}.section h3{margin:16px 0 8px;color:var(--sfm-primary-hover);font-size:15px}.summary-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.summary-grid.three{grid-template-columns:repeat(3,minmax(0,1fr))}.metric{border:1px solid rgba(29,140,255,.14);background:rgba(29,140,255,.10);border-radius:var(--r-lg);padding:14px}.metric small{display:block;color:var(--sfm-primary-hover);font-weight:800}.metric strong{display:block;margin-top:6px;color:var(--sfm-primary-dark);font-size:20px;overflow-wrap:anywhere}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse;font-size:12px}th,td{padding:10px;border-bottom:1px solid rgba(29,140,255,.12);text-align:start;vertical-align:top}th{color:var(--sfm-primary-hover);background:rgba(29,140,255,.10)}.empty{color:var(--sfm-muted);margin:0;line-height:1.8}ul{margin:0 20px;color:var(--sfm-midnight)}footer{padding:20px 30px;background:var(--sfm-light-card);color:var(--sfm-muted);font-size:12px;line-height:1.8}footer span{display:block;margin-top:8px;color:var(--sfm-primary-hover);font-weight:900}
        @media(max-width:720px){.report-page{padding:12px}.report-actions{display:grid}.report-actions button{justify-content:center}.cover{padding:24px}.cover h1{font-size:30px}.section{padding:18px}.summary-grid,.summary-grid.three{grid-template-columns:1fr}.report-sheet{border-radius:var(--r-xl)}}
        @media print{.no-print{display:none!important}.report-page{background:white;padding:0}.report-sheet{max-width:none;border:0;border-radius:0;box-shadow:none}.section{break-inside:avoid}.cover{border-radius:0}footer{position:running(footer)}}
      `}</style>
    </main>
  );
}

function Metric({ label, value }: { label: string; value: string }) {
  return <div className="metric"><small>{label}</small><strong>{value}</strong></div>;
}

export default function CharityReportPage() {
  return (
    <Suspense fallback={null}>
      <ReportContent />
    </Suspense>
  );
}
