'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { useLanguage } from '@/hooks/useLanguage';
import { Button } from '@/components/ui/button';
import { WorkspacePageContainer } from '@/components/layout/WorkspacePageContainer';
import styles from '@/components/platform/platform.module.css';
type InstallEvent=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>};
const copy={ar:{title:'تطبيق THE SFM',install:'تثبيت على هذا الجهاز',note:'افتح مساحاتك من تطبيق الموقع المثبت. يلزم الاتصال لتحميل البيانات المالية؛ لا تُخزّن بيانات الحساب للعمل دون اتصال.',ios:'على iPhone وiPad: افتح الموقع في Safari، ثم مشاركة ← إضافة إلى الشاشة الرئيسية. على Android أو Huawei استخدم خيار تثبيت التطبيق أو إضافة إلى الشاشة الرئيسية في المتصفح.',installed:'التطبيق مفتوح بوضع مستقل.',native:'تطبيقات iOS الأصلية المستقلة لم تصدر بعد؛ هذا تثبيت لتطبيق الويب.',finance:'SFM Finance',trader:'SFM Trader',business:'SFM Business',connections:'إدارة التكاملات',notifications:'إشعارات الجهاز'},en:{title:'THE SFM app',install:'Install on this device',note:'Open your workspaces from the installed web app. Financial data requires a connection; account data is never cached for offline use.',ios:'On iPhone or iPad: open in Safari, Share → Add to Home Screen. On Android or Huawei, use Install app or Add to Home Screen in your browser.',installed:'Running as an installed app.',native:'Separate native iOS apps have not been released. This installs the web app.',finance:'SFM Finance',trader:'SFM Trader',business:'SFM Business',connections:'Manage integrations',notifications:'Device notifications'},fr:{title:'Application THE SFM',install:'Installer sur cet appareil',note:'Ouvrez vos espaces depuis l’application web installée. Une connexion est requise ; les données financières ne sont pas mises en cache hors ligne.',ios:'Sur iPhone ou iPad : ouvrez dans Safari, Partager → Sur l’écran d’accueil. Sur Android ou Huawei, utilisez Installer ou Ajouter à l’écran d’accueil.',installed:'Application ouverte en mode autonome.',native:'Les applications iOS natives séparées ne sont pas publiées. Ceci installe l’application web.',finance:'SFM Finance',trader:'SFM Trader',business:'SFM Business',connections:'Gérer les intégrations',notifications:'Notifications de l’appareil'}};
export default function AppsPage(){
 const {lang}=useLanguage();const text=copy[lang==='en'||lang==='fr'?lang:'ar'];const [install,setInstall]=useState<InstallEvent|null>(null);const [installed,setInstalled]=useState(false);
 useEffect(()=>{const capture=(e:Event)=>{e.preventDefault();setInstall(e as InstallEvent);};const done=()=>{setInstall(null);setInstalled(true);};setInstalled(window.matchMedia('(display-mode: standalone)').matches);window.addEventListener('beforeinstallprompt',capture);window.addEventListener('appinstalled',done);return()=>{window.removeEventListener('beforeinstallprompt',capture);window.removeEventListener('appinstalled',done);};},[]);
 return <WorkspacePageContainer variant="reading" className={styles.page}><h1>{text.title}</h1><p>{text.note}</p><section className={styles.card}>{installed?<p>{text.installed}</p>:install?<Button onClick={async()=>{await install.prompt();await install.userChoice;setInstall(null);}}>{text.install}</Button>:<p>{text.ios}</p>}<p>{text.native}</p></section><nav className={styles.grid}><Link className={styles.card} href="/today">{text.finance}</Link><Link className={styles.card} href="/ai-analyst/overview">{text.trader}</Link><Link className={styles.card} href="/business-hub">{text.business}</Link><Link href="/settings/integrations">{text.connections}</Link><Link href="/notifications/channels">{text.notifications}</Link></nav></WorkspacePageContainer>;
}
