export type BusinessLang = 'ar' | 'en' | 'fr';

export type SaleStatus = 'completed' | 'pending' | 'canceled';
export type EmployeeStatus = 'active' | 'on_leave' | 'inactive';
export type BusinessRole = 'manager' | 'accountant' | 'employee';
export type BusinessInvoiceStatus = 'draft' | 'sent' | 'paid' | 'overdue';
export type BusinessOperatingExpenseCategory =
  | 'rent'
  | 'salaries'
  | 'subscriptions'
  | 'operating_purchases'
  | 'marketing'
  | 'maintenance'
  | 'shipping_delivery'
  | 'other';

export const SALE_STATUS_OPTIONS: SaleStatus[] = ['completed', 'pending', 'canceled'];
export const EMPLOYEE_STATUS_OPTIONS: EmployeeStatus[] = ['active', 'on_leave', 'inactive'];
export const BUSINESS_INVOICE_STATUS_OPTIONS: BusinessInvoiceStatus[] = ['draft', 'sent', 'paid', 'overdue'];
export const BUSINESS_OPERATING_EXPENSE_CATEGORY_OPTIONS: BusinessOperatingExpenseCategory[] = [
  'rent',
  'salaries',
  'subscriptions',
  'operating_purchases',
  'marketing',
  'maintenance',
  'shipping_delivery',
  'other',
];

export const BUSINESS_TEXT = {
  ar: {
    businessOperations: 'إدارة الأعمال',
    businessOperationsSubtitle: 'نظّم مبيعاتك، موظفيك، فواتيرك، وعناصر التشغيل من مكان واحد.',
    operationsBadge: 'عمليات الأعمال',
    projects: 'المشاريع',
    projectsDescription: 'تابع المشاريع التجارية ودراسات الجدوى وخطط التنفيذ.',
    openProjects: 'فتح المشاريع',
    sales: 'المبيعات',
    salesDescription: 'تابع عمليات البيع والفواتير والإيرادات التجارية.',
    openSales: 'فتح المبيعات',
    employees: 'الموظفين والرواتب',
    employeesDescription: 'نظّم بيانات الموظفين والرواتب ومستويات الكفاءة.',
    openEmployees: 'فتح الموظفين',
    openCustomers: 'فتح العملاء',
    openInvoices: 'فتح الفواتير',
    openSuppliers: 'فتح الموردين',
    openOperatingExpenses: 'فتح المصروفات التشغيلية',
    customers: 'العملاء',
    invoices: 'الفواتير',
    suppliers: 'الموردين',
    operatingExpenses: 'المصروفات التشغيلية',
    customersDescription: 'نظّم بيانات العملاء وسجّل جهات التواصل المرتبطة بعملياتك.',
    invoicesDescription: 'تابع الفواتير التجارية وحالتها عند توفر بيانات المبيعات.',
    suppliersDescription: 'احتفظ ببيانات الموردين والمشتريات التشغيلية في مكان واضح.',
    operatingExpensesDescription: 'سجّل مصروفات التشغيل واربطها بتحليلات الأعمال.',
    comingSoon: 'قريباً',
    noDataYet: 'لا توجد بيانات كافية حتى الآن.',
    emptyDashboardBody: 'أضف أول مشروع أو عملية بيع أو مصروف لبدء عرض التحليلات.',
    startAddingFirstData: 'أضف أول مشروع أو عملية بيع أو مصروف لبدء عرض التحليلات.',
    analyticsNeedMoreData: 'لا توجد بيانات كافية لبعض التحليلات. أضف مبيعات أو مصروفات لعرض النتائج.',
    addProject: 'إضافة مشروع',
    addCustomer: 'إضافة عميل',
    addExpense: 'إضافة مصروف',
    addInvoice: 'إضافة فاتورة',
    addSupplier: 'إضافة مورد',
    addOperatingExpense: 'إضافة مصروف تشغيلي',
    addFirstProject: 'إضافة أول مشروع',
    noPayrollDate: 'لا يوجد موعد حتى الآن',
    itemCount: '{count} عنصر',
    unclassified: 'غير مصنف',
    addSale: 'إضافة عملية بيع',
    role: 'الدور',
    manager: 'مدير',
    accountant: 'محاسب',
    employee: 'موظف عادي',
    permissionDenied: 'ليست لديك صلاحية كافية لعرض هذا القسم.',
    exportPdf: 'تصدير PDF',
    exportExcel: 'تصدير Excel',
    exportCsv: 'تصدير CSV',
    noDataToExport: 'لا توجد بيانات للتصدير.',
    generatedAt: 'تاريخ الإنشاء',
    filtersUsed: 'الفلاتر المستخدمة',
    dateRange: 'نطاق التاريخ',
    fromDate: 'من تاريخ',
    toDate: 'إلى تاريخ',
    allDates: 'كل التواريخ',
    monthlySales: 'المبيعات الشهرية',
    yearlySales: 'المبيعات السنوية',
    salesByStatus: 'المبيعات حسب الحالة',
    topProducts: 'أفضل المنتجات والخدمات',
    salesByCustomer: 'المبيعات حسب العميل',
    insufficientChartData: 'لا توجد بيانات كافية للرسم البياني',
    chartEmptyBody: 'أضف أول عملية بيع أو مصروف لبدء عرض التحليلات.',
    editSale: 'تعديل عملية بيع',
    deleteSale: 'حذف عملية بيع',
    noSalesYet: 'لا توجد عمليات بيع حتى الآن.',
    saleEmptyBody: 'أضف أول عملية بيع حقيقية لعرض الإجماليات والفواتير.',
    invoiceNumber: 'رقم الفاتورة',
    customer: 'العميل',
    customerName: 'اسم العميل',
    productService: 'المنتج / الخدمة',
    amount: 'المبلغ',
    currency: 'العملة',
    status: 'الحالة',
    saleDate: 'تاريخ البيع',
    notes: 'ملاحظات',
    completed: 'مكتمل',
    pending: 'قيد المعالجة',
    canceled: 'ملغي',
    totalSales: 'إجمالي المبيعات',
    totalProjects: 'إجمالي المشاريع',
    completedSales: 'العمليات المكتملة',
    pendingSales: 'قيد المعالجة',
    canceledSales: 'الملغية',
    searchSales: 'ابحث عن عميل أو فاتورة أو خدمة...',
    allStatuses: 'كل الحالات',
    saveSale: 'حفظ عملية البيع',
    updateSale: 'حفظ التعديل',
    saleSaved: 'تم حفظ عملية البيع.',
    saleDeleted: 'تم حذف عملية البيع.',
    confirmDeleteSale: 'هل تريد حذف عملية البيع؟',
    customerNameField: 'اسم العميل',
    supplierName: 'اسم المورد',
    phone: 'رقم الهاتف',
    email: 'البريد الإلكتروني',
    company: 'الشركة',
    address: 'العنوان',
    invoiceTitle: 'عنوان الفاتورة',
    invoiceDate: 'تاريخ الفاتورة',
    dueDate: 'تاريخ الاستحقاق',
    supplierType: 'نوع التوريد',
    expenseName: 'اسم المصروف',
    expenseCategory: 'التصنيف',
    expenseDate: 'تاريخ المصروف',
    recurringMonthly: 'يتكرر شهريًا',
    draft: 'مسودة',
    sent: 'مرسلة',
    paid: 'مدفوعة',
    overdue: 'متأخرة',
    rent: 'إيجار',
    salaries: 'رواتب',
    subscriptions: 'اشتراكات',
    operatingPurchases: 'مشتريات تشغيلية',
    marketing: 'تسويق',
    maintenance: 'صيانة',
    shippingDelivery: 'شحن وتوصيل',
    other: 'أخرى',
    editCustomer: 'تعديل عميل',
    deleteCustomer: 'حذف عميل',
    customerSaved: 'تم حفظ بيانات العميل.',
    customerDeleted: 'تم حذف العميل.',
    confirmDeleteCustomer: 'هل تريد حذف هذا العميل؟',
    noCustomersYet: 'لا يوجد عملاء حتى الآن.',
    customerEmptyBody: 'ابدأ بإضافة أول عميل لتنظيم بيانات التواصل والفواتير.',
    searchCustomers: 'ابحث عن عميل أو شركة أو بريد إلكتروني...',
    editInvoice: 'تعديل فاتورة',
    deleteInvoice: 'حذف فاتورة',
    invoiceSaved: 'تم حفظ الفاتورة.',
    invoiceDeleted: 'تم حذف الفاتورة.',
    confirmDeleteInvoice: 'هل تريد حذف هذه الفاتورة؟',
    noInvoicesYet: 'لا توجد فواتير حتى الآن.',
    invoiceEmptyBody: 'ابدأ بإضافة أول فاتورة وربطها بعميل عند الحاجة.',
    searchInvoices: 'ابحث عن رقم فاتورة أو عميل أو عنوان...',
    editSupplier: 'تعديل مورد',
    deleteSupplier: 'حذف مورد',
    supplierSaved: 'تم حفظ بيانات المورد.',
    supplierDeleted: 'تم حذف المورد.',
    confirmDeleteSupplier: 'هل تريد حذف هذا المورد؟',
    noSuppliersYet: 'لا يوجد موردون حتى الآن.',
    supplierEmptyBody: 'ابدأ بإضافة أول مورد لتنظيم بيانات الشراء والتوريد.',
    searchSuppliers: 'ابحث عن مورد أو شركة أو نوع توريد...',
    editOperatingExpense: 'تعديل مصروف تشغيلي',
    deleteOperatingExpense: 'حذف مصروف تشغيلي',
    operatingExpenseSaved: 'تم حفظ المصروف التشغيلي.',
    operatingExpenseDeleted: 'تم حذف المصروف التشغيلي.',
    confirmDeleteOperatingExpense: 'هل تريد حذف هذا المصروف التشغيلي؟',
    noOperatingExpensesYet: 'لا توجد مصروفات تشغيلية حتى الآن.',
    operatingExpenseEmptyBody: 'ابدأ بإضافة أول مصروف تشغيلي لعرض إجمالي المصروفات الشهرية.',
    searchOperatingExpenses: 'ابحث عن مصروف أو تصنيف أو ملاحظة...',
    monthlyOperatingExpenses: 'مصروفات التشغيل الشهرية',
    addEmployee: 'إضافة موظف',
    editEmployee: 'تعديل موظف',
    deleteEmployee: 'حذف موظف',
    noEmployeesYet: 'لا يوجد موظفون حتى الآن.',
    employeeEmptyBody: 'أضف بيانات الموظفين الحقيقية لعرض الرواتب والإحصاءات.',
    employeeName: 'اسم الموظف',
    department: 'القسم',
    salary: 'الراتب',
    bonus: 'البدل / المكافأة',
    skillLevel: 'المهارة / الكفاءة',
    payrollDueDay: 'يوم استحقاق الراتب',
    payrollDue: 'استحقاق الرواتب',
    payrollReminder: 'تذكير الرواتب',
    payrollReminder7: 'رواتب الموظفين مستحقة خلال 7 أيام.',
    payrollReminder3: 'رواتب الموظفين مستحقة خلال 3 أيام.',
    payrollReminderToday: 'رواتب الموظفين مستحقة اليوم.',
    openEmployeesPayroll: 'فتح الموظفين والرواتب',
    totalAllowances: 'إجمالي البدلات',
    totalMonthlyCost: 'إجمالي التكلفة الشهرية',
    nearestPayrollDate: 'أقرب موعد رواتب',
    joinDate: 'تاريخ الانضمام',
    active: 'نشط',
    onLeave: 'في إجازة',
    inactive: 'غير نشط',
    totalMonthlyPayroll: 'إجمالي الرواتب الشهرية',
    totalEmployees: 'إجمالي الموظفين',
    activeEmployees: 'الموظفون النشطون',
    averageSalary: 'متوسط الراتب',
    searchEmployees: 'ابحث عن موظف أو دور أو قسم...',
    allDepartments: 'كل الأقسام',
    allCategories: 'كل التصنيفات',
    gridView: 'عرض بطاقات',
    tableView: 'عرض جدول',
    saveEmployee: 'حفظ الموظف',
    updateEmployee: 'حفظ التعديل',
    employeeSaved: 'تم حفظ بيانات الموظف.',
    employeeDeleted: 'تم حذف الموظف.',
    confirmDeleteEmployee: 'هل تريد حذف هذا الموظف؟',
    loading: 'جاري تحميل البيانات...',
    loadError: 'تعذر تحميل البيانات حالياً',
    partialLoadWarning: 'حدث خطأ أثناء تحميل بعض البيانات. حاول تحديث الصفحة.',
    retry: 'إعادة المحاولة',
    saveError: 'تعذر حفظ البيانات حالياً.',
    employeeNameRequired: 'يرجى إدخال اسم الموظف.',
    salaryRequired: 'يرجى إدخال راتب صحيح.',
    salaryDayInvalid: 'يوم استحقاق الراتب يجب أن يكون بين 1 و31.',
    skillLevelInvalid: 'مستوى الكفاءة يجب أن يكون بين 0 و100.',
    joinDateInvalid: 'تاريخ الانضمام غير صالح.',
    loginRequiredToSaveEmployee: 'يجب تسجيل الدخول لحفظ بيانات الموظف.',
    employeeAccessDeniedSave: 'تعذر حفظ البيانات بسبب صلاحيات الوصول. يرجى مراجعة إعدادات قاعدة البيانات.',
    employeeSaveFailedDetailed: 'تعذر حفظ بيانات الموظف. يرجى التحقق من البيانات والمحاولة مرة أخرى.',
    deleteError: 'تعذر حذف السجل حالياً.',
    edit: 'تعديل',
    delete: 'حذف',
    cancel: 'إلغاء',
    search: 'بحث',
    clear: 'مسح',
    requiredField: 'هذا الحقل مطلوب.',
    invalidAmount: 'أدخل مبلغاً صحيحاً.',
    backToOperations: 'العودة إلى إدارة الأعمال',
  },
  en: {
    businessOperations: 'Business Operations',
    businessOperationsSubtitle: 'Organize your sales, employees, invoices, and operations from one place.',
    operationsBadge: 'Business operations',
    projects: 'Projects',
    projectsDescription: 'Track business projects, feasibility work, and execution plans.',
    openProjects: 'Open Projects',
    sales: 'Sales',
    salesDescription: 'Track sales, invoices, and business revenue.',
    openSales: 'Open Sales',
    employees: 'Employees & Payroll',
    employeesDescription: 'Organize employee records, salaries, and skill levels.',
    openEmployees: 'Open Employees',
    openCustomers: 'Open Customers',
    openInvoices: 'Open Invoices',
    openSuppliers: 'Open Suppliers',
    openOperatingExpenses: 'Open Operating Expenses',
    customers: 'Customers',
    invoices: 'Invoices',
    suppliers: 'Suppliers',
    operatingExpenses: 'Operating Expenses',
    customersDescription: 'Organize customer records and the contacts linked to your operations.',
    invoicesDescription: 'Track business invoices and their status once sales data is available.',
    suppliersDescription: 'Keep supplier and operating purchase details in one clear place.',
    operatingExpensesDescription: 'Record operating expenses and connect them to business analytics.',
    comingSoon: 'Coming soon',
    noDataYet: 'Not enough data yet.',
    emptyDashboardBody: 'Add your first project, sale, or expense to start showing analytics.',
    startAddingFirstData: 'Add your first project, sale, or expense to start showing analytics.',
    analyticsNeedMoreData: 'Some analytics need more data. Add sales or expenses to display results.',
    addProject: 'Add Project',
    addCustomer: 'Add Customer',
    addExpense: 'Add Expense',
    addInvoice: 'Add Invoice',
    addSupplier: 'Add Supplier',
    addOperatingExpense: 'Add Operating Expense',
    addFirstProject: 'Add first project',
    noPayrollDate: 'No payroll date yet',
    itemCount: '{count} items',
    unclassified: 'Unclassified',
    addSale: 'Add Sale',
    role: 'Role',
    manager: 'Manager',
    accountant: 'Accountant',
    employee: 'Employee',
    permissionDenied: 'You do not have permission to view this section.',
    exportPdf: 'Export PDF',
    exportExcel: 'Export Excel',
    exportCsv: 'Export CSV',
    noDataToExport: 'There is no data to export.',
    generatedAt: 'Generated at',
    filtersUsed: 'Filters used',
    dateRange: 'Date range',
    fromDate: 'From date',
    toDate: 'To date',
    allDates: 'All dates',
    monthlySales: 'Monthly Sales',
    yearlySales: 'Yearly Sales',
    salesByStatus: 'Sales by Status',
    topProducts: 'Top Products and Services',
    salesByCustomer: 'Sales by Customer',
    insufficientChartData: 'There is not enough data for this chart',
    chartEmptyBody: 'Add your first sale or expense to start showing analytics.',
    editSale: 'Edit Sale',
    deleteSale: 'Delete Sale',
    noSalesYet: 'No sales yet.',
    saleEmptyBody: 'Add your first real sale to see totals and invoices.',
    invoiceNumber: 'Invoice Number',
    customer: 'Customer',
    customerName: 'Customer Name',
    productService: 'Product / Service',
    amount: 'Amount',
    currency: 'Currency',
    status: 'Status',
    saleDate: 'Sale Date',
    notes: 'Notes',
    completed: 'Completed',
    pending: 'Pending',
    canceled: 'Canceled',
    totalSales: 'Total Sales',
    totalProjects: 'Total Projects',
    completedSales: 'Completed Sales',
    pendingSales: 'Pending',
    canceledSales: 'Canceled',
    searchSales: 'Search customer, invoice, or service...',
    allStatuses: 'All statuses',
    saveSale: 'Save Sale',
    updateSale: 'Save Changes',
    saleSaved: 'Sale saved.',
    saleDeleted: 'Sale deleted.',
    confirmDeleteSale: 'Do you want to delete this sale?',
    customerNameField: 'Customer Name',
    supplierName: 'Supplier Name',
    phone: 'Phone Number',
    email: 'Email',
    company: 'Company',
    address: 'Address',
    invoiceTitle: 'Invoice Title',
    invoiceDate: 'Invoice Date',
    dueDate: 'Due Date',
    supplierType: 'Supply Type',
    expenseName: 'Expense Name',
    expenseCategory: 'Category',
    expenseDate: 'Expense Date',
    recurringMonthly: 'Recurring Monthly',
    draft: 'Draft',
    sent: 'Sent',
    paid: 'Paid',
    overdue: 'Overdue',
    rent: 'Rent',
    salaries: 'Salaries',
    subscriptions: 'Subscriptions',
    operatingPurchases: 'Operating Purchases',
    marketing: 'Marketing',
    maintenance: 'Maintenance',
    shippingDelivery: 'Shipping & Delivery',
    other: 'Other',
    editCustomer: 'Edit Customer',
    deleteCustomer: 'Delete Customer',
    customerSaved: 'Customer saved.',
    customerDeleted: 'Customer deleted.',
    confirmDeleteCustomer: 'Do you want to delete this customer?',
    noCustomersYet: 'No customers yet.',
    customerEmptyBody: 'Add your first customer to organize contact and invoice data.',
    searchCustomers: 'Search customer, company, or email...',
    editInvoice: 'Edit Invoice',
    deleteInvoice: 'Delete Invoice',
    invoiceSaved: 'Invoice saved.',
    invoiceDeleted: 'Invoice deleted.',
    confirmDeleteInvoice: 'Do you want to delete this invoice?',
    noInvoicesYet: 'No invoices yet.',
    invoiceEmptyBody: 'Add your first invoice and link it to a customer when needed.',
    searchInvoices: 'Search invoice number, customer, or title...',
    editSupplier: 'Edit Supplier',
    deleteSupplier: 'Delete Supplier',
    supplierSaved: 'Supplier saved.',
    supplierDeleted: 'Supplier deleted.',
    confirmDeleteSupplier: 'Do you want to delete this supplier?',
    noSuppliersYet: 'No suppliers yet.',
    supplierEmptyBody: 'Add your first supplier to organize purchasing and supply data.',
    searchSuppliers: 'Search supplier, company, or supply type...',
    editOperatingExpense: 'Edit Operating Expense',
    deleteOperatingExpense: 'Delete Operating Expense',
    operatingExpenseSaved: 'Operating expense saved.',
    operatingExpenseDeleted: 'Operating expense deleted.',
    confirmDeleteOperatingExpense: 'Do you want to delete this operating expense?',
    noOperatingExpensesYet: 'No operating expenses yet.',
    operatingExpenseEmptyBody: 'Add your first operating expense to show monthly operating totals.',
    searchOperatingExpenses: 'Search expense, category, or note...',
    monthlyOperatingExpenses: 'Monthly Operating Expenses',
    addEmployee: 'Add Employee',
    editEmployee: 'Edit Employee',
    deleteEmployee: 'Delete Employee',
    noEmployeesYet: 'No employees yet.',
    employeeEmptyBody: 'Add real employee records to see payroll and stats.',
    employeeName: 'Employee Name',
    department: 'Department',
    salary: 'Salary',
    bonus: 'Bonus',
    skillLevel: 'Skill / Efficiency',
    payrollDueDay: 'Payroll Due Day',
    payrollDue: 'Payroll Due',
    payrollReminder: 'Payroll Reminder',
    payrollReminder7: 'Employee payroll is due in 7 days.',
    payrollReminder3: 'Employee payroll is due in 3 days.',
    payrollReminderToday: 'Employee payroll is due today.',
    openEmployeesPayroll: 'Open Employees & Payroll',
    totalAllowances: 'Total Allowances',
    totalMonthlyCost: 'Total Monthly Cost',
    nearestPayrollDate: 'Nearest Payroll Date',
    joinDate: 'Join Date',
    active: 'Active',
    onLeave: 'On Leave',
    inactive: 'Inactive',
    totalMonthlyPayroll: 'Total Monthly Payroll',
    totalEmployees: 'Total Employees',
    activeEmployees: 'Active Employees',
    averageSalary: 'Average Salary',
    searchEmployees: 'Search employee, role, or department...',
    allDepartments: 'All departments',
    allCategories: 'All categories',
    gridView: 'Grid view',
    tableView: 'Table view',
    saveEmployee: 'Save Employee',
    updateEmployee: 'Save Changes',
    employeeSaved: 'Employee saved.',
    employeeDeleted: 'Employee deleted.',
    confirmDeleteEmployee: 'Do you want to delete this employee?',
    loading: 'Loading data...',
    loadError: 'Could not load data right now.',
    partialLoadWarning: 'An error occurred while loading some data. Try refreshing the page.',
    retry: 'Retry',
    saveError: 'Could not save data right now.',
    employeeNameRequired: 'Please enter the employee name.',
    salaryRequired: 'Please enter a valid salary.',
    salaryDayInvalid: 'Payroll due day must be between 1 and 31.',
    skillLevelInvalid: 'Skill level must be between 0 and 100.',
    joinDateInvalid: 'Join date is invalid.',
    loginRequiredToSaveEmployee: 'You must sign in to save employee data.',
    employeeAccessDeniedSave: 'Could not save data because of access permissions. Please review the database settings.',
    employeeSaveFailedDetailed: 'Could not save employee data. Please check the details and try again.',
    deleteError: 'Could not delete the record right now.',
    edit: 'Edit',
    delete: 'Delete',
    cancel: 'Cancel',
    search: 'Search',
    clear: 'Clear',
    requiredField: 'This field is required.',
    invalidAmount: 'Enter a valid amount.',
    backToOperations: 'Back to Business Operations',
  },
  fr: {
    businessOperations: 'Opérations commerciales',
    businessOperationsSubtitle: 'Organisez vos ventes, employés, factures et opérations depuis un seul endroit.',
    operationsBadge: 'Opérations commerciales',
    projects: 'Projets',
    projectsDescription: 'Suivez les projets commerciaux, les études de faisabilité et les plans d’exécution.',
    openProjects: 'Ouvrir les projets',
    sales: 'Ventes',
    salesDescription: 'Suivez les ventes, factures et revenus commerciaux.',
    openSales: 'Ouvrir les ventes',
    employees: 'Employés et paie',
    employeesDescription: 'Organisez les dossiers employés, salaires et niveaux de compétence.',
    openEmployees: 'Ouvrir les employés',
    openCustomers: 'Ouvrir les clients',
    openInvoices: 'Ouvrir les factures',
    openSuppliers: 'Ouvrir les fournisseurs',
    openOperatingExpenses: 'Ouvrir les dépenses opérationnelles',
    customers: 'Clients',
    invoices: 'Factures',
    suppliers: 'Fournisseurs',
    operatingExpenses: 'Dépenses opérationnelles',
    customersDescription: 'Organisez les clients et les contacts liés à vos opérations.',
    invoicesDescription: 'Suivez les factures commerciales et leur statut lorsque les ventes existent.',
    suppliersDescription: 'Gardez les fournisseurs et achats opérationnels dans un endroit clair.',
    operatingExpensesDescription: 'Enregistrez les dépenses opérationnelles et reliez-les aux analyses.',
    comingSoon: 'Bientôt disponible',
    noDataYet: 'Pas encore assez de données.',
    emptyDashboardBody: 'Ajoutez votre premier projet, votre première vente ou votre première dépense pour afficher les analyses.',
    startAddingFirstData: 'Ajoutez votre premier projet, votre première vente ou votre première dépense pour afficher les analyses.',
    analyticsNeedMoreData: 'Certaines analyses nécessitent plus de données. Ajoutez des ventes ou des dépenses pour afficher les résultats.',
    addProject: 'Ajouter un projet',
    addCustomer: 'Ajouter un client',
    addExpense: 'Ajouter une dépense',
    addInvoice: 'Ajouter une facture',
    addSupplier: 'Ajouter un fournisseur',
    addOperatingExpense: 'Ajouter une dépense opérationnelle',
    addFirstProject: 'Ajouter le premier projet',
    noPayrollDate: 'Aucune date de paie pour le moment',
    itemCount: '{count} éléments',
    unclassified: 'Non classé',
    addSale: 'Ajouter une vente',
    role: 'Rôle',
    manager: 'Manager',
    accountant: 'Comptable',
    employee: 'Employé',
    permissionDenied: 'Vous n’avez pas l’autorisation de consulter cette section.',
    exportPdf: 'Exporter PDF',
    exportExcel: 'Exporter Excel',
    exportCsv: 'Exporter CSV',
    noDataToExport: 'Aucune donnée à exporter.',
    generatedAt: 'Date de génération',
    filtersUsed: 'Filtres utilisés',
    dateRange: 'Plage de dates',
    fromDate: 'Date de début',
    toDate: 'Date de fin',
    allDates: 'Toutes les dates',
    monthlySales: 'Ventes mensuelles',
    yearlySales: 'Ventes annuelles',
    salesByStatus: 'Ventes par statut',
    topProducts: 'Meilleurs produits et services',
    salesByCustomer: 'Ventes par client',
    insufficientChartData: 'Données insuffisantes pour ce graphique',
    chartEmptyBody: 'Ajoutez une première vente ou dépense pour commencer à afficher les analyses.',
    editSale: 'Modifier la vente',
    deleteSale: 'Supprimer la vente',
    noSalesYet: 'Aucune vente pour le moment.',
    saleEmptyBody: 'Ajoutez votre première vente réelle pour voir les totaux et factures.',
    invoiceNumber: 'Numéro de facture',
    customer: 'Client',
    customerName: 'Nom du client',
    productService: 'Produit / Service',
    amount: 'Montant',
    currency: 'Devise',
    status: 'Statut',
    saleDate: 'Date de vente',
    notes: 'Notes',
    completed: 'Terminée',
    pending: 'En traitement',
    canceled: 'Annulée',
    totalSales: 'Ventes totales',
    totalProjects: 'Total des projets',
    completedSales: 'Ventes terminées',
    pendingSales: 'En traitement',
    canceledSales: 'Annulées',
    searchSales: 'Rechercher client, facture ou service...',
    allStatuses: 'Tous les statuts',
    saveSale: 'Enregistrer la vente',
    updateSale: 'Enregistrer',
    saleSaved: 'Vente enregistrée.',
    saleDeleted: 'Vente supprimée.',
    confirmDeleteSale: 'Voulez-vous supprimer cette vente ?',
    customerNameField: 'Nom du client',
    supplierName: 'Nom du fournisseur',
    phone: 'Numéro de téléphone',
    email: 'E-mail',
    company: 'Société',
    address: 'Adresse',
    invoiceTitle: 'Titre de la facture',
    invoiceDate: 'Date de facture',
    dueDate: 'Date d’échéance',
    supplierType: 'Type de fourniture',
    expenseName: 'Nom de la dépense',
    expenseCategory: 'Catégorie',
    expenseDate: 'Date de dépense',
    recurringMonthly: 'Récurrente mensuellement',
    draft: 'Brouillon',
    sent: 'Envoyée',
    paid: 'Payée',
    overdue: 'En retard',
    rent: 'Loyer',
    salaries: 'Salaires',
    subscriptions: 'Abonnements',
    operatingPurchases: 'Achats opérationnels',
    marketing: 'Marketing',
    maintenance: 'Maintenance',
    shippingDelivery: 'Expédition et livraison',
    other: 'Autre',
    editCustomer: 'Modifier le client',
    deleteCustomer: 'Supprimer le client',
    customerSaved: 'Client enregistré.',
    customerDeleted: 'Client supprimé.',
    confirmDeleteCustomer: 'Voulez-vous supprimer ce client ?',
    noCustomersYet: 'Aucun client pour le moment.',
    customerEmptyBody: 'Ajoutez votre premier client pour organiser contacts et factures.',
    searchCustomers: 'Rechercher client, société ou e-mail...',
    editInvoice: 'Modifier la facture',
    deleteInvoice: 'Supprimer la facture',
    invoiceSaved: 'Facture enregistrée.',
    invoiceDeleted: 'Facture supprimée.',
    confirmDeleteInvoice: 'Voulez-vous supprimer cette facture ?',
    noInvoicesYet: 'Aucune facture pour le moment.',
    invoiceEmptyBody: 'Ajoutez votre première facture et reliez-la à un client si nécessaire.',
    searchInvoices: 'Rechercher numéro de facture, client ou titre...',
    editSupplier: 'Modifier le fournisseur',
    deleteSupplier: 'Supprimer le fournisseur',
    supplierSaved: 'Fournisseur enregistré.',
    supplierDeleted: 'Fournisseur supprimé.',
    confirmDeleteSupplier: 'Voulez-vous supprimer ce fournisseur ?',
    noSuppliersYet: 'Aucun fournisseur pour le moment.',
    supplierEmptyBody: 'Ajoutez votre premier fournisseur pour organiser achats et fournitures.',
    searchSuppliers: 'Rechercher fournisseur, société ou type de fourniture...',
    editOperatingExpense: 'Modifier la dépense opérationnelle',
    deleteOperatingExpense: 'Supprimer la dépense opérationnelle',
    operatingExpenseSaved: 'Dépense opérationnelle enregistrée.',
    operatingExpenseDeleted: 'Dépense opérationnelle supprimée.',
    confirmDeleteOperatingExpense: 'Voulez-vous supprimer cette dépense opérationnelle ?',
    noOperatingExpensesYet: 'Aucune dépense opérationnelle pour le moment.',
    operatingExpenseEmptyBody: 'Ajoutez votre première dépense opérationnelle pour afficher les totaux mensuels.',
    searchOperatingExpenses: 'Rechercher dépense, catégorie ou note...',
    monthlyOperatingExpenses: 'Dépenses opérationnelles mensuelles',
    addEmployee: 'Ajouter un employé',
    editEmployee: 'Modifier l’employé',
    deleteEmployee: 'Supprimer l’employé',
    noEmployeesYet: 'Aucun employé pour le moment.',
    employeeEmptyBody: 'Ajoutez de vrais employés pour voir la paie et les statistiques.',
    employeeName: 'Nom de l’employé',
    department: 'Département',
    salary: 'Salaire',
    bonus: 'Prime',
    skillLevel: 'Compétence / efficacité',
    payrollDueDay: 'Jour de paie',
    payrollDue: 'Échéance de paie',
    payrollReminder: 'Rappel de paie',
    payrollReminder7: 'La paie des employés est due dans 7 jours.',
    payrollReminder3: 'La paie des employés est due dans 3 jours.',
    payrollReminderToday: 'La paie des employés est due aujourd’hui.',
    openEmployeesPayroll: 'Ouvrir employés et paie',
    totalAllowances: 'Total des primes',
    totalMonthlyCost: 'Coût mensuel total',
    nearestPayrollDate: 'Prochaine date de paie',
    joinDate: 'Date d’arrivée',
    active: 'Actif',
    onLeave: 'En congé',
    inactive: 'Inactif',
    totalMonthlyPayroll: 'Paie mensuelle totale',
    totalEmployees: 'Total employés',
    activeEmployees: 'Employés actifs',
    averageSalary: 'Salaire moyen',
    searchEmployees: 'Rechercher employé, rôle ou département...',
    allDepartments: 'Tous les départements',
    allCategories: 'Toutes les catégories',
    gridView: 'Vue cartes',
    tableView: 'Vue tableau',
    saveEmployee: 'Enregistrer l’employé',
    updateEmployee: 'Enregistrer',
    employeeSaved: 'Employé enregistré.',
    employeeDeleted: 'Employé supprimé.',
    confirmDeleteEmployee: 'Voulez-vous supprimer cet employé ?',
    loading: 'Chargement des données...',
    loadError: 'Impossible de charger les données pour le moment.',
    partialLoadWarning: 'Une erreur est survenue lors du chargement de certaines données. Essayez d’actualiser la page.',
    retry: 'Réessayer',
    saveError: 'Impossible d’enregistrer les données pour le moment.',
    employeeNameRequired: 'Veuillez saisir le nom de l’employé.',
    salaryRequired: 'Veuillez saisir un salaire valide.',
    salaryDayInvalid: 'Le jour de paie doit être compris entre 1 et 31.',
    skillLevelInvalid: 'Le niveau de compétence doit être compris entre 0 et 100.',
    joinDateInvalid: 'La date d’arrivée n’est pas valide.',
    loginRequiredToSaveEmployee: 'Vous devez vous connecter pour enregistrer les données de l’employé.',
    employeeAccessDeniedSave: 'Impossible d’enregistrer les données en raison des autorisations d’accès. Veuillez vérifier les paramètres de la base de données.',
    employeeSaveFailedDetailed: 'Impossible d’enregistrer les données de l’employé. Vérifiez les informations puis réessayez.',
    deleteError: 'Impossible de supprimer cet enregistrement pour le moment.',
    edit: 'Modifier',
    delete: 'Supprimer',
    cancel: 'Annuler',
    search: 'Rechercher',
    clear: 'Effacer',
    requiredField: 'Ce champ est requis.',
    invalidAmount: 'Saisissez un montant valide.',
    backToOperations: 'Retour aux opérations commerciales',
  },
} as const;

export function normalizeBusinessLang(lang?: string): BusinessLang {
  return lang === 'en' || lang === 'fr' || lang === 'ar' ? lang : 'ar';
}

export function saleStatusLabel(status: string | null | undefined, lang: BusinessLang) {
  const text = BUSINESS_TEXT[lang];
  if (status === 'completed') return text.completed;
  if (status === 'canceled') return text.canceled;
  return text.pending;
}

export function employeeStatusLabel(status: string | null | undefined, lang: BusinessLang) {
  const text = BUSINESS_TEXT[lang];
  if (status === 'on_leave') return text.onLeave;
  if (status === 'inactive') return text.inactive;
  return text.active;
}

export function invoiceStatusLabel(status: string | null | undefined, lang: BusinessLang) {
  const text = BUSINESS_TEXT[lang];
  if (status === 'sent') return text.sent;
  if (status === 'paid') return text.paid;
  if (status === 'overdue') return text.overdue;
  return text.draft;
}

export function operatingExpenseCategoryLabel(category: string | null | undefined, lang: BusinessLang) {
  const text = BUSINESS_TEXT[lang];
  if (category === 'rent') return text.rent;
  if (category === 'salaries') return text.salaries;
  if (category === 'subscriptions') return text.subscriptions;
  if (category === 'operating_purchases') return text.operatingPurchases;
  if (category === 'marketing') return text.marketing;
  if (category === 'maintenance') return text.maintenance;
  if (category === 'shipping_delivery') return text.shippingDelivery;
  return text.other;
}

export function businessRoleLabel(role: string | null | undefined, lang: BusinessLang) {
  const text = BUSINESS_TEXT[lang];
  if (role === 'accountant') return text.accountant;
  if (role === 'employee') return text.employee;
  return text.manager;
}

export function businessPermissions(role: BusinessRole) {
  return {
    canViewSales: role === 'manager' || role === 'accountant',
    canWriteSales: role === 'manager' || role === 'accountant',
    canDeleteSales: role === 'manager',
    canViewEmployees: role === 'manager' || role === 'accountant',
    canWriteEmployees: role === 'manager',
    canDeleteEmployees: role === 'manager',
    canViewPayrollTotals: role === 'manager' || role === 'accountant',
    canViewBusinessModules: role === 'manager' || role === 'accountant',
    canWriteBusinessModules: role === 'manager' || role === 'accountant',
    canDeleteBusinessModules: role === 'manager',
    canExport: role === 'manager' || role === 'accountant',
    canManageSettings: role === 'manager',
  };
}

export function numericValue(value: unknown) {
  if (typeof value === 'string') {
    const parsed = Number(value.replace(/[^\d.-]/g, ''));
    return Number.isFinite(parsed) ? parsed : 0;
  }
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : 0;
}
