export type BusinessLang = 'ar' | 'en' | 'fr';

export type SaleStatus = 'completed' | 'pending' | 'canceled';
export type EmployeeStatus = 'active' | 'on_leave' | 'inactive';
export type BusinessRole = 'manager' | 'accountant' | 'employee';

export const SALE_STATUS_OPTIONS: SaleStatus[] = ['completed', 'pending', 'canceled'];
export const EMPLOYEE_STATUS_OPTIONS: EmployeeStatus[] = ['active', 'on_leave', 'inactive'];

export const BUSINESS_TEXT = {
  ar: {
    businessOperations: 'إدارة الأعمال',
    businessOperationsSubtitle: 'نظّم مبيعاتك، موظفيك، فواتيرك، وعناصر التشغيل من مكان واحد.',
    operationsBadge: 'عمليات الأعمال',
    projects: 'المشاريع',
    projectsDescription: 'تابع المشاريع التجارية ودراسات الجدوى وخطط التنفيذ.',
    openProjects: 'فتح المشاريع',
    sales: 'المبيعات',
    salesDescription: 'تابع عمليات البيع والفواتير والإيرادات التجارية.',
    openSales: 'فتح المبيعات',
    employees: 'الموظفين والرواتب',
    employeesDescription: 'نظّم بيانات الموظفين والرواتب والبدلات.',
    openEmployees: 'فتح الموظفين',
    customers: 'العملاء',
    invoices: 'الفواتير',
    suppliers: 'الموردين',
    operatingExpenses: 'المصروفات التشغيلية',
    customersDescription: 'نظّم بيانات العملاء وسجّل جهات التواصل المرتبطة بعملياتك.',
    invoicesDescription: 'تابع الفواتير التجارية وحالتها عند توفر بيانات المبيعات.',
    suppliersDescription: 'احتفظ ببيانات الموردين والمشتريات التشغيلية في مكان واضح.',
    operatingExpensesDescription: 'سجّل مصروفات التشغيل واربطها بتحليلات الأعمال.',
    comingSoon: 'قريباً',
    noDataYet: 'لا توجد بيانات أعمال بعد',
    emptyDashboardBody: 'ابدأ بإضافة أول عملية بيع أو موظف أو عميل.',
    addFirstProject: 'إضافة أول مشروع',
    noPayrollDate: 'لا يوجد موعد حتى الآن',
    itemCount: '{count} عنصر',
    unclassified: 'غير مصنف',
    addSale: 'إضافة عملية بيع',
    role: 'الدور',
    manager: 'مدير',
    accountant: 'محاسب',
    employee: 'موظف عادي',
    permissionDenied: 'ليست لديك صلاحية كافية لعرض هذا القسم.',
    exportPdf: 'تصدير PDF',
    exportExcel: 'تصدير Excel',
    exportCsv: 'تصدير CSV',
    noDataToExport: 'لا توجد بيانات للتصدير.',
    generatedAt: 'تاريخ الإنشاء',
    filtersUsed: 'الفلاتر المستخدمة',
    dateRange: 'نطاق التاريخ',
    fromDate: 'من تاريخ',
    toDate: 'إلى تاريخ',
    allDates: 'كل التواريخ',
    monthlySales: 'المبيعات الشهرية',
    yearlySales: 'المبيعات السنوية',
    salesByStatus: 'المبيعات حسب الحالة',
    topProducts: 'أفضل المنتجات والخدمات',
    salesByCustomer: 'المبيعات حسب العميل',
    insufficientChartData: 'لا توجد بيانات كافية للرسم البياني',
    chartEmptyBody: 'أضف أول عملية بيع أو مصروف لبدء عرض التحليلات.',
    editSale: 'تعديل عملية بيع',
    deleteSale: 'حذف عملية بيع',
    noSalesYet: 'لا توجد عمليات بيع حتى الآن.',
    saleEmptyBody: 'أضف أول عملية بيع حقيقية لعرض الإجماليات والفواتير.',
    invoiceNumber: 'رقم الفاتورة',
    customer: 'العميل',
    customerName: 'اسم العميل',
    productService: 'المنتج / الخدمة',
    amount: 'المبلغ',
    currency: 'العملة',
    status: 'الحالة',
    saleDate: 'تاريخ البيع',
    notes: 'ملاحظات',
    completed: 'مكتمل',
    pending: 'قيد المعالجة',
    canceled: 'ملغي',
    totalSales: 'إجمالي المبيعات',
    totalProjects: 'إجمالي المشاريع',
    completedSales: 'العمليات المكتملة',
    pendingSales: 'قيد المعالجة',
    canceledSales: 'الملغية',
    searchSales: 'ابحث عن عميل أو فاتورة أو خدمة...',
    allStatuses: 'كل الحالات',
    saveSale: 'حفظ عملية البيع',
    updateSale: 'حفظ التعديل',
    saleSaved: 'تم حفظ عملية البيع.',
    saleDeleted: 'تم حذف عملية البيع.',
    confirmDeleteSale: 'هل تريد حذف عملية البيع؟',
    addEmployee: 'إضافة موظف',
    editEmployee: 'تعديل موظف',
    deleteEmployee: 'حذف موظف',
    noEmployeesYet: 'لا يوجد موظفون حتى الآن.',
    employeeEmptyBody: 'أضف بيانات الموظفين الحقيقية لعرض الرواتب والإحصاءات.',
    employeeName: 'اسم الموظف',
    department: 'القسم',
    salary: 'الراتب',
    bonus: 'البدل / المكافأة',
    payrollDueDay: 'يوم استحقاق الرواتب',
    payrollDue: 'استحقاق الرواتب',
    payrollReminder: 'تذكير الرواتب',
    payrollReminder7: 'رواتب الموظفين مستحقة خلال 7 أيام.',
    payrollReminder3: 'رواتب الموظفين مستحقة خلال 3 أيام.',
    payrollReminderToday: 'رواتب الموظفين مستحقة اليوم.',
    openEmployeesPayroll: 'فتح الموظفين والرواتب',
    totalAllowances: 'إجمالي البدلات',
    totalMonthlyCost: 'إجمالي التكلفة الشهرية',
    nearestPayrollDate: 'أقرب موعد رواتب',
    joinDate: 'تاريخ الانضمام',
    active: 'نشط',
    onLeave: 'إجازة',
    inactive: 'متوقف',
    totalMonthlyPayroll: 'إجمالي الرواتب الشهرية',
    totalEmployees: 'إجمالي الموظفين',
    activeEmployees: 'الموظفون النشطون',
    averageSalary: 'متوسط الراتب',
    searchEmployees: 'ابحث عن موظف أو دور أو قسم...',
    allDepartments: 'كل الأقسام',
    gridView: 'عرض بطاقات',
    tableView: 'عرض جدول',
    saveEmployee: 'حفظ الموظف',
    updateEmployee: 'حفظ التعديل',
    employeeSaved: 'تم حفظ بيانات الموظف.',
    employeeDeleted: 'تم حذف الموظف.',
    confirmDeleteEmployee: 'هل تريد حذف هذا الموظف؟',
    loading: 'جاري تحميل البيانات...',
    loadError: 'تعذر تحميل البيانات حالياً',
    partialLoadWarning: 'تعذر تحميل بعض الأقسام، لكن البيانات المتاحة ظاهرة.',
    retry: 'إعادة المحاولة',
    saveError: 'تعذر حفظ البيانات حالياً.',
    deleteError: 'تعذر حذف السجل حالياً.',
    edit: 'تعديل',
    delete: 'حذف',
    cancel: 'إلغاء',
    search: 'بحث',
    clear: 'مسح',
    requiredField: 'هذا الحقل مطلوب.',
    invalidAmount: 'أدخل مبلغاً صحيحاً.',
    backToOperations: 'العودة إلى إدارة الأعمال',
  },
  en: {
    businessOperations: 'Business Operations',
    businessOperationsSubtitle: 'Organize your sales, employees, invoices, and operations from one place.',
    operationsBadge: 'Business operations',
    projects: 'Projects',
    projectsDescription: 'Track business projects, feasibility work, and execution plans.',
    openProjects: 'Open Projects',
    sales: 'Sales',
    salesDescription: 'Track sales, invoices, and business revenue.',
    openSales: 'Open Sales',
    employees: 'Employees & Payroll',
    employeesDescription: 'Organize employee records, salaries, and allowances.',
    openEmployees: 'Open Employees',
    customers: 'Customers',
    invoices: 'Invoices',
    suppliers: 'Suppliers',
    operatingExpenses: 'Operating Expenses',
    customersDescription: 'Organize customer records and the contacts linked to your operations.',
    invoicesDescription: 'Track business invoices and their status once sales data is available.',
    suppliersDescription: 'Keep supplier and operating purchase details in one clear place.',
    operatingExpensesDescription: 'Record operating expenses and connect them to business analytics.',
    comingSoon: 'Coming soon',
    noDataYet: 'No business data yet',
    emptyDashboardBody: 'Start by adding your first sale, employee, or customer.',
    addFirstProject: 'Add first project',
    noPayrollDate: 'No payroll date yet',
    itemCount: '{count} items',
    unclassified: 'Unclassified',
    addSale: 'Add Sale',
    role: 'Role',
    manager: 'Manager',
    accountant: 'Accountant',
    employee: 'Employee',
    permissionDenied: 'You do not have permission to view this section.',
    exportPdf: 'Export PDF',
    exportExcel: 'Export Excel',
    exportCsv: 'Export CSV',
    noDataToExport: 'There is no data to export.',
    generatedAt: 'Generated at',
    filtersUsed: 'Filters used',
    dateRange: 'Date range',
    fromDate: 'From date',
    toDate: 'To date',
    allDates: 'All dates',
    monthlySales: 'Monthly Sales',
    yearlySales: 'Yearly Sales',
    salesByStatus: 'Sales by Status',
    topProducts: 'Top Products and Services',
    salesByCustomer: 'Sales by Customer',
    insufficientChartData: 'There is not enough data for this chart',
    chartEmptyBody: 'Add your first sale or expense to start showing analytics.',
    editSale: 'Edit Sale',
    deleteSale: 'Delete Sale',
    noSalesYet: 'No sales yet.',
    saleEmptyBody: 'Add your first real sale to see totals and invoices.',
    invoiceNumber: 'Invoice Number',
    customer: 'Customer',
    customerName: 'Customer Name',
    productService: 'Product / Service',
    amount: 'Amount',
    currency: 'Currency',
    status: 'Status',
    saleDate: 'Sale Date',
    notes: 'Notes',
    completed: 'Completed',
    pending: 'Pending',
    canceled: 'Canceled',
    totalSales: 'Total Sales',
    totalProjects: 'Total Projects',
    completedSales: 'Completed Sales',
    pendingSales: 'Pending',
    canceledSales: 'Canceled',
    searchSales: 'Search customer, invoice, or service...',
    allStatuses: 'All statuses',
    saveSale: 'Save Sale',
    updateSale: 'Save Changes',
    saleSaved: 'Sale saved.',
    saleDeleted: 'Sale deleted.',
    confirmDeleteSale: 'Do you want to delete this sale?',
    addEmployee: 'Add Employee',
    editEmployee: 'Edit Employee',
    deleteEmployee: 'Delete Employee',
    noEmployeesYet: 'No employees yet.',
    employeeEmptyBody: 'Add real employee records to see payroll and stats.',
    employeeName: 'Employee Name',
    department: 'Department',
    salary: 'Salary',
    bonus: 'Bonus',
    payrollDueDay: 'Payroll Due Day',
    payrollDue: 'Payroll Due',
    payrollReminder: 'Payroll Reminder',
    payrollReminder7: 'Employee payroll is due in 7 days.',
    payrollReminder3: 'Employee payroll is due in 3 days.',
    payrollReminderToday: 'Employee payroll is due today.',
    openEmployeesPayroll: 'Open Employees & Payroll',
    totalAllowances: 'Total Allowances',
    totalMonthlyCost: 'Total Monthly Cost',
    nearestPayrollDate: 'Nearest Payroll Date',
    joinDate: 'Join Date',
    active: 'Active',
    onLeave: 'On Leave',
    inactive: 'Inactive',
    totalMonthlyPayroll: 'Total Monthly Payroll',
    totalEmployees: 'Total Employees',
    activeEmployees: 'Active Employees',
    averageSalary: 'Average Salary',
    searchEmployees: 'Search employee, role, or department...',
    allDepartments: 'All departments',
    gridView: 'Grid view',
    tableView: 'Table view',
    saveEmployee: 'Save Employee',
    updateEmployee: 'Save Changes',
    employeeSaved: 'Employee saved.',
    employeeDeleted: 'Employee deleted.',
    confirmDeleteEmployee: 'Do you want to delete this employee?',
    loading: 'Loading data...',
    loadError: 'Could not load data right now.',
    partialLoadWarning: 'Some sections could not load, but available business data is still shown.',
    retry: 'Retry',
    saveError: 'Could not save data right now.',
    deleteError: 'Could not delete the record right now.',
    edit: 'Edit',
    delete: 'Delete',
    cancel: 'Cancel',
    search: 'Search',
    clear: 'Clear',
    requiredField: 'This field is required.',
    invalidAmount: 'Enter a valid amount.',
    backToOperations: 'Back to Business Operations',
  },
  fr: {
    businessOperations: 'Opérations commerciales',
    businessOperationsSubtitle: 'Organisez vos ventes, employés, factures et opérations depuis un seul endroit.',
    operationsBadge: 'Opérations commerciales',
    projects: 'Projets',
    projectsDescription: 'Suivez les projets commerciaux, les études de faisabilité et les plans d’exécution.',
    openProjects: 'Ouvrir les projets',
    sales: 'Ventes',
    salesDescription: 'Suivez les ventes, factures et revenus commerciaux.',
    openSales: 'Ouvrir les ventes',
    employees: 'Employés et paie',
    employeesDescription: 'Organisez les dossiers employés, salaires et primes.',
    openEmployees: 'Ouvrir les employés',
    customers: 'Clients',
    invoices: 'Factures',
    suppliers: 'Fournisseurs',
    operatingExpenses: 'Dépenses opérationnelles',
    customersDescription: 'Organisez les clients et les contacts liés à vos opérations.',
    invoicesDescription: 'Suivez les factures commerciales et leur statut lorsque les ventes existent.',
    suppliersDescription: 'Gardez les fournisseurs et achats opérationnels dans un endroit clair.',
    operatingExpensesDescription: 'Enregistrez les dépenses opérationnelles et reliez-les aux analyses.',
    comingSoon: 'Bientôt disponible',
    noDataYet: 'Aucune donnée business pour le moment',
    emptyDashboardBody: 'Commencez par ajouter votre première vente, votre premier employé ou votre premier client.',
    addFirstProject: 'Ajouter le premier projet',
    noPayrollDate: 'Aucune date de paie pour le moment',
    itemCount: '{count} éléments',
    unclassified: 'Non classé',
    addSale: 'Ajouter une vente',
    role: 'Rôle',
    manager: 'Manager',
    accountant: 'Comptable',
    employee: 'Employé',
    permissionDenied: 'Vous n’avez pas l’autorisation de consulter cette section.',
    exportPdf: 'Exporter PDF',
    exportExcel: 'Exporter Excel',
    exportCsv: 'Exporter CSV',
    noDataToExport: 'Aucune donnée à exporter.',
    generatedAt: 'Date de génération',
    filtersUsed: 'Filtres utilisés',
    dateRange: 'Plage de dates',
    fromDate: 'Date de début',
    toDate: 'Date de fin',
    allDates: 'Toutes les dates',
    monthlySales: 'Ventes mensuelles',
    yearlySales: 'Ventes annuelles',
    salesByStatus: 'Ventes par statut',
    topProducts: 'Meilleurs produits et services',
    salesByCustomer: 'Ventes par client',
    insufficientChartData: 'Données insuffisantes pour ce graphique',
    chartEmptyBody: 'Ajoutez une première vente ou dépense pour commencer à afficher les analyses.',
    editSale: 'Modifier la vente',
    deleteSale: 'Supprimer la vente',
    noSalesYet: 'Aucune vente pour le moment.',
    saleEmptyBody: 'Ajoutez votre première vente réelle pour voir les totaux et factures.',
    invoiceNumber: 'Numéro de facture',
    customer: 'Client',
    customerName: 'Nom du client',
    productService: 'Produit / Service',
    amount: 'Montant',
    currency: 'Devise',
    status: 'Statut',
    saleDate: 'Date de vente',
    notes: 'Notes',
    completed: 'Terminée',
    pending: 'En traitement',
    canceled: 'Annulée',
    totalSales: 'Ventes totales',
    totalProjects: 'Total des projets',
    completedSales: 'Ventes terminées',
    pendingSales: 'En traitement',
    canceledSales: 'Annulées',
    searchSales: 'Rechercher client, facture ou service...',
    allStatuses: 'Tous les statuts',
    saveSale: 'Enregistrer la vente',
    updateSale: 'Enregistrer',
    saleSaved: 'Vente enregistrée.',
    saleDeleted: 'Vente supprimée.',
    confirmDeleteSale: 'Voulez-vous supprimer cette vente ?',
    addEmployee: 'Ajouter un employé',
    editEmployee: 'Modifier l’employé',
    deleteEmployee: 'Supprimer l’employé',
    noEmployeesYet: 'Aucun employé pour le moment.',
    employeeEmptyBody: 'Ajoutez de vrais employés pour voir la paie et les statistiques.',
    employeeName: 'Nom de l’employé',
    department: 'Département',
    salary: 'Salaire',
    bonus: 'Prime',
    payrollDueDay: 'Jour de paie',
    payrollDue: 'Échéance de paie',
    payrollReminder: 'Rappel de paie',
    payrollReminder7: 'La paie des employés est due dans 7 jours.',
    payrollReminder3: 'La paie des employés est due dans 3 jours.',
    payrollReminderToday: 'La paie des employés est due aujourd’hui.',
    openEmployeesPayroll: 'Ouvrir employés et paie',
    totalAllowances: 'Total des primes',
    totalMonthlyCost: 'Coût mensuel total',
    nearestPayrollDate: 'Prochaine date de paie',
    joinDate: 'Date d’arrivée',
    active: 'Actif',
    onLeave: 'En congé',
    inactive: 'Inactif',
    totalMonthlyPayroll: 'Paie mensuelle totale',
    totalEmployees: 'Total employés',
    activeEmployees: 'Employés actifs',
    averageSalary: 'Salaire moyen',
    searchEmployees: 'Rechercher employé, rôle ou département...',
    allDepartments: 'Tous les départements',
    gridView: 'Vue cartes',
    tableView: 'Vue tableau',
    saveEmployee: 'Enregistrer l’employé',
    updateEmployee: 'Enregistrer',
    employeeSaved: 'Employé enregistré.',
    employeeDeleted: 'Employé supprimé.',
    confirmDeleteEmployee: 'Voulez-vous supprimer cet employé ?',
    loading: 'Chargement des données...',
    loadError: 'Impossible de charger les données pour le moment.',
    partialLoadWarning: 'Certaines sections n’ont pas pu être chargées, mais les données disponibles restent affichées.',
    retry: 'Réessayer',
    saveError: 'Impossible d’enregistrer les données pour le moment.',
    deleteError: 'Impossible de supprimer cet enregistrement pour le moment.',
    edit: 'Modifier',
    delete: 'Supprimer',
    cancel: 'Annuler',
    search: 'Rechercher',
    clear: 'Effacer',
    requiredField: 'Ce champ est requis.',
    invalidAmount: 'Saisissez un montant valide.',
    backToOperations: 'Retour aux opérations commerciales',
  },
} as const;

export function normalizeBusinessLang(lang?: string): BusinessLang {
  return lang === 'en' || lang === 'fr' || lang === 'ar' ? lang : 'ar';
}

export function saleStatusLabel(status: string | null | undefined, lang: BusinessLang) {
  const text = BUSINESS_TEXT[lang];
  if (status === 'completed') return text.completed;
  if (status === 'canceled') return text.canceled;
  return text.pending;
}

export function employeeStatusLabel(status: string | null | undefined, lang: BusinessLang) {
  const text = BUSINESS_TEXT[lang];
  if (status === 'on_leave') return text.onLeave;
  if (status === 'inactive') return text.inactive;
  return text.active;
}

export function businessRoleLabel(role: string | null | undefined, lang: BusinessLang) {
  const text = BUSINESS_TEXT[lang];
  if (role === 'accountant') return text.accountant;
  if (role === 'employee') return text.employee;
  return text.manager;
}

export function businessPermissions(role: BusinessRole) {
  return {
    canViewSales: role === 'manager' || role === 'accountant',
    canWriteSales: role === 'manager' || role === 'accountant',
    canDeleteSales: role === 'manager',
    canViewEmployees: role === 'manager' || role === 'accountant',
    canWriteEmployees: role === 'manager',
    canDeleteEmployees: role === 'manager',
    canViewPayrollTotals: role === 'manager' || role === 'accountant',
    canExport: role === 'manager' || role === 'accountant',
    canManageSettings: role === 'manager',
  };
}

export function numericValue(value: unknown) {
  if (typeof value === 'string') {
    const parsed = Number(value.replace(/[^\d.-]/g, ''));
    return Number.isFinite(parsed) ? parsed : 0;
  }
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : 0;
}
