export type BusinessLang = 'ar' | 'en' | 'fr';

export type SaleStatus = 'completed' | 'pending' | 'canceled';
export type EmployeeStatus = 'active' | 'on_leave' | 'inactive';

export const SALE_STATUS_OPTIONS: SaleStatus[] = ['completed', 'pending', 'canceled'];
export const EMPLOYEE_STATUS_OPTIONS: EmployeeStatus[] = ['active', 'on_leave', 'inactive'];

export const BUSINESS_TEXT = {
  ar: {
    businessOperations: 'إدارة الأعمال',
    businessOperationsSubtitle: 'نظّم مبيعاتك، موظفيك، فواتيرك، وعناصر التشغيل من مكان واحد.',
    operationsBadge: 'عمليات الأعمال',
    sales: 'المبيعات',
    salesDescription: 'تابع عمليات البيع والفواتير والإيرادات التجارية.',
    openSales: 'فتح المبيعات',
    employees: 'الموظفين والرواتب',
    employeesDescription: 'نظّم بيانات الموظفين والرواتب والبدلات.',
    openEmployees: 'فتح الموظفين',
    customers: 'العملاء',
    invoices: 'الفواتير',
    suppliers: 'الموردين',
    operatingExpenses: 'المصروفات التشغيلية',
    comingSoon: 'قريباً',
    noDataYet: 'لا توجد بيانات حتى الآن.',
    addSale: 'إضافة عملية بيع',
    editSale: 'تعديل عملية بيع',
    deleteSale: 'حذف عملية بيع',
    noSalesYet: 'لا توجد عمليات بيع حتى الآن.',
    saleEmptyBody: 'أضف أول عملية بيع حقيقية لعرض الإجماليات والفواتير.',
    invoiceNumber: 'رقم الفاتورة',
    customer: 'العميل',
    customerName: 'اسم العميل',
    productService: 'المنتج / الخدمة',
    amount: 'المبلغ',
    currency: 'العملة',
    status: 'الحالة',
    saleDate: 'تاريخ البيع',
    notes: 'ملاحظات',
    completed: 'مكتمل',
    pending: 'قيد المعالجة',
    canceled: 'ملغي',
    totalSales: 'إجمالي المبيعات',
    completedSales: 'العمليات المكتملة',
    pendingSales: 'قيد المعالجة',
    canceledSales: 'الملغية',
    searchSales: 'ابحث عن عميل أو فاتورة أو خدمة...',
    allStatuses: 'كل الحالات',
    saveSale: 'حفظ عملية البيع',
    updateSale: 'حفظ التعديل',
    saleSaved: 'تم حفظ عملية البيع.',
    saleDeleted: 'تم حذف عملية البيع.',
    confirmDeleteSale: 'هل تريد حذف عملية البيع؟',
    addEmployee: 'إضافة موظف',
    editEmployee: 'تعديل موظف',
    deleteEmployee: 'حذف موظف',
    noEmployeesYet: 'لا يوجد موظفون حتى الآن.',
    employeeEmptyBody: 'أضف بيانات الموظفين الحقيقية لعرض الرواتب والإحصاءات.',
    employeeName: 'اسم الموظف',
    role: 'الدور',
    department: 'القسم',
    salary: 'الراتب',
    bonus: 'البدل / المكافأة',
    joinDate: 'تاريخ الانضمام',
    active: 'نشط',
    onLeave: 'إجازة',
    inactive: 'متوقف',
    totalMonthlyPayroll: 'إجمالي الرواتب الشهرية',
    totalEmployees: 'إجمالي الموظفين',
    activeEmployees: 'الموظفون النشطون',
    averageSalary: 'متوسط الراتب',
    searchEmployees: 'ابحث عن موظف أو دور أو قسم...',
    allDepartments: 'كل الأقسام',
    gridView: 'عرض بطاقات',
    tableView: 'عرض جدول',
    saveEmployee: 'حفظ الموظف',
    updateEmployee: 'حفظ التعديل',
    employeeSaved: 'تم حفظ بيانات الموظف.',
    employeeDeleted: 'تم حذف الموظف.',
    confirmDeleteEmployee: 'هل تريد حذف هذا الموظف؟',
    loading: 'جاري التحميل...',
    loadError: 'تعذر تحميل البيانات حالياً.',
    saveError: 'تعذر حفظ البيانات حالياً.',
    deleteError: 'تعذر حذف السجل حالياً.',
    edit: 'تعديل',
    delete: 'حذف',
    cancel: 'إلغاء',
    search: 'بحث',
    clear: 'مسح',
    requiredField: 'هذا الحقل مطلوب.',
    invalidAmount: 'أدخل مبلغاً صحيحاً.',
    backToOperations: 'العودة إلى إدارة الأعمال',
  },
  en: {
    businessOperations: 'Business Operations',
    businessOperationsSubtitle: 'Organize your sales, employees, invoices, and operations from one place.',
    operationsBadge: 'Business operations',
    sales: 'Sales',
    salesDescription: 'Track sales, invoices, and business revenue.',
    openSales: 'Open Sales',
    employees: 'Employees & Payroll',
    employeesDescription: 'Organize employee records, salaries, and allowances.',
    openEmployees: 'Open Employees',
    customers: 'Customers',
    invoices: 'Invoices',
    suppliers: 'Suppliers',
    operatingExpenses: 'Operating Expenses',
    comingSoon: 'Coming soon',
    noDataYet: 'No data yet.',
    addSale: 'Add Sale',
    editSale: 'Edit Sale',
    deleteSale: 'Delete Sale',
    noSalesYet: 'No sales yet.',
    saleEmptyBody: 'Add your first real sale to see totals and invoices.',
    invoiceNumber: 'Invoice Number',
    customer: 'Customer',
    customerName: 'Customer Name',
    productService: 'Product / Service',
    amount: 'Amount',
    currency: 'Currency',
    status: 'Status',
    saleDate: 'Sale Date',
    notes: 'Notes',
    completed: 'Completed',
    pending: 'Pending',
    canceled: 'Canceled',
    totalSales: 'Total Sales',
    completedSales: 'Completed Sales',
    pendingSales: 'Pending',
    canceledSales: 'Canceled',
    searchSales: 'Search customer, invoice, or service...',
    allStatuses: 'All statuses',
    saveSale: 'Save Sale',
    updateSale: 'Save Changes',
    saleSaved: 'Sale saved.',
    saleDeleted: 'Sale deleted.',
    confirmDeleteSale: 'Do you want to delete this sale?',
    addEmployee: 'Add Employee',
    editEmployee: 'Edit Employee',
    deleteEmployee: 'Delete Employee',
    noEmployeesYet: 'No employees yet.',
    employeeEmptyBody: 'Add real employee records to see payroll and stats.',
    employeeName: 'Employee Name',
    role: 'Role',
    department: 'Department',
    salary: 'Salary',
    bonus: 'Bonus',
    joinDate: 'Join Date',
    active: 'Active',
    onLeave: 'On Leave',
    inactive: 'Inactive',
    totalMonthlyPayroll: 'Total Monthly Payroll',
    totalEmployees: 'Total Employees',
    activeEmployees: 'Active Employees',
    averageSalary: 'Average Salary',
    searchEmployees: 'Search employee, role, or department...',
    allDepartments: 'All departments',
    gridView: 'Grid view',
    tableView: 'Table view',
    saveEmployee: 'Save Employee',
    updateEmployee: 'Save Changes',
    employeeSaved: 'Employee saved.',
    employeeDeleted: 'Employee deleted.',
    confirmDeleteEmployee: 'Do you want to delete this employee?',
    loading: 'Loading...',
    loadError: 'Could not load data right now.',
    saveError: 'Could not save data right now.',
    deleteError: 'Could not delete the record right now.',
    edit: 'Edit',
    delete: 'Delete',
    cancel: 'Cancel',
    search: 'Search',
    clear: 'Clear',
    requiredField: 'This field is required.',
    invalidAmount: 'Enter a valid amount.',
    backToOperations: 'Back to Business Operations',
  },
  fr: {
    businessOperations: 'Opérations commerciales',
    businessOperationsSubtitle: 'Organisez vos ventes, employés, factures et opérations depuis un seul endroit.',
    operationsBadge: 'Opérations commerciales',
    sales: 'Ventes',
    salesDescription: 'Suivez les ventes, factures et revenus commerciaux.',
    openSales: 'Ouvrir les ventes',
    employees: 'Employés et paie',
    employeesDescription: 'Organisez les dossiers employés, salaires et primes.',
    openEmployees: 'Ouvrir les employés',
    customers: 'Clients',
    invoices: 'Factures',
    suppliers: 'Fournisseurs',
    operatingExpenses: 'Dépenses opérationnelles',
    comingSoon: 'Bientôt disponible',
    noDataYet: 'Aucune donnée pour le moment.',
    addSale: 'Ajouter une vente',
    editSale: 'Modifier la vente',
    deleteSale: 'Supprimer la vente',
    noSalesYet: 'Aucune vente pour le moment.',
    saleEmptyBody: 'Ajoutez votre première vente réelle pour voir les totaux et factures.',
    invoiceNumber: 'Numéro de facture',
    customer: 'Client',
    customerName: 'Nom du client',
    productService: 'Produit / Service',
    amount: 'Montant',
    currency: 'Devise',
    status: 'Statut',
    saleDate: 'Date de vente',
    notes: 'Notes',
    completed: 'Terminée',
    pending: 'En traitement',
    canceled: 'Annulée',
    totalSales: 'Ventes totales',
    completedSales: 'Ventes terminées',
    pendingSales: 'En traitement',
    canceledSales: 'Annulées',
    searchSales: 'Rechercher client, facture ou service...',
    allStatuses: 'Tous les statuts',
    saveSale: 'Enregistrer la vente',
    updateSale: 'Enregistrer',
    saleSaved: 'Vente enregistrée.',
    saleDeleted: 'Vente supprimée.',
    confirmDeleteSale: 'Voulez-vous supprimer cette vente ?',
    addEmployee: 'Ajouter un employé',
    editEmployee: 'Modifier l’employé',
    deleteEmployee: 'Supprimer l’employé',
    noEmployeesYet: 'Aucun employé pour le moment.',
    employeeEmptyBody: 'Ajoutez de vrais employés pour voir la paie et les statistiques.',
    employeeName: 'Nom de l’employé',
    role: 'Rôle',
    department: 'Département',
    salary: 'Salaire',
    bonus: 'Prime',
    joinDate: 'Date d’arrivée',
    active: 'Actif',
    onLeave: 'En congé',
    inactive: 'Inactif',
    totalMonthlyPayroll: 'Paie mensuelle totale',
    totalEmployees: 'Total employés',
    activeEmployees: 'Employés actifs',
    averageSalary: 'Salaire moyen',
    searchEmployees: 'Rechercher employé, rôle ou département...',
    allDepartments: 'Tous les départements',
    gridView: 'Vue cartes',
    tableView: 'Vue tableau',
    saveEmployee: 'Enregistrer l’employé',
    updateEmployee: 'Enregistrer',
    employeeSaved: 'Employé enregistré.',
    employeeDeleted: 'Employé supprimé.',
    confirmDeleteEmployee: 'Voulez-vous supprimer cet employé ?',
    loading: 'Chargement...',
    loadError: 'Impossible de charger les données pour le moment.',
    saveError: 'Impossible d’enregistrer les données pour le moment.',
    deleteError: 'Impossible de supprimer cet enregistrement pour le moment.',
    edit: 'Modifier',
    delete: 'Supprimer',
    cancel: 'Annuler',
    search: 'Rechercher',
    clear: 'Effacer',
    requiredField: 'Ce champ est requis.',
    invalidAmount: 'Saisissez un montant valide.',
    backToOperations: 'Retour aux opérations commerciales',
  },
} as const;

export function normalizeBusinessLang(lang?: string): BusinessLang {
  return lang === 'en' || lang === 'fr' || lang === 'ar' ? lang : 'ar';
}

export function saleStatusLabel(status: string | null | undefined, lang: BusinessLang) {
  const text = BUSINESS_TEXT[lang];
  if (status === 'completed') return text.completed;
  if (status === 'canceled') return text.canceled;
  return text.pending;
}

export function employeeStatusLabel(status: string | null | undefined, lang: BusinessLang) {
  const text = BUSINESS_TEXT[lang];
  if (status === 'on_leave') return text.onLeave;
  if (status === 'inactive') return text.inactive;
  return text.active;
}

export function numericValue(value: unknown) {
  if (typeof value === 'string') {
    const parsed = Number(value.replace(/[^\d.-]/g, ''));
    return Number.isFinite(parsed) ? parsed : 0;
  }
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : 0;
}
