import {
  BellRing,
  BookOpen,
  Bot,
  BriefcaseBusiness,
  Calculator,
  CheckCircle2,
  FileText,
  FolderKanban,
  HandHeart,
  PiggyBank,
  Presentation,
  ReceiptText,
  ShieldCheck,
  Sparkles,
  Target,
  TrendingUp,
  Wallet,
} from 'lucide-react';

export const landingNavigation = {
  home: { href: '/dashboard', labelKey: 'nav_home', icon: Wallet },
  income: { href: '/income', labelKey: 'nav_income', icon: Wallet },
  expenses: { href: '/expenses', labelKey: 'nav_expenses', icon: ReceiptText },
  goals: { href: '/goals', labelKey: 'nav_goals', icon: Target },
  savings: { href: '/savings', labelKey: 'nav_savings', icon: PiggyBank },
  invest: { href: '/invest', labelKey: 'nav_invest', icon: TrendingUp },
  'ai-analyst': { href: '/ai-analyst/overview', labelKey: 'nav_ai_analyst', icon: Bot },
  decisions: { href: '/decisions', labelKey: 'nav_decisions', icon: CheckCircle2 },
  'smart-assistant': { href: '/ai', labelKey: 'nav_smart_assistant', icon: Sparkles },
  'reports-center': { href: '/reports-center', labelKey: 'nav_reports_center', icon: FileText },
  'documents-center': { href: '/documents', labelKey: 'nav_documents_center', icon: FileText },
  'business-operations': { href: '/business-operations', labelKey: 'nav_business_operations', icon: BriefcaseBusiness },
  projects: { href: '/projects', labelKey: 'nav_projects', icon: FolderKanban },
  'investment-offers': { href: '/investment-offers', labelKey: 'nav_pitch_decks', icon: Presentation },
  zakat: { href: '/zakat', labelKey: 'nav_zakat', icon: Calculator },
  charity: { href: '/charity', labelKey: 'nav_charity', icon: HandHeart },
  'financial-theories': { href: '/financial-theories', labelKey: 'nav_financial_theories', icon: BookOpen },
  tasks: { href: '/tasks', labelKey: 'nav_tasks', icon: CheckCircle2 },
  notif: { href: '/notifications', labelKey: 'nav_notif', icon: BellRing },
  security: { href: '/security', labelKey: 'nav_security', icon: ShieldCheck },
  profile: { href: '/profile', labelKey: 'nav_profile', icon: Wallet },
} as const;

export type LandingNavigationId = keyof typeof landingNavigation;
