// Current tender codes from SIX / ISO 4217, published 2026-09-17.
// Source: https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/lists/list-one.xml
// Keep this deterministic across browser ICU versions. Funds, metals and test codes are not purchase currencies.
export const WORLD_CURRENCY_METADATA: Record<string, { name: string; decimals: number; country: string }> = {
  AED: {"name": "UAE Dirham", "decimals": 2, "country": "UNITED ARAB EMIRATES (THE)"},
  AFN: {"name": "Afghani", "decimals": 2, "country": "AFGHANISTAN"},
  ALL: {"name": "Lek", "decimals": 2, "country": "ALBANIA"},
  AMD: {"name": "Armenian Dram", "decimals": 2, "country": "ARMENIA"},
  AOA: {"name": "Kwanza", "decimals": 2, "country": "ANGOLA"},
  ARS: {"name": "Argentine Peso", "decimals": 2, "country": "ARGENTINA"},
  AUD: {"name": "Australian Dollar", "decimals": 2, "country": "AUSTRALIA, CHRISTMAS ISLAND, COCOS (KEELING) ISLANDS (THE), HEARD ISLAND AND McDONALD ISLANDS, KIRIBATI, NAURU, NORFOLK ISLAND, TUVALU"},
  AWG: {"name": "Aruban Florin", "decimals": 2, "country": "ARUBA"},
  AZN: {"name": "Azerbaijan Manat", "decimals": 2, "country": "AZERBAIJAN"},
  BAM: {"name": "Convertible Mark", "decimals": 2, "country": "BOSNIA AND HERZEGOVINA"},
  BBD: {"name": "Barbados Dollar", "decimals": 2, "country": "BARBADOS"},
  BDT: {"name": "Taka", "decimals": 2, "country": "BANGLADESH"},
  BHD: {"name": "Bahraini Dinar", "decimals": 3, "country": "BAHRAIN"},
  BIF: {"name": "Burundi Franc", "decimals": 0, "country": "BURUNDI"},
  BMD: {"name": "Bermudian Dollar", "decimals": 2, "country": "BERMUDA"},
  BND: {"name": "Brunei Dollar", "decimals": 2, "country": "BRUNEI DARUSSALAM"},
  BOB: {"name": "Boliviano", "decimals": 2, "country": "BOLIVIA (PLURINATIONAL STATE OF)"},
  BRL: {"name": "Brazilian Real", "decimals": 2, "country": "BRAZIL"},
  BSD: {"name": "Bahamian Dollar", "decimals": 2, "country": "BAHAMAS (THE)"},
  BTN: {"name": "Ngultrum", "decimals": 2, "country": "BHUTAN"},
  BWP: {"name": "Pula", "decimals": 2, "country": "BOTSWANA"},
  BYN: {"name": "Belarusian Ruble", "decimals": 2, "country": "BELARUS"},
  BZD: {"name": "Belize Dollar", "decimals": 2, "country": "BELIZE"},
  CAD: {"name": "Canadian Dollar", "decimals": 2, "country": "CANADA"},
  CDF: {"name": "Congolese Franc", "decimals": 2, "country": "CONGO (THE DEMOCRATIC REPUBLIC OF THE)"},
  CHF: {"name": "Swiss Franc", "decimals": 2, "country": "LIECHTENSTEIN, SWITZERLAND"},
  CLP: {"name": "Chilean Peso", "decimals": 0, "country": "CHILE"},
  CNY: {"name": "Yuan Renminbi", "decimals": 2, "country": "CHINA"},
  COP: {"name": "Colombian Peso", "decimals": 2, "country": "COLOMBIA"},
  CRC: {"name": "Costa Rican Colon", "decimals": 2, "country": "COSTA RICA"},
  CUP: {"name": "Cuban Peso", "decimals": 2, "country": "CUBA"},
  CVE: {"name": "Cabo Verde Escudo", "decimals": 2, "country": "CABO VERDE"},
  CZK: {"name": "Czech Koruna", "decimals": 2, "country": "CZECHIA"},
  DJF: {"name": "Djibouti Franc", "decimals": 0, "country": "DJIBOUTI"},
  DKK: {"name": "Danish Krone", "decimals": 2, "country": "DENMARK, FAROE ISLANDS (THE), GREENLAND"},
  DOP: {"name": "Dominican Peso", "decimals": 2, "country": "DOMINICAN REPUBLIC (THE)"},
  DZD: {"name": "Algerian Dinar", "decimals": 2, "country": "ALGERIA"},
  EGP: {"name": "Egyptian Pound", "decimals": 2, "country": "EGYPT"},
  ERN: {"name": "Nakfa", "decimals": 2, "country": "ERITREA"},
  ETB: {"name": "Ethiopian Birr", "decimals": 2, "country": "ETHIOPIA"},
  EUR: {"name": "Euro", "decimals": 2, "country": "ÅLAND ISLANDS, ANDORRA, AUSTRIA, BELGIUM, BULGARIA, CROATIA, CYPRUS, ESTONIA, EUROPEAN UNION, FINLAND, FRANCE, FRENCH GUIANA, FRENCH SOUTHERN TERRITORIES (THE), GERMANY, GREECE, GUADELOUPE, HOLY SEE (THE), IRELAND, ITALY, LATVIA, LITHUANIA, LUXEMBOURG, MALTA, MARTINIQUE, MAYOTTE, MONACO, MONTENEGRO, NETHERLANDS (THE), PORTUGAL, RÉUNION, SAINT BARTHÉLEMY, SAINT MARTIN (FRENCH PART), SAINT PIERRE AND MIQUELON, SAN MARINO, SLOVAKIA, SLOVENIA, SPAIN"},
  FJD: {"name": "Fiji Dollar", "decimals": 2, "country": "FIJI"},
  FKP: {"name": "Falkland Islands Pound", "decimals": 2, "country": "FALKLAND ISLANDS (THE) [MALVINAS]"},
  GBP: {"name": "Pound Sterling", "decimals": 2, "country": "GUERNSEY, ISLE OF MAN, JERSEY, UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)"},
  GEL: {"name": "Lari", "decimals": 2, "country": "GEORGIA"},
  GHS: {"name": "Ghana Cedi", "decimals": 2, "country": "GHANA"},
  GIP: {"name": "Gibraltar Pound", "decimals": 2, "country": "GIBRALTAR"},
  GMD: {"name": "Dalasi", "decimals": 2, "country": "GAMBIA (THE)"},
  GNF: {"name": "Guinean Franc", "decimals": 0, "country": "GUINEA"},
  GTQ: {"name": "Quetzal", "decimals": 2, "country": "GUATEMALA"},
  GYD: {"name": "Guyana Dollar", "decimals": 2, "country": "GUYANA"},
  HKD: {"name": "Hong Kong Dollar", "decimals": 2, "country": "HONG KONG"},
  HNL: {"name": "Lempira", "decimals": 2, "country": "HONDURAS"},
  HTG: {"name": "Gourde", "decimals": 2, "country": "HAITI"},
  HUF: {"name": "Forint", "decimals": 2, "country": "HUNGARY"},
  IDR: {"name": "Rupiah", "decimals": 2, "country": "INDONESIA"},
  ILS: {"name": "New Israeli Sheqel", "decimals": 2, "country": "ISRAEL"},
  INR: {"name": "Indian Rupee", "decimals": 2, "country": "BHUTAN, INDIA"},
  IQD: {"name": "Iraqi Dinar", "decimals": 3, "country": "IRAQ"},
  IRR: {"name": "Iranian Rial", "decimals": 2, "country": "IRAN (ISLAMIC REPUBLIC OF)"},
  ISK: {"name": "Iceland Krona", "decimals": 0, "country": "ICELAND"},
  JMD: {"name": "Jamaican Dollar", "decimals": 2, "country": "JAMAICA"},
  JOD: {"name": "Jordanian Dinar", "decimals": 3, "country": "JORDAN"},
  JPY: {"name": "Yen", "decimals": 0, "country": "JAPAN"},
  KES: {"name": "Kenyan Shilling", "decimals": 2, "country": "KENYA"},
  KGS: {"name": "Som", "decimals": 2, "country": "KYRGYZSTAN"},
  KHR: {"name": "Riel", "decimals": 2, "country": "CAMBODIA"},
  KMF: {"name": "Comorian Franc", "decimals": 0, "country": "COMOROS (THE)"},
  KPW: {"name": "North Korean Won", "decimals": 2, "country": "KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)"},
  KRW: {"name": "Won", "decimals": 0, "country": "KOREA (THE REPUBLIC OF)"},
  KWD: {"name": "Kuwaiti Dinar", "decimals": 3, "country": "KUWAIT"},
  KYD: {"name": "Cayman Islands Dollar", "decimals": 2, "country": "CAYMAN ISLANDS (THE)"},
  KZT: {"name": "Tenge", "decimals": 2, "country": "KAZAKHSTAN"},
  LAK: {"name": "Lao Kip", "decimals": 2, "country": "LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)"},
  LBP: {"name": "Lebanese Pound", "decimals": 2, "country": "LEBANON"},
  LKR: {"name": "Sri Lanka Rupee", "decimals": 2, "country": "SRI LANKA"},
  LRD: {"name": "Liberian Dollar", "decimals": 2, "country": "LIBERIA"},
  LSL: {"name": "Loti", "decimals": 2, "country": "LESOTHO"},
  LYD: {"name": "Libyan Dinar", "decimals": 3, "country": "LIBYA"},
  MAD: {"name": "Moroccan Dirham", "decimals": 2, "country": "MOROCCO, WESTERN SAHARA"},
  MDL: {"name": "Moldovan Leu", "decimals": 2, "country": "MOLDOVA (THE REPUBLIC OF)"},
  MGA: {"name": "Malagasy Ariary", "decimals": 2, "country": "MADAGASCAR"},
  MKD: {"name": "Denar", "decimals": 2, "country": "NORTH MACEDONIA"},
  MMK: {"name": "Kyat", "decimals": 2, "country": "MYANMAR"},
  MNT: {"name": "Tugrik", "decimals": 2, "country": "MONGOLIA"},
  MOP: {"name": "Pataca", "decimals": 2, "country": "MACAO"},
  MRU: {"name": "Ouguiya", "decimals": 2, "country": "MAURITANIA"},
  MUR: {"name": "Mauritius Rupee", "decimals": 2, "country": "MAURITIUS"},
  MVR: {"name": "Rufiyaa", "decimals": 2, "country": "MALDIVES"},
  MWK: {"name": "Malawi Kwacha", "decimals": 2, "country": "MALAWI"},
  MXN: {"name": "Mexican Peso", "decimals": 2, "country": "MEXICO"},
  MYR: {"name": "Malaysian Ringgit", "decimals": 2, "country": "MALAYSIA"},
  MZN: {"name": "Mozambique Metical", "decimals": 2, "country": "MOZAMBIQUE"},
  NAD: {"name": "Namibia Dollar", "decimals": 2, "country": "NAMIBIA"},
  NGN: {"name": "Naira", "decimals": 2, "country": "NIGERIA"},
  NIO: {"name": "Cordoba Oro", "decimals": 2, "country": "NICARAGUA"},
  NOK: {"name": "Norwegian Krone", "decimals": 2, "country": "BOUVET ISLAND, NORWAY, SVALBARD AND JAN MAYEN"},
  NPR: {"name": "Nepalese Rupee", "decimals": 2, "country": "NEPAL"},
  NZD: {"name": "New Zealand Dollar", "decimals": 2, "country": "COOK ISLANDS (THE), NEW ZEALAND, NIUE, PITCAIRN, TOKELAU"},
  OMR: {"name": "Rial Omani", "decimals": 3, "country": "OMAN"},
  PAB: {"name": "Balboa", "decimals": 2, "country": "PANAMA"},
  PEN: {"name": "Sol", "decimals": 2, "country": "PERU"},
  PGK: {"name": "Kina", "decimals": 2, "country": "PAPUA NEW GUINEA"},
  PHP: {"name": "Philippine Peso", "decimals": 2, "country": "PHILIPPINES (THE)"},
  PKR: {"name": "Pakistan Rupee", "decimals": 2, "country": "PAKISTAN"},
  PLN: {"name": "Zloty", "decimals": 2, "country": "POLAND"},
  PYG: {"name": "Guarani", "decimals": 0, "country": "PARAGUAY"},
  QAR: {"name": "Qatari Rial", "decimals": 2, "country": "QATAR"},
  RON: {"name": "Romanian Leu", "decimals": 2, "country": "ROMANIA"},
  RSD: {"name": "Serbian Dinar", "decimals": 2, "country": "SERBIA"},
  RUB: {"name": "Russian Ruble", "decimals": 2, "country": "RUSSIAN FEDERATION (THE)"},
  RWF: {"name": "Rwanda Franc", "decimals": 0, "country": "RWANDA"},
  SAR: {"name": "Saudi Riyal", "decimals": 2, "country": "SAUDI ARABIA"},
  SBD: {"name": "Solomon Islands Dollar", "decimals": 2, "country": "SOLOMON ISLANDS"},
  SCR: {"name": "Seychelles Rupee", "decimals": 2, "country": "SEYCHELLES"},
  SDG: {"name": "Sudanese Pound", "decimals": 2, "country": "SUDAN (THE)"},
  SEK: {"name": "Swedish Krona", "decimals": 2, "country": "SWEDEN"},
  SGD: {"name": "Singapore Dollar", "decimals": 2, "country": "SINGAPORE"},
  SHP: {"name": "Saint Helena Pound", "decimals": 2, "country": "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA"},
  SLE: {"name": "Leone", "decimals": 2, "country": "SIERRA LEONE"},
  SOS: {"name": "Somali Shilling", "decimals": 2, "country": "SOMALIA"},
  SRD: {"name": "Surinam Dollar", "decimals": 2, "country": "SURINAME"},
  SSP: {"name": "South Sudanese Pound", "decimals": 2, "country": "SOUTH SUDAN"},
  STN: {"name": "Dobra", "decimals": 2, "country": "SAO TOME AND PRINCIPE"},
  SVC: {"name": "El Salvador Colon", "decimals": 2, "country": "EL SALVADOR"},
  SYP: {"name": "Syrian Pound", "decimals": 2, "country": "SYRIAN ARAB REPUBLIC"},
  SZL: {"name": "Lilangeni", "decimals": 2, "country": "ESWATINI"},
  THB: {"name": "Baht", "decimals": 2, "country": "THAILAND"},
  TJS: {"name": "Somoni", "decimals": 2, "country": "TAJIKISTAN"},
  TMT: {"name": "Turkmenistan New Manat", "decimals": 2, "country": "TURKMENISTAN"},
  TND: {"name": "Tunisian Dinar", "decimals": 3, "country": "TUNISIA"},
  TOP: {"name": "Pa’anga", "decimals": 2, "country": "TONGA"},
  TRY: {"name": "Turkish Lira", "decimals": 2, "country": "TÜRKİYE"},
  TTD: {"name": "Trinidad and Tobago Dollar", "decimals": 2, "country": "TRINIDAD AND TOBAGO"},
  TWD: {"name": "New Taiwan Dollar", "decimals": 2, "country": "TAIWAN (PROVINCE OF CHINA)"},
  TZS: {"name": "Tanzanian Shilling", "decimals": 2, "country": "TANZANIA, UNITED REPUBLIC OF"},
  UAH: {"name": "Hryvnia", "decimals": 2, "country": "UKRAINE"},
  UGX: {"name": "Uganda Shilling", "decimals": 0, "country": "UGANDA"},
  USD: {"name": "US Dollar", "decimals": 2, "country": "AMERICAN SAMOA, BONAIRE, SINT EUSTATIUS AND SABA, BRITISH INDIAN OCEAN TERRITORY (THE), ECUADOR, EL SALVADOR, GUAM, HAITI, MARSHALL ISLANDS (THE), MICRONESIA (FEDERATED STATES OF), NORTHERN MARIANA ISLANDS (THE), PALAU, PANAMA, PUERTO RICO, TIMOR-LESTE, TURKS AND CAICOS ISLANDS (THE), UNITED STATES MINOR OUTLYING ISLANDS (THE), UNITED STATES OF AMERICA (THE), VIRGIN ISLANDS (BRITISH), VIRGIN ISLANDS (U.S.)"},
  UYU: {"name": "Peso Uruguayo", "decimals": 2, "country": "URUGUAY"},
  UZS: {"name": "Uzbekistan Sum", "decimals": 2, "country": "UZBEKISTAN"},
  VED: {"name": "Bolívar Soberano", "decimals": 2, "country": "VENEZUELA (BOLIVARIAN REPUBLIC OF)"},
  VES: {"name": "Bolívar Soberano", "decimals": 2, "country": "VENEZUELA (BOLIVARIAN REPUBLIC OF)"},
  VND: {"name": "Dong", "decimals": 0, "country": "VIET NAM"},
  VUV: {"name": "Vatu", "decimals": 0, "country": "VANUATU"},
  WST: {"name": "Tala", "decimals": 2, "country": "SAMOA"},
  XAF: {"name": "CFA Franc BEAC", "decimals": 0, "country": "CAMEROON, CENTRAL AFRICAN REPUBLIC (THE), CHAD, CONGO (THE), EQUATORIAL GUINEA, GABON"},
  XCD: {"name": "East Caribbean Dollar", "decimals": 2, "country": "ANGUILLA, ANTIGUA AND BARBUDA, DOMINICA, GRENADA, MONTSERRAT, SAINT KITTS AND NEVIS, SAINT LUCIA, SAINT VINCENT AND THE GRENADINES"},
  XCG: {"name": "Caribbean Guilder", "decimals": 2, "country": "CURAÇAO, SINT MAARTEN (DUTCH PART)"},
  XOF: {"name": "CFA Franc BCEAO", "decimals": 0, "country": "BENIN, BURKINA FASO, CÔTE D'IVOIRE, GUINEA-BISSAU, MALI, NIGER (THE), SENEGAL, TOGO"},
  XPF: {"name": "CFP Franc", "decimals": 0, "country": "FRENCH POLYNESIA, NEW CALEDONIA, WALLIS AND FUTUNA"},
  YER: {"name": "Yemeni Rial", "decimals": 2, "country": "YEMEN"},
  ZAR: {"name": "Rand", "decimals": 2, "country": "LESOTHO, NAMIBIA, SOUTH AFRICA"},
  ZMW: {"name": "Zambian Kwacha", "decimals": 2, "country": "ZAMBIA"},
  ZWG: {"name": "Zimbabwe Gold", "decimals": 2, "country": "ZIMBABWE"},
};
