'use client';
import { useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { usePrivateResource } from './usePrivateResource';
import { Button } from '@/components/ui/button';
import styles from './platform.module.css';
const copy={ar:{title:'ملفي في SFMer',handle:'اسم المستخدم الفريد (حروف إنجليزية وأرقام و _)',name:'الاسم الظاهر',bio:'نبذة',save:'حفظ الملف العام',note:'يظهر ملفك للأعضاء المسجلين فقط. الاسم ليس توثيقًا مهنيًا أو لهويتك.',error:'تعذر الحفظ؛ قد يكون اسم المستخدم مستخدمًا.',saved:'تم الحفظ'},en:{title:'My SFMer profile',handle:'Unique handle (letters, numbers and _)',name:'Display name',bio:'Bio',save:'Save public profile',note:'Visible to signed-in members only. A handle is not professional or identity verification.',error:'Could not save; the handle may already be used.',saved:'Saved'},fr:{title:'Mon profil SFMer',handle:'Identifiant unique (lettres, chiffres et _)',name:'Nom affiché',bio:'Présentation',save:'Enregistrer le profil public',note:'Visible uniquement aux membres connectés. Le pseudonyme ne vérifie ni identité ni qualifications.',error:'Impossible d’enregistrer ; identifiant peut-être déjà utilisé.',saved:'Enregistré'}};
async function load(userId:string){const r=await supabase.from('sfmer_profiles').select('handle,display_name,bio').eq('user_id',userId).maybeSingle();if(r.error)throw r.error;return r.data as {handle:string;display_name:string;bio:string}|null;}
export function SFMerProfile({language}:{language:'ar'|'en'|'fr'}){
 const text=copy[language];const {userId,data,error,refresh}=usePrivateResource(load);const [busy,setBusy]=useState(false);const [failed,setFailed]=useState(false);const [saved,setSaved]=useState(false);
 if(!userId)return null;
 return <details className={styles.card}><summary>{text.title}</summary><p>{text.note}</p>{error||failed?<p role="alert">{text.error}</p>:null}{saved?<p role="status">{text.saved}</p>:null}<form key={data?.handle??'new'} className={styles.field} onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);setFailed(false);setSaved(false);try{const r=await supabase.rpc('sfmer_save_profile',{p_handle:String(form.get('handle')),p_name:String(form.get('name')),p_bio:String(form.get('bio'))});if(r.error)throw r.error;await refresh();setSaved(true);}catch{setFailed(true);}finally{setBusy(false);}}}><label>{text.handle}<input className={styles.input} name="handle" required pattern="[a-z][a-z0-9_]{2,29}" maxLength={30} defaultValue={data?.handle} dir="ltr"/></label><label>{text.name}<input className={styles.input} name="name" required minLength={2} maxLength={60} defaultValue={data?.display_name}/></label><label>{text.bio}<textarea className={styles.input} name="bio" maxLength={500} defaultValue={data?.bio}/></label><Button disabled={busy}>{text.save}</Button></form></details>;
}
