'use client';
import { useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { usePrivateResource } from './usePrivateResource';
import { Button } from '@/components/ui/button';
import styles from './platform.module.css';
type Task={id:string;title:string;status:string;due_date:string|null;author_id:string;assignee_id:string|null};
const copy={ar:{title:'مهام الفريق',name:'المهمة',assignee:'المسؤول',unassigned:'دون تعيين',due:'الموعد',create:'إضافة مهمة',todo:'لم تبدأ',doing:'قيد التنفيذ',done:'مكتملة',remove:'حذف',error:'تعذر حفظ المهمة أو تحميلها.',empty:'لا توجد مهام.',refresh:'تحديث'},en:{title:'Team tasks',name:'Task',assignee:'Assignee',unassigned:'Unassigned',due:'Due date',create:'Add task',todo:'To do',doing:'In progress',done:'Done',remove:'Delete',error:'Could not save or load tasks.',empty:'No tasks.',refresh:'Refresh'},fr:{title:'Tâches de l’équipe',name:'Tâche',assignee:'Responsable',unassigned:'Non attribuée',due:'Échéance',create:'Ajouter',todo:'À faire',doing:'En cours',done:'Terminée',remove:'Supprimer',error:'Impossible de charger ou enregistrer.',empty:'Aucune tâche.',refresh:'Actualiser'}};
export function TeamTasks({teamId,userId,owner,members,language}:{teamId:string;userId:string;owner:boolean;members:Array<{user_id:string;display_name:string}>;language:'ar'|'en'|'fr'}){
 const text=copy[language];const [loader]=useState(()=>async()=>{const r=await supabase.from('sfm_team_tasks').select('id,title,status,due_date,author_id,assignee_id').eq('team_id',teamId).order('created_at',{ascending:false}).limit(1000);if(r.error)throw r.error;return r.data as Task[];});
 const {data,error,refresh}=usePrivateResource(loader);const [title,setTitle]=useState('');const [assignee,setAssignee]=useState('');const [due,setDue]=useState('');const [busy,setBusy]=useState(false);const [failed,setFailed]=useState(false);
 async function act(action:string,id?:string,status?:string){if(busy)return;setBusy(true);setFailed(false);try{const r=await supabase.rpc('sfm_team_task',{p_team:teamId,p_action:action,p_id:id??null,p_title:title.trim(),p_assignee:action==='create'?assignee||null:null,p_due:action==='create'?due||null:null,p_status:status??null});if(r.error)throw r.error;if(action==='create')setTitle('');await refresh();}catch{setFailed(true);}finally{setBusy(false);}}
 return <section className={styles.card}><h3>{text.title}</h3>{error||failed?<p role="alert">{text.error}</p>:null}<form className={styles.field} onSubmit={e=>{e.preventDefault();void act('create');}}><label>{text.name}<input className={styles.input} required maxLength={240} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>{text.assignee}<select className={styles.input} value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">{text.unassigned}</option>{members.map(m=><option key={m.user_id} value={m.user_id}>{m.display_name}</option>)}</select></label><label>{text.due}<input className={styles.input} type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><Button disabled={busy||!title.trim()}>{text.create}</Button></form><Button variant="outline" disabled={busy} onClick={()=>void refresh()}>{text.refresh}</Button>{data?.length===0?<p>{text.empty}</p>:null}{data?.map(task=><article key={task.id} className={styles.card}><h4>{task.title}</h4><p>{members.find(m=>m.user_id===task.assignee_id)?.display_name??text.unassigned} · <span dir="ltr">{task.due_date}</span></p><label>{text.title}<select className={styles.input} value={task.status} disabled={busy||!(owner||task.author_id===userId||task.assignee_id===userId)} onChange={e=>void act('status',task.id,e.target.value)}>{(['todo','doing','done'] as const).map(s=><option key={s} value={s}>{text[s]}</option>)}</select></label>{owner||task.author_id===userId?<Button variant="outline" disabled={busy} onClick={()=>void act('delete',task.id)}>{text.remove}</Button>:null}</article>)}</section>;
}
