import type { StockCategoryStock } from './stockCategoryConfigs';

// Research universe, not a claim that every issuer passes the growth screen.
export const GROWTH_WATCHLIST: StockCategoryStock[] = [
      { symbol: 'AMZN', name: 'Amazon', filter: 'ecommerce', filters: ['ecommerce', 'cloud', 'digital_consumption'] },
      { symbol: 'TSLA', name: 'Tesla', filter: 'electric_vehicles', filters: ['electric_vehicles', 'digital_consumption'] },
      { symbol: 'SHOP', name: 'Shopify', filter: 'ecommerce' },
      { symbol: 'CRM', name: 'Salesforce', filter: 'software' },
      { symbol: 'NOW', name: 'ServiceNow', filter: 'software' },
      { symbol: 'SNOW', name: 'Snowflake', filter: 'cloud', filters: ['software', 'cloud'] },
      { symbol: 'DDOG', name: 'Datadog', filter: 'cloud', filters: ['software', 'cloud'] },
      { symbol: 'NET', name: 'Cloudflare', filter: 'cloud' },
      { symbol: 'PLTR', name: 'Palantir', filter: 'artificial_intelligence', filters: ['software', 'artificial_intelligence'] },
      { symbol: 'UBER', name: 'Uber', filter: 'digital_consumption' },
      { symbol: 'XYZ', name: 'Block', filter: 'fintech', aliases: ['Block', 'Square'] },
      { symbol: 'MELI', name: 'MercadoLibre', filter: 'ecommerce', aliases: ['Mercado Libre'] },
      { symbol: 'RBLX', name: 'Roblox', filter: 'digital_consumption' },
      { symbol: 'ABNB', name: 'Airbnb', filter: 'digital_consumption' },
      { symbol: 'ISRG', name: 'Intuitive Surgical', filter: 'innovative_healthcare' },
      { symbol: 'TTD', name: 'The Trade Desk', filter: 'digital_consumption' },
      { symbol: 'DXCM', name: 'DexCom', filter: 'innovative_healthcare' },
      { symbol: 'CRWD', name: 'CrowdStrike', filter: 'cybersecurity', filters: ['software', 'cybersecurity'] },
      { symbol: 'ZS', name: 'Zscaler', filter: 'cybersecurity', filters: ['software', 'cybersecurity'] },
      { symbol: 'MDB', name: 'MongoDB', filter: 'software', filters: ['software', 'cloud'] },
      { symbol: 'NVDA', name: 'NVIDIA', filter: 'artificial_intelligence', filters: ['artificial_intelligence', 'semiconductors'] },
      { symbol: 'AMD', name: 'Advanced Micro Devices', filter: 'semiconductors', filters: ['semiconductors', 'artificial_intelligence'], aliases: ['AMD'] },
      { symbol: 'AVGO', name: 'Broadcom', filter: 'semiconductors' },
      { symbol: 'AAPL', name: 'Apple', filter: 'digital_consumption', filters: ['digital_consumption', 'software'], aliases: ['Apple Intelligence', 'iPhone'] },
      { symbol: 'META', name: 'Meta Platforms', filter: 'artificial_intelligence', filters: ['artificial_intelligence', 'digital_consumption'], aliases: ['Meta', 'Facebook', 'Instagram'] },
      { symbol: 'MSFT', name: 'Microsoft', filter: 'artificial_intelligence', filters: ['artificial_intelligence', 'cloud', 'software'], aliases: ['Microsoft Copilot'] },
      { symbol: 'GOOGL', name: 'Alphabet', filter: 'artificial_intelligence', filters: ['artificial_intelligence', 'cloud', 'digital_consumption'], aliases: ['Google', 'Gemini'] },
      { symbol: 'PYPL', name: 'PayPal', filter: 'fintech' },
  { symbol: 'ADBE', name: 'Adobe', filter: 'software' },
  { symbol: 'INTU', name: 'Intuit', filter: 'software' },
  { symbol: 'ORCL', name: 'Oracle', filter: 'software' },
  { symbol: 'WDAY', name: 'Workday', filter: 'software' },
  { symbol: 'ADSK', name: 'Autodesk', filter: 'software' },
  { symbol: 'TEAM', name: 'Atlassian', filter: 'software' },
  { symbol: 'HUBS', name: 'HubSpot', filter: 'software' },
  { symbol: 'VEEV', name: 'Veeva Systems', filter: 'software' },
  { symbol: 'GTLB', name: 'GitLab', filter: 'software' },
  { symbol: 'DOCU', name: 'DocuSign', filter: 'software' },
  { symbol: 'TWLO', name: 'Twilio', filter: 'software' },
  { symbol: 'ZM', name: 'Zoom Communications', filter: 'software' },
  { symbol: 'PATH', name: 'UiPath', filter: 'software' },
  { symbol: 'DUOL', name: 'Duolingo', filter: 'software' },
  { symbol: 'APP', name: 'AppLovin', filter: 'software' },
  { symbol: 'U', name: 'Unity Software', filter: 'software' },
  { symbol: 'PTC', name: 'PTC', filter: 'software' },
  { symbol: 'MNDY', name: 'monday.com', filter: 'software' },
  { symbol: 'ANET', name: 'Arista Networks', filter: 'cloud' },
  { symbol: 'NTNX', name: 'Nutanix', filter: 'cloud' },
  { symbol: 'CFLT', name: 'Confluent', filter: 'cloud' },
  { symbol: 'ESTC', name: 'Elastic', filter: 'cloud' },
  { symbol: 'DOCN', name: 'DigitalOcean', filter: 'cloud' },
  { symbol: 'FSLY', name: 'Fastly', filter: 'cloud' },
  { symbol: 'IOT', name: 'Samsara', filter: 'cloud' },
  { symbol: 'TOST', name: 'Toast', filter: 'cloud' },
  { symbol: 'MU', name: 'Micron Technology', filter: 'semiconductors' },
  { symbol: 'QCOM', name: 'Qualcomm', filter: 'semiconductors' },
  { symbol: 'TSM', name: 'Taiwan Semiconductor Manufacturing', filter: 'semiconductors' },
  { symbol: 'ASML', name: 'ASML', filter: 'semiconductors' },
  { symbol: 'ARM', name: 'Arm Holdings', filter: 'semiconductors' },
  { symbol: 'MRVL', name: 'Marvell Technology', filter: 'semiconductors' },
  { symbol: 'AMAT', name: 'Applied Materials', filter: 'semiconductors' },
  { symbol: 'LRCX', name: 'Lam Research', filter: 'semiconductors' },
  { symbol: 'KLAC', name: 'KLA', filter: 'semiconductors' },
  { symbol: 'MPWR', name: 'Monolithic Power Systems', filter: 'semiconductors' },
  { symbol: 'ON', name: 'ON Semiconductor', filter: 'semiconductors' },
  { symbol: 'NXPI', name: 'NXP Semiconductors', filter: 'semiconductors' },
  { symbol: 'ALAB', name: 'Astera Labs', filter: 'semiconductors' },
  { symbol: 'RMBS', name: 'Rambus', filter: 'semiconductors' },
  { symbol: 'SNPS', name: 'Synopsys', filter: 'semiconductors' },
  { symbol: 'CDNS', name: 'Cadence Design Systems', filter: 'semiconductors' },
  { symbol: 'PANW', name: 'Palo Alto Networks', filter: 'cybersecurity' },
  { symbol: 'FTNT', name: 'Fortinet', filter: 'cybersecurity' },
  { symbol: 'OKTA', name: 'Okta', filter: 'cybersecurity' },
  { symbol: 'S', name: 'SentinelOne', filter: 'cybersecurity' },
  { symbol: 'TENB', name: 'Tenable', filter: 'cybersecurity' },
  { symbol: 'QLYS', name: 'Qualys', filter: 'cybersecurity' },
  { symbol: 'SE', name: 'Sea', filter: 'ecommerce' },
  { symbol: 'ETSY', name: 'Etsy', filter: 'ecommerce' },
  { symbol: 'EBAY', name: 'eBay', filter: 'ecommerce' },
  { symbol: 'BABA', name: 'Alibaba Group', filter: 'ecommerce' },
  { symbol: 'PDD', name: 'PDD Holdings', filter: 'ecommerce' },
  { symbol: 'JD', name: 'JD.com', filter: 'ecommerce' },
  { symbol: 'COIN', name: 'Coinbase Global', filter: 'fintech' },
  { symbol: 'HOOD', name: 'Robinhood Markets', filter: 'fintech' },
  { symbol: 'SOFI', name: 'SoFi Technologies', filter: 'fintech' },
  { symbol: 'AFRM', name: 'Affirm Holdings', filter: 'fintech' },
  { symbol: 'NU', name: 'Nu Holdings', filter: 'fintech' },
  { symbol: 'FUTU', name: 'Futu Holdings', filter: 'fintech' },
  { symbol: 'V', name: 'Visa', filter: 'fintech' },
  { symbol: 'MA', name: 'Mastercard', filter: 'fintech' },
  { symbol: 'LLY', name: 'Eli Lilly', filter: 'innovative_healthcare' },
  { symbol: 'NVO', name: 'Novo Nordisk', filter: 'innovative_healthcare' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals', filter: 'innovative_healthcare' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals', filter: 'innovative_healthcare' },
  { symbol: 'PODD', name: 'Insulet', filter: 'innovative_healthcare' },
  { symbol: 'TMDX', name: 'TransMedics Group', filter: 'innovative_healthcare' },
  { symbol: 'NFLX', name: 'Netflix', filter: 'digital_consumption' },
  { symbol: 'SPOT', name: 'Spotify Technology', filter: 'digital_consumption' },
  { symbol: 'DASH', name: 'DoorDash', filter: 'digital_consumption' },
  { symbol: 'BKNG', name: 'Booking Holdings', filter: 'digital_consumption' },
];
