'use client';
import { useState } from 'react';
import Link from 'next/link';
import { useAuth } from '@/hooks/useAuth';
import { useLanguage } from '@/hooks/useLanguage';
import { usePrivateResource } from '@/components/platform/usePrivateResource';
import { WorkspacePageContainer } from '@/components/layout/WorkspacePageContainer';
import { Button } from '@/components/ui/button';
import styles from '@/components/platform/platform.module.css';
type Key={id:string;label:string;scopes:string[];expires_at:string;revoked_at:string|null;last_used_at:string|null};
type Snapshot={id:string;source:string;external_id:string;observed_at:string;received_at:string;payload:{currency:string;balance:number|null;equity:number|null;positions:Array<{symbol:string;quantity:number;value:number|null;currency:string}>}};
type Data={keys:Key[];snapshots:Snapshot[]};
const copy={
 ar:{title:'التطبيقات والتكاملات',note:'اربط أدواتك بمفتاح محدود الصلاحية. القراءة لا تنفذ صفقات. اللقطات الواردة مستقلة عن سجلاتك المالية ولا تغيّرها تلقائيًا.',label:'اسم التكامل',scopes:'الصلاحيات',days:'الصلاحية بالأيام (1–90)',create:'إنشاء مفتاح',once:'انسخ المفتاح الآن؛ لن يظهر مرة أخرى. احفظه في إعدادات أداتك الخاصة.',revoke:'إلغاء المفتاح',keys:'المفاتيح',received:'اللقطات المستلمة',none:'لا توجد بيانات بعد.',error:'تعذر إكمال الطلب. أعد المحاولة.',login:'تسجيل الدخول',last:'آخر استخدام',expires:'ينتهي',revoked:'ملغى',portfolio:'قراءة سجلات المحفظة',notifications:'قراءة التنبيهات',write:'إرسال لقطات خارجية',install:'تثبيت تطبيق الموقع',source:'المصدر',observed:'تاريخ المصدر',balance:'الرصيد',equity:'حقوق الحساب',unknown:'غير متاح',mt5:'تنزيل مُصدّر MT5',help:'تعليمات الربط وعقد API',limits:'يدعم MT5 مُصدّرًا يعمل من جهازك. ربط IBKR أو بنك مباشرة يحتاج موافقة وبيانات مزوّده؛ وجود مفتاح API لا يعني اتصالًا به. اللقطات بيانات أداتك ولم يُتحقق منها مستقلًا.',symbol:'الرمز',quantity:'الكمية',value:'القيمة',refresh:'تحديث'},
 en:{title:'Apps and integrations',note:'Connect tools with a scoped, expiring key. Read access never places trades. Incoming snapshots are separate and never overwrite your financial records.',label:'Integration name',scopes:'Permissions',days:'Expiry in days (1–90)',create:'Create key',once:'Copy this key now; it will not be shown again. Save it in your own tool settings.',revoke:'Revoke key',keys:'Keys',received:'Received snapshots',none:'No records yet.',error:'Could not complete the request. Please retry.',login:'Sign in',last:'Last used',expires:'Expires',revoked:'Revoked',portfolio:'Read portfolio records',notifications:'Read notifications',write:'Submit external snapshots',install:'Install the web app',source:'Source',observed:'Source timestamp',balance:'Balance',equity:'Equity',unknown:'Unavailable',mt5:'Download MT5 exporter',help:'Connection guide and API contract',limits:'MT5 uses an exporter on your computer. Direct IBKR or bank connections require provider consent and access; an API key does not establish such a connection. Snapshots are tool-supplied and not independently verified.',symbol:'Symbol',quantity:'Quantity',value:'Value',refresh:'Refresh'},
 fr:{title:'Applications et intégrations',note:'Connectez vos outils avec une clé limitée et temporaire. La lecture ne passe aucun ordre. Les instantanés reçus restent séparés de vos données financières.',label:'Nom de l’intégration',scopes:'Autorisations',days:'Validité en jours (1–90)',create:'Créer une clé',once:'Copiez cette clé maintenant ; elle ne sera plus affichée. Enregistrez-la dans votre outil.',revoke:'Révoquer',keys:'Clés',received:'Instantanés reçus',none:'Aucune donnée.',error:'Impossible de terminer. Réessayez.',login:'Connexion',last:'Dernière utilisation',expires:'Expiration',revoked:'Révoquée',portfolio:'Lire le portefeuille',notifications:'Lire les notifications',write:'Envoyer des instantanés',install:'Installer l’application web',source:'Source',observed:'Date de la source',balance:'Solde',equity:'Fonds propres',unknown:'Indisponible',mt5:'Télécharger l’exportateur MT5',help:'Guide et contrat API',limits:'MT5 utilise un exportateur sur votre ordinateur. Une connexion directe IBKR ou bancaire exige un accès fournisseur ; une clé ne constitue pas cette connexion. Les instantanés ne sont pas vérifiés indépendamment.',symbol:'Symbole',quantity:'Quantité',value:'Valeur',refresh:'Actualiser'},
};
async function load():Promise<Data>{const r=await fetch('/api/integrations/keys',{cache:'no-store'});if(!r.ok)throw new Error('FAILED');return r.json();}
export default function IntegrationsPage(){const {user}=useAuth();return <IntegrationWorkspace key={user?.id??'guest'}/>;}
function IntegrationWorkspace(){
 const {lang}=useLanguage();const language=lang==='en'||lang==='fr'?lang:'ar';const text=copy[language];
 const {userId,data,error,refresh}=usePrivateResource(load);const [label,setLabel]=useState('');const [days,setDays]=useState(30);const [scopes,setScopes]=useState<string[]>([]);const [secret,setSecret]=useState('');const [busy,setBusy]=useState(false);const [failed,setFailed]=useState(false);
 async function action(body:Record<string,unknown>){setBusy(true);setFailed(false);setSecret('');try{const r=await fetch('/api/integrations/keys',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error('FAILED');const result=await r.json();if(result.token)setSecret(result.token);await refresh();}catch{setFailed(true);}finally{setBusy(false);}}
 return <WorkspacePageContainer className={styles.page}><h1>{text.title}</h1><p>{text.note}</p><p>{text.limits}</p><nav className={styles.row}><Link href="/settings/apps">{text.install}</Link><a href="/integrations/sfm-mt5-exporter.mq5" download>{text.mt5}</a><a href="/integrations/README.md">{text.help}</a></nav>
 {!userId?<Link href="/login">{text.login}</Link>:null}{error||failed?<p role="alert">{text.error}</p>:null}
 <form className={styles.card} onSubmit={e=>{e.preventDefault();void action({action:'create',label,days,scopes});}}><label className={styles.field}>{text.label}<input className={styles.input} required maxLength={80} value={label} onChange={e=>setLabel(e.target.value)}/></label><label className={styles.field}>{text.days}<input className={styles.input} type="number" required min={1} max={90} value={days} onChange={e=>setDays(Number(e.target.value))}/></label><fieldset className={styles.field}><legend>{text.scopes}</legend>{[['portfolio:read',text.portfolio],['notifications:read',text.notifications],['snapshots:write',text.write]].map(([scope,name])=><label key={scope} className={styles.row}><input type="checkbox" checked={scopes.includes(scope)} onChange={e=>setScopes(e.target.checked?[...scopes,scope]:scopes.filter(s=>s!==scope))}/>{name}</label>)}</fieldset><Button disabled={busy||!userId||!scopes.length}>{text.create}</Button></form>
 {secret?<section className={styles.card}><label className={styles.field}>{text.once}<input className={styles.input} value={secret} readOnly dir="ltr" autoComplete="off" onFocus={e=>e.target.select()}/></label></section>:null}
 <section className={styles.card}><h2>{text.keys}</h2>{data?.keys.length===0?<p>{text.none}</p>:null}{data?.keys.map(key=><article key={key.id} className={styles.card}><h3>{key.label}</h3><p dir="ltr">{key.scopes.join(' · ')}</p><p>{text.expires}: <span dir="ltr">{key.expires_at.slice(0,19)} UTC</span> · {text.last}: <span dir="ltr">{key.last_used_at?.slice(0,19)??'—'}</span></p>{key.revoked_at?<p>{text.revoked}</p>:<Button variant="outline" disabled={busy} onClick={()=>void action({action:'revoke',id:key.id})}>{text.revoke}</Button>}</article>)}</section>
 <section className={styles.card}><h2>{text.received}</h2><Button variant="outline" disabled={busy} onClick={()=>void refresh()}>{text.refresh}</Button>{data?.snapshots.length===0?<p>{text.none}</p>:null}{data?.snapshots.map(s=><article key={s.id} className={styles.card}><h3>{text.source}: {s.source.toUpperCase()}</h3><p>{text.observed}: <span dir="ltr">{s.observed_at}</span></p><p dir="ltr">{text.balance}: {s.payload.balance??text.unknown} {s.payload.currency} · {text.equity}: {s.payload.equity??text.unknown} {s.payload.currency}</p><details><summary>{text.portfolio}</summary><div className={styles.scroll}><table className={styles.table}><thead><tr><th>{text.symbol}</th><th>{text.quantity}</th><th>{text.value}</th></tr></thead><tbody>{s.payload.positions.map((p,i)=><tr key={i}><td dir="ltr">{p.symbol}</td><td>{p.quantity}</td><td dir="ltr">{p.value??text.unknown} {p.currency}</td></tr>)}</tbody></table></div></details></article>)}</section>
 </WorkspacePageContainer>;
}
