'use client';
import { useState } from 'react';
import Link from 'next/link';
import { Languages } from 'lucide-react';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
type Language = 'ar' | 'en' | 'fr';
const content = {
  ar: { back: 'العودة للرئيسية', title: 'أنواع المصروفات', intro: 'المصروفات هي كل ما تنفقه من أموالك. فهم أنواعها يساعدك على التحكم في ميزانيتك وتحقيق أهدافك المالية.', tipsTitle: 'نصائح مهمة', tips: ['سجّل كل مصروف ولا تعتمد على الذاكرة.', 'راجع نفقاتك شهرياً لتعرف أين يذهب مالك.', 'قلّل المصروفات غير الضرورية تدريجياً.', 'استخدم قاعدة 50/30/20: 50% للضرورة، 30% للرغبات، 20% للادخار.'], categories: [['الضرورة', 'مصاريف لا غنى عنها للحياة اليومية.'], ['الرغبات', 'مصاريف تضيف راحة ومتعة لكنها ليست ضرورية.'], ['الادخار والاستثمار', 'مصاريف موجهة لبناء الثروة والمستقبل.']], items: [['السكن', 'الإيجار أو القسط الشهري، الصيانة، الفواتير.', ['الإيجار', 'الكهرباء', 'الماء', 'الغاز', 'الإنترنت']], ['الطعام', 'البقالة والوجبات الجاهزة والمطاعم.', ['السوبرماركت', 'مطاعم', 'طلبات توصيل']], ['النقل', 'المواصلات العامة أو وقود السيارة وصيانتها.', ['بنزين', 'مواصلات عامة', 'صيانة السيارة', 'تأمين السيارة']], ['الصحة', 'الأدوية والعلاج والتأمين الصحي.', ['زيارة الطبيب', 'الأدوية', 'التأمين الصحي', 'العلاج الطبيعي']], ['التعليم', 'الرسوم الدراسية والكتب والدورات.', ['الرسوم الدراسية', 'الكتب', 'الدورات التدريبية']], ['التسوق', 'الملابس والإلكترونيات ومستلزمات المنزل.', ['ملابس', 'إلكترونيات', 'أثاث', 'مستلزمات منزلية']], ['الترفيه', 'السينما والألعاب والرحلات.', ['سينما', 'ألعاب', 'رحلات', 'اشتراكات streaming']], ['الهدايا والتبرعات', 'الهدايا للأهل والأصدقاء والتبرعات الخيرية.', ['هدايا المناسبات', 'تبرعات خيرية', 'زكاة']], ['التأمينات', 'تأمينات الحياة والصحة والممتلكات.', ['تأمين حياة', 'تأمين صحة', 'تأمين عقار']], ['الديون', 'تسديد القروض وبطاقات الائتمان.', ['قسط سيارة', 'قسط منزل', 'سحب بطاقة ائتمان']]] },
  en: { back: 'Back to home', title: 'Expense Types', intro: 'Expenses are everything you spend your money on. Understanding their types helps you control your budget and achieve your financial goals.', tipsTitle: 'Important tips', tips: ['Record every expense and do not rely on memory.', 'Review your expenses monthly to know where your money goes.', 'Reduce non-essential expenses gradually.', 'Use the 50/30/20 rule: 50% for needs, 30% for wants, 20% for savings.'], categories: [['Needs', 'Essential expenses for daily life.'], ['Wants', 'Expenses that add comfort and pleasure but are not essential.'], ['Savings and investment', 'Expenses directed toward building wealth and the future.']], items: [['Housing', 'Rent or monthly installments, maintenance, bills.', ['Rent', 'Electricity', 'Water', 'Gas', 'Internet']], ['Food', 'Groceries, takeout, and restaurants.', ['Supermarket', 'Restaurants', 'Delivery orders']], ['Transportation', 'Public transport or car fuel and maintenance.', ['Gas', 'Public transit', 'Car maintenance', 'Car insurance']], ['Healthcare', 'Medicines, treatment, and health insurance.', ['Doctor visit', 'Medicines', 'Health insurance', 'Physical therapy']], ['Education', 'Tuition fees, books, and courses.', ['Tuition', 'Books', 'Training courses']], ['Shopping', 'Clothes, electronics, and home supplies.', ['Clothes', 'Electronics', 'Furniture', 'Home supplies']], ['Entertainment', 'Movies, games, and trips.', ['Cinema', 'Games', 'Trips', 'Streaming subscriptions']], ['Gifts and donations', 'Gifts for family, friends, and charitable donations.', ['Occasion gifts', 'Charity', 'Zakat']], ['Insurances', 'Life, health, and property insurance.', ['Life insurance', 'Health insurance', 'Property insurance']], ['Debts', 'Repaying loans and credit cards.', ['Car installment', 'Home installment', 'Credit card draw']]] },
  fr: { back: 'Retour à l\'accueil', title: 'Types de dépenses', intro: 'Les dépenses sont tout ce que vous dépensez. Comprendre leurs types vous aide à contrôler votre budget et atteindre vos objectifs financiers.', tipsTitle: 'Conseils importants', tips: ['Enregistrez chaque dépense et ne comptez pas sur la mémoire.', 'Révisez vos dépenses mensuellement pour savoir où va votre argent.', 'Réduisez progressivement les dépenses non essentielles.', 'Utilisez la règle 50/30/20: 50% pour les besoins, 30% pour les envies, 20% pour l\'épargne.'], categories: [['Besoins', 'Dépenses essentielles pour la vie quotidienne.'], ['Envies', 'Dépenses qui ajoutent du confort mais ne sont pas essentielles.'], ['Épargne et investissement', 'Dépenses dirigées vers la construction de patrimoine.']], items: [['Logement', 'Loyer ou mensualités, entretien, factures.', ['Loyer', 'Électricité', 'Eau', 'Gaz', 'Internet']], ['Alimentation', 'Épicerie, plats à emporter et restaurants.', ['Supermarché', 'Restaurants', 'Livraisons']], ['Transport', 'Transports en commun ou carburant et entretien auto.', ['Essence', 'Transports publics', 'Entretien auto', 'Assurance auto']], ['Santé', 'Médicaments, soins et assurance santé.', ['Visite médecin', 'Médicaments', 'Assurance santé', 'Kinésithérapie']], ['Éducation', 'Frais de scolarité, livres et cours.', ['Frais de scolarité', 'Livres', 'Formations']], ['Shopping', 'Vêtements, électronique et fournitures ménagères.', ['Vêtements', 'Électronique', 'Meubles', 'Fournitures']], ['Divertissement', 'Cinéma, jeux et voyages.', ['Cinéma', 'Jeux', 'Voyages', 'Abonnements streaming']], ['Cadeaux et dons', 'Cadeaux pour la famille, amis et dons caritatifs.', ['Cadeaux d\'occasion', 'Dons caritatifs', 'Zakat']], ['Assurances', 'Assurances vie, santé et biens.', ['Assurance vie', 'Assurance santé', 'Assurance biens']], ['Dettes', 'Remboursement de prêts et cartes de crédit.', ['Mensualité voiture', 'Mensualité maison', 'Retrait carte crédit']]] },
};
export default function ExpensesEducationPage() {
  const [language, setLanguage] = useState<Language>('ar');
  const t = content[language];
  const isArabic = language === 'ar';
  return (
    <main dir={isArabic ? 'rtl' : 'ltr'} className="min-h-screen bg-gradient-to-br from-purple-50 via-white to-purple-100 px-4 py-8 text-slate-900">
      <div className="mx-auto max-w-5xl space-y-6">
        <div className="rounded-3xl bg-purple-950 p-6 text-white shadow-xl">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <Link href="/" className="text-sm text-purple-100 hover:text-white">{t.back}</Link>
            <Select value={language} onValueChange={(value) => setLanguage(value as Language)}><SelectTrigger className="w-[150px] border-white/20 bg-white/10 text-white [&>span]:text-white"><Languages className="h-4 w-4 me-2" /><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ar">العربية</SelectItem><SelectItem value="en">English</SelectItem><SelectItem value="fr">Français</SelectItem></SelectContent></Select>
          </div>
          <h1 className="mt-4 text-4xl font-bold">{t.title}</h1>
          <p className="mt-3 max-w-3xl text-purple-100">{t.intro}</p>
        </div>
        <div className="grid gap-4 md:grid-cols-3">{t.categories.map(([title, desc]) => (<div key={title as string} className="rounded-2xl bg-white p-4 text-center shadow-sm border border-purple-100"><h3 className="text-xl font-bold text-purple-900">{title as string}</h3><p className="mt-2 text-slate-600">{desc as string}</p></div>))}</div>
        <section className="grid gap-4 md:grid-cols-2">{t.items.map(([title, desc, examples]) => (<article key={title as string} className="rounded-2xl border border-purple-100 bg-white p-5 shadow-sm"><h2 className="text-xl font-bold text-purple-900">{title as string}</h2><p className="mt-2 text-slate-700">{desc as string}</p><div className="mt-4 flex flex-wrap gap-2">{(examples as string[]).map((example) => <span key={example} className="rounded-full bg-purple-50 px-3 py-1 text-sm font-medium text-purple-800">{example}</span>)}</div></article>))}</section>
        <div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-amber-900"><h2 className="text-xl font-bold">{t.tipsTitle}</h2><ul className="mt-3 list-disc space-y-2 ps-6">{t.tips.map((tip) => <li key={tip}>{tip}</li>)}</ul></div>
      </div>
    </main>
  );
}
