import { expect, test } from '@playwright/test';
import { ASSETS } from '../../src/domain/macro-simulator/engine';
import { assetLabels } from '../../src/components/macro-simulator/copy';
import { gameCopy, modeCopy } from '../../src/components/macro-simulator/game-copy';

// Normal guest access only. Do not record login DOM, account data or provider responses.
test.use({ trace: 'off', screenshot: 'off', video: 'off' });
test('macro game locks decisions, compounds rounds and retains a hold comparator', async ({ page }) => {
  test.setTimeout(90_000);
  await page.addInitScript(() => { localStorage.setItem('sfm_lang', 'ar'); });
  await page.goto('/login?mode=register', { waitUntil: 'domcontentloaded' });
  await page.locator('button.guest-btn').first().click();
  await page.waitForURL(/\/dashboard(?:\?|$)/);
  await page.goto('/economic-intelligence/simulator', { waitUntil: 'domcontentloaded' });
  await page.getByRole('link', { name: modeCopy.game.ar, exact: true }).click();
  const game = page.getByTestId('macro-game');
  const result = game.getByTestId('macro-game-outcome');
  const reveal = game.getByTestId('macro-game-reveal');
  const next = game.getByTestId('macro-game-next');
  await expect(game).toBeVisible();
  await expect(game).toHaveAttribute('dir', 'rtl');
  await expect(game).toHaveAttribute('lang', 'ar');
  await expect(result).toHaveCount(0);
  await game.getByRole('button', { name: gameCopy.start.ar, exact: true }).click();
  await expect(next).toHaveCount(0);
  await reveal.click();
  await expect(game.getByRole('alert')).toHaveText(gameCopy.rationaleError.ar);
  await expect(result).toHaveCount(0);
  const rationale = game.getByLabel(gameCopy.rationale.ar, { exact: true });
  await rationale.fill('أحتفظ بالحيازات وأراقب الافتراضات دون ادعاء معرفة النتيجة.');
  await reveal.click();
  await expect(result).toBeVisible();
  await expect(result.locator('article')).toHaveCount(3);
  await expect(rationale).toBeDisabled();
  await expect(reveal).toHaveCount(0);
  await expect(game.getByTestId('macro-game-journal').locator('tbody tr')).toHaveCount(1);
  await next.click();
  await expect(result).toHaveCount(0);
  await expect(rationale).toHaveValue('');
  await game.getByLabel(gameCopy.action.ar, { exact: true }).selectOption('rebalance');
  for (const asset of ASSETS) await game.getByLabel(`${assetLabels[asset].ar} (%)`, { exact: true }).fill(asset === 'cash' ? '100' : '0');
  const gold = game.getByLabel(`${assetLabels.gold.ar} (%)`, { exact: true });
  await gold.fill('1');
  await expect(reveal).toBeDisabled();
  await gold.fill('0');
  await rationale.fill('أختبر النقد الافتراضي دون عائد، مع تذكّر أن الرسوم غير محتسبة.');
  await reveal.click();
  await expect(result).toBeVisible();
  await result.getByText(gameCopy.attribution.ar, { exact: true }).first().click();
  await expect(result.locator('tbody tr')).toHaveCount(ASSETS.length);
  await next.click();
  await expect(result).toHaveCount(0);
  await expect(game.getByLabel(gameCopy.action.ar, { exact: true })).toHaveValue('hold');
  await rationale.fill('أبقي الحيازات الحالية كما هي للمقارنة مع الجولة السابقة.');
  await reveal.click();
  await next.click();
  await expect(game.getByTestId('macro-game-complete')).toBeVisible();
  await expect(game.getByTestId('macro-game-journal').locator('tbody tr')).toHaveCount(3);
  await expect(result).toHaveCount(0);
  await expect(game.getByRole('img', { name: new RegExp(gameCopy.chart.ar) })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 900 });
  await expect.poll(() => game.evaluate(element => element.scrollWidth - element.clientWidth)).toBeLessThanOrEqual(4);
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(4);
  await game.getByRole('button', { name: gameCopy.reset.ar, exact: true }).click();
  await game.getByRole('button', { name: gameCopy.cancel.ar, exact: true }).click();
  await expect(game.getByTestId('macro-game-journal')).toBeVisible();
  await game.getByRole('button', { name: gameCopy.reset.ar, exact: true }).click();
  await game.getByRole('button', { name: gameCopy.confirm.ar, exact: true }).click();
  await expect(game.getByTestId('macro-game-journal')).toHaveCount(0);
  await expect(game.getByRole('button', { name: gameCopy.start.ar, exact: true })).toBeVisible();
});
