-- Runs only in the disposable CI database; all fixture writes roll back.
begin;
create or replace function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth to authenticated,anon;
create function pg_temp.check_result(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'ASSERTION: %',label;end if;end$$;
create function pg_temp.denied(statement text) returns void language plpgsql as $$begin begin execute statement;exception when insufficient_privilege then return;end;raise exception 'EXPECTED_PERMISSION_DENIAL';end$$;
insert into auth.users(id) values('20000000-0000-4000-8000-000000000001'),('20000000-0000-4000-8000-000000000002');
insert into public.sfm_advisor_plans(user_id,report) values('20000000-0000-4000-8000-000000000001','{"capability":"coach"}');
insert into public.sfm_notification_channels(id,user_id,channel,destination,enabled,verified_at) values('20000000-0000-4000-8000-000000000010','20000000-0000-4000-8000-000000000001','email','{"email":"fixture@example.test"}',true,now());
insert into public.notifications(id,user_id,type,title) values('20000000-0000-4000-8000-000000000011','20000000-0000-4000-8000-000000000001','system','Fixture only');
select pg_temp.check_result((select count(*)=1 from public.sfm_notification_deliveries),'new opted-in notification queued');
select pg_temp.check_result((select count(*)=1 from public.sfm_claim_notification_deliveries()),'claim a delivery');
select pg_temp.check_result((select count(*)=0 from public.sfm_claim_notification_deliveries()),'cannot claim same delivery twice');
update public.sfm_notification_deliveries set locked_at=now()-interval '6 minutes' where notification_id='20000000-0000-4000-8000-000000000011';
select * from public.sfm_claim_notification_deliveries();
select pg_temp.check_result((select status='uncertain' from public.sfm_notification_deliveries limit 1),'interrupted sends are not resent');
insert into public.sfm_notification_link_codes(token_hash,user_id,channel,locale,expires_at) values('test-hash','20000000-0000-4000-8000-000000000001','telegram','en',now()+interval '1 minute');
select pg_temp.check_result(public.sfm_verify_notification_channel('test-hash','telegram','{"chatId":"fixture"}'),'verified link consumed');
select pg_temp.check_result(not public.sfm_verify_notification_channel('test-hash','telegram','{}'),'link cannot replay');
insert into public.sfm_integration_keys(id,user_id,label,token_hash,scopes,expires_at) values('20000000-0000-4000-8000-000000000012','20000000-0000-4000-8000-000000000001','Fixture','fixture-key',array['portfolio:read'],now()+interval '1 day');
select pg_temp.check_result(public.sfm_authorize_integration('fixture-key','snapshots:write') is null,'scope denied');
select public.sfm_authorize_integration('fixture-key','portfolio:read') from generate_series(1,30);
select pg_temp.check_result(public.sfm_authorize_integration('fixture-key','portfolio:read') is null,'durable per-key quota');
update public.sfm_integration_keys set requests=0,revoked_at=now();
select pg_temp.check_result(public.sfm_authorize_integration('fixture-key','portfolio:read') is null,'revocation immediate');
insert into public.sfm_integration_snapshots(user_id,source,external_id,observed_at,payload) values('20000000-0000-4000-8000-000000000001','custom','a',now(),'{}');
set local role authenticated;
select set_config('request.jwt.claim.sub','20000000-0000-4000-8000-000000000002',true);
select pg_temp.check_result((select count(*)=0 from public.sfm_advisor_plans),'plan isolation');
select pg_temp.check_result((select count(*)=0 from public.sfm_notification_deliveries),'delivery isolation');
select pg_temp.check_result((select count(*)=0 from public.sfm_integration_snapshots),'snapshot isolation');
select pg_temp.denied('select * from public.sfm_notification_channels');
select pg_temp.denied('select * from public.sfm_notification_link_codes');
select pg_temp.denied('select * from public.sfm_integration_keys');
select pg_temp.denied($q$select public.sfm_claim_notification_deliveries()$q$);
select pg_temp.denied($q$select public.sfm_verify_notification_channel('test','telegram','{}')$q$);
select pg_temp.denied($q$select public.sfm_authorize_integration('fixture-key','portfolio:read')$q$);
select pg_temp.denied($q$insert into public.sfm_advisor_plans(user_id,report) values(auth.uid(),'{}')$q$);
select set_config('request.jwt.claim.sub','20000000-0000-4000-8000-000000000001',true);
select pg_temp.check_result((select count(*)=1 from public.sfm_advisor_plans),'owner reads plans');
select set_config('test.team',(public.sfm_team_action('create',null,'Expansion team')->>'id'),true);
select public.sfm_team_task(current_setting('test.team')::uuid,'create',p_title=>'Actual team task');
select set_config('test.task',(select id::text from public.sfm_team_tasks limit 1),true);
select pg_temp.check_result((select count(*)=1 from public.sfm_team_tasks),'owner sees task');
select public.sfm_team_task(current_setting('test.team')::uuid,'status',current_setting('test.task')::uuid,p_status=>'done');
select pg_temp.check_result((select status='done' from public.sfm_team_tasks limit 1),'status updated');
select public.sfmer_save_profile('sfm_fixture','Fixture name','Private fixture biography');
select set_config('request.jwt.claim.sub','20000000-0000-4000-8000-000000000002',true);
select pg_temp.check_result((select count(*)=0 from public.sfm_team_tasks),'nonmember cannot read task');
reset role;
set local role anon;
select pg_temp.denied('select * from public.sfmer_profiles');
select pg_temp.denied('select * from public.sfm_advisor_plans');
select pg_temp.denied('select * from public.sfm_integration_snapshots');
rollback;
