'use client';
import { useState } from 'react';
import Link from 'next/link';
import { Languages } from 'lucide-react';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
type Language = 'ar' | 'en' | 'fr' | 'zh';
const content = {
  ar: { back: 'العودة للرئيسية', title: 'أنواع الإدخار', intro: 'الإدخار يعني وضع جزء من المال جانباً للاستخدام المستقبلي. البدء مبكراً يصنع فرقاً كبيراً مع مرور الوقت بفضل الفائدة المركبة.', tipsTitle: 'نصائح مهمة', tips: ['ابدأ بأقل مبلغ ممكن ولا تنتظر للراتب التالي.', 'حدد هدفاً واضحاً للإدخار لتبقى متحمساً.', 'افصل حساب الإدخار عن حساب المصروفات.', 'راجع خطتك شهرياً وعدّلها حسب الحاجة.'], items: [['حساب التوفير العادي', 'حساب في البنك بسحب وإيداع بسهولة.', ['حساب جاري', 'حساب توفير عادي', 'حساب توفير ذهبي']], ['شهادات الإدخار', 'ودائع بمعدلات فائدة أعلى من الحساب العادي.', ['شهادة 12 شهر', 'شهادة 24 شهر', 'شهادة 36 شهر']], ['الصناديق الاستثمارية', 'محافظ يديرها مختصون لتحقيق عائد أفضل.', ['صناديق سوق النقد', 'صناديق الدخل الثابت', 'صناديق الأسهم']], ['التأمين على الحياة', 'ادخار مع حماية مالية لأسرتك.', ['تأمين مدى الحياة', 'تأمين مؤقت', 'تأمين توفير']], ['المعاشات التقاعدية', 'خطة ادخار للمستقبل بعد التقاعد.', ['صندوق حكومي', 'صندوق خاص', 'حساب تقاعدي فردي']], ['الذهب والمعادن', 'شراء أصول حقيقية للحماية من التضخم.', ['ذهب عيار 21', 'فضة', 'بلاتين']], ['العقارات', 'شراء عقار وتأجيره كمصدر دخل ثابت.', ['شقة', 'محل تجاري', 'أرض', 'مجمع سكني']], ['العملات الأجنبية', 'ادخار بعملة مستقرة ذات قيمة ثابتة.', ['دولار أمريكي', 'يورو', 'فرنك سويسري']], ['إعادة الاستثمار', 'إعادة توجيه الأرباح لشراء أصول إضافية.', ['أرباح الأسهم', 'أرباح العقار', 'عوائد الاستثمار']] },
  en: { back: 'Back to home', title: 'Savings Types', intro: 'Saving means setting aside money for future use. Starting early makes a big difference over time thanks to compound interest.', tipsTitle: 'Important tips', tips: ['Start with the smallest amount and do not wait for next salary.', 'Set a clear savings goal to stay motivated.', 'Separate your savings account from your spending account.', 'Review your plan monthly and adjust as needed.'], items: [['Regular savings account', 'A bank account for easy withdrawal and deposit.', ['Current account', 'Regular savings', 'Golden savings']], ['Savings certificates', 'Deposits with higher interest rates than regular accounts.', ['12-month certificate', '24-month certificate', '36-month certificate']], ['Investment funds', 'Portfolios managed by specialists for better returns.', ['Money market funds', 'Fixed income funds', 'Equity funds']], ['Life insurance', 'Savings with financial protection for your family.', ['Whole life insurance', 'Term insurance', 'Endowment insurance']], ['Pension plans', 'Savings plan for the future after retirement.', ['Government fund', 'Private fund', 'Individual pension account']], ['Gold and metals', 'Buying real assets for inflation protection.', ['21K gold', 'Silver', 'Platinum']], ['Real estate', 'Buying property to rent as a steady income source.', ['Apartment', 'Commercial shop', 'Land', 'Residential complex']], ['Foreign currencies', 'Saving in stable currency with fixed value.', ['US Dollar', 'Euro', 'Swiss Franc']], ['Reinvestment', 'Redirecting profits to purchase additional assets.', ['Stock dividends', 'Real estate profits', 'Investment returns']]] },
  fr: { back: 'Retour à l\'accueil', title: "Types d'épargne", intro: "Épargner signifie mettre de l'argent de côté pour une utilisation future. Commencer tôt fait une grande différence avec le temps grâce aux intérêts composés.", tipsTitle: 'Conseils importants', tips: ['Commencez avec le plus petit montant sans attendre le prochain salaire.', 'Fixez un objectif d\'épargne clair pour rester motivé.', 'Séparez votre compte épargne de votre compte de dépenses.', 'Révisez votre plan mensuellement et ajustez si nécessaire.'], items: [['Compte épargne ordinaire', 'Compte bancaire avec retrait et dépôt faciles.', ['Compte courant', 'Épargne ordinaire', 'Épargne dorée']], ['Certificats d\'épargne', 'Dépôts avec des taux plus élevés que les comptes ordinaires.', ['Certificat 12 mois', 'Certificat 24 mois', 'Certificat 36 mois']], ['Fonds d\'investissement', 'Portefeuilles gérés par des spécialistes pour de meilleurs rendements.', ['Fonds du marché monétaire', 'Fonds à revenu fixe', 'Fonds d\'actions']], ['Assurance-vie', 'Épargne avec protection financière pour votre famille.', ['Assurance-vie entière', 'Assurance temporaire', 'Assurance épargne']], ['Plans de pension', 'Plan d\'épargne pour l\'avenir après la retraite.', ['Fonds gouvernemental', 'Fonds privé', 'Compte de pension individuel']], ['Or et métaux', 'Acheter des actifs réels pour se protéger de l\'inflation.', ['Or 21K', 'Argent', 'Platine']], ['Immobilier', 'Acheter une propriété à louer comme source de revenus stable.', ['Appartement', 'Local commercial', 'Terrain', 'Complexe résidentiel']], ['Devises étrangères', 'Épargner en monnaie stable à valeur fixe.', ['Dollar américain', 'Euro', 'Franc suisse']], ['Réinvestissement', 'Rediriger les bénéfices pour acheter des actifs supplémentaires.', ['Dividendes', 'Profits immobiliers', 'Rendements d\'investissement']]] },
  zh: { back: '返回首页', title: '储蓄类型', intro: '储蓄意味着把钱存起来以备将来使用。由于复利的作用，尽早开始会随着时间产生巨大的差异。', tipsTitle: '重要建议', tips: ['从最小的金额开始，不要等到下次发薪。', '设定明确的储蓄目标以保持动力。', '将储蓄账户与消费账户分开。', '每月检查计划并根据需要调整。'], items: [['普通储蓄账户', '易于存取款的银行账户。', ['活期账户', '普通储蓄', '黄金储蓄']], ['储蓄证明', '利率高于普通账户的存款。', ['12个月存单', '24个月存单', '36个月存单']], ['投资基金', '由专业人士管理的投资组合，以获得更好回报。', ['货币市场基金', '固定收益基金', '股票基金']], [['人寿保险'], '带有家庭财务保护的储蓄。', ['终身保险', '定期保险', '储蓄保险']], [['养老计划'], '退休后使用的储蓄计划。', ['政府基金', '私人基金', '个人养老金账户']], ['黄金和金属', '购买实物资产以抵御通货膨胀。', ['21K黄金', '白银', '铂金']], ['房地产', '购买房产出租作为稳定收入来源。', ['公寓', '商铺', '土地', '住宅综合体']], ['外币', '以稳定货币储蓄保值。', ['美元', '欧元', '瑞士法郎']], ['再投资', '将利润重新用于购买额外资产。', ['股票分红', '房产利润', '投资收益']] },
};
export default function SavingsEducationPage() {
  const [language, setLanguage] = useState<Language>('ar');
  const t = content[language];
  const isArabic = language === 'ar';
  return (
    <main dir={isArabic ? 'rtl' : 'ltr'} className="min-h-screen bg-gradient-to-br from-green-50 via-white to-green-100 px-4 py-8 text-slate-900">
      <div className="mx-auto max-w-5xl space-y-6">
        <div className="rounded-3xl bg-green-950 p-6 text-white shadow-xl">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <Link href="/" className="text-sm text-green-100 hover:text-white">{t.back}</Link>
            <Select value={language} onValueChange={(value) => setLanguage(value as Language)}><SelectTrigger className="w-[150px] border-white/20 bg-white/10 text-white [&>span]:text-white"><Languages className="h-4 w-4 me-2" /><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ar">العربية</SelectItem><SelectItem value="en">English</SelectItem><SelectItem value="fr">Français</SelectItem><SelectItem value="zh">中文</SelectItem></SelectContent></Select>
          </div>
          <h1 className="mt-4 text-4xl font-bold">{t.title}</h1>
          <p className="mt-3 max-w-3xl text-green-100">{t.intro}</p>
        </div>
        <section className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{t.items.map(([title, desc, examples]) => (<article key={title as string} className="rounded-2xl border border-green-100 bg-white p-5 shadow-sm"><h2 className="text-xl font-bold text-green-900">{title as string}</h2><p className="mt-2 text-slate-700">{desc as string}</p><div className="mt-4 flex flex-wrap gap-2">{(examples as string[]).map((example) => <span key={example} className="rounded-full bg-green-50 px-3 py-1 text-sm font-medium text-green-800">{example}</span>)}</div></article>))}</section>
        <div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-amber-900"><h2 className="text-xl font-bold">{t.tipsTitle}</h2><ul className="mt-3 list-disc space-y-2 ps-6">{t.tips.map((tip) => <li key={tip}>{tip}</li>)}</ul></div>
      </div>
    </main>
  );
}
