import type { MetadataRoute } from 'next';
import { absoluteUrl } from '@/lib/seo';

const privateRoutes = [
  '/api',
  '/ai',
  '/alerts',
  '/dashboard',
  '/onboarding',
  '/command-center',
  '/decisions',
  '/today',
  '/tasks',
  '/notifications',
  '/notif',
  '/reports-center',
  '/reports',
  '/business',
  '/business-hub',
  '/business-operations',
  '/zakat',
  '/khums',
  '/charity',
  '/charity-projects',
  '/documents',
  '/setup',
  '/profile',
  '/login',
  '/reset-password',
  '/mfa',
  '/auth',
  '/guest',
  '/expenses',
  '/income',
  '/goals',
  '/debts',
  '/projects',
  '/invest',
  '/savings',
  '/investment-offers',
  '/market-alerts',
  '/market-analysis',
  '/market-watchlist',
  '/watchlist',
  '/employees',
  '/sales',
  '/customers',
  '/invoices',
  '/suppliers',
  '/operating-expenses',
  '/education',
  '/services',
  '/settings',
  '/security',
  '/site-map',
  '/sfm-admin-control',
  '/thesfm-trader-own',
  '/wakeel',
  '/zoer_proxy',
];

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: '*',
      allow: ['/', '/about', '/contact', '/financial-theories', '/ebooks', '/privacy', '/terms'],
      disallow: privateRoutes,
    },
    sitemap: absoluteUrl('/sitemap.xml'),
  };
}
