import type { useLanguage } from '@/hooks/useLanguage';

export type PageKind = 'expenses' | 'income' | 'invest' | 'savings' | 'goals' | 'reports' | 'ai';
export type ExpensePageTab = 'overview' | 'records' | 'receipts' | 'categories' | 'analytics' | 'reports';
export type ExpensePeriodPreset = 'current' | 'previous' | 'last3' | 'last6' | 'year' | 'all' | 'custom';
export type ExpensePeriodState = { preset: ExpensePeriodPreset; month: number; year: number };
export type ExpensePeriodRange = {
  start: Date;
  end: Date;
  startDate: string;
  endDate: string;
  months: number;
};
export type LangText = { ar: string; en: string; fr?: string };
export type TranslateFn = ReturnType<typeof useLanguage>['t'];
export type MoneyItem = {
  id: string;
  name: string;
  amount: number;
  converted_market_value?: number | string | null;
  current_value?: number | string | null;
  current_market_value?: number | string | null;
  native_market_value?: number | string | null;
  currency?: string | null;
  saving_type?: string | null;
  saving_method?: string | null;
  method?: string | null;
  saved_at?: string | null;
  note?: string | null;
  notes?: string | null;
  goal_id?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
};
export type IncomeSource = MoneyItem & {
  label?: string | null;
  category?: string | null;
  project_id?: string | null;
  related_project_id?: string | null;
  project_income_id?: string | null;
  transferred_to_personal_income?: boolean | string | null;
  enhanced?: Record<string, unknown> | null;
};
export type EntryKind = Extract<PageKind, 'expenses' | 'income' | 'invest' | 'savings'>;
export type EntryFormState = {
  id?: string;
  name: string;
  amount: string;
  category: string;
  currency: string;
  savingType: string;
  savingMethod: string;
  savedAt: string;
  note: string;
  goalId: string;
};
export type EntryRow = { id: string; title: string; subtitle: string; value: string; item?: MoneyItem | IncomeSource };
export type GoalItem = {
  id: string;
  name: string;
  target_amount: number;
  current_amount: number;
  monthly_contribution: number;
  goal_type: string;
  category: string;
  priority: string;
  funding_source: string;
  currency: string;
  ai_enabled: boolean;
  icon?: string | null;
  color?: string | null;
  deadline?: string | null;
  notes?: string | null;
  created_at?: string | null;
};
export type GoalRow = {
  id: string;
  goal?: string | null;
  title?: string | null;
  name?: string | null;
  amount: number | string | null;
  target_amount?: number | string | null;
  targetAmount?: number | string | null;
  goal_amount?: number | string | null;
  current_amount?: number | string | null;
  currentAmount?: number | string | null;
  saved_amount?: number | string | null;
  savedAmount?: number | string | null;
  progress_amount?: number | string | null;
  progressAmount?: number | string | null;
  monthly_contribution?: number | string | null;
  monthlyContribution?: number | string | null;
  monthly_saving?: number | string | null;
  monthlySaving?: number | string | null;
  target_date?: string | null;
  targetDate?: string | null;
  deadline?: string | null;
  currency?: string | null;
  duration?: string | null;
  duration_unit?: string | null;
  notes?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
};
export type GoalFormState = {
  id: string;
  name: string;
  goalType: string;
  targetAmount: string;
  currentAmount: string;
  monthlyContribution: string;
  deadline: string;
  category: string;
  priority: string;
  fundingSource: string;
  currency: string;
  notes: string;
  aiEnabled: boolean;
};
export type QueryResult<T> = PromiseLike<{ data: T[] | null; error: { message: string } | null }>;
export type ChatMessage = { role: 'user' | 'assistant'; content: string };
export type DataErrorKind = 'database' | 'permission' | 'auth' | 'unknown';
export type DataLoadError = {
  page: string;
  functionName: string;
  queryName: string;
  table?: string;
  missingColumn?: string;
  message: string;
  kind: DataErrorKind;
};
export type DataResult<T> = {
  data: T[];
  error: DataLoadError | null;
  source: 'database' | 'fallback';
};
export type ReceiptItem = { name: string; price?: number; quantity?: number; unitPrice?: number; total?: number };
export type ReceiptAmountCandidate = {
  label: string;
  kind?: string;
  amount: number;
  currency?: string;
  confidence?: number;
  source?: string;
};
export type AiExtractedData = {
  merchantName?: string;
  description?: string;
  provider?: 'google-document-ai' | 'openai-vision' | 'manual';
  invoiceNumber?: string;
  totalAmount?: number;
  subtotal?: number;
  amount?: number;
  total?: number;
  finalTotal?: number;
  currency?: string;
  taxAmount?: number;
  discountAmount?: number;
  paidAmount?: number;
  changeAmount?: number;
  receiptDate?: string;
  date?: string;
  category?: string;
  paymentMethod?: string;
  rawText?: string;
  items?: ReceiptItem[];
  amountCandidates?: ReceiptAmountCandidate[];
  selectedAmountLabel?: string;
  confidenceLevel?: 'high' | 'medium' | 'low';
  warnings?: string[];
  confidenceScore?: number;
  confidence?: number;
};
export type ReceiptScanDebug = {
  stage?: 'upload' | 'provider' | 'ai' | 'parser' | 'ui' | 'google' | 'openai';
  fileName?: string;
  fileType?: string;
  fileSize?: number;
  providerConfigured?: boolean;
  googleConfigured?: boolean;
  openaiConfigured?: boolean;
  provider?: 'google-document-ai' | 'openai-vision' | 'manual';
  rawTextLength?: number;
  candidateCount?: number;
  selectedAmount?: number;
  confidence?: string;
  errorSource?: string;
  status?: number;
  message?: string;
  providerStatusCode?: number;
  providerReason?: string;
};
export type ReceiptScanApiResult = {
  fileName: string;
  success?: boolean;
  provider?: 'google-document-ai' | 'openai-vision' | 'manual';
  confidence?: 'high' | 'medium' | 'low';
  code?: string;
  data?: AiExtractedData;
  error?: string;
  debug?: ReceiptScanDebug;
};
export type ReceiptScanApiPayload = {
  success?: boolean;
  provider?: 'google-document-ai' | 'openai-vision' | 'manual';
  confidence?: 'high' | 'medium' | 'low';
  code?: string;
  error?: string;
  data?: AiExtractedData;
  debug?: ReceiptScanDebug;
  results?: ReceiptScanApiResult[];
};
export type SmartExpense = MoneyItem & {
  category?: string | null;
  date?: string | null;
  currency?: string | null;
  payment_method?: string | null;
  notes?: string | null;
  enhanced?: Record<string, unknown> | null;
  receipt_image_url?: string | null;
  receipt_file_name?: string | null;
  ai_extracted_data?: AiExtractedData | null;
  ai_confidence_score?: number | null;
  updated_at?: string | null;
  project_id?: string | null;
  related_project_id?: string | null;
  project_expense_id?: string | null;
  paid_from_personal_budget?: boolean | null;
  is_recurring?: boolean | string | null;
  recurring?: boolean | string | null;
  frequency?: string | null;
  start_date?: string | null;
  end_date?: string | null;
  expense_type?: string | null;
};
export type ExpenseFormState = {
  id?: string;
  name: string;
  amount: string;
  currency: string;
  category: string;
  date: string;
  paymentMethod: string;
  notes: string;
  receiptFile: File | null;
  receiptPreview: string;
  receiptImageUrl?: string | null;
  receiptFileName?: string | null;
  aiExtractedData?: AiExtractedData | null;
  aiConfidenceScore?: number | null;
};
export type ExpenseModalMode = 'manual' | 'scan';
export type PendingReceiptExpense = {
  id: string;
  selected: boolean;
  status: 'ready' | 'review' | 'failed';
  file: File;
  fileName: string;
  previewUrl: string;
  name: string;
  amount: string;
  currency: string;
  date: string;
  category: string;
  paymentMethod: string;
  notes: string;
  aiConfidenceScore: number;
  aiExtractedData: AiExtractedData | null;
  error: string | null;
};

export interface Snapshot {
  income: IncomeSource[];
  expenses: SmartExpense[];
  savings: MoneyItem[];
  investments: MoneyItem[];
  goals: GoalItem[];
  error: DataLoadError | null;
}

export interface SectionCard {
  title: LangText;
  body: LangText;
  value?: string;
  tone: string;
}
