'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, BarChart3, BriefcaseBusiness, CalendarDays, CheckCircle2, CircleDollarSign, Download, Edit3, ExternalLink, FileDown, FileText, LineChart, Paperclip, Plus, ReceiptText, Sparkles, Trash2, Wallet, X } from 'lucide-react';
import { AppHeader } from '@/components/AppHeader';
import { Sidebar } from '@/components/Sidebar';
import { useAuth } from '@/hooks/useAuth';
import { useLanguage } from '@/hooks/useLanguage';
import { supabase } from '@/integrations/supabase/client';

type IncomeType = 'salary' | 'side' | 'investment' | 'bonus' | 'gift' | 'rent' | 'other';
type IncomeStatus = 'received' | 'pending' | 'expected' | 'late';
type Frequency = 'monthly' | 'weekly' | 'yearly';
type Lang = 'ar' | 'en' | 'fr';
type IncomeFilter = 'all' | IncomeStatus | 'recurring' | 'one-time';
type SupportedCurrency = 'KWD' | 'USD' | 'EUR' | 'SAR' | 'AED';

type IncomeRow = {
  id: string;
  user_id?: string;
  label?: string | null;
  name?: string | null;
  category?: string | null;
  amount: number;
  income_type?: string | null;
  status?: string | null;
  received_date?: string | null;
  currency?: string | null;
  attachment_url?: string | null;
  attachment_name?: string | null;
  attachment_type?: string | null;
  attachment_size?: number | null;
  exchange_rate?: number | null;
  amount_kwd?: number | null;
  source_name?: string | null;
  notes?: string | null;
  is_recurring?: boolean | null;
  frequency?: string | null;
  recurrence_start_date?: string | null;
  recurrence_end_date?: string | null;
  parent_recurring_income_id?: string | null;
  generated_for_date?: string | null;
  confirmed_at?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
};

type IncomeViewRow = IncomeRow & {
  workflowStatus: IncomeStatus;
};

type IncomeForm = {
  id?: string;
  name: string;
  amount: string;
  currency: SupportedCurrency;
  incomeType: IncomeType;
  receivedDate: string;
  status: IncomeStatus;
  isRecurring: boolean;
  frequency: Frequency;
  recurrenceStartDate: string;
  recurrenceEndDate: string;
  sourceName: string;
  notes: string;
};

type AttachmentPayload = {
  attachment_url: string | null;
  attachment_name: string | null;
  attachment_type: string | null;
  attachment_size: number | null;
};

const TX: Record<string, Record<Lang, string>> = {
  breadcrumb: { ar: 'THE SFM / الدخل', en: 'THE SFM / Income', fr: 'THE SFM / Revenus' },
  title: { ar: 'الدخل', en: 'Income', fr: 'Revenus' },
  monthNow: { ar: 'مايو 2026 • محدّث الآن', en: 'May 2026 • Updated now', fr: 'Mai 2026 • Mis à jour maintenant' },
  export: { ar: 'تصدير', en: 'Export', fr: 'Exporter' },
  exportPdf: { ar: 'تصدير PDF', en: 'Export PDF', fr: 'Exporter PDF' },
  exportExcel: { ar: 'تصدير Excel', en: 'Export Excel', fr: 'Exporter Excel' },
  generatedReport: { ar: 'تقرير الدخل', en: 'Income Report', fr: 'Rapport des revenus' },
  exportSuccess: { ar: 'تم تصدير التقرير بنجاح.', en: 'Report exported successfully.', fr: 'Rapport exporté avec succès.' },
  exportFailed: { ar: 'تعذر تصدير التقرير.', en: 'Could not export report.', fr: 'Impossible d’exporter le rapport.' },
  reportDisclaimer: { ar: 'هذا التقرير تم إنشاؤه من THE SFM لأغراض المتابعة المالية الشخصية.', en: 'This report was generated by THE SFM for personal financial tracking.', fr: 'Ce rapport a été généré par THE SFM pour le suivi financier personnel.' },
  addIncome: { ar: '+ إضافة دخل', en: '+ Add Income', fr: '+ Ajouter un revenu' },
  savingsInsight: { ar: 'معدل الادخار 43% — أعلى من المستهدف', en: 'Savings rate 43% — above target', fr: 'Taux d’épargne 43% — au-dessus de l’objectif' },
  spendingInsight: { ar: 'نسبة الصرف 57% — تجاوزت قاعدة 50/30/20', en: 'Spending ratio 57% — above the 50/30/20 rule', fr: 'Ratio de dépenses 57% — au-dessus de la règle 50/30/20' },
  forecastInsight: { ar: 'توقع الشهر القادم +5.2% بناءً على 6 شهور', en: 'Next month forecast +5.2% based on 6 months', fr: 'Prévision du mois prochain +5,2% sur 6 mois' },
  viewExpenses: { ar: 'اعرض المصاريف', en: 'View expenses', fr: 'Voir les dépenses' },
  totalIncome: { ar: 'إجمالي الدخل', en: 'Total Income', fr: 'Revenu total' },
  incomeSources: { ar: 'مصادر الدخل', en: 'Income Sources', fr: 'Sources de revenus' },
  active: { ar: 'نشطة', en: 'active', fr: 'actives' },
  expectedNet: { ar: 'الصافي المتوقع', en: 'Expected Net', fr: 'Net prévu' },
  distribution: { ar: 'توزيع الدخل', en: 'Income Distribution', fr: 'Répartition des revenus' },
  trend: { ar: 'اتجاه الدخل الشهري', en: 'Monthly Income Trend', fr: 'Tendance mensuelle des revenus' },
  incomeList: { ar: 'مصادر الدخل', en: 'Income Sources', fr: 'Sources de revenus' },
  noIncome: { ar: 'لا توجد مصادر دخل بعد', en: 'No income sources yet', fr: 'Aucune source de revenu pour le moment' },
  name: { ar: 'اسم الدخل', en: 'Income name', fr: 'Nom du revenu' },
  amount: { ar: 'المبلغ', en: 'Amount', fr: 'Montant' },
  currency: { ar: 'العملة', en: 'Currency', fr: 'Devise' },
  conversionDisabled: { ar: 'التحويل إلى الدينار الكويتي غير مفعّل حالياً.', en: 'Conversion to KWD is not enabled yet.', fr: 'La conversion vers le KWD n’est pas encore activée.' },
  attachFile: { ar: 'إرفاق ملف', en: 'Attach file', fr: 'Joindre un fichier' },
  removeAttachment: { ar: 'إزالة المرفق', en: 'Remove attachment', fr: 'Supprimer la pièce jointe' },
  attachment: { ar: 'يوجد مرفق', en: 'Attachment', fr: 'Pièce jointe' },
  viewAttachment: { ar: 'عرض المرفق', en: 'View attachment', fr: 'Voir la pièce jointe' },
  unsupportedFile: { ar: 'نوع الملف غير مدعوم', en: 'Unsupported file type', fr: 'Type de fichier non pris en charge' },
  fileTooLarge: { ar: 'حجم الملف كبير جداً', en: 'File size is too large', fr: 'Le fichier est trop volumineux' },
  uploadFailed: { ar: 'تعذر رفع الملف', en: 'Could not upload file', fr: 'Impossible de téléverser le fichier' },
  storageSetup: { ar: 'احفظ الدخل بدون المرفق الآن. يحتاج تخزين Supabase إلى تفعيل حاوية income-attachments.', en: 'Income was saved without the attachment. Supabase Storage needs the income-attachments bucket enabled.', fr: 'Le revenu a été enregistré sans pièce jointe. Supabase Storage doit activer le bucket income-attachments.' },
  type: { ar: 'النوع', en: 'Type', fr: 'Type' },
  receivedDate: { ar: 'تاريخ الاستلام', en: 'Received date', fr: 'Date de réception' },
  status: { ar: 'الحالة', en: 'Status', fr: 'Statut' },
  recurring: { ar: 'متكرر', en: 'Recurring', fr: 'Récurrent' },
  oneTime: { ar: 'لمرة واحدة', en: 'One time', fr: 'Une fois' },
  frequency: { ar: 'التكرار', en: 'Frequency', fr: 'Fréquence' },
  startDate: { ar: 'تاريخ البداية', en: 'Start date', fr: 'Date de début' },
  endDateOptional: { ar: 'تاريخ النهاية اختياري', en: 'End date optional', fr: 'Date de fin facultative' },
  upcomingIncome: { ar: 'دخل متوقع قادم', en: 'Upcoming Income', fr: 'Revenus à venir' },
  lateWarning: { ar: 'يوجد دخل متأخر يحتاج تأكيد.', en: 'There is overdue income that needs confirmation.', fr: 'Un revenu en retard nécessite une confirmation.' },
  viewLateIncome: { ar: 'عرض المتأخرات', en: 'View late income', fr: 'Voir les revenus en retard' },
  confirmReceived: { ar: 'تأكيد الاستلام', en: 'Confirm received', fr: 'Confirmer la réception' },
  confirmed: { ar: 'تم تأكيد استلام الدخل.', en: 'Income receipt confirmed.', fr: 'Réception du revenu confirmée.' },
  confirmError: { ar: 'تعذر تأكيد الاستلام. حاول مرة أخرى.', en: 'Could not confirm receipt. Please try again.', fr: 'Impossible de confirmer la réception. Réessayez.' },
  all: { ar: 'الكل', en: 'All', fr: 'Tous' },
  recurringFilter: { ar: 'متكرر', en: 'Recurring', fr: 'Récurrent' },
  oneTimeFilter: { ar: 'لمرة واحدة', en: 'One-time', fr: 'Unique' },
  editThisOnly: { ar: 'تعديل هذا السجل فقط', en: 'Edit this entry only', fr: 'Modifier uniquement cette entrée' },
  editFutureEntries: { ar: 'تعديل السجلات القادمة', en: 'Edit future entries', fr: 'Modifier les entrées futures' },
  deleteThisOnly: { ar: 'حذف هذا فقط', en: 'Delete this only', fr: 'Supprimer uniquement celui-ci' },
  deleteFutureEntries: { ar: 'حذف السجلات القادمة', en: 'Delete future entries', fr: 'Supprimer les entrées futures' },
  sourceCompany: { ar: 'المصدر / الجهة', en: 'Source / Company', fr: 'Source / organisme' },
  notes: { ar: 'ملاحظات', en: 'Notes', fr: 'Notes' },
  cancel: { ar: 'إلغاء', en: 'Cancel', fr: 'Annuler' },
  add: { ar: '+ إضافة', en: '+ Add', fr: '+ Ajouter' },
  save: { ar: 'حفظ', en: 'Save', fr: 'Enregistrer' },
  saving: { ar: 'جارٍ الحفظ...', en: 'Saving...', fr: 'Enregistrement...' },
  edit: { ar: 'تعديل', en: 'Edit', fr: 'Modifier' },
  delete: { ar: 'حذف', en: 'Delete', fr: 'Supprimer' },
  close: { ar: 'إغلاق', en: 'Close', fr: 'Fermer' },
  source: { ar: 'المصدر', en: 'Source', fr: 'Source' },
  date: { ar: 'التاريخ', en: 'Date', fr: 'Date' },
  percent: { ar: 'من الإجمالي', en: 'of total', fr: 'du total' },
  nameError: { ar: 'الرجاء إدخال اسم الدخل.', en: 'Please enter income name.', fr: 'Veuillez saisir le nom du revenu.' },
  amountError: { ar: 'المبلغ يجب أن يكون أكبر من صفر.', en: 'Amount must be greater than zero.', fr: 'Le montant doit être supérieur à zéro.' },
  requiredError: { ar: 'يرجى إكمال الحقول المطلوبة.', en: 'Please complete the required fields.', fr: 'Veuillez compléter les champs requis.' },
  saved: { ar: 'تم حفظ الدخل', en: 'Income saved', fr: 'Revenu enregistré' },
  deleted: { ar: 'تم حذف الدخل', en: 'Income deleted', fr: 'Revenu supprimé' },
  exportSoon: { ar: 'التصدير غير مفعّل في هذه المرحلة.', en: 'Export is not enabled in this phase.', fr: 'L’export n’est pas activé dans cette phase.' },
  insightDetails: { ar: 'هذه قراءة إرشادية مؤقتة لتحسين التخطيط الشهري.', en: 'This is a temporary guidance insight for monthly planning.', fr: 'Il s’agit d’un aperçu indicatif temporaire pour la planification mensuelle.' },
};

const TYPES: Array<{ id: IncomeType; icon: string; label: Record<Lang, string> }> = [
  { id: 'salary', icon: '💼', label: { ar: 'راتب', en: 'Salary', fr: 'Salaire' } },
  { id: 'side', icon: '🧰', label: { ar: 'دخل جانبي', en: 'Side income', fr: 'Revenu secondaire' } },
  { id: 'investment', icon: '📈', label: { ar: 'استثمار', en: 'Investment', fr: 'Investissement' } },
  { id: 'bonus', icon: '✨', label: { ar: 'مكافأة', en: 'Bonus', fr: 'Prime' } },
  { id: 'gift', icon: '🎁', label: { ar: 'هدية', en: 'Gift', fr: 'Cadeau' } },
  { id: 'rent', icon: '🏠', label: { ar: 'إيجار', en: 'Rent', fr: 'Loyer' } },
  { id: 'other', icon: '💰', label: { ar: 'أخرى', en: 'Other', fr: 'Autre' } },
];

const STATUSES: Array<{ id: IncomeStatus; label: Record<Lang, string> }> = [
  { id: 'received', label: { ar: 'مستلم', en: 'Received', fr: 'Reçu' } },
  { id: 'pending', label: { ar: 'بانتظار', en: 'Pending', fr: 'En attente' } },
  { id: 'expected', label: { ar: 'متوقع', en: 'Expected', fr: 'Prévu' } },
  { id: 'late', label: { ar: 'متأخر', en: 'Late', fr: 'En retard' } },
];

const FREQUENCIES: Array<{ id: Frequency; label: Record<Lang, string> }> = [
  { id: 'monthly', label: { ar: 'شهري', en: 'Monthly', fr: 'Mensuel' } },
  { id: 'weekly', label: { ar: 'أسبوعي', en: 'Weekly', fr: 'Hebdomadaire' } },
  { id: 'yearly', label: { ar: 'سنوي', en: 'Yearly', fr: 'Annuel' } },
];

const CURRENCIES: Array<{ id: SupportedCurrency; label: Record<Lang, string> }> = [
  { id: 'KWD', label: { ar: 'د.ك', en: 'KWD', fr: 'KWD' } },
  { id: 'USD', label: { ar: 'دولار', en: 'USD', fr: 'USD' } },
  { id: 'EUR', label: { ar: 'يورو', en: 'EUR', fr: 'EUR' } },
  { id: 'SAR', label: { ar: 'ريال سعودي', en: 'SAR', fr: 'SAR' } },
  { id: 'AED', label: { ar: 'درهم إماراتي', en: 'AED', fr: 'AED' } },
];

const ALLOWED_ATTACHMENT_TYPES = ['application/pdf', 'image/png', 'image/jpeg', 'image/webp'];
const MAX_ATTACHMENT_SIZE = 10 * 1024 * 1024;

const emptyForm = (): IncomeForm => ({
  name: '',
  amount: '',
  currency: 'KWD',
  incomeType: 'other',
  receivedDate: todayDateOnly(),
  status: 'received',
  isRecurring: false,
  frequency: 'monthly',
  recurrenceStartDate: todayDateOnly(),
  recurrenceEndDate: '',
  sourceName: '',
  notes: '',
});

function tr(key: keyof typeof TX, lang: string) {
  const safe = lang === 'fr' || lang === 'en' || lang === 'ar' ? lang : 'ar';
  return TX[key][safe];
}

function normalizeType(value?: string | null): IncomeType {
  if (value === 'salary' || value === 'side' || value === 'investment' || value === 'bonus' || value === 'gift' || value === 'rent') return value;
  if (value === 'business' || value === 'additional' || value === 'active') return 'side';
  if (value === 'passive') return 'rent';
  return 'other';
}

function normalizeStatus(value?: string | null): IncomeStatus {
  if (value === 'pending' || value === 'expected' || value === 'late') return value;
  return 'received';
}

function todayDateOnly() {
  const now = new Date();
  const offset = now.getTimezoneOffset() * 60000;
  return new Date(now.getTime() - offset).toISOString().slice(0, 10);
}

function dateOnlyToLocalDate(value: string | null | undefined) {
  if (!value) return new Date();
  const [year, month, day] = value.slice(0, 10).split('-').map(Number);
  if (!year || !month || !day) return new Date(value);
  return new Date(year, month - 1, day);
}

function compareDateOnly(a: string, b: string) {
  return dateOnlyToLocalDate(a).getTime() - dateOnlyToLocalDate(b).getTime();
}

function addFrequencyDate(value: string, frequency: Frequency) {
  const date = dateOnlyToLocalDate(value);
  if (frequency === 'weekly') date.setDate(date.getDate() + 7);
  if (frequency === 'monthly') date.setMonth(date.getMonth() + 1);
  if (frequency === 'yearly') date.setFullYear(date.getFullYear() + 1);
  const offset = date.getTimezoneOffset() * 60000;
  return new Date(date.getTime() - offset).toISOString().slice(0, 10);
}

function generateOccurrenceDates(startDate: string, frequency: Frequency, endDate?: string | null) {
  const dates: string[] = [];
  let cursor = startDate;
  for (let index = 0; index < 6; index += 1) {
    if (endDate && compareDateOnly(cursor, endDate) > 0) break;
    dates.push(cursor);
    cursor = addFrequencyDate(cursor, frequency);
  }
  return dates;
}

function workflowStatus(row: IncomeRow): IncomeStatus {
  if (row.confirmed_at || row.status === 'received') return 'received';
  const dueDate = (row.received_date || row.generated_for_date || row.created_at || todayDateOnly()).slice(0, 10);
  const diff = compareDateOnly(dueDate, todayDateOnly());
  if (diff > 0) return 'expected';
  if (diff === 0) return 'pending';
  return 'late';
}

function formatMoney(value: number, lang: string, currency = 'KWD') {
  const locale = lang === 'ar' ? 'ar-KW' : lang === 'fr' ? 'fr-FR' : 'en-US';
  try {
    return new Intl.NumberFormat(locale, { style: 'currency', currency, minimumFractionDigits: currency === 'KWD' ? 3 : 2, maximumFractionDigits: currency === 'KWD' ? 3 : 2 }).format(value);
  } catch {
    const formatted = new Intl.NumberFormat(locale, { minimumFractionDigits: currency === 'KWD' ? 3 : 2, maximumFractionDigits: currency === 'KWD' ? 3 : 2 }).format(value);
    return `${formatted} ${currency === 'KWD' && lang === 'ar' ? 'د.ك' : currency}`;
  }
}

function currencyLabel(currency: string | null | undefined, lang: string) {
  const item = CURRENCIES.find(entry => entry.id === currency);
  return item?.label[lang as Lang] ?? currency ?? 'KWD';
}

function formatFileSize(size?: number | null) {
  if (!size) return '';
  if (size < 1024 * 1024) return `${Math.round(size / 1024)} KB`;
  return `${(size / (1024 * 1024)).toFixed(1)} MB`;
}

function csvEscape(value: string | number | boolean | null | undefined) {
  const text = String(value ?? '');
  return `"${text.replaceAll('"', '""')}"`;
}

function formatDate(value: string | null | undefined, lang: string) {
  const date = dateOnlyToLocalDate(value);
  const locale = lang === 'ar' ? 'ar-KW' : lang === 'fr' ? 'fr-FR' : 'en-US';
  return new Intl.DateTimeFormat(locale, { day: 'numeric', month: 'short', year: 'numeric' }).format(date);
}

function typeLabel(type: string | null | undefined, lang: string) {
  const item = TYPES.find(entry => entry.id === normalizeType(type)) ?? TYPES.at(-1)!;
  return item.label[lang as Lang] ?? item.label.ar;
}

function typeIcon(type: string | null | undefined) {
  return (TYPES.find(entry => entry.id === normalizeType(type)) ?? TYPES.at(-1)!).icon;
}

function statusLabel(status: string | null | undefined, lang: string) {
  const item = STATUSES.find(entry => entry.id === normalizeStatus(status)) ?? STATUSES[0];
  return item.label[lang as Lang] ?? item.label.ar;
}

function legacyName(row: IncomeRow) {
  return row.label || row.name || row.source_name || 'Income';
}

export default function IncomePage() {
  const { lang, dir } = useLanguage();
  const { user, isGuest } = useAuth();
  const [rows, setRows] = useState<IncomeRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [modalOpen, setModalOpen] = useState(false);
  const [form, setForm] = useState<IncomeForm>(() => emptyForm());
  const [saving, setSaving] = useState(false);
  const [formError, setFormError] = useState('');
  const [toast, setToast] = useState('');
  const [insightOpen, setInsightOpen] = useState<string | null>(null);
  const [statusFilter, setStatusFilter] = useState<IncomeFilter>('all');
  const [exportOpen, setExportOpen] = useState(false);
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [attachmentError, setAttachmentError] = useState('');

  const locale = lang === 'ar' ? 'ar-KW' : lang === 'fr' ? 'fr-FR' : 'en-US';

  const load = useCallback(async () => {
    setLoading(true);
    if (isGuest || !user) {
      try {
        const local = JSON.parse(localStorage.getItem('sfm_guest_income') || '[]') as IncomeRow[];
        setRows(local);
      } catch {
        setRows([]);
      }
      setLoading(false);
      return;
    }
    const { data } = await supabase
      .from('monthly_income_sources')
      .select('*')
      .eq('user_id', user.id)
      .order('received_date', { ascending: false, nullsFirst: false })
      .order('created_at', { ascending: false });
    setRows((data ?? []) as IncomeRow[]);
    setLoading(false);
  }, [isGuest, user]);

  useEffect(() => {
    void load();
  }, [load]);

  useEffect(() => {
    if (!modalOpen) return;
    const onKey = (event: KeyboardEvent) => {
      if (event.key === 'Escape') setModalOpen(false);
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [modalOpen]);

  useEffect(() => {
    if (!exportOpen) return;
    const onKey = (event: KeyboardEvent) => {
      if (event.key === 'Escape') setExportOpen(false);
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [exportOpen]);

  const viewRows = useMemo<IncomeViewRow[]>(() => rows.map(row => ({ ...row, workflowStatus: workflowStatus(row) })), [rows]);
  const filteredRows = useMemo(() => {
    if (statusFilter === 'all') return viewRows;
    if (statusFilter === 'recurring') return viewRows.filter(row => row.is_recurring);
    if (statusFilter === 'one-time') return viewRows.filter(row => !row.is_recurring);
    return viewRows.filter(row => row.workflowStatus === statusFilter);
  }, [statusFilter, viewRows]);
  const upcomingRows = useMemo(() => viewRows
    .filter(row => row.workflowStatus === 'expected' || row.workflowStatus === 'pending')
    .sort((a, b) => compareDateOnly(a.received_date || a.generated_for_date || todayDateOnly(), b.received_date || b.generated_for_date || todayDateOnly()))
    .slice(0, 5), [viewRows]);
  const lateRows = useMemo(() => viewRows.filter(row => row.workflowStatus === 'late'), [viewRows]);

  const total = viewRows.reduce((sum, row) => sum + Number(row.amount || 0), 0);
  const activeSources = viewRows.filter(row => row.workflowStatus !== 'late').length;
  const expectedNet = Math.max(total * 0.433, 0);

  const distribution = useMemo(() => {
    const data = [
      { label: typeLabel('salary', lang), value: 74, color: '#3D2914' },
      { label: typeLabel('bonus', lang), value: 19.8, color: '#BA7517' },
      { label: typeLabel('rent', lang), value: 6.2, color: '#EF9F27' },
    ];
    return data;
  }, [lang]);

  const trend = [1850, 1910, 1980, 2025, 2100, 2160, 2210, 2260, 2310, 2380, 2416, 2542];
  const points = trend.map((value, index) => {
    const x = (index / (trend.length - 1)) * 360;
    const min = Math.min(...trend);
    const max = Math.max(...trend);
    const y = 130 - ((value - min) / (max - min || 1)) * 110;
    return `${x.toFixed(1)},${y.toFixed(1)}`;
  }).join(' ');

  function openCreate() {
    setForm(emptyForm());
    setFormError('');
    setAttachmentError('');
    setSelectedFile(null);
    setModalOpen(true);
  }

  function openEdit(row: IncomeRow) {
    setForm({
      id: row.id,
      name: legacyName(row),
      amount: String(row.amount || ''),
      currency: row.currency || 'KWD',
      incomeType: normalizeType(row.income_type || row.category),
      receivedDate: row.received_date || (row.created_at ? row.created_at.slice(0, 10) : new Date().toISOString().slice(0, 10)),
      status: normalizeStatus(row.status),
      isRecurring: Boolean(row.is_recurring),
      frequency: (row.frequency === 'weekly' || row.frequency === 'yearly' ? row.frequency : 'monthly'),
      recurrenceStartDate: row.recurrence_start_date || row.received_date || (row.created_at ? row.created_at.slice(0, 10) : todayDateOnly()),
      recurrenceEndDate: row.recurrence_end_date || '',
      sourceName: row.source_name || '',
      notes: row.notes || '',
    });
    setFormError('');
    setAttachmentError('');
    setSelectedFile(null);
    setModalOpen(true);
  }

  function showToast(message: string) {
    setToast(message);
    window.setTimeout(() => setToast(''), 2200);
  }

  function validateAttachment(file: File) {
    if (!ALLOWED_ATTACHMENT_TYPES.includes(file.type)) return tr('unsupportedFile', lang);
    if (file.size > MAX_ATTACHMENT_SIZE) return tr('fileTooLarge', lang);
    return '';
  }

  function handleFileSelect(file: File | null) {
    setAttachmentError('');
    if (!file) {
      setSelectedFile(null);
      return;
    }
    const error = validateAttachment(file);
    if (error) {
      setAttachmentError(error);
      setSelectedFile(null);
      return;
    }
    setSelectedFile(file);
  }

  async function uploadAttachment(incomeId: string): Promise<AttachmentPayload> {
    if (!selectedFile) {
      const existing = rows.find(row => row.id === incomeId);
      return {
        attachment_url: existing?.attachment_url ?? null,
        attachment_name: existing?.attachment_name ?? null,
        attachment_type: existing?.attachment_type ?? null,
        attachment_size: existing?.attachment_size ?? null,
      };
    }
    if (isGuest || !user) {
      return {
        attachment_url: URL.createObjectURL(selectedFile),
        attachment_name: selectedFile.name,
        attachment_type: selectedFile.type,
        attachment_size: selectedFile.size,
      };
    }
    const safeName = selectedFile.name.replace(/[^\w.\-]+/g, '-');
    const path = `${user.id}/${incomeId}/${Date.now()}-${safeName}`;
    const { error } = await supabase.storage.from('income-attachments').upload(path, selectedFile, {
      cacheControl: '3600',
      upsert: true,
      contentType: selectedFile.type,
    });
    if (error) throw error;
    const { data } = supabase.storage.from('income-attachments').getPublicUrl(path);
    return {
      attachment_url: data.publicUrl,
      attachment_name: selectedFile.name,
      attachment_type: selectedFile.type,
      attachment_size: selectedFile.size,
    };
  }

  function exportCsv() {
    try {
      const headers = ['date', 'name', 'type', 'status', 'amount', 'currency', 'source', 'notes', 'recurring', 'frequency'];
      const lines = viewRows.map(row => [
        row.received_date || row.generated_for_date || '',
        legacyName(row),
        typeLabel(row.income_type || row.category, lang),
        statusLabel(row.workflowStatus, lang),
        Number(row.amount || 0),
        row.currency || 'KWD',
        row.source_name || '',
        row.notes || '',
        row.is_recurring ? tr('recurring', lang) : tr('oneTime', lang),
        row.frequency || '',
      ].map(csvEscape).join(','));
      const blob = new Blob([`\uFEFF${headers.join(',')}\n${lines.join('\n')}`], { type: 'text/csv;charset=utf-8;' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `income-data-${todayDateOnly().slice(0, 7)}.csv`;
      link.click();
      URL.revokeObjectURL(url);
      setExportOpen(false);
      showToast(tr('exportSuccess', lang));
    } catch {
      showToast(tr('exportFailed', lang));
    }
  }

  function exportPdf() {
    try {
      const report = window.open('', '_blank', 'noopener,noreferrer,width=900,height=700');
      if (!report) throw new Error('Popup blocked');
      const rowsHtml = viewRows.map(row => `
        <tr>
          <td>${formatDate(row.received_date || row.generated_for_date, lang)}</td>
          <td>${legacyName(row)}</td>
          <td>${typeLabel(row.income_type || row.category, lang)}</td>
          <td>${statusLabel(row.workflowStatus, lang)}</td>
          <td>${formatMoney(Number(row.amount || 0), lang, row.currency || 'KWD')}</td>
        </tr>
      `).join('');
      report.document.write(`
        <!doctype html>
        <html dir="${dir}" lang="${lang}">
          <head>
            <meta charset="utf-8" />
            <title>${tr('generatedReport', lang)}</title>
            <style>
              body{font-family:Arial,sans-serif;background:#f5f1e8;color:#24180d;padding:32px}
              .page{background:#fff;border:1px solid rgba(0,0,0,.08);border-radius:18px;padding:24px}
              h1{margin:0 0 8px;color:#3D2914}.brand{color:#BA7517;font-weight:700}
              .stats{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:20px 0}
              .stat{border:1px solid rgba(0,0,0,.08);border-radius:12px;padding:12px}.stat b{display:block;margin-top:6px}
              table{width:100%;border-collapse:collapse;margin-top:16px}th,td{border-bottom:1px solid rgba(0,0,0,.08);padding:10px;text-align:start;font-size:13px}
              footer{margin-top:22px;color:#6f5b45;font-size:12px}
              @media print{body{background:#fff;padding:0}.page{border:0}}
            </style>
          </head>
          <body>
            <main class="page">
              <div class="brand">THE SFM</div>
              <h1>${tr('generatedReport', lang)}</h1>
              <p>${tr('monthNow', lang)} · ${formatDate(todayDateOnly(), lang)}</p>
              <section class="stats">
                <div class="stat">${tr('totalIncome', lang)}<b>${formatMoney(total || 0, lang)}</b></div>
                <div class="stat">${tr('incomeSources', lang)}<b>${activeSources}</b></div>
                <div class="stat">${tr('expectedNet', lang)}<b>${formatMoney(expectedNet || 0, lang)}</b></div>
              </section>
              <h2>${tr('distribution', lang)}</h2>
              <p>${distribution.map(item => `${item.label}: ${item.value}%`).join(' · ')}</p>
              <table>
                <thead><tr><th>${tr('date', lang)}</th><th>${tr('name', lang)}</th><th>${tr('type', lang)}</th><th>${tr('status', lang)}</th><th>${tr('amount', lang)}</th></tr></thead>
                <tbody>${rowsHtml}</tbody>
              </table>
              <footer>${tr('reportDisclaimer', lang)}</footer>
            </main>
            <script>window.addEventListener('load',()=>setTimeout(()=>window.print(),250));</script>
          </body>
        </html>
      `);
      report.document.close();
      setExportOpen(false);
      showToast(tr('exportSuccess', lang));
    } catch {
      showToast(tr('exportFailed', lang));
    }
  }

  async function saveIncome(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (saving) return;
    const name = form.name.trim();
    const amount = Number(form.amount);
    if (name.length < 2) return setFormError(tr('nameError', lang));
    if (!amount || amount <= 0) return setFormError(tr('amountError', lang));
    if (!form.incomeType || !form.status) return setFormError(tr('requiredError', lang));
    if (form.isRecurring && (!form.frequency || !form.recurrenceStartDate)) return setFormError(tr('requiredError', lang));
    if (!form.isRecurring && !form.receivedDate) return setFormError(tr('requiredError', lang));

    setSaving(true);
    const id = form.id || crypto.randomUUID();
    const now = new Date().toISOString();
    const receivedDate = form.isRecurring ? form.recurrenceStartDate : form.receivedDate;
    const savedStatus = form.isRecurring ? workflowStatus({ id, amount, status: 'expected', received_date: receivedDate }) : form.status;
    let attachmentPayload: AttachmentPayload = {
      attachment_url: rows.find(row => row.id === id)?.attachment_url ?? null,
      attachment_name: rows.find(row => row.id === id)?.attachment_name ?? null,
      attachment_type: rows.find(row => row.id === id)?.attachment_type ?? null,
      attachment_size: rows.find(row => row.id === id)?.attachment_size ?? null,
    };
    if (selectedFile) {
      try {
        attachmentPayload = await uploadAttachment(id);
      } catch {
        setAttachmentError(tr('uploadFailed', lang));
        showToast(tr('storageSetup', lang));
      }
    }
    const payload = {
      label: name,
      category: form.incomeType,
      amount,
      amount_kwd: form.currency === 'KWD' ? amount : null,
      exchange_rate: null,
      income_type: form.incomeType,
      status: savedStatus,
      received_date: receivedDate,
      currency: form.currency,
      ...attachmentPayload,
      source_name: form.sourceName || null,
      notes: form.notes || null,
      is_recurring: form.isRecurring,
      frequency: form.isRecurring ? form.frequency : null,
      recurrence_start_date: form.isRecurring ? form.recurrenceStartDate : null,
      recurrence_end_date: form.isRecurring && form.recurrenceEndDate ? form.recurrenceEndDate : null,
      parent_recurring_income_id: null,
      generated_for_date: form.isRecurring ? form.recurrenceStartDate : null,
      confirmed_at: savedStatus === 'received' ? now : null,
      updated_at: now,
    };
    const nextRow: IncomeRow = { id, ...payload, created_at: now };
    const occurrenceDates = form.isRecurring ? generateOccurrenceDates(form.recurrenceStartDate, form.frequency, form.recurrenceEndDate) : [];
    const futureDates = occurrenceDates.slice(1);
    const makeGeneratedRows = (parentId: string, createdAt = now): IncomeRow[] => futureDates.map(date => ({
      ...nextRow,
      id: crypto.randomUUID(),
      status: 'expected',
      received_date: date,
      recurrence_start_date: form.recurrenceStartDate,
      recurrence_end_date: form.recurrenceEndDate || null,
      parent_recurring_income_id: parentId,
      generated_for_date: date,
      confirmed_at: null,
      created_at: createdAt,
      updated_at: createdAt,
    }));

    try {
      if (isGuest || !user) {
        const generatedRows = form.isRecurring && !form.id ? makeGeneratedRows(id) : [];
        const combined = form.id ? rows.map(row => row.id === id ? { ...row, ...nextRow } : row) : [nextRow, ...generatedRows, ...rows];
        const seen = new Set<string>();
        const next = combined.filter(row => {
          const key = row.parent_recurring_income_id && row.generated_for_date ? `${row.parent_recurring_income_id}:${row.generated_for_date}` : row.id;
          if (seen.has(key)) return false;
          seen.add(key);
          return true;
        });
        localStorage.setItem('sfm_guest_income', JSON.stringify(next));
        setRows(next);
      } else if (form.id) {
        const { error } = await supabase.from('monthly_income_sources').update(payload).eq('id', id).eq('user_id', user.id);
        if (error) throw error;
        setRows(previous => previous.map(row => row.id === id ? { ...row, ...nextRow } : row));
      } else {
        const { data, error } = await supabase
          .from('monthly_income_sources')
          .insert({ ...payload, user_id: user.id })
          .select('*')
          .single();
        if (error) throw error;
        const parent = data as IncomeRow;
        let generatedRows: IncomeRow[] = [];
        if (form.isRecurring && futureDates.length > 0) {
          const { data: existing } = await supabase
            .from('monthly_income_sources')
            .select('generated_for_date')
            .eq('user_id', user.id)
            .eq('parent_recurring_income_id', parent.id)
            .in('generated_for_date', futureDates);
          const existingDates = new Set((existing ?? []).map(item => item.generated_for_date));
          const inserts = futureDates
            .filter(date => !existingDates.has(date))
            .map(date => ({
              label: name,
              category: form.incomeType,
              amount,
              amount_kwd: form.currency === 'KWD' ? amount : null,
              exchange_rate: null,
              income_type: form.incomeType,
              status: 'expected',
              received_date: date,
              currency: form.currency,
              source_name: form.sourceName || null,
              notes: form.notes || null,
              is_recurring: true,
              frequency: form.frequency,
              recurrence_start_date: form.recurrenceStartDate,
              recurrence_end_date: form.recurrenceEndDate || null,
              parent_recurring_income_id: parent.id,
              generated_for_date: date,
              confirmed_at: null,
              user_id: user.id,
              updated_at: now,
            }));
          if (inserts.length > 0) {
            const { data: inserted, error: insertError } = await supabase
              .from('monthly_income_sources')
              .insert(inserts)
              .select('*');
            if (insertError) throw insertError;
            generatedRows = (inserted ?? []) as IncomeRow[];
          }
        }
        setRows(previous => [parent, ...generatedRows, ...previous]);
      }
      setModalOpen(false);
      setSelectedFile(null);
      setAttachmentError('');
      showToast(tr('saved', lang));
    } catch (error) {
      setFormError(error instanceof Error ? error.message : tr('requiredError', lang));
    } finally {
      setSaving(false);
    }
  }

  async function deleteIncome(row: IncomeRow) {
    if (isGuest || !user) {
      const next = rows.filter(item => item.id !== row.id);
      localStorage.setItem('sfm_guest_income', JSON.stringify(next));
      setRows(next);
    } else {
      await supabase.from('monthly_income_sources').delete().eq('id', row.id).eq('user_id', user.id);
      setRows(previous => previous.filter(item => item.id !== row.id));
    }
    showToast(tr('deleted', lang));
  }

  async function confirmReceived(row: IncomeRow) {
    const confirmedAt = new Date().toISOString();
    const nextRow = { ...row, status: 'received', confirmed_at: confirmedAt, updated_at: confirmedAt };
    try {
      if (isGuest || !user) {
        const next = rows.map(item => item.id === row.id ? nextRow : item);
        localStorage.setItem('sfm_guest_income', JSON.stringify(next));
        setRows(next);
      } else {
        const { error } = await supabase
          .from('monthly_income_sources')
          .update({ status: 'received', confirmed_at: confirmedAt, updated_at: confirmedAt })
          .eq('id', row.id)
          .eq('user_id', user.id);
        if (error) throw error;
        setRows(previous => previous.map(item => item.id === row.id ? nextRow : item));
      }
      showToast(tr('confirmed', lang));
    } catch {
      showToast(tr('confirmError', lang));
    }
  }

  function donutBackground() {
    let cursor = 0;
    const stops = distribution.map(item => {
      const start = cursor;
      cursor += item.value;
      return `${item.color} ${start}% ${cursor}%`;
    }).join(', ');
    return `conic-gradient(${stops})`;
  }

  return (
    <div className="income-shell" dir={dir}>
      <AppHeader />
      <Sidebar />
      <main className="income-main">
        <header className="income-header">
          <div>
            <p>{tr('breadcrumb', lang)}</p>
            <h1>{tr('title', lang)}</h1>
            <span>{tr('monthNow', lang)}</span>
          </div>
          <div className="income-actions">
            <div className="export-wrap">
              <button type="button" className="ghost" aria-label={tr('export', lang)} onClick={() => setExportOpen(open => !open)}>
                <Download size={16} />{tr('export', lang)}
              </button>
              {exportOpen && (
                <div className="export-menu" role="menu">
                  <button type="button" role="menuitem" onClick={exportPdf}><FileText size={15} />{tr('exportPdf', lang)}</button>
                  <button type="button" role="menuitem" onClick={exportCsv}><FileDown size={15} />{tr('exportExcel', lang)}</button>
                </div>
              )}
            </div>
            <button type="button" className="primary" onClick={openCreate}>
              <Plus size={16} />{tr('addIncome', lang)}
            </button>
          </div>
        </header>

        <section className="insights" aria-label="income insights">
          {[
            ['success', tr('savingsInsight', lang), null],
            ['warning', tr('spendingInsight', lang), tr('viewExpenses', lang)],
            ['info', tr('forecastInsight', lang), null],
          ].map(([tone, text, action]) => (
            <button type="button" className={`insight ${tone}`} key={text} onClick={() => setInsightOpen(text)}>
              <Sparkles size={17} />
              <span>{text}</span>
              {action && <b>{action}</b>}
            </button>
          ))}
        </section>

        <section className="stat-grid">
          <article><span><Wallet size={18} />{tr('totalIncome', lang)}</span><strong>{formatMoney(total || 2416, lang)}</strong><em>↑ 8.2%</em></article>
          <article><span><BriefcaseBusiness size={18} />{tr('incomeSources', lang)}</span><strong>{activeSources || 3} {tr('active', lang)}</strong><em>↑ 2</em></article>
          <article><span><CircleDollarSign size={18} />{tr('expectedNet', lang)}</span><strong>{formatMoney(expectedNet || 1046.4, lang)}</strong><em>↑ 3.1%</em></article>
        </section>

        {lateRows.length > 0 && (
          <section className="late-card">
            <span><AlertTriangle size={18} />{tr('lateWarning', lang)}</span>
            <button type="button" onClick={() => setStatusFilter('late')}>{tr('viewLateIncome', lang)}</button>
          </section>
        )}

        <section className="panel upcoming-panel">
          <div className="panel-title list-title">
            <CalendarDays size={18} /><h2>{tr('upcomingIncome', lang)}</h2>
          </div>
          <div className="upcoming-list">
            {upcomingRows.length === 0 ? <div className="empty">{tr('noIncome', lang)}</div> : upcomingRows.map(row => (
              <article className="upcoming-item" key={row.id}>
                <div>
                  <strong>{legacyName(row)}</strong>
                  <span>{formatDate(row.received_date || row.generated_for_date, lang)} · {formatMoney(Number(row.amount || 0), lang, row.currency || 'KWD')}</span>
                </div>
                <em className={`status ${row.workflowStatus}`}>{statusLabel(row.workflowStatus, lang)}</em>
                {row.workflowStatus !== 'expected' || compareDateOnly(row.received_date || row.generated_for_date || todayDateOnly(), todayDateOnly()) <= 0 ? (
                  <button type="button" onClick={() => void confirmReceived(row)} aria-label={tr('confirmReceived', lang)}>
                    <CheckCircle2 size={15} />{tr('confirmReceived', lang)}
                  </button>
                ) : null}
              </article>
            ))}
          </div>
        </section>

        <section className="chart-grid">
          <article className="panel">
            <div className="panel-title"><BarChart3 size={18} /><h2>{tr('distribution', lang)}</h2></div>
            <div className="donut-wrap">
              <div className="donut" style={{ background: donutBackground() }}><span>{new Intl.NumberFormat(locale).format(100)}%</span></div>
              <div className="legend">
                {distribution.map(item => <div key={item.label}><i style={{ background: item.color }} /> <span>{item.label}</span><b>{new Intl.NumberFormat(locale).format(item.value)}%</b></div>)}
              </div>
            </div>
          </article>
          <article className="panel">
            <div className="panel-title"><LineChart size={18} /><h2>{tr('trend', lang)}</h2></div>
            <svg className="line-chart" viewBox="0 0 360 150" role="img" aria-label={tr('trend', lang)}>
              <polyline points={points} fill="none" stroke="#BA7517" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round" />
              <circle cx="360" cy={points.split(' ').at(-1)?.split(',')[1] || 20} r="5" fill="#EF9F27" />
            </svg>
          </article>
        </section>

        <section className="panel">
          <div className="panel-title list-title">
            <ReceiptText size={18} /><h2>{tr('incomeList', lang)}</h2>
          </div>
          <div className="income-filters" role="group" aria-label={tr('status', lang)}>
            {[
              ['all', tr('all', lang)],
              ['received', statusLabel('received', lang)],
              ['pending', statusLabel('pending', lang)],
              ['expected', statusLabel('expected', lang)],
              ['late', statusLabel('late', lang)],
              ['recurring', tr('recurringFilter', lang)],
              ['one-time', tr('oneTimeFilter', lang)],
            ].map(([id, label]) => (
              <button key={id} type="button" className={statusFilter === id ? 'active' : ''} onClick={() => setStatusFilter(id as IncomeFilter)}>
                {label}
              </button>
            ))}
          </div>
          <div className="income-list">
            {loading ? <div className="empty">{tr('title', lang)}...</div> : filteredRows.length === 0 ? <div className="empty">{tr('noIncome', lang)}</div> : filteredRows.map(row => {
              const amount = Number(row.amount || 0);
              const pct = total > 0 ? Math.round((amount / total) * 100) : 0;
              return (
                <article className="income-row" key={row.id}>
                  <div className="row-main">
                    <div className="row-icon">{typeIcon(row.income_type || row.category)}</div>
                    <div>
                      <strong>{legacyName(row)}</strong>
                      <span>{typeLabel(row.income_type || row.category, lang)} · {row.source_name || tr('source', lang)}</span>
                      <div className="row-meta">
                        <em className={`status ${row.workflowStatus}`}>{statusLabel(row.workflowStatus, lang)}</em>
                        <em>{row.is_recurring ? tr('recurring', lang) : tr('oneTime', lang)}</em>
                        <em><CalendarDays size={12} />{formatDate(row.received_date || row.generated_for_date || row.created_at, lang)}</em>
                        {row.attachment_url && <em><Paperclip size={12} />{tr('attachment', lang)}</em>}
                        <em>{pct}% {tr('percent', lang)}</em>
                      </div>
                    </div>
                  </div>
                  <div className="row-side">
                    <b>{formatMoney(amount, lang, row.currency || 'KWD')}</b>
                    <div>
                      {row.workflowStatus !== 'received' && (
                        <button type="button" aria-label={tr('confirmReceived', lang)} onClick={() => void confirmReceived(row)}><CheckCircle2 size={15} /></button>
                      )}
                      {row.attachment_url && (
                        <button type="button" aria-label={tr('viewAttachment', lang)} onClick={() => window.open(row.attachment_url || '', '_blank', 'noopener,noreferrer')}><ExternalLink size={15} /></button>
                      )}
                      <button type="button" aria-label={tr('edit', lang)} onClick={() => openEdit(row)}><Edit3 size={15} /></button>
                      <button type="button" aria-label={tr('delete', lang)} onClick={() => void deleteIncome(row)}><Trash2 size={15} /></button>
                    </div>
                  </div>
                </article>
              );
            })}
          </div>
        </section>
      </main>

      {modalOpen && (
        <div className="modal-backdrop" role="presentation" onMouseDown={() => setModalOpen(false)}>
          <div className="income-modal" role="dialog" aria-modal="true" aria-labelledby="income-modal-title" onMouseDown={event => event.stopPropagation()}>
            <div className="modal-head">
              <div><p>{tr('breadcrumb', lang)}</p><h2 id="income-modal-title">{form.id ? tr('edit', lang) : tr('addIncome', lang)}</h2></div>
              <button type="button" aria-label={tr('close', lang)} onClick={() => setModalOpen(false)}><X size={18} /></button>
            </div>
            <form className="income-form" onSubmit={saveIncome}>
              <label><span>{tr('name', lang)}</span><input autoFocus value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} required minLength={2} /></label>
              <label><span>{tr('amount', lang)}</span><input value={form.amount} inputMode="decimal" onChange={e => setForm({ ...form, amount: e.target.value })} required /></label>
              <label><span>{tr('currency', lang)}</span><select value={form.currency} onChange={e => setForm({ ...form, currency: e.target.value as SupportedCurrency })}>{CURRENCIES.map(item => <option key={item.id} value={item.id}>{currencyLabel(item.id, lang)}</option>)}</select></label>
              {form.currency !== 'KWD' && <div className="form-note">{tr('conversionDisabled', lang)}</div>}
              <label><span>{tr('receivedDate', lang)}</span><input type="date" value={form.receivedDate} onChange={e => setForm({ ...form, receivedDate: e.target.value })} required={!form.isRecurring} /></label>
              <label><span>{tr('type', lang)}</span><select value={form.incomeType} onChange={e => setForm({ ...form, incomeType: e.target.value as IncomeType })}>{TYPES.map(item => <option key={item.id} value={item.id}>{item.icon} {item.label[lang as Lang]}</option>)}</select></label>
              <label><span>{tr('status', lang)}</span><select value={form.status} onChange={e => setForm({ ...form, status: e.target.value as IncomeStatus })}>{STATUSES.map(item => <option key={item.id} value={item.id}>{item.label[lang as Lang]}</option>)}</select></label>
              <label className="toggle-line"><span>{tr('recurring', lang)}</span><button type="button" className={form.isRecurring ? 'toggle on' : 'toggle'} onClick={() => setForm({ ...form, isRecurring: !form.isRecurring })}><span />{form.isRecurring ? tr('recurring', lang) : tr('oneTime', lang)}</button></label>
              {form.isRecurring && (
                <>
                  <label><span>{tr('frequency', lang)}</span><select value={form.frequency} onChange={e => setForm({ ...form, frequency: e.target.value as Frequency })}>{FREQUENCIES.map(item => <option key={item.id} value={item.id}>{item.label[lang as Lang]}</option>)}</select></label>
                  <label><span>{tr('startDate', lang)}</span><input type="date" value={form.recurrenceStartDate} onChange={e => setForm({ ...form, recurrenceStartDate: e.target.value, receivedDate: e.target.value })} required /></label>
                  <label><span>{tr('endDateOptional', lang)}</span><input type="date" value={form.recurrenceEndDate} onChange={e => setForm({ ...form, recurrenceEndDate: e.target.value })} /></label>
                  {form.id && <div className="form-note">{tr('editThisOnly', lang)}</div>}
                </>
              )}
              <label><span>{tr('sourceCompany', lang)}</span><input value={form.sourceName} onChange={e => setForm({ ...form, sourceName: e.target.value })} /></label>
              <label className="wide"><span>{tr('notes', lang)}</span><textarea value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} /></label>
              <div className="attachment-field">
                <label>
                  <span>{tr('attachFile', lang)}</span>
                  <input type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,application/pdf,image/png,image/jpeg,image/webp" onChange={event => handleFileSelect(event.target.files?.[0] ?? null)} />
                </label>
                {(selectedFile || (form.id && rows.find(row => row.id === form.id)?.attachment_name)) && (
                  <div className="attachment-chip">
                    <Paperclip size={14} />
                    <span>{selectedFile?.name || rows.find(row => row.id === form.id)?.attachment_name}</span>
                    <small>{formatFileSize(selectedFile?.size || rows.find(row => row.id === form.id)?.attachment_size)}</small>
                    {selectedFile && <button type="button" onClick={() => setSelectedFile(null)} aria-label={tr('removeAttachment', lang)}><X size={13} /></button>}
                  </div>
                )}
                {attachmentError && <div className="form-error">{attachmentError}</div>}
              </div>
              {formError && <div className="form-error">{formError}</div>}
              <div className="form-actions">
                <button type="button" className="ghost-light" onClick={() => setModalOpen(false)} disabled={saving}>{tr('cancel', lang)}</button>
                <button type="submit" className="primary-dark" disabled={saving}>{saving ? tr('saving', lang) : form.id ? tr('save', lang) : tr('add', lang)}</button>
              </div>
            </form>
          </div>
        </div>
      )}

      {insightOpen && (
        <div className="mini-pop" role="dialog" aria-modal="true">
          <button type="button" aria-label={tr('close', lang)} onClick={() => setInsightOpen(null)}><X size={14} /></button>
          <strong>{insightOpen}</strong>
          <p>{tr('insightDetails', lang)}</p>
        </div>
      )}
      {toast && <div className="toast">{toast}</div>}

      <style jsx>{`
        .income-shell{min-height:100dvh;background:#F5F1E8;color:#24180d;font-family:Cairo,Tajawal,"IBM Plex Sans Arabic",Arial,sans-serif;overflow-x:hidden}
        .income-main{width:100%;max-width:1320px;margin:0 auto;padding:24px;margin-inline-start:250px;display:grid;gap:16px}
        .income-header{display:flex;justify-content:space-between;align-items:flex-end;gap:16px;background:#fff;border:1px solid rgba(0,0,0,.08);border-radius:18px;padding:20px}
        .income-header p,.income-header span{margin:0;color:#7b6248;font-size:13px;font-weight:500}.income-header h1{margin:6px 0;font-size:34px;font-weight:600;color:#3D2914}
        .income-actions{display:flex;gap:10px;flex-wrap:wrap}.export-wrap{position:relative}.export-menu{position:absolute;z-index:60;inset-block-start:48px;inset-inline-end:0;min-width:190px;background:#fff;border:1px solid rgba(0,0,0,.08);border-radius:14px;padding:8px;box-shadow:0 16px 38px rgba(61,41,20,.12)}.export-menu button{width:100%;height:38px;border:0;border-radius:10px;background:#fff;color:#3D2914;display:flex;align-items:center;gap:8px;padding:0 10px;font:600 13px inherit;cursor:pointer;text-align:start}.export-menu button:hover{background:#FAEEDA;color:#854F0B}.primary,.ghost,.primary-dark,.ghost-light{border-radius:12px;border:1px solid rgba(0,0,0,.08);height:42px;padding:0 14px;display:inline-flex;align-items:center;justify-content:center;gap:8px;font:500 14px inherit;cursor:pointer}.primary,.primary-dark{background:#3D2914;color:#fff}.ghost{background:#fff;color:#3D2914}.ghost:disabled{opacity:.55;cursor:not-allowed}.ghost-light{background:#fff;color:#3D2914}
        .insights{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.insight{min-height:74px;text-align:start;border:1px solid rgba(0,0,0,.08);border-radius:16px;padding:14px;background:#fff;display:flex;align-items:center;gap:10px;color:#3D2914;cursor:pointer}.insight span{line-height:1.6;font-weight:500}.insight b{margin-inline-start:auto;font-size:12px;color:#854F0B}.insight.success{background:#EAF3DE;color:#27500A}.insight.warning{background:#FAEEDA;color:#854F0B}.insight.info{background:#E6F1FB;color:#0C447C}
        .stat-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.stat-grid article,.panel{background:#fff;border:1px solid rgba(0,0,0,.08);border-radius:18px;padding:18px;box-shadow:0 8px 22px rgba(61,41,20,.04)}.stat-grid span{display:flex;gap:8px;align-items:center;color:#7b6248;font-size:13px}.stat-grid strong{display:block;margin-top:10px;font-size:26px;font-weight:600;color:#3D2914}.stat-grid em{display:inline-flex;margin-top:10px;border-radius:999px;background:#EAF3DE;color:#27500A;padding:4px 9px;font-style:normal;font-size:12px}
        .chart-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.panel-title{display:flex;align-items:center;gap:9px;margin-bottom:16px;color:#BA7517}.panel-title h2{margin:0;font-size:18px;font-weight:600;color:#3D2914}.donut-wrap{display:grid;grid-template-columns:180px 1fr;gap:18px;align-items:center}.donut{width:170px;aspect-ratio:1;border-radius:50%;display:grid;place-items:center;position:relative}.donut:after{content:"";position:absolute;inset:32px;background:#fff;border-radius:50%}.donut span{position:relative;z-index:1;font-weight:600;color:#3D2914}.legend{display:grid;gap:10px}.legend div{display:grid;grid-template-columns:auto 1fr auto;gap:8px;align-items:center;font-size:13px}.legend i{width:10px;height:10px;border-radius:50%}.line-chart{width:100%;height:auto;min-height:170px;background:#F5F1E8;border-radius:14px;padding:12px;overflow:visible}
        .late-card{display:flex;align-items:center;justify-content:space-between;gap:12px;background:#FAEEDA;color:#854F0B;border:1px solid rgba(133,79,11,.16);border-radius:16px;padding:14px 16px}.late-card span{display:flex;align-items:center;gap:8px;font-weight:600}.late-card button,.upcoming-item button{border:1px solid rgba(133,79,11,.16);background:#fff7eb;color:#854F0B;border-radius:12px;min-height:38px;padding:0 12px;display:inline-flex;align-items:center;gap:7px;font:600 12px inherit;cursor:pointer}.upcoming-panel{display:grid;gap:10px}.upcoming-list{display:grid;gap:9px}.upcoming-item{display:grid;grid-template-columns:1fr auto auto;align-items:center;gap:10px;border:1px solid rgba(0,0,0,.08);border-radius:14px;padding:12px;background:#fff}.upcoming-item strong{display:block;color:#3D2914;font-weight:600}.upcoming-item span{display:block;margin-top:4px;color:#7b6248;font-size:12px}.upcoming-item em,.income-filters button{font-style:normal;border-radius:999px;background:#F5F1E8;color:#7b6248;padding:5px 10px;font-size:12px;white-space:nowrap}.upcoming-item .received{background:#EAF3DE;color:#27500A}.upcoming-item .pending,.upcoming-item .expected{background:#FAEEDA;color:#854F0B}.upcoming-item .late{background:#FCEBEB;color:#791F1F}.income-filters{display:flex;gap:8px;overflow-x:auto;padding:0 0 12px;margin-top:-4px;scrollbar-width:thin}.income-filters button{border:1px solid rgba(0,0,0,.08);cursor:pointer;font:600 12px inherit}.income-filters button.active{background:#3D2914;color:#fff;border-color:#3D2914}
        .income-list{display:grid;gap:10px}.income-row{display:flex;justify-content:space-between;gap:14px;border:1px solid rgba(0,0,0,.08);border-radius:16px;padding:14px;background:#fff}.row-main{display:flex;gap:12px;min-width:0}.row-icon{width:44px;height:44px;border-radius:14px;background:#FAEEDA;display:grid;place-items:center;font-size:21px}.row-main strong{display:block;font-size:15px;font-weight:600;color:#3D2914}.row-main span{display:block;margin-top:4px;color:#7b6248;font-size:12px}.row-meta{display:flex;flex-wrap:wrap;gap:6px;margin-top:9px}.row-meta em{font-style:normal;border-radius:999px;background:#F5F1E8;color:#7b6248;padding:4px 8px;font-size:11px;display:inline-flex;align-items:center;gap:4px}.row-meta .received{background:#EAF3DE;color:#27500A}.row-meta .pending,.row-meta .expected{background:#FAEEDA;color:#854F0B}.row-meta .late{background:#FCEBEB;color:#791F1F}.row-side{display:flex;align-items:center;gap:12px}.row-side b{white-space:nowrap;color:#3D2914}.row-side div{display:flex;gap:6px}.row-side button,.modal-head button,.mini-pop button{width:36px;height:36px;border-radius:11px;border:1px solid rgba(0,0,0,.08);background:#fff;color:#3D2914;display:grid;place-items:center;cursor:pointer}.empty{padding:24px;text-align:center;color:#7b6248;border:1px dashed rgba(0,0,0,.12);border-radius:14px}
        .modal-backdrop{position:fixed;inset:0;z-index:90;background:rgba(36,24,13,.42);display:grid;place-items:center;padding:18px}.income-modal{width:min(760px,100%);max-height:min(92dvh,900px);overflow:auto;background:#fff;border-radius:20px;border:1px solid rgba(0,0,0,.08);padding:20px}.modal-head{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:16px}.modal-head p{margin:0;color:#BA7517;font-size:12px}.modal-head h2{margin:4px 0 0;font-size:24px;color:#3D2914}.income-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px}.income-form label{display:grid;gap:7px;color:#3D2914;font-size:13px;font-weight:500}.income-form input,.income-form select,.income-form textarea{width:100%;border:1px solid rgba(0,0,0,.08);border-radius:12px;background:#F5F1E8;color:#3D2914;padding:0 12px;min-height:46px;font:500 14px inherit;outline:none}.income-form input[type=file]{padding:11px 12px}.income-form textarea{min-height:92px;padding-top:12px;resize:vertical}.income-form input:focus,.income-form select:focus,.income-form textarea:focus{border-color:#BA7517;box-shadow:0 0 0 3px rgba(186,117,23,.14);background:#fff}.wide,.form-actions,.form-error,.form-note,.attachment-field{grid-column:1/-1}.attachment-field{display:grid;gap:10px}.attachment-chip{display:flex;align-items:center;gap:8px;border:1px solid rgba(0,0,0,.08);border-radius:12px;background:#F5F1E8;color:#3D2914;padding:9px 10px;font-size:13px}.attachment-chip span{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.attachment-chip small{color:#7b6248;margin-inline-start:auto}.attachment-chip button{width:28px;height:28px;border-radius:9px;border:1px solid rgba(0,0,0,.08);background:#fff;color:#3D2914;display:grid;place-items:center;cursor:pointer}.toggle-line{align-content:end}.toggle{height:46px;border-radius:12px;border:1px solid rgba(0,0,0,.08);background:#F5F1E8;color:#3D2914;display:flex;align-items:center;gap:9px;padding:0 12px;cursor:pointer}.toggle span{width:20px;height:20px;border-radius:50%;background:#c9bea9}.toggle.on span{background:#BA7517}.form-actions{display:flex;justify-content:flex-end;gap:10px}.form-error{background:#FCEBEB;color:#791F1F;border-radius:12px;padding:10px 12px;font-size:13px}.form-note{background:#E6F1FB;color:#0C447C;border-radius:12px;padding:10px 12px;font-size:13px}
        .mini-pop,.toast{position:fixed;z-index:100;inset-inline-end:22px;bottom:22px;background:#fff;border:1px solid rgba(0,0,0,.08);border-radius:16px;padding:14px;max-width:min(360px,calc(100vw - 32px));box-shadow:0 16px 38px rgba(61,41,20,.12)}.mini-pop strong{display:block;margin-bottom:6px}.mini-pop p{margin:0;color:#7b6248;line-height:1.6}.mini-pop button{float:inline-end;width:28px;height:28px}.toast{background:#EAF3DE;color:#27500A;font-weight:600}
        @media(max-width:1024px){.income-main{margin-inline-start:0;padding:calc(84px + env(safe-area-inset-top)) 16px 24px}.insights,.chart-grid{grid-template-columns:1fr}.stat-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
        @media(max-width:680px){.income-header,.income-row,.late-card{display:grid}.income-actions,.form-actions{display:grid;grid-template-columns:1fr}.export-wrap,.primary,.ghost,.primary-dark,.ghost-light{width:100%}.export-menu{position:static;margin-top:8px}.stat-grid,.income-form,.donut-wrap,.upcoming-item{grid-template-columns:1fr}.row-side{justify-content:space-between}.modal-backdrop{align-items:end;padding:10px}.income-modal{border-radius:20px 20px 0 0;max-height:94dvh;padding-bottom:calc(20px + env(safe-area-inset-bottom))}.insight{align-items:flex-start}.insight b{margin-inline-start:0}.row-meta{gap:5px}.upcoming-item button,.late-card button{width:100%;justify-content:center}}
      `}</style>
    </div>
  );
}
