'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowLeftRight, Loader2 } from 'lucide-react';
import { DashboardPageShell } from '@/components/DashboardPageShell';
import { PageHero } from '@/components/layout/PageHero';
import { useAuth } from '@/hooks/useAuth';
import { useLanguage } from '@/hooks/useLanguage';
import { useCurrency } from '@/lib/useCurrency';
import { supabase } from '@/integrations/supabase/client';
import { loadUserDataTables, personalExpenseRows, personalIncomeRows } from '@/lib/data/financeData';
import { formatCurrency } from '@/lib/format';
import { compareFinancialDecisions } from '@/lib/decisions/decisionComparison';
import { missingTemplateInputs } from '@/lib/decisions/decisionTemplates';
import type { DecisionInputs, DecisionSourceData, DecisionType } from '@/lib/decisions/decisionAnalysis';

const TABLES = [
  { key: 'income', table: 'monthly_income_sources' }, { key: 'expenses', table: 'expense_items' },
  { key: 'debts', table: 'debts' }, { key: 'savings', table: 'savings_items' },
  { key: 'investments', table: 'investment_items' }, { key: 'goals', table: 'financial_goals' },
  { key: 'projects', table: 'projects' }, { key: 'financialModels', table: 'project_financial_models' },
  { key: 'zakatCalculations', table: 'zakat_calculations' }, { key: 'zakatAssets', table: 'zakat_assets' },
  { key: 'charityCommitments', table: 'charity_commitments' },
];

type Form = { label:string; title:string; decisionType:DecisionType; amount:string; upfront:string; financing:string; payment:string; term:string; monthlyCost:string; monthlyIncome:string; debtDirection:''|'new_loan'|'repay_debt'; debtPaydown:string; paymentReduction:string; riskLevel:'low'|'medium'|'high' };
const blank = (label:string):Form => ({ label,title:'',decisionType:'purchase',amount:'',upfront:'',financing:'',payment:'',term:'',monthlyCost:'',monthlyIncome:'',debtDirection:'',debtPaydown:'',paymentReduction:'',riskLevel:'medium' });
const n=(v:string)=>{const x=Number(v);return Number.isFinite(x)&&x>=0?x:0};

const COPY={
 ar:{eyebrow:'مختبر القرار',title:'قارن القرار قبل تنفيذه',sub:'قارن خيارين على نفس وضعك المالي الحقيقي. لا يفترض SFM دفعة أو تمويلاً أو دخلاً غير مدخل.',back:'العودة لمركز القرارات',a:'الخيار أ',b:'الخيار ب',name:'اسم الخيار',type:'نوع القرار',amount:'القيمة الإجمالية',upfront:'الدفعة الأولى / الكاش',financing:'مبلغ التمويل',payment:'القسط الشهري',term:'مدة التمويل بالأشهر',monthlyCost:'تكلفة شهرية إضافية',monthlyIncome:'تغير الدخل الشهري المتوقع',direction:'نوع قرار الدين',newLoan:'قرض جديد',repay:'سداد دين',paydown:'مبلغ سداد الدين',reduction:'انخفاض القسط بعد السداد',risk:'مخاطرة الاستثمار',result:'نتيجة المقارنة',recommended:'الأفضل حسب الوضع الحالي',missing:'بيانات مطلوبة ناقصة',riskScore:'درجة الملاءمة',monthlyNet:'الفائض بعد القرار',savings:'المدخرات بعد القرار',noWinner:'لا توجد توصية حتى تكتمل البيانات لكلا الخيارين.',loading:'جارٍ تحميل بياناتك المالية…'},
 en:{eyebrow:'Decision Lab',title:'Compare before you commit',sub:'Compare two options against the same real financial position. SFM does not invent a down payment, financing amount, or project income.',back:'Back to Decisions Center',a:'Option A',b:'Option B',name:'Option name',type:'Decision type',amount:'Total amount',upfront:'Down payment / cash',financing:'Financing principal',payment:'Monthly payment',term:'Loan term (months)',monthlyCost:'Additional monthly cost',monthlyIncome:'Expected monthly income change',direction:'Debt action',newLoan:'New loan',repay:'Repay debt',paydown:'Debt payoff amount',reduction:'Monthly payment reduction',risk:'Investment risk',result:'Comparison result',recommended:'Best fit for current position',missing:'Missing required inputs',riskScore:'Fit score',monthlyNet:'Surplus after decision',savings:'Savings after decision',noWinner:'No recommendation until both options have complete comparable inputs.',loading:'Loading your financial data…'},
 fr:{eyebrow:'Laboratoire de décision',title:'Comparez avant de vous engager',sub:'Comparez deux options avec la même situation financière réelle. SFM n’invente ni apport, ni financement, ni revenu de projet.',back:'Retour au centre de décisions',a:'Option A',b:'Option B',name:'Nom de l’option',type:'Type de décision',amount:'Montant total',upfront:'Apport / espèces',financing:'Montant financé',payment:'Mensualité',term:'Durée du prêt (mois)',monthlyCost:'Coût mensuel additionnel',monthlyIncome:'Variation mensuelle de revenu prévue',direction:'Action sur la dette',newLoan:'Nouveau prêt',repay:'Rembourser la dette',paydown:'Montant remboursé',reduction:'Réduction de mensualité',risk:'Risque investissement',result:'Résultat de comparaison',recommended:'Meilleure adéquation actuelle',missing:'Données requises manquantes',riskScore:'Score d’adéquation',monthlyNet:'Surplus après décision',savings:'Épargne après décision',noWinner:'Aucune recommandation tant que les deux options ne sont pas complètes et comparables.',loading:'Chargement de vos données financières…'}
} as const;
const TYPE:{[K in DecisionType]:{ar:string;en:string;fr:string}}={purchase:{ar:'شراء',en:'Purchase',fr:'Achat'},investment:{ar:'استثمار',en:'Investment',fr:'Investissement'},project:{ar:'مشروع',en:'Project',fr:'Projet'},debt_saving:{ar:'قرض / دين',en:'Loan / debt',fr:'Prêt / dette'},charity_zakat:{ar:'زكاة / خير',en:'Zakat / charity',fr:'Zakat / charité'},budget:{ar:'ميزانية',en:'Budget',fr:'Budget'}};

function inputs(f:Form,currency:string):DecisionInputs{return {title:f.title||f.label,decisionType:f.decisionType,amount:n(f.amount),currency,priority:'medium',riskLevel:f.riskLevel,upfrontCashOutflow:f.upfront===''?undefined:n(f.upfront),financingPrincipal:f.financing===''?undefined:n(f.financing),monthlyPayment:f.payment===''?undefined:n(f.payment),loanTermMonths:f.term===''?undefined:n(f.term),recurringCost:f.monthlyCost===''?undefined:n(f.monthlyCost),expectedMonthlyCost:f.decisionType==='project'&&f.monthlyCost!==''?n(f.monthlyCost):undefined,expectedMonthlyIncomeChange:f.monthlyIncome===''?undefined:n(f.monthlyIncome),debtDirection:f.debtDirection||undefined,debtPaydownAmount:f.debtPaydown===''?undefined:n(f.debtPaydown),monthlyDebtPaymentReduction:f.paymentReduction===''?undefined:n(f.paymentReduction),debtAmount:f.decisionType==='debt_saving'?n(f.amount):undefined,usesSavings:f.decisionType==='investment'||f.decisionType==='project'};}

export default function DecisionSimulatorPage(){
 const {user}=useAuth(); const {lang,dir}=useLanguage(); const {currency}=useCurrency(); const locale=lang==='fr'?'fr':lang==='en'?'en':'ar'; const t=COPY[locale];
 const [a,setA]=useState<Form>(blank(t.a)); const [b,setB]=useState<Form>(blank(t.b)); const [data,setData]=useState<DecisionSourceData|null>(null);
 useEffect(()=>{if(!user?.id)return; let live=true; (async()=>{const r=await loadUserDataTables(supabase as any,user.id,TABLES);if(!live)return;const x=r.records as Record<string,any[]>;setData({income:personalIncomeRows(x.income??[]),expenses:personalExpenseRows(x.expenses??[]),debts:x.debts??[],savings:x.savings??[],investments:x.investments??[],goals:x.goals??[],projects:x.projects??[],financialModels:x.financialModels??[],zakatCalculations:x.zakatCalculations??[],zakatAssets:x.zakatAssets??[],charityCommitments:x.charityCommitments??[]});})();return()=>{live=false}},[user?.id]);
 const ai=useMemo(()=>inputs(a,currency),[a,currency]); const bi=useMemo(()=>inputs(b,currency),[b,currency]);
 const comparison=useMemo(()=>data?compareFinancialDecisions([{id:'a',label:a.title||t.a,inputs:ai},{id:'b',label:b.title||t.b,inputs:bi}],data):null,[a.title,ai,b.title,bi,data,t.a,t.b]);
 const money=(v:number|null)=>v==null?'—':formatCurrency(v,currency,locale);
 const render=(f:Form,set:(v:Form)=>void,id:string)=>{const setv=(k:keyof Form,v:string)=>set({...f,[k]:v}); const financed=f.decisionType==='purchase'&&(f.financing!==''||f.payment!==''||f.upfront!==''); return <article className="decision-card"><h2>{id==='a'?t.a:t.b}</h2><div className="decision-form-grid"><label><span>{t.name}</span><input value={f.title} onChange={e=>setv('title',e.target.value)}/></label><label><span>{t.type}</span><select value={f.decisionType} onChange={e=>set({...f,decisionType:e.target.value as DecisionType})}>{Object.entries(TYPE).map(([k,v])=><option key={k} value={k}>{v[locale]}</option>)}</select></label><label><span>{t.amount}</span><input inputMode="decimal" value={f.amount} onChange={e=>setv('amount',e.target.value)}/></label>{f.decisionType==='purchase'&&<><label><span>{t.upfront}</span><input inputMode="decimal" value={f.upfront} onChange={e=>setv('upfront',e.target.value)}/></label><label><span>{t.financing}</span><input inputMode="decimal" value={f.financing} onChange={e=>setv('financing',e.target.value)}/></label>{financed&&<><label><span>{t.payment}</span><input inputMode="decimal" value={f.payment} onChange={e=>setv('payment',e.target.value)}/></label><label><span>{t.term}</span><input inputMode="numeric" value={f.term} onChange={e=>setv('term',e.target.value)}/></label></>}</>}{f.decisionType==='debt_saving'&&<><label><span>{t.direction}</span><select value={f.debtDirection} onChange={e=>setv('debtDirection',e.target.value)}><option value="">—</option><option value="new_loan">{t.newLoan}</option><option value="repay_debt">{t.repay}</option></select></label>{f.debtDirection==='new_loan'&&<><label><span>{t.financing}</span><input value={f.financing} onChange={e=>setv('financing',e.target.value)}/></label><label><span>{t.payment}</span><input value={f.payment} onChange={e=>setv('payment',e.target.value)}/></label></>}{f.debtDirection==='repay_debt'&&<><label><span>{t.paydown}</span><input value={f.debtPaydown} onChange={e=>setv('debtPaydown',e.target.value)}/></label><label><span>{t.reduction}</span><input value={f.paymentReduction} onChange={e=>setv('paymentReduction',e.target.value)}/></label></>}</>}{f.decisionType==='project'&&<><label><span>{t.monthlyCost}</span><input value={f.monthlyCost} onChange={e=>setv('monthlyCost',e.target.value)}/></label><label><span>{t.monthlyIncome}</span><input value={f.monthlyIncome} onChange={e=>setv('monthlyIncome',e.target.value)}/></label></>}{f.decisionType==='investment'&&<label><span>{t.risk}</span><select value={f.riskLevel} onChange={e=>setv('riskLevel',e.target.value)}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label>}</div>{missingTemplateInputs(inputs(f,currency)).length>0&&<p className="decision-message">{t.missing}: {missingTemplateInputs(inputs(f,currency)).join(', ')}</p>}</article>};
 if(!data)return <div dir={dir}><DashboardPageShell ariaLabel={t.title}><div className="decision-loading"><Loader2 className="spin" size={20}/>{t.loading}</div></DashboardPageShell></div>;
 return <div className="decisions-page" dir={dir}><DashboardPageShell ariaLabel={t.title} contentClassName="decisions-content"><PageHero eyebrow={t.eyebrow} title={t.title} subtitle={t.sub} icon={<ArrowLeftRight size={28}/>}/><p><Link href="/decisions">← {t.back}</Link></p><section className="decision-layout">{render(a,setA,'a')}{render(b,setB,'b')}</section><section className="decision-card"><h2>{t.result}</h2>{comparison?.recommendedId?<><h3>{t.recommended}: {comparison.entries.find(e=>e.id===comparison.recommendedId)?.label}</h3><div className="decision-layout">{comparison.entries.map(e=><div key={e.id} className="decision-card"><strong>{e.label}</strong><p>{t.riskScore}: {e.analysis.score==null?'—':Math.round(e.analysis.score)}</p><p>{t.monthlyNet}: {money(e.analysis.netAfterDecision)}</p><p>{t.savings}: {money(e.analysis.savingsAfterDecision)}</p></div>)}</div></>:<p>{t.noWinner}</p>}</section></DashboardPageShell></div>;
}
