import type { Lang } from '@/lib/translations';

const en = {
  centerAria: 'Charity Center',
  eyebrow: 'Islamic giving, clearly organized',
  centerTitle: 'Charity Center',
  centerSubtitle: 'A calm overview of your Zakat, Khums, donations, projects, beneficiaries, receipts, and reminders.',
  centerPrinciple: 'One center. Independent obligations.',
  centerPrincipleNote: 'Zakat and Khums are shown side by side for visibility, but their rules, calculations, and payments remain separate.',
  partialData: 'Some records could not be loaded. Available figures are still shown and no values were estimated.',
  loading: 'Preparing your charity overview',
  zakat: 'Zakat',
  khums: 'Khums',
  independent: 'Independent calculation',
  zakatRule: 'Based only on your latest saved Zakat calculation and Zakat-designated payments.',
  khumsRule: 'Based only on the selected Khums year and its recorded payments.',
  amountDue: 'Amount due',
  paidToward: 'Paid toward this obligation',
  remaining: 'Remaining',
  noZakatCalculation: 'No Zakat calculation saved',
  noKhumsYear: 'No Khums year saved',
  latestCalculation: 'Latest calculation',
  currentYear: 'Current year',
  calculationSource: 'Source',
  formula: 'Formula',
  zakatFormula: 'Net Zakat base × applicable Zakat rate, after the selected Nisab test.',
  khumsFormula: 'Eligible annual surplus × 20%, with distribution handled inside the Khums workflow.',
  sourceSavedZakat: 'Latest saved Zakat calculation',
  sourceSavedKhums: 'Latest saved Khums year',
  lastUpdated: 'Last updated',
  unavailable: 'Not available',
  openZakat: 'Open Zakat',
  openKhums: 'Open Khums',
  paidThisYear: 'Paid this year',
  paidThisYearHelp: 'KWD-denominated charitable outflows tracked this calendar year: donations, project gifts, and Khums payments. Other currencies stay separate.',
  splitRemaining: 'Remaining by obligation',
  splitRemainingHelp: 'Displayed separately to avoid combining Zakat and Khums rules.',
  nextReminder: 'Next due or reminder',
  noReminder: 'No reminder scheduled',
  overdue: 'Overdue',
  upcoming: 'Upcoming',
  recommendedAction: 'Recommended next action',
  recommendationOverdueTitle: 'Review an overdue reminder',
  recommendationOverdueBody: 'A scheduled charity or Khums reminder has passed its due date.',
  recommendationZakatTitle: 'Complete your Zakat payment',
  recommendationZakatBody: 'Your latest Zakat calculation has an unpaid balance. Review the calculation before paying.',
  recommendationKhumsTitle: 'Review the remaining Khums balance',
  recommendationKhumsBody: 'The current Khums year has a recorded balance remaining.',
  recommendationDonationTitle: 'Record your first donation',
  recommendationDonationBody: 'Start a clear giving history by recording a donation.',
  recommendationReportsTitle: 'Organize your receipts',
  recommendationReportsBody: 'Your obligations are up to date. Keep evidence ready by reviewing reports and receipts.',
  takeAction: 'Take action',
  pathwaysTitle: 'Choose a clear pathway',
  pathwaysSubtitle: 'Each area opens as its own workflow. Nothing is calculated together here.',
  navZakat: 'Zakat',
  navZakatDesc: 'Assets, Nisab, calculation, payment, and evidence.',
  navKhums: 'Khums',
  navKhumsDesc: 'Annual data, calculation, distribution, and history.',
  navDonations: 'Donations',
  navDonationsDesc: 'Record and review independent charitable gifts.',
  navProjects: 'Charity Projects',
  navProjectsDesc: 'Track targets, progress, status, and transparency.',
  navBeneficiaries: 'Beneficiaries',
  navBeneficiariesDesc: 'Review verification, priority, and support history.',
  navReports: 'Reports & Receipts',
  navReportsDesc: 'Find evidence, payment records, and documents.',
  navImpact: 'Impact',
  navImpactDesc: 'Understand where your charitable support is reaching.',
  navReminders: 'Reminders',
  navRemindersDesc: 'See upcoming dates without mixing obligations.',
  recentDonations: 'Recent donations',
  recentDonationsSubtitle: 'Your latest recorded gifts across charity and supported projects.',
  viewAll: 'View all',
  noDonationsTitle: 'No payments yet',
  noDonationsBody: 'Recorded donations will appear here with their date and purpose.',
  recordDonation: 'Record a donation',
  generalDonation: 'General charity donation',
  projectDonation: 'Project donation',
  zakatPayment: 'Zakat-designated payment',
  supportedProjects: 'Supported charity projects',
  supportedProjectsSubtitle: 'Active projects that you are currently tracking.',
  noProjectsTitle: 'No charity projects',
  noProjectsBody: 'Create or follow a project to see its target and progress here.',
  exploreProjects: 'Open projects',
  raised: 'Raised',
  target: 'Target',
  remainingToTarget: 'Remaining',
  projectProgress: 'Project progress',
  beneficiarySummary: 'Beneficiaries',
  activeBeneficiaries: 'Active beneficiaries',
  totalBeneficiaries: 'Total records',
  viewBeneficiaries: 'Review beneficiaries',
  receiptsReports: 'Recent receipts and reports',
  receiptsReportsSubtitle: 'The newest evidence stored in your charity workspace.',
  noReportsTitle: 'No reports or receipts',
  noReportsBody: 'Uploaded receipts and generated reports will appear here.',
  openDocument: 'Open document',
  viewReports: 'View reports',
  impactTitle: 'Charitable impact',
  impactSubtitle: 'A concise view of tracked giving and the people and projects it supports.',
  givingThisYear: 'KWD giving this year',
  projectsSupported: 'Projects supported',
  peopleSupported: 'People supported',
  viewImpact: 'Explore impact',
  receipt: 'Receipt',
  report: 'Report',
  certificate: 'Certificate',
  document: 'Document',
  active: 'Active',
  tracked: 'Tracked',
  donationsAria: 'Donations workflow',
  backToCenter: 'Back to Charity Center',
  donationEyebrow: 'Independent charitable giving',
  donationsTitle: 'Donations',
  donationsSubtitle: 'Record voluntary charity separately from Zakat and Khums, then keep a readable payment history.',
  thisMonth: 'This month',
  thisYear: 'This year',
  allTime: 'All time',
  paymentCount: 'Payment records',
  newDonation: 'Record a donation',
  newDonationSubtitle: 'This entry is saved as a general charity expense. It does not alter Zakat or Khums calculations.',
  month: 'Month',
  amount: 'Amount',
  purpose: 'Purpose or recipient',
  amountPlaceholder: '0.000',
  purposePlaceholder: 'For example: food support or local relief',
  saveDonation: 'Save donation',
  saving: 'Saving…',
  invalidAmount: 'Enter a valid amount greater than zero.',
  invalidName: 'Add a purpose or recipient.',
  loadError: 'Donations could not be loaded',
  saveError: 'Donation could not be saved',
  saveSuccess: 'Donation saved successfully.',
  deleteError: 'Donation could not be deleted',
  deleteSuccess: 'Donation deleted.',
  defaultDonationName: 'Charity donation',
  historyTitle: 'Donation history',
  historySubtitle: 'Filter by month to review what was paid and why.',
  selectedMonthTotal: 'Selected month total',
  noMonthPaymentsTitle: 'No payments this month',
  noMonthPaymentsBody: 'Choose another month or record a new donation.',
  deleteDonation: 'Delete donation',
  deleting: 'Deleting…',
  recordedOn: 'Recorded',
  storageNoteTitle: 'How this is recorded',
  storageNote: 'Donations continue to use the existing charity expense record so your finance totals stay consistent.',
};

type CopyKey = keyof typeof en;
type CharityCopy = Record<CopyKey, string>;

const ar: CharityCopy = {
  centerAria: 'مركز العطاء',
  eyebrow: 'عطاء إسلامي واضح ومنظّم',
  centerTitle: 'مركز الزكاة والخُمس والعمل الخيري',
  centerSubtitle: 'نظرة هادئة على الزكاة والخُمس والتبرعات والمشاريع والمستفيدين والإيصالات والتذكيرات.',
  centerPrinciple: 'مركز واحد، والتزامات مستقلة.',
  centerPrincipleNote: 'تُعرض الزكاة والخُمس جنباً إلى جنب للوضوح، مع بقاء الأحكام والحسابات والمدفوعات منفصلة.',
  partialData: 'تعذّر تحميل بعض السجلات. تُعرض البيانات المتاحة فقط من دون تقدير أي قيمة.',
  loading: 'جارٍ تجهيز ملخص العطاء',
  zakat: 'الزكاة',
  khums: 'الخُمس',
  independent: 'حساب مستقل',
  zakatRule: 'يعتمد فقط على آخر حساب زكاة محفوظ والمدفوعات المصنّفة للزكاة.',
  khumsRule: 'يعتمد فقط على سنة الخُمس المحددة والمدفوعات المسجلة لها.',
  amountDue: 'المبلغ المستحق',
  paidToward: 'المدفوع لهذا الالتزام',
  remaining: 'المتبقي',
  noZakatCalculation: 'لا يوجد حساب زكاة محفوظ',
  noKhumsYear: 'لا توجد سنة خُمس محفوظة',
  latestCalculation: 'آخر حساب',
  currentYear: 'السنة الحالية',
  calculationSource: 'المصدر',
  formula: 'المعادلة',
  zakatFormula: 'صافي الوعاء الزكوي × نسبة الزكاة المطبقة، بعد التحقق من النصاب المختار.',
  khumsFormula: 'الفائض السنوي المشمول × 20٪، مع إدارة التوزيع داخل مسار الخُمس.',
  sourceSavedZakat: 'آخر حساب زكاة محفوظ',
  sourceSavedKhums: 'آخر سنة خُمس محفوظة',
  lastUpdated: 'آخر تحديث',
  unavailable: 'غير متاح',
  openZakat: 'فتح الزكاة',
  openKhums: 'فتح الخُمس',
  paidThisYear: 'المدفوع هذا العام',
  paidThisYearHelp: 'مبالغ العطاء المسجلة بالدينار الكويتي خلال السنة الميلادية: التبرعات ودعم المشاريع ومدفوعات الخُمس. تبقى العملات الأخرى منفصلة.',
  splitRemaining: 'المتبقي حسب الالتزام',
  splitRemainingHelp: 'يُعرض كل التزام منفصلاً حتى لا تختلط أحكام الزكاة والخُمس.',
  nextReminder: 'الموعد أو التذكير القادم',
  noReminder: 'لا يوجد تذكير مجدول',
  overdue: 'متأخر',
  upcoming: 'قادم',
  recommendedAction: 'الخطوة التالية المقترحة',
  recommendationOverdueTitle: 'راجع تذكيراً متأخراً',
  recommendationOverdueBody: 'تجاوز أحد تذكيرات العمل الخيري أو الخُمس موعده المحدد.',
  recommendationZakatTitle: 'أكمل دفع الزكاة',
  recommendationZakatBody: 'يتبقى رصيد في آخر حساب للزكاة. راجع الحساب قبل الدفع.',
  recommendationKhumsTitle: 'راجع رصيد الخُمس المتبقي',
  recommendationKhumsBody: 'يوجد مبلغ متبقٍ مسجل في سنة الخُمس الحالية.',
  recommendationDonationTitle: 'سجّل أول تبرع',
  recommendationDonationBody: 'ابدأ سجلاً واضحاً للعطاء بتسجيل تبرع.',
  recommendationReportsTitle: 'نظّم الإيصالات',
  recommendationReportsBody: 'التزاماتك المسجلة محدثة. احتفظ بالأدلة جاهزة بمراجعة التقارير والإيصالات.',
  takeAction: 'اتخذ الإجراء',
  pathwaysTitle: 'اختر المسار المناسب',
  pathwaysSubtitle: 'يُفتح كل قسم كمسار مستقل، ولا تُجمع الحسابات هنا.',
  navZakat: 'الزكاة',
  navZakatDesc: 'الأصول والنصاب والحساب والدفع والأدلة.',
  navKhums: 'الخُمس',
  navKhumsDesc: 'البيانات السنوية والحساب والتوزيع والسجل.',
  navDonations: 'التبرعات',
  navDonationsDesc: 'تسجيل الهبات الخيرية المستقلة ومراجعتها.',
  navProjects: 'المشاريع الخيرية',
  navProjectsDesc: 'متابعة الأهداف والتقدم والحالة والشفافية.',
  navBeneficiaries: 'المستفيدون',
  navBeneficiariesDesc: 'مراجعة التحقق والأولوية وسجل الدعم.',
  navReports: 'التقارير والإيصالات',
  navReportsDesc: 'العثور على الأدلة وسجلات الدفع والمستندات.',
  navImpact: 'الأثر',
  navImpactDesc: 'فهم الجهات التي يصل إليها دعمك الخيري.',
  navReminders: 'التذكيرات',
  navRemindersDesc: 'متابعة المواعيد القادمة دون خلط الالتزامات.',
  recentDonations: 'أحدث التبرعات',
  recentDonationsSubtitle: 'آخر مبالغ العطاء المسجلة للجمعيات والمشاريع المدعومة.',
  viewAll: 'عرض الكل',
  noDonationsTitle: 'لا توجد مدفوعات بعد',
  noDonationsBody: 'ستظهر التبرعات المسجلة هنا مع التاريخ والغرض.',
  recordDonation: 'تسجيل تبرع',
  generalDonation: 'تبرع خيري عام',
  projectDonation: 'تبرع لمشروع',
  zakatPayment: 'دفعة مخصصة للزكاة',
  supportedProjects: 'المشاريع الخيرية المدعومة',
  supportedProjectsSubtitle: 'المشاريع النشطة التي تتابعها حالياً.',
  noProjectsTitle: 'لا توجد مشاريع خيرية',
  noProjectsBody: 'أنشئ مشروعاً أو تابعه لتظهر أهدافه ونسبة تقدمه هنا.',
  exploreProjects: 'فتح المشاريع',
  raised: 'المحصّل',
  target: 'الهدف',
  remainingToTarget: 'المتبقي',
  projectProgress: 'تقدم المشروع',
  beneficiarySummary: 'المستفيدون',
  activeBeneficiaries: 'المستفيدون النشطون',
  totalBeneficiaries: 'إجمالي السجلات',
  viewBeneficiaries: 'مراجعة المستفيدين',
  receiptsReports: 'أحدث الإيصالات والتقارير',
  receiptsReportsSubtitle: 'أحدث الأدلة المحفوظة في مساحة العمل الخيري.',
  noReportsTitle: 'لا توجد تقارير أو إيصالات',
  noReportsBody: 'ستظهر الإيصالات المرفوعة والتقارير المنشأة هنا.',
  openDocument: 'فتح المستند',
  viewReports: 'عرض التقارير',
  impactTitle: 'الأثر الخيري',
  impactSubtitle: 'ملخص موجز للعطاء المسجل والأشخاص والمشاريع التي يدعمها.',
  givingThisYear: 'العطاء بالدينار هذا العام',
  projectsSupported: 'المشاريع المدعومة',
  peopleSupported: 'الأشخاص المدعومون',
  viewImpact: 'استكشاف الأثر',
  receipt: 'إيصال',
  report: 'تقرير',
  certificate: 'شهادة',
  document: 'مستند',
  active: 'نشط',
  tracked: 'مسجل',
  donationsAria: 'مسار التبرعات',
  backToCenter: 'العودة إلى مركز العطاء',
  donationEyebrow: 'عطاء خيري مستقل',
  donationsTitle: 'التبرعات',
  donationsSubtitle: 'سجّل الصدقة التطوعية بصورة مستقلة عن الزكاة والخُمس، واحتفظ بسجل مدفوعات واضح.',
  thisMonth: 'هذا الشهر',
  thisYear: 'هذا العام',
  allTime: 'كل الوقت',
  paymentCount: 'سجلات الدفع',
  newDonation: 'تسجيل تبرع',
  newDonationSubtitle: 'يُحفظ هذا القيد كمصروف خيري عام ولا يغيّر حساب الزكاة أو الخُمس.',
  month: 'الشهر',
  amount: 'المبلغ',
  purpose: 'الغرض أو المستفيد',
  amountPlaceholder: '0.000',
  purposePlaceholder: 'مثال: دعم غذائي أو إغاثة محلية',
  saveDonation: 'حفظ التبرع',
  saving: 'جارٍ الحفظ…',
  invalidAmount: 'أدخل مبلغاً صحيحاً أكبر من صفر.',
  invalidName: 'أضف الغرض أو المستفيد.',
  loadError: 'تعذّر تحميل التبرعات',
  saveError: 'تعذّر حفظ التبرع',
  saveSuccess: 'تم حفظ التبرع بنجاح.',
  deleteError: 'تعذّر حذف التبرع',
  deleteSuccess: 'تم حذف التبرع.',
  defaultDonationName: 'تبرع خيري',
  historyTitle: 'سجل التبرعات',
  historySubtitle: 'صفِّ السجل حسب الشهر لمراجعة ما دُفع والغرض منه.',
  selectedMonthTotal: 'إجمالي الشهر المحدد',
  noMonthPaymentsTitle: 'لا توجد مدفوعات هذا الشهر',
  noMonthPaymentsBody: 'اختر شهراً آخر أو سجّل تبرعاً جديداً.',
  deleteDonation: 'حذف التبرع',
  deleting: 'جارٍ الحذف…',
  recordedOn: 'سُجل في',
  storageNoteTitle: 'طريقة تسجيل التبرع',
  storageNote: 'تستمر التبرعات باستخدام سجل المصروف الخيري الحالي حتى تبقى إجمالياتك المالية متسقة.',
};

const fr: CharityCopy = {
  centerAria: 'Centre de charité',
  eyebrow: 'La générosité islamique, clairement organisée',
  centerTitle: 'Centre de charité',
  centerSubtitle: 'Une vue sereine de votre Zakat, Khums, dons, projets, bénéficiaires, reçus et rappels.',
  centerPrinciple: 'Un seul centre. Des obligations indépendantes.',
  centerPrincipleNote: 'La Zakat et le Khums sont présentés côte à côte pour la visibilité, mais leurs règles, calculs et paiements restent séparés.',
  partialData: 'Certains dossiers n’ont pas pu être chargés. Les chiffres disponibles restent affichés sans aucune estimation.',
  loading: 'Préparation de votre aperçu caritatif',
  zakat: 'Zakat',
  khums: 'Khums',
  independent: 'Calcul indépendant',
  zakatRule: 'Basé uniquement sur le dernier calcul de Zakat enregistré et les paiements désignés comme Zakat.',
  khumsRule: 'Basé uniquement sur l’année de Khums sélectionnée et ses paiements enregistrés.',
  amountDue: 'Montant dû',
  paidToward: 'Payé pour cette obligation',
  remaining: 'Restant',
  noZakatCalculation: 'Aucun calcul de Zakat enregistré',
  noKhumsYear: 'Aucune année de Khums enregistrée',
  latestCalculation: 'Dernier calcul',
  currentYear: 'Année en cours',
  calculationSource: 'Source',
  formula: 'Formule',
  zakatFormula: 'Assiette nette de Zakat × taux applicable, après le test du Nisab sélectionné.',
  khumsFormula: 'Excédent annuel éligible × 20 %, la répartition étant gérée dans le parcours Khums.',
  sourceSavedZakat: 'Dernier calcul de Zakat enregistré',
  sourceSavedKhums: 'Dernière année de Khums enregistrée',
  lastUpdated: 'Dernière mise à jour',
  unavailable: 'Non disponible',
  openZakat: 'Ouvrir la Zakat',
  openKhums: 'Ouvrir le Khums',
  paidThisYear: 'Payé cette année',
  paidThisYearHelp: 'Les décaissements caritatifs libellés en KWD cette année : dons, projets et paiements de Khums. Les autres devises restent séparées.',
  splitRemaining: 'Restant par obligation',
  splitRemainingHelp: 'Affiché séparément pour ne pas mélanger les règles de la Zakat et du Khums.',
  nextReminder: 'Prochaine échéance ou rappel',
  noReminder: 'Aucun rappel planifié',
  overdue: 'En retard',
  upcoming: 'À venir',
  recommendedAction: 'Prochaine action recommandée',
  recommendationOverdueTitle: 'Examiner un rappel en retard',
  recommendationOverdueBody: 'Un rappel de charité ou de Khums a dépassé sa date prévue.',
  recommendationZakatTitle: 'Finaliser votre paiement de Zakat',
  recommendationZakatBody: 'Votre dernier calcul de Zakat présente un solde impayé. Vérifiez le calcul avant de payer.',
  recommendationKhumsTitle: 'Examiner le solde de Khums',
  recommendationKhumsBody: 'L’année de Khums en cours présente un solde restant enregistré.',
  recommendationDonationTitle: 'Enregistrer votre premier don',
  recommendationDonationBody: 'Commencez un historique clair en enregistrant un don.',
  recommendationReportsTitle: 'Organiser vos reçus',
  recommendationReportsBody: 'Vos obligations enregistrées sont à jour. Gardez les justificatifs prêts en consultant rapports et reçus.',
  takeAction: 'Agir maintenant',
  pathwaysTitle: 'Choisir un parcours clair',
  pathwaysSubtitle: 'Chaque domaine s’ouvre dans son propre parcours. Aucun calcul n’est fusionné ici.',
  navZakat: 'Zakat',
  navZakatDesc: 'Actifs, Nisab, calcul, paiement et justificatifs.',
  navKhums: 'Khums',
  navKhumsDesc: 'Données annuelles, calcul, répartition et historique.',
  navDonations: 'Dons',
  navDonationsDesc: 'Enregistrer et consulter les dons caritatifs indépendants.',
  navProjects: 'Projets caritatifs',
  navProjectsDesc: 'Suivre objectifs, progression, statut et transparence.',
  navBeneficiaries: 'Bénéficiaires',
  navBeneficiariesDesc: 'Examiner vérification, priorité et historique du soutien.',
  navReports: 'Rapports et reçus',
  navReportsDesc: 'Retrouver justificatifs, paiements et documents.',
  navImpact: 'Impact',
  navImpactDesc: 'Comprendre où parvient votre soutien caritatif.',
  navReminders: 'Rappels',
  navRemindersDesc: 'Voir les échéances sans mélanger les obligations.',
  recentDonations: 'Dons récents',
  recentDonationsSubtitle: 'Vos derniers dons enregistrés et soutiens de projets.',
  viewAll: 'Tout voir',
  noDonationsTitle: 'Aucun paiement pour le moment',
  noDonationsBody: 'Les dons enregistrés apparaîtront ici avec leur date et leur objet.',
  recordDonation: 'Enregistrer un don',
  generalDonation: 'Don caritatif général',
  projectDonation: 'Don à un projet',
  zakatPayment: 'Paiement désigné comme Zakat',
  supportedProjects: 'Projets caritatifs soutenus',
  supportedProjectsSubtitle: 'Les projets actifs que vous suivez actuellement.',
  noProjectsTitle: 'Aucun projet caritatif',
  noProjectsBody: 'Créez ou suivez un projet pour voir son objectif et sa progression ici.',
  exploreProjects: 'Ouvrir les projets',
  raised: 'Collecté',
  target: 'Objectif',
  remainingToTarget: 'Restant',
  projectProgress: 'Progression du projet',
  beneficiarySummary: 'Bénéficiaires',
  activeBeneficiaries: 'Bénéficiaires actifs',
  totalBeneficiaries: 'Total des dossiers',
  viewBeneficiaries: 'Examiner les bénéficiaires',
  receiptsReports: 'Reçus et rapports récents',
  receiptsReportsSubtitle: 'Les justificatifs les plus récents de votre espace caritatif.',
  noReportsTitle: 'Aucun rapport ni reçu',
  noReportsBody: 'Les reçus importés et rapports générés apparaîtront ici.',
  openDocument: 'Ouvrir le document',
  viewReports: 'Voir les rapports',
  impactTitle: 'Impact caritatif',
  impactSubtitle: 'Une vue concise des dons suivis et des personnes et projets soutenus.',
  givingThisYear: 'Dons en KWD cette année',
  projectsSupported: 'Projets soutenus',
  peopleSupported: 'Personnes soutenues',
  viewImpact: 'Explorer l’impact',
  receipt: 'Reçu',
  report: 'Rapport',
  certificate: 'Certificat',
  document: 'Document',
  active: 'Actif',
  tracked: 'Suivi',
  donationsAria: 'Parcours des dons',
  backToCenter: 'Retour au Centre de charité',
  donationEyebrow: 'Générosité caritative indépendante',
  donationsTitle: 'Dons',
  donationsSubtitle: 'Enregistrez la charité volontaire séparément de la Zakat et du Khums, avec un historique lisible.',
  thisMonth: 'Ce mois-ci',
  thisYear: 'Cette année',
  allTime: 'Depuis le début',
  paymentCount: 'Paiements enregistrés',
  newDonation: 'Enregistrer un don',
  newDonationSubtitle: 'Cette entrée est enregistrée comme dépense caritative générale et ne modifie aucun calcul de Zakat ou de Khums.',
  month: 'Mois',
  amount: 'Montant',
  purpose: 'Objet ou bénéficiaire',
  amountPlaceholder: '0.000',
  purposePlaceholder: 'Par exemple : aide alimentaire ou secours local',
  saveDonation: 'Enregistrer le don',
  saving: 'Enregistrement…',
  invalidAmount: 'Saisissez un montant valide supérieur à zéro.',
  invalidName: 'Ajoutez un objet ou un bénéficiaire.',
  loadError: 'Les dons n’ont pas pu être chargés',
  saveError: 'Le don n’a pas pu être enregistré',
  saveSuccess: 'Don enregistré avec succès.',
  deleteError: 'Le don n’a pas pu être supprimé',
  deleteSuccess: 'Don supprimé.',
  defaultDonationName: 'Don caritatif',
  historyTitle: 'Historique des dons',
  historySubtitle: 'Filtrez par mois pour vérifier les paiements et leur objet.',
  selectedMonthTotal: 'Total du mois sélectionné',
  noMonthPaymentsTitle: 'Aucun paiement ce mois-ci',
  noMonthPaymentsBody: 'Choisissez un autre mois ou enregistrez un nouveau don.',
  deleteDonation: 'Supprimer le don',
  deleting: 'Suppression…',
  recordedOn: 'Enregistré',
  storageNoteTitle: 'Mode d’enregistrement',
  storageNote: 'Les dons continuent d’utiliser le registre de dépense caritative existant afin de conserver des totaux financiers cohérents.',
};

export const CHARITY_TEXT: Record<Lang, CharityCopy> = { ar, en, fr };
