// Auto-extracted TEXT translations for projects/[id]/page
export const TEXT = {
  ar: {
    workspace: 'مساحة المشروع',
    projectName: 'اسم المشروع',
    projectType: 'نوع المشروع',
    status: 'الحالة',
    capital: 'رأس المال',
    financialTarget: 'الهدف المالي',
    startDate: 'تاريخ البداية',
    endDate: 'تاريخ النهاية',
    editProject: 'تعديل المشروع',
    addExpense: 'إضافة مصروف للمشروع',
    projectExpenses: 'مصروفات المشروع',
    expenseName: 'اسم المصروف',
    amount: 'المبلغ',
    currency: 'العملة',
    date: 'التاريخ',
    category: 'التصنيف',
    paymentMethod: 'طريقة الدفع',
    notes: 'ملاحظات',
    receipt: 'إيصال أو فاتورة اختيارية',
    aiReceiptReading: 'قراءة الإيصال بالذكاء الاصطناعي',
    aiReceiptHelper: 'ارفع صورة أو PDF للفاتورة ليتم تحليلها تلقائياً.',
    readReceipt: 'قراءة الإيصال',
    analyzeExpense: 'تحليل المصروف',
    readingReceipt: 'جاري قراءة الإيصال...',
    analyzingExpense: 'جاري تحليل المصروف...',
    receiptReadSuccess: 'تم استخراج البيانات، يرجى مراجعتها قبل الحفظ.',
    receiptReadError: 'تعذر تحليل الإيصال حالياً، يمكنك إدخال البيانات يدوياً.',
    extractedReceiptTitle: 'نتيجة قراءة الإيصال',
    applyExtractedData: 'تطبيق البيانات',
    clearAiResult: 'مسح النتيجة',
    confidence: 'الثقة',
    vendorName: 'اسم المورد',
    notClear: 'غير واضح',
    aiExpenseAnalysis: 'تحليل المصروف',
    aiExpenseAnalysisError: 'تعذر تحليل المصروف حالياً، يمكنك الحفظ يدوياً.',
    budgetImpact: 'أثره على الميزانية',
    remainingBudgetAfterExpense: 'المتبقي بعد هذا المصروف',
    budgetUsedPercent: 'نسبة استخدام الميزانية',
    noProjectBudgetForAnalysis: 'لا توجد ميزانية محددة لهذا المشروع، أضف ميزانية للحصول على تحليل أدق.',
    suggestedAction: 'الإجراء المقترح',
    expenseAction_approve: 'اعتماد',
    expenseAction_review: 'مراجعة',
    expenseAction_reduce: 'تخفيض',
    expenseAction_move_category: 'نقل لتصنيف آخر',
    expenseAction_attach_document: 'إرفاق مستند داعم',
    amountLevel: 'مستوى المبلغ',
    amountLevel_low: 'منخفض',
    amountLevel_normal: 'طبيعي',
    amountLevel_high: 'مرتفع',
    amountLevel_unknown: 'غير محدد',
    paidFromPersonalBudget: 'تم الدفع من ميزانيتي الشخصية',
    doNotIncludeInPersonalBudget: 'لا يؤثر هذا المصروف على مصروفاتك الشخصية إلا إذا اخترت ذلك.',
    includeInPersonalBudget: 'سيظهر هذا المصروف أيضاً في صفحة المصروفات الشخصية بعلامة مصروف مشروع.',
    projectExpense: 'مصروف مشروع',
    totalProjectExpenses: 'إجمالي مصروفات المشروع',
    projectExpensesThisMonth: 'مصروفات هذا الشهر',
    personalBudgetProjectExpenses: 'مدفوع من الميزانية الشخصية',
    noProjectExpensesYet: 'لا توجد مصروفات مسجلة لهذا المشروع.',
    actualVsPlanned: 'الفعلي مقابل المخطط',
    saveProjectExpense: 'حفظ مصروف المشروع',
    cancel: 'إلغاء',
    general: 'عام',
    operations: 'تشغيل',
    marketingExpense: 'تسويق',
    payroll: 'رواتب',
    rent: 'إيجار',
    equipment: 'معدات',
    licenses: 'تراخيص',
    cash: 'نقداً',
    card: 'بطاقة',
    transfer: 'تحويل',
    projectExpenseSaved: 'تم حفظ مصروف المشروع.',
    projectExpenseSaveError: 'تعذر حفظ مصروف المشروع حالياً.',
    requiredExpenseName: 'أدخل اسم المصروف.',
    requiredExpenseAmount: 'أدخل مبلغاً صحيحاً.',
    missingDataChecklist: 'بيانات تحتاج متابعة',
    addProjectExpensesHint: 'أضف مصروفات المشروع لعرض الفعلي مقابل المخطط.',
    addFinancialModelHint: 'أضف النموذج المالي لحساب جاهزية المشروع.',
    addTasksHint: 'أضف المهام لعرض تقدم المشروع.',
    addIncome: 'إضافة دخل للمشروع',
    projectIncome: 'دخل المشروع',
    incomeName: 'اسم الدخل',
    incomeSource: 'المصدر / التصنيف',
    source: 'المصدر',
    transferredToPersonalIncome: 'تم تحويله إلى دخلي الشخصي',
    doNotIncludeInPersonalIncome: 'لا يؤثر هذا الدخل على دخلك الشخصي إلا إذا اخترت ذلك.',
    includeInPersonalIncome: 'سيظهر هذا الدخل أيضاً في صفحة الدخل الشخصي بعلامة دخل مشروع.',
    totalProjectIncome: 'إجمالي دخل المشروع',
    projectIncomeThisMonth: 'دخل هذا الشهر',
    personalIncomeProjectIncome: 'الدخل المحوّل للدخل الشخصي',
    noProjectIncomeYet: 'لا توجد إيرادات مسجلة لهذا المشروع.',
    actualVsExpected: 'الفعلي مقابل المتوقع',
    saveProjectIncome: 'حفظ دخل المشروع',
    projectIncomeSaved: 'تم حفظ دخل المشروع.',
    projectIncomeSaveError: 'تعذر حفظ دخل المشروع حالياً.',
    requiredIncomeName: 'أدخل اسم الدخل.',
    requiredIncomeAmount: 'أدخل مبلغاً صحيحاً.',
    salesIncome: 'مبيعات',
    servicesIncome: 'خدمات',
    rentalIncome: 'إيجار',
    investmentIncome: 'استثمار',
    otherIncomeSource: 'مصدر آخر',
    analyzeProject: 'تحليل المشروع',
    chooseJurisdiction: 'اختيار دولة التأسيس',
    back: 'العودة إلى مشاريعي',
    signIn: 'سجّل الدخول لعرض تفاصيل مشاريعك.',
    notFound: 'لم يتم العثور على المشروع.',
    overview: 'نظرة عامة',
    feasibility: 'دراسة الجدوى',
    financial: 'النموذج المالي',
    tasks: 'المهام',
    documents: 'المستندات',
    documentsCenter: 'مركز المستندات',
    kpis: 'المؤشرات',
    ai: 'مستشار AI',
    pitchDeck: 'العرض الاستثماري',
    comingSoon: 'سيتم تفعيل هذا القسم في المرحلة القادمة.',
    projectSummary: 'ملخص المشروع',
    financialSnapshot: 'اللقطة المالية',
    timelineSnapshot: 'ملخص الجدول الزمني',
    timelineInsufficient: 'لا توجد بيانات كافية لعرض ملخص الجدول الزمني.',
    riskSnapshot: 'ملخص المخاطر',
    quickActions: 'إجراءات سريعة',
    description: 'الوصف',
    priority: 'الأولوية',
    currentPhase: 'المرحلة الحالية',
    totalIncome: 'إجمالي دخل المشروع',
    totalExpenses: 'إجمالي مصروفات المشروع',
    netResult: 'الصافي',
    remainingBudget: 'الميزانية المتبقية',
    targetProgress: 'التقدم نحو الهدف',
    daysRemaining: 'الأيام المتبقية',
    duration: 'مدة المشروع',
    noDate: 'غير محدد',
    noData: 'بيانات غير كافية',
    low: 'منخفض',
    medium: 'متوسط',
    high: 'مرتفع',
    riskLowText: 'المؤشرات الحالية تبدو مستقرة لهذا المشروع.',
    riskMediumText: 'يحتاج المشروع إلى متابعة مالية وتشغيلية منتظمة.',
    riskHighText: 'المشروع يحتاج مراجعة عاجلة للمخاطر والميزانية.',
    addTask: 'إضافة مهمة',
    generateFeasibility: 'إنشاء دراسة جدوى',
    createFinancialModel: 'إنشاء نموذج مالي',
    idea: 'فكرة',
    study: 'دراسة',
    setup: 'تأسيس',
    launch: 'إطلاق',
    growth: 'نمو',
    paused: 'متوقف',
    completed: 'مكتمل',
    ecommerce: 'متجر إلكتروني',
    restaurant: 'مطعم / كافيه',
    services: 'خدمات',
    saas: 'SaaS / تطبيق',
    trading: 'تجارة عامة',
    realEstate: 'عقار',
    otherProject: 'مشروع آخر',
    feasibilityHint: 'دراسة جدوى تشمل السوق، التكاليف، المنافسين، التراخيص، والمخاطر.',
    financialHint: 'نموذج مالي يتضمن الإيرادات، المصاريف، التدفق النقدي، ونقطة التعادل.',
    tasksHint: 'لوحة مهام وخط زمني لتنفيذ المشروع.',
    documentsHint: 'خزنة مستندات للعقود والتراخيص والفواتير.',
    kpisHint: 'مؤشرات أداء المشروع والربحية والتقدم.',
    aiHint: 'مستشار ذكي يقرأ بيانات مشروعك ويقترح الخطوات القادمة.',
    pitchDeckHint: 'عرض استثماري منظم مبني على بيانات المشروع الحقيقية.',
    feasibilitySummary: 'ملخص دراسة الجدوى',
    marketFeasibility: 'الجدوى السوقية',
    technicalFeasibility: 'الجدوى الفنية',
    financialFeasibility: 'الجدوى المالية',
    legalFeasibility: 'الجدوى القانونية والتنظيمية',
    marketSize: 'حجم السوق المتوقع',
    targetCustomers: 'شريحة العملاء المستهدفة',
    problemSolved: 'المشكلة التي يحلها المشروع',
    competitors: 'المنافسون الرئيسيون',
    competitiveAdvantage: 'ميزة المشروع التنافسية',
    pricingStrategy: 'استراتيجية التسعير',
    acquisitionChannels: 'قنوات الوصول للعملاء',
    requiredResources: 'الموارد المطلوبة',
    requiredTechnology: 'التكنولوجيا أو الأدوات المطلوبة',
    operationalSetup: 'الموقع أو البنية التشغيلية',
    keySuppliers: 'الموردون الرئيسيون',
    teamSize: 'عدد الموظفين المطلوب',
    implementationChallenges: 'صعوبات التنفيذ المتوقعة',
    requiredCapital: 'رأس المال المطلوب',
    capex: 'التكاليف التأسيسية CAPEX',
    monthlyOpex: 'التكاليف التشغيلية الشهرية OPEX',
    expectedMonthlyRevenue: 'الإيرادات الشهرية المتوقعة',
    expectedProfitMargin: 'هامش الربح المتوقع %',
    breakEvenPoint: 'نقطة التعادل التقريبية',
    paybackPeriod: 'فترة الاسترداد المتوقعة',
    targetCountry: 'الدولة / السوق المستهدف',
    licenseType: 'نوع الترخيص المطلوب',
    governmentEntities: 'الجهات الحكومية ذات العلاقة',
    legalRequirements: 'متطلبات قانونية خاصة',
    insuranceObligations: 'التأمينات أو الالتزامات النظامية',
    legalNotes: 'ملاحظات قانونية',
    kuwait: 'الكويت',
    saudiArabia: 'السعودية',
    uae: 'الإمارات',
    qatar: 'قطر',
    bahrain: 'البحرين',
    oman: 'عُمان',
    globalOther: 'عالمي / أخرى',
    feasibilityScore: 'درجة الجدوى',
    feasible: 'قابل للتنفيذ',
    needsReview: 'يحتاج مراجعة',
    highRisk: 'مخاطرة مرتفعة',
    monthlyProfitEstimate: 'الربح الشهري المتوقع',
    breakEvenEstimate: 'نقطة التعادل المقدرة',
    roiEstimate: 'تقدير العائد السنوي ROI',
    missingSections: 'الأقسام غير المكتملة',
    saveFeasibilityStudy: 'حفظ دراسة الجدوى',
    feasibilitySaved: 'تم حفظ دراسة الجدوى.',
    feasibilitySaveError: 'تعذر حفظ دراسة الجدوى حالياً.',
    aiFeasibilityAnalysis: 'تحليل AI لدراسة الجدوى',
    aiFeasibilitySoon: 'سيتم تفعيل تحليل الذكاء الاصطناعي المتقدم في مرحلة لاحقة.',
    exportFeasibilityPdf: 'تصدير دراسة الجدوى PDF',
    creatingFeasibilityPdf: 'جاري إنشاء PDF...',
    feasibilityPdfExported: 'تم تصدير PDF بنجاح',
    feasibilityPdfExportError: 'تعذر تصدير PDF، حاول مرة أخرى',
    saveFeasibilityBeforeExport: 'احفظ دراسة الجدوى أولاً قبل التصدير',
    comingSoonShort: 'قريباً',
    internalScoreDisclaimer: 'هذه درجة تخطيط داخلية وليست توصية مضمونة لنجاح المشروع.',
    months: 'شهر',
    projectProgress: 'تقدم المشروع',
    totalTasks: 'إجمالي المهام',
    completedTasks: 'المهام المكتملة',
    lateTasks: 'المهام المتأخرة',
    upcomingDeadlines: 'المواعيد القادمة',
    nextMilestone: 'المعلم القادم',
    estimatedTaskCosts: 'تكلفة المهام المتوقعة',
    documentsCount: 'عدد المستندات',
    projectHealthScore: 'درجة صحة المشروع',
    strong: 'قوي',
    good: 'جيد',
    needs_review: 'يحتاج مراجعة',
    high_risk: 'عالي المخاطر',
    insufficient: 'بيانات غير كافية',
    topRiskFlag: 'أبرز تنبيه مخاطر',
    openKpis: 'فتح المؤشرات',
    noRiskFlags: 'لا توجد تنبيهات مخاطر حالياً.',
    financial_model_missing: 'النموذج المالي غير مكتمل',
    feasibility_incomplete: 'دراسة الجدوى غير مكتملة',
    overdue_tasks: 'يوجد مهام متأخرة',
    no_documents: 'لا توجد مستندات',
    project_end_passed: 'تاريخ نهاية المشروع تجاوز اليوم',
    expenses_exceed_budget: 'المصاريف تجاوزت الميزانية',
    negative_cash: 'التدفق النقدي المتوقع سلبي',
    payback_too_long: 'فترة الاسترداد طويلة',
    behind_schedule: 'التقدم الفعلي أقل من المخطط',
    edit: 'تعديل',
    delete: 'حذف',
    showMore: 'عرض المزيد',
    showLess: 'عرض أقل',
    recentActivity: 'النشاط الأخير',
    nextSteps: 'الخطوات التالية',
    projectStatus: 'حالة المشروع',
    editProjectIncome: 'تعديل دخل المشروع',
    editProjectExpense: 'تعديل مصروف المشروع',
    deleteProjectIncome: 'حذف دخل المشروع',
    deleteProjectExpense: 'حذف مصروف المشروع',
    saveEdit: 'حفظ التعديل',
    deleteFromProjectOnly: 'حذف من المشروع فقط',
    deleteFromBothProjectAndPersonalRecords: 'حذف من المشروع والسجل الشخصي',
    deleteProjectIncomeBody: 'هل تريد حذف دخل المشروع؟ سيتم حذف هذا الدخل من المشروع فقط.',
    deleteProjectExpenseBody: 'هل تريد حذف مصروف المشروع؟ سيتم حذف هذا المصروف من المشروع فقط.',
    linkedIncomeDeletePrompt: 'هذا الدخل مرتبط أيضاً بالدخل الشخصي. اختر ما تريد حذفه.',
    linkedExpenseDeletePrompt: 'هذا المصروف مرتبط أيضاً بمصاريفك الشخصية. اختر ما تريد حذفه.',
    projectIncomeUpdated: 'تم تحديث دخل المشروع.',
    projectExpenseUpdated: 'تم تحديث مصروف المشروع.',
    projectIncomeDeleted: 'تم حذف دخل المشروع.',
    projectExpenseDeleted: 'تم حذف مصروف المشروع.',
    projectIncomeDeleteError: 'تعذر حذف دخل المشروع حالياً.',
    projectExpenseDeleteError: 'تعذر حذف مصروف المشروع حالياً.',
    updateLinkedPersonalIncomeConfirm: 'هذا الدخل مرتبط بالدخل الشخصي. هل تريد إزالة النسخة الشخصية أيضاً؟',
    updateLinkedPersonalExpenseConfirm: 'هذا المصروف مرتبط بالمصاريف الشخصية. هل تريد إزالة النسخة الشخصية أيضاً؟',
  },
  en: {
    workspace: 'Project Workspace',
    projectName: 'Project name',
    projectType: 'Project type',
    status: 'Status',
    capital: 'Capital',
    financialTarget: 'Financial target',
    startDate: 'Start date',
    endDate: 'End date',
    editProject: 'Edit Project',
    addExpense: 'Add Project Expense',
    projectExpenses: 'Project Expenses',
    expenseName: 'Expense name',
    amount: 'Amount',
    currency: 'Currency',
    date: 'Date',
    category: 'Category',
    paymentMethod: 'Payment method',
    notes: 'Notes',
    receipt: 'Optional receipt or invoice',
    aiReceiptReading: 'AI receipt reading',
    aiReceiptHelper: 'Upload a receipt or invoice image/PDF so it can be analyzed automatically.',
    readReceipt: 'Read receipt',
    analyzeExpense: 'Analyze expense',
    readingReceipt: 'Reading receipt...',
    analyzingExpense: 'Analyzing expense...',
    receiptReadSuccess: 'Data was extracted. Please review it before saving.',
    receiptReadError: 'Could not analyze the receipt right now. You can enter the data manually.',
    extractedReceiptTitle: 'Receipt reading result',
    applyExtractedData: 'Apply data',
    clearAiResult: 'Clear result',
    confidence: 'Confidence',
    vendorName: 'Vendor name',
    notClear: 'Unclear',
    aiExpenseAnalysis: 'Expense analysis',
    aiExpenseAnalysisError: 'Could not analyze the expense right now. You can still save it manually.',
    budgetImpact: 'Budget impact',
    remainingBudgetAfterExpense: 'Remaining after this expense',
    budgetUsedPercent: 'Budget used',
    noProjectBudgetForAnalysis: 'No budget is defined for this project. Add a budget for more accurate analysis.',
    suggestedAction: 'Suggested action',
    expenseAction_approve: 'Approve',
    expenseAction_review: 'Review',
    expenseAction_reduce: 'Reduce',
    expenseAction_move_category: 'Move category',
    expenseAction_attach_document: 'Attach supporting document',
    amountLevel: 'Amount level',
    amountLevel_low: 'Low',
    amountLevel_normal: 'Normal',
    amountLevel_high: 'High',
    amountLevel_unknown: 'Unknown',
    paidFromPersonalBudget: 'Paid from personal budget',
    doNotIncludeInPersonalBudget: 'This expense will not affect your personal spending unless you choose that.',
    includeInPersonalBudget: 'This expense will also appear on the personal expenses page marked as Project Expense.',
    projectExpense: 'Project Expense',
    totalProjectExpenses: 'Total Project Expenses',
    projectExpensesThisMonth: 'Project expenses this month',
    personalBudgetProjectExpenses: 'Paid from personal budget',
    noProjectExpensesYet: 'No project expenses have been recorded for this project.',
    actualVsPlanned: 'Actual vs Planned',
    saveProjectExpense: 'Save Project Expense',
    cancel: 'Cancel',
    general: 'General',
    operations: 'Operations',
    marketingExpense: 'Marketing',
    payroll: 'Payroll',
    rent: 'Rent',
    equipment: 'Equipment',
    licenses: 'Licenses',
    cash: 'Cash',
    card: 'Card',
    transfer: 'Transfer',
    projectExpenseSaved: 'Project expense saved.',
    projectExpenseSaveError: 'Could not save the project expense right now.',
    requiredExpenseName: 'Enter the expense name.',
    requiredExpenseAmount: 'Enter a valid amount.',
    missingDataChecklist: 'Missing data checklist',
    addProjectExpensesHint: 'Add project expenses to show actual vs planned.',
    addFinancialModelHint: 'Add the financial model to calculate project readiness.',
    addTasksHint: 'Add tasks to show project progress.',
    addIncome: 'Add Project Income',
    projectIncome: 'Project Income',
    incomeName: 'Income name',
    incomeSource: 'Source / category',
    source: 'Source',
    transferredToPersonalIncome: 'Transferred to personal income',
    doNotIncludeInPersonalIncome: 'This income does not affect your personal income unless you choose it.',
    includeInPersonalIncome: 'This income will also appear on the personal income page with a Project Income label.',
    totalProjectIncome: 'Total Project Income',
    projectIncomeThisMonth: 'Project income this month',
    personalIncomeProjectIncome: 'Transferred to personal income',
    noProjectIncomeYet: 'No income is recorded for this project yet.',
    actualVsExpected: 'Actual vs Expected',
    saveProjectIncome: 'Save Project Income',
    projectIncomeSaved: 'Project income saved.',
    projectIncomeSaveError: 'Could not save project income right now.',
    requiredIncomeName: 'Enter income name.',
    requiredIncomeAmount: 'Enter a valid amount.',
    salesIncome: 'Sales',
    servicesIncome: 'Services',
    rentalIncome: 'Rental',
    investmentIncome: 'Investment',
    otherIncomeSource: 'Other source',
    analyzeProject: 'Analyze Project',
    chooseJurisdiction: 'Choose Jurisdiction',
    back: 'Back to My Projects',
    signIn: 'Sign in to view your project details.',
    notFound: 'Project not found.',
    overview: 'Overview',
    feasibility: 'Feasibility',
    financial: 'Financial Model',
    tasks: 'Tasks',
    documents: 'Documents',
    documentsCenter: 'Documents Center',
    kpis: 'KPIs',
    ai: 'AI Advisor',
    pitchDeck: 'Pitch Deck',
    comingSoon: 'This section will be activated in the next phase.',
    projectSummary: 'Project Summary',
    financialSnapshot: 'Financial Snapshot',
    timelineSnapshot: 'Timeline Snapshot',
    timelineInsufficient: 'Not enough data to show the timeline summary.',
    riskSnapshot: 'Risk Snapshot',
    quickActions: 'Quick Actions',
    description: 'Description',
    priority: 'Priority',
    currentPhase: 'Current phase',
    totalIncome: 'Total project income',
    totalExpenses: 'Total project expenses',
    netResult: 'Net result',
    remainingBudget: 'Remaining budget',
    targetProgress: 'Progress toward target',
    daysRemaining: 'Days remaining',
    duration: 'Project duration',
    noDate: 'Not set',
    noData: 'Not enough data',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    riskLowText: 'Current indicators look stable for this project.',
    riskMediumText: 'This project needs regular financial and operational review.',
    riskHighText: 'This project needs urgent risk and budget review.',
    addTask: 'Add task',
    generateFeasibility: 'Generate feasibility',
    createFinancialModel: 'Create financial model',
    idea: 'Idea',
    study: 'Study',
    setup: 'Setup',
    launch: 'Launch',
    growth: 'Growth',
    paused: 'Paused',
    completed: 'Completed',
    ecommerce: 'E-commerce',
    restaurant: 'Restaurant / Cafe',
    services: 'Services',
    saas: 'SaaS / App',
    trading: 'General Trading',
    realEstate: 'Real Estate',
    otherProject: 'Other Project',
    feasibilityHint: 'A feasibility study covering market, costs, competitors, licenses, and risks.',
    financialHint: 'A financial model covering revenue, expenses, cash flow, and break-even point.',
    tasksHint: 'A task board and timeline for project execution.',
    documentsHint: 'A document vault for contracts, licenses, and invoices.',
    kpisHint: 'Project performance, profitability, and progress KPIs.',
    aiHint: 'An intelligent advisor that reads your project data and suggests next steps.',
    pitchDeckHint: 'Structured investor deck based on real project data.',
    feasibilitySummary: 'Feasibility Summary',
    marketFeasibility: 'Market Feasibility',
    technicalFeasibility: 'Technical Feasibility',
    financialFeasibility: 'Financial Feasibility',
    legalFeasibility: 'Legal / Regulatory Feasibility',
    marketSize: 'Expected market size',
    targetCustomers: 'Target customer segment',
    problemSolved: 'Problem solved by the project',
    competitors: 'Main competitors',
    competitiveAdvantage: 'Competitive advantage',
    pricingStrategy: 'Pricing strategy',
    acquisitionChannels: 'Customer acquisition channels',
    requiredResources: 'Required resources',
    requiredTechnology: 'Required technology/tools',
    operationalSetup: 'Location or operational setup',
    keySuppliers: 'Key suppliers',
    teamSize: 'Required team size',
    implementationChallenges: 'Expected implementation challenges',
    requiredCapital: 'Required capital',
    capex: 'Setup costs CAPEX',
    monthlyOpex: 'Monthly operating costs OPEX',
    expectedMonthlyRevenue: 'Expected monthly revenue',
    expectedProfitMargin: 'Expected profit margin %',
    breakEvenPoint: 'Estimated break-even point',
    paybackPeriod: 'Expected payback period',
    targetCountry: 'Country / target market',
    licenseType: 'Required license type',
    governmentEntities: 'Relevant government entities',
    legalRequirements: 'Special legal requirements',
    insuranceObligations: 'Insurance or regulatory obligations',
    legalNotes: 'Legal notes',
    kuwait: 'Kuwait',
    saudiArabia: 'Saudi Arabia',
    uae: 'UAE',
    qatar: 'Qatar',
    bahrain: 'Bahrain',
    oman: 'Oman',
    globalOther: 'Global / Other',
    feasibilityScore: 'Feasibility Score',
    feasible: 'Feasible',
    needsReview: 'Needs Review',
    highRisk: 'High Risk',
    monthlyProfitEstimate: 'Monthly profit estimate',
    breakEvenEstimate: 'Break-even estimate',
    roiEstimate: 'Annual ROI estimate',
    missingSections: 'Missing sections',
    saveFeasibilityStudy: 'Save Feasibility Study',
    feasibilitySaved: 'Feasibility study saved.',
    feasibilitySaveError: 'Could not save the feasibility study right now.',
    aiFeasibilityAnalysis: 'AI Feasibility Analysis',
    aiFeasibilitySoon: 'Advanced AI analysis will be enabled in a later phase.',
    exportFeasibilityPdf: 'Export Feasibility PDF',
    creatingFeasibilityPdf: 'Creating PDF...',
    feasibilityPdfExported: 'PDF exported successfully',
    feasibilityPdfExportError: 'Could not export PDF, please try again',
    saveFeasibilityBeforeExport: 'Save the feasibility study before exporting',
    comingSoonShort: 'Coming soon',
    internalScoreDisclaimer: 'This is an internal planning score, not a guaranteed business recommendation.',
    months: 'months',
    projectProgress: 'Project Progress',
    totalTasks: 'Total tasks',
    completedTasks: 'Completed tasks',
    lateTasks: 'Late tasks',
    upcomingDeadlines: 'Upcoming deadlines',
    nextMilestone: 'Next milestone',
    estimatedTaskCosts: 'Estimated Task Costs',
    documentsCount: 'Documents count',
    projectHealthScore: 'Project Health Score',
    strong: 'Strong',
    good: 'Good',
    needs_review: 'Needs Review',
    high_risk: 'High Risk',
    insufficient: 'Insufficient data',
    topRiskFlag: 'Top risk flag',
    openKpis: 'Open KPIs',
    noRiskFlags: 'No current risk flags.',
    financial_model_missing: 'Financial model missing',
    feasibility_incomplete: 'Feasibility study incomplete',
    overdue_tasks: 'Overdue tasks',
    no_documents: 'No documents uploaded',
    project_end_passed: 'Project end date passed',
    expenses_exceed_budget: 'Expenses exceed budget',
    negative_cash: 'Negative projected cash balance',
    payback_too_long: 'Payback period too long',
    behind_schedule: 'Actual progress is behind schedule',
    edit: 'Edit',
    delete: 'Delete',
    showMore: 'Show more',
    showLess: 'Show less',
    recentActivity: 'Recent Activity',
    nextSteps: 'Next Steps',
    projectStatus: 'Project Status',
    editProjectIncome: 'Edit Project Income',
    editProjectExpense: 'Edit Project Expense',
    deleteProjectIncome: 'Delete Project Income',
    deleteProjectExpense: 'Delete Project Expense',
    saveEdit: 'Save Changes',
    deleteFromProjectOnly: 'Delete from project only',
    deleteFromBothProjectAndPersonalRecords: 'Delete from project and personal records',
    deleteProjectIncomeBody: 'Do you want to delete this project income? This will delete it from the project only.',
    deleteProjectExpenseBody: 'Do you want to delete this project expense? This will delete it from the project only.',
    linkedIncomeDeletePrompt: 'This income is also linked to personal income. Choose what you want to delete.',
    linkedExpenseDeletePrompt: 'This expense is also linked to personal expenses. Choose what you want to delete.',
    projectIncomeUpdated: 'Project income updated.',
    projectExpenseUpdated: 'Project expense updated.',
    projectIncomeDeleted: 'Project income deleted.',
    projectExpenseDeleted: 'Project expense deleted.',
    projectIncomeDeleteError: 'Could not delete project income right now.',
    projectExpenseDeleteError: 'Could not delete project expense right now.',
    updateLinkedPersonalIncomeConfirm: 'This income is linked to personal income. Do you want to remove the personal copy too?',
    updateLinkedPersonalExpenseConfirm: 'This expense is linked to personal expenses. Do you want to remove the personal copy too?',
  },
  fr: {
    workspace: 'Espace projet',
    projectName: 'Nom du projet',
    projectType: 'Type de projet',
    status: 'Statut',
    capital: 'Capital',
    financialTarget: 'Objectif financier',
    startDate: 'Date de début',
    endDate: 'Date de fin',
    editProject: 'Modifier le projet',
    addExpense: 'Ajouter une dépense',
    projectExpenses: 'Dépenses du projet',
    expenseName: 'Nom de la dépense',
    amount: 'Montant',
    currency: 'Devise',
    date: 'Date',
    category: 'Catégorie',
    paymentMethod: 'Mode de paiement',
    notes: 'Notes',
    receipt: 'Reçu ou facture optionnel',
    aiReceiptReading: 'Lecture IA du reçu',
    aiReceiptHelper: 'Importez une image ou un PDF de reçu/facture pour une analyse automatique.',
    readReceipt: 'Lire le reçu',
    analyzeExpense: 'Analyser la dépense',
    readingReceipt: 'Lecture du reçu...',
    analyzingExpense: 'Analyse de la dépense...',
    receiptReadSuccess: 'Les données ont été extraites. Vérifiez-les avant l’enregistrement.',
    receiptReadError: 'Impossible d’analyser le reçu pour le moment. Vous pouvez saisir les données manuellement.',
    extractedReceiptTitle: 'Résultat de lecture du reçu',
    applyExtractedData: 'Appliquer les données',
    clearAiResult: 'Effacer le résultat',
    confidence: 'Confiance',
    vendorName: 'Nom du fournisseur',
    notClear: 'Peu clair',
    aiExpenseAnalysis: 'Analyse de la dépense',
    aiExpenseAnalysisError: 'Impossible d’analyser la dépense pour le moment. Vous pouvez l’enregistrer manuellement.',
    budgetImpact: 'Impact sur le budget',
    remainingBudgetAfterExpense: 'Restant après cette dépense',
    budgetUsedPercent: 'Budget utilisé',
    noProjectBudgetForAnalysis: 'Aucun budget n’est défini pour ce projet. Ajoutez un budget pour une analyse plus précise.',
    suggestedAction: 'Action suggérée',
    expenseAction_approve: 'Approuver',
    expenseAction_review: 'Vérifier',
    expenseAction_reduce: 'Réduire',
    expenseAction_move_category: 'Changer de catégorie',
    expenseAction_attach_document: 'Joindre un document',
    amountLevel: 'Niveau du montant',
    amountLevel_low: 'Faible',
    amountLevel_normal: 'Normal',
    amountLevel_high: 'Élevé',
    amountLevel_unknown: 'Inconnu',
    paidFromPersonalBudget: 'Payé depuis mon budget personnel',
    doNotIncludeInPersonalBudget: 'Cette dépense n’affecte pas vos dépenses personnelles sauf si vous le choisissez.',
    includeInPersonalBudget: 'Cette dépense apparaîtra aussi dans les dépenses personnelles avec le libellé Dépense de projet.',
    projectExpense: 'Dépense de projet',
    totalProjectExpenses: 'Total des dépenses du projet',
    projectExpensesThisMonth: 'Dépenses du projet ce mois-ci',
    personalBudgetProjectExpenses: 'Payé depuis le budget personnel',
    noProjectExpensesYet: 'Aucune dépense enregistrée pour ce projet.',
    actualVsPlanned: 'Réel vs prévu',
    saveProjectExpense: 'Enregistrer la dépense',
    cancel: 'Annuler',
    general: 'Général',
    operations: 'Opérations',
    marketingExpense: 'Marketing',
    payroll: 'Salaires',
    rent: 'Loyer',
    equipment: 'Équipement',
    licenses: 'Licences',
    cash: 'Espèces',
    card: 'Carte',
    transfer: 'Virement',
    projectExpenseSaved: 'Dépense du projet enregistrée.',
    projectExpenseSaveError: 'Impossible d’enregistrer la dépense du projet pour le moment.',
    requiredExpenseName: 'Saisissez le nom de la dépense.',
    requiredExpenseAmount: 'Saisissez un montant valide.',
    missingDataChecklist: 'Données à compléter',
    addProjectExpensesHint: 'Ajoutez les dépenses du projet pour afficher le réel vs prévu.',
    addFinancialModelHint: 'Ajoutez le modèle financier pour calculer la préparation du projet.',
    addTasksHint: 'Ajoutez des tâches pour afficher l’avancement du projet.',
    addIncome: 'Ajouter un revenu',
    projectIncome: 'Revenu du projet',
    incomeName: 'Nom du revenu',
    incomeSource: 'Source / catégorie',
    source: 'Source',
    transferredToPersonalIncome: 'Transféré vers mon revenu personnel',
    doNotIncludeInPersonalIncome: 'Ce revenu n’affecte pas votre revenu personnel sauf si vous le choisissez.',
    includeInPersonalIncome: 'Ce revenu apparaîtra aussi sur la page des revenus personnels avec une étiquette Revenu de projet.',
    totalProjectIncome: 'Total des revenus du projet',
    projectIncomeThisMonth: 'Revenus du projet ce mois-ci',
    personalIncomeProjectIncome: 'Transféré vers le revenu personnel',
    noProjectIncomeYet: 'Aucun revenu enregistré pour ce projet.',
    actualVsExpected: 'Réel vs attendu',
    saveProjectIncome: 'Enregistrer le revenu du projet',
    projectIncomeSaved: 'Revenu du projet enregistré.',
    projectIncomeSaveError: 'Impossible d’enregistrer le revenu du projet pour le moment.',
    requiredIncomeName: 'Saisissez le nom du revenu.',
    requiredIncomeAmount: 'Saisissez un montant valide.',
    salesIncome: 'Ventes',
    servicesIncome: 'Services',
    rentalIncome: 'Location',
    investmentIncome: 'Investissement',
    otherIncomeSource: 'Autre source',
    analyzeProject: 'Analyser le projet',
    chooseJurisdiction: 'Choisir la juridiction',
    back: 'Retour à mes projets',
    signIn: 'Connectez-vous pour voir les détails de vos projets.',
    notFound: 'Projet introuvable.',
    overview: 'Vue d’ensemble',
    feasibility: 'Faisabilité',
    financial: 'Modèle financier',
    tasks: 'Tâches',
    documents: 'Documents',
    documentsCenter: 'Centre des documents',
    kpis: 'KPI',
    ai: 'Conseiller IA',
    pitchDeck: 'Pitch Deck',
    comingSoon: 'Cette section sera activée dans la prochaine phase.',
    projectSummary: 'Résumé du projet',
    financialSnapshot: 'Aperçu financier',
    timelineSnapshot: 'Aperçu du calendrier',
    timelineInsufficient: 'Données insuffisantes pour afficher le résumé du calendrier.',
    riskSnapshot: 'Aperçu des risques',
    quickActions: 'Actions rapides',
    description: 'Description',
    priority: 'Priorité',
    currentPhase: 'Phase actuelle',
    totalIncome: 'Revenus du projet',
    totalExpenses: 'Dépenses du projet',
    netResult: 'Résultat net',
    remainingBudget: 'Budget restant',
    targetProgress: 'Progression vers l’objectif',
    daysRemaining: 'Jours restants',
    duration: 'Durée du projet',
    noDate: 'Non défini',
    noData: 'Données insuffisantes',
    low: 'Faible',
    medium: 'Moyen',
    high: 'Élevé',
    riskLowText: 'Les indicateurs actuels semblent stables pour ce projet.',
    riskMediumText: 'Ce projet nécessite un suivi financier et opérationnel régulier.',
    riskHighText: 'Ce projet nécessite une revue urgente des risques et du budget.',
    addTask: 'Ajouter une tâche',
    generateFeasibility: 'Créer une faisabilité',
    createFinancialModel: 'Créer un modèle financier',
    idea: 'Idée',
    study: 'Étude',
    setup: 'Mise en place',
    launch: 'Lancement',
    growth: 'Croissance',
    paused: 'En pause',
    completed: 'Terminé',
    ecommerce: 'E-commerce',
    restaurant: 'Restaurant / Café',
    services: 'Services',
    saas: 'SaaS / Application',
    trading: 'Commerce général',
    realEstate: 'Immobilier',
    otherProject: 'Autre projet',
    feasibilityHint: 'Une étude couvrant le marché, les coûts, les concurrents, les licences et les risques.',
    financialHint: 'Un modèle financier couvrant les revenus, les dépenses, la trésorerie et le seuil de rentabilité.',
    tasksHint: 'Un tableau de tâches et un calendrier pour exécuter le projet.',
    documentsHint: 'Un coffre de documents pour les contrats, licences et factures.',
    kpisHint: 'Indicateurs de performance, rentabilité et progression du projet.',
    aiHint: 'Un conseiller intelligent qui lit vos données et suggère les prochaines étapes.',
    pitchDeckHint: 'Pitch deck structuré basé sur les données réelles du projet.',
    feasibilitySummary: 'Résumé de faisabilité',
    marketFeasibility: 'Faisabilité du marché',
    technicalFeasibility: 'Faisabilité technique',
    financialFeasibility: 'Faisabilité financière',
    legalFeasibility: 'Faisabilité juridique et réglementaire',
    marketSize: 'Taille estimée du marché',
    targetCustomers: 'Segment client cible',
    problemSolved: 'Problème résolu par le projet',
    competitors: 'Principaux concurrents',
    competitiveAdvantage: 'Avantage concurrentiel',
    pricingStrategy: 'Stratégie de prix',
    acquisitionChannels: 'Canaux d’acquisition client',
    requiredResources: 'Ressources nécessaires',
    requiredTechnology: 'Technologies/outils nécessaires',
    operationalSetup: 'Emplacement ou configuration opérationnelle',
    keySuppliers: 'Fournisseurs clés',
    teamSize: 'Taille d’équipe requise',
    implementationChallenges: 'Difficultés de mise en œuvre prévues',
    requiredCapital: 'Capital requis',
    capex: 'Coûts de démarrage CAPEX',
    monthlyOpex: 'Coûts opérationnels mensuels OPEX',
    expectedMonthlyRevenue: 'Revenu mensuel attendu',
    expectedProfitMargin: 'Marge bénéficiaire estimée %',
    breakEvenPoint: 'Point mort estimé',
    paybackPeriod: 'Période de récupération estimée',
    targetCountry: 'Pays / marché cible',
    licenseType: 'Type de licence requis',
    governmentEntities: 'Entités gouvernementales concernées',
    legalRequirements: 'Exigences légales particulières',
    insuranceObligations: 'Assurances ou obligations réglementaires',
    legalNotes: 'Notes juridiques',
    kuwait: 'Koweït',
    saudiArabia: 'Arabie saoudite',
    uae: 'Émirats arabes unis',
    qatar: 'Qatar',
    bahrain: 'Bahreïn',
    oman: 'Oman',
    globalOther: 'Global / Autre',
    feasibilityScore: 'Score de faisabilité',
    feasible: 'Faisable',
    needsReview: 'À réviser',
    highRisk: 'Risque élevé',
    monthlyProfitEstimate: 'Bénéfice mensuel estimé',
    breakEvenEstimate: 'Seuil de rentabilité estimé',
    roiEstimate: 'ROI annuel estimé',
    missingSections: 'Sections manquantes',
    saveFeasibilityStudy: 'Enregistrer l’étude de faisabilité',
    feasibilitySaved: 'Étude de faisabilité enregistrée.',
    feasibilitySaveError: 'Impossible d’enregistrer l’étude de faisabilité pour le moment.',
    aiFeasibilityAnalysis: 'Analyse IA de faisabilité',
    aiFeasibilitySoon: 'L’analyse IA avancée sera activée dans une phase ultérieure.',
    exportFeasibilityPdf: 'Exporter l’étude PDF',
    creatingFeasibilityPdf: 'Création du PDF...',
    feasibilityPdfExported: 'PDF exporté avec succès',
    feasibilityPdfExportError: 'Impossible d’exporter le PDF, veuillez réessayer',
    saveFeasibilityBeforeExport: 'Enregistrez l’étude de faisabilité avant l’export',
    comingSoonShort: 'Bientôt',
    internalScoreDisclaimer: 'Il s’agit d’un score interne de planification, pas d’une recommandation commerciale garantie.',
    months: 'mois',
    projectProgress: 'Progression du projet',
    totalTasks: 'Total des tâches',
    completedTasks: 'Tâches terminées',
    lateTasks: 'Tâches en retard',
    upcomingDeadlines: 'Échéances à venir',
    nextMilestone: 'Prochain jalon',
    estimatedTaskCosts: 'Coûts estimés des tâches',
    documentsCount: 'Nombre de documents',
    projectHealthScore: 'Score de santé du projet',
    strong: 'Fort',
    good: 'Bon',
    needs_review: 'À réviser',
    high_risk: 'Risque élevé',
    insufficient: 'Données insuffisantes',
    topRiskFlag: 'Principale alerte de risque',
    openKpis: 'Ouvrir les KPI',
    noRiskFlags: 'Aucune alerte de risque actuellement.',
    financial_model_missing: 'Modèle financier manquant',
    feasibility_incomplete: 'Étude de faisabilité incomplète',
    overdue_tasks: 'Tâches en retard',
    no_documents: 'Aucun document téléversé',
    project_end_passed: 'Date de fin du projet dépassée',
    expenses_exceed_budget: 'Les dépenses dépassent le budget',
    negative_cash: 'Solde de trésorerie projeté négatif',
    payback_too_long: 'Période de récupération trop longue',
    behind_schedule: 'Progression réelle en retard',
    edit: 'Modifier',
    delete: 'Supprimer',
    showMore: 'Afficher plus',
    showLess: 'Afficher moins',
    recentActivity: 'Activité récente',
    nextSteps: 'Prochaines étapes',
    projectStatus: 'Statut du projet',
    editProjectIncome: 'Modifier le revenu du projet',
    editProjectExpense: 'Modifier la dépense du projet',
    deleteProjectIncome: 'Supprimer le revenu du projet',
    deleteProjectExpense: 'Supprimer la dépense du projet',
    saveEdit: 'Enregistrer les modifications',
    deleteFromProjectOnly: 'Supprimer du projet uniquement',
    deleteFromBothProjectAndPersonalRecords: 'Supprimer du projet et des dossiers personnels',
    deleteProjectIncomeBody: 'Voulez-vous supprimer ce revenu du projet ? Il sera supprimé du projet uniquement.',
    deleteProjectExpenseBody: 'Voulez-vous supprimer cette dépense du projet ? Elle sera supprimée du projet uniquement.',
    linkedIncomeDeletePrompt: 'Ce revenu est aussi lié au revenu personnel. Choisissez ce que vous voulez supprimer.',
    linkedExpenseDeletePrompt: 'Cette dépense est aussi liée aux dépenses personnelles. Choisissez ce que vous voulez supprimer.',
    projectIncomeUpdated: 'Revenu du projet mis à jour.',
    projectExpenseUpdated: 'Dépense du projet mise à jour.',
    projectIncomeDeleted: 'Revenu du projet supprimé.',
    projectExpenseDeleted: 'Dépense du projet supprimée.',
    projectIncomeDeleteError: 'Impossible de supprimer le revenu du projet pour le moment.',
    projectExpenseDeleteError: 'Impossible de supprimer la dépense du projet pour le moment.',
    updateLinkedPersonalIncomeConfirm: 'Ce revenu est lié au revenu personnel. Voulez-vous aussi supprimer la copie personnelle ?',
    updateLinkedPersonalExpenseConfirm: 'Cette dépense est liée aux dépenses personnelles. Voulez-vous aussi supprimer la copie personnelle ?',
  },
} as const;

export type Translation = Record<keyof typeof TEXT.ar, string>;

