// TEXT translations for debts/page
export const TEXT = {
  title: { ar: 'الديون', en: 'Debts', fr: 'Dettes' },
  subtitle: {
    ar: 'تابع التزاماتك الشهرية وخطط لسدادها دون التأثير على ميزانيتك.',
    en: 'Track monthly obligations and plan repayments without disrupting your budget.',
    fr: 'Suivez vos engagements mensuels et planifiez leur remboursement sans déséquilibrer votre budget.',
  },
  addDebt: { ar: 'إضافة دين', en: 'Add debt', fr: 'Ajouter une dette' },
  editDebt: { ar: 'تعديل الدين', en: 'Edit debt', fr: 'Modifier la dette' },
  totalDebts: { ar: 'إجمالي الديون', en: 'Total debts', fr: 'Total des dettes' },
  remainingToPay: { ar: 'المتبقي للسداد', en: 'Remaining to pay', fr: 'Reste à rembourser' },
  monthlyInstallments: { ar: 'إجمالي الأقساط الشهرية', en: 'Monthly payments', fr: 'Mensualités totales' },
  highestDebt: { ar: 'أعلى دين', en: 'Highest debt', fr: 'Dette la plus élevée' },
  debtToIncome: { ar: 'نسبة الديون من الدخل الشهري', en: 'Debt-to-income ratio', fr: 'Ratio dette/revenu' },
  debtAnalysis: { ar: 'تحليل الديون', en: 'Debt analysis', fr: 'Analyse des dettes' },
  educational: { ar: 'تحليل تعليمي محسوب من بياناتك', en: 'Educational analysis from your data', fr: 'Analyse éducative calculée à partir de vos données' },
  noDebts: { ar: 'لا توجد ديون بعد', en: 'No debts yet', fr: 'Aucune dette pour le moment' },
  noDebtsBody: {
    ar: 'أضف أول دين لتتبع الرصيد المتبقي، الأقساط، وتاريخ السداد القادم.',
    en: 'Add your first debt to track remaining balance, payments, and the next due date.',
    fr: 'Ajoutez votre première dette pour suivre le solde restant, les paiements et la prochaine échéance.',
  },
  name: { ar: 'اسم الدين', en: 'Debt name', fr: 'Nom de la dette' },
  namePlaceholder: { ar: 'مثال: قرض سيارة أو بطاقة ائتمان', en: 'Example: car loan or credit card', fr: 'Exemple : prêt auto ou carte de crédit' },
  creditor: { ar: 'الجهة الدائنة', en: 'Creditor', fr: 'Créancier' },
  creditorPlaceholder: { ar: 'بنك أو شركة تمويل أو شخص', en: 'Bank, finance company, or person', fr: 'Banque, société de financement ou personne' },
  originalAmount: { ar: 'مبلغ الدين الأصلي', en: 'Original amount', fr: 'Montant initial' },
  remainingAmount: { ar: 'المبلغ المتبقي', en: 'Remaining amount', fr: 'Montant restant' },
  currency: { ar: 'العملة', en: 'Currency', fr: 'Devise' },
  startDate: { ar: 'تاريخ بداية الدين', en: 'Start date', fr: 'Date de début' },
  firstPaymentDate: { ar: 'تاريخ أول دفعة شهرية', en: 'First monthly payment date', fr: 'Date de la première mensualité' },
  firstPaymentDateHelp: {
    ar: 'يُستخدم هذا التاريخ لحساب الدفعات الشهرية المستحقة وخصمها من الرصيد المتبقي.',
    en: 'This date is used to calculate due monthly payments and deduct them from the remaining balance.',
    fr: 'Cette date sert à calculer les mensualités dues et à les déduire du solde restant.',
  },
  monthlyPayment: { ar: 'قيمة الدفع الشهري', en: 'Monthly payment', fr: 'Paiement mensuel' },
  interestRate: { ar: 'نسبة الفائدة', en: 'Interest rate', fr: 'Taux d’intérêt' },
  interestType: { ar: 'نوع الفائدة', en: 'Interest type', fr: 'Type d’intérêt' },
  noInterest: { ar: 'بدون فائدة', en: 'No interest', fr: 'Sans intérêt' },
  annualInterest: { ar: 'فائدة سنوية', en: 'Annual interest', fr: 'Intérêt annuel' },
  monthlyInterest: { ar: 'فائدة شهرية', en: 'Monthly interest', fr: 'Intérêt mensuel' },
  paymentDay: { ar: 'يوم الدفع الشهري', en: 'Monthly payment day', fr: 'Jour de paiement mensuel' },
  autoExpense: { ar: 'إضافة الدفعة الشهرية إلى المصروفات تلقائيًا', en: 'Add monthly payment to expenses automatically', fr: 'Ajouter automatiquement la mensualité aux dépenses' },
  notes: { ar: 'ملاحظات', en: 'Notes', fr: 'Notes' },
  save: { ar: 'حفظ الدين', en: 'Save debt', fr: 'Enregistrer la dette' },
  saving: { ar: 'جارٍ الحفظ...', en: 'Saving...', fr: 'Enregistrement...' },
  cancel: { ar: 'إلغاء', en: 'Cancel', fr: 'Annuler' },
  active: { ar: 'نشط', en: 'Active', fr: 'Active' },
  paid: { ar: 'مدفوع', en: 'Paid', fr: 'Payée' },
  paused: { ar: 'متوقف', en: 'Paused', fr: 'Suspendue' },
  remaining: { ar: 'المتبقي', en: 'Remaining', fr: 'Restant' },
  paidAmount: { ar: 'المدفوع', en: 'Paid', fr: 'Payé' },
  totalPaidAmount: { ar: 'إجمالي المدفوع', en: 'Total paid', fr: 'Total payé' },
  totalInterestPaid: { ar: 'إجمالي الفائدة المدفوعة', en: 'Total interest paid', fr: 'Total des intérêts payés' },
  paidPaymentsCount: { ar: 'عدد الدفعات المدفوعة', en: 'Paid payments', fr: 'Paiements effectués' },
  lastPayment: { ar: 'آخر دفعة تم خصمها', en: 'Last deducted payment', fr: 'Dernier paiement déduit' },
  payoffRate: { ar: 'نسبة السداد', en: 'Payoff rate', fr: 'Taux de remboursement' },
  nextPayment: { ar: 'الدفعة القادمة', en: 'Next payment', fr: 'Prochain paiement' },
  paymentDayLabel: { ar: 'يوم الدفع', en: 'Payment day', fr: 'Jour de paiement' },
  recordPayment: { ar: 'تسجيل دفعة', en: 'Record payment', fr: 'Enregistrer un paiement' },
  pause: { ar: 'إيقاف مؤقت', en: 'Pause', fr: 'Suspendre' },
  resume: { ar: 'استئناف', en: 'Resume', fr: 'Reprendre' },
  markPaid: { ar: 'تم السداد', en: 'Mark paid', fr: 'Marquer payée' },
  delete: { ar: 'حذف', en: 'Delete', fr: 'Supprimer' },
  edit: { ar: 'تعديل', en: 'Edit', fr: 'Modifier' },
  monthlyRatio: { ar: 'نسبة الأقساط من الدخل الشهري', en: 'Payments as share of income', fr: 'Mensualités en part du revenu' },
  incomeUnavailable: { ar: 'لا توجد بيانات دخل كافية لحساب النسبة.', en: 'Not enough income data to calculate the ratio.', fr: 'Données de revenu insuffisantes pour calculer le ratio.' },
  ratioHigh: { ar: 'تتجاوز أقساط الديون 30% من الدخل الشهري المسجل. راجع الالتزامات بعناية.', en: 'Debt payments exceed 30% of recorded monthly income. Review obligations carefully.', fr: 'Les mensualités dépassent 30 % du revenu mensuel enregistré. Examinez les engagements avec attention.' },
  ratioOk: { ar: 'نسبة الأقساط ضمن نطاق يمكن متابعته وفق البيانات المسجلة.', en: 'The payment ratio is within a trackable range based on recorded data.', fr: 'Le ratio de mensualités reste dans une plage suivable selon les données enregistrées.' },
  highestImpact: { ar: 'أعلى دين تأثيرًا على الميزانية', en: 'Highest budget impact', fr: 'Impact budgétaire le plus élevé' },
  payoffOrder: { ar: 'اقتراح ترتيب السداد', en: 'Suggested payoff order', fr: 'Ordre de remboursement suggéré' },
  highestInterestFirst: { ar: 'الأعلى فائدة أولًا', en: 'Highest interest first', fr: 'Taux le plus élevé d’abord' },
  smallestDebtFirst: { ar: 'أصغر دين أولًا', en: 'Smallest debt first', fr: 'Plus petite dette d’abord' },
  payoffEstimate: { ar: 'تقدير مدة السداد', en: 'Estimated payoff period', fr: 'Durée estimée de remboursement' },
  months: { ar: 'شهر', en: 'months', fr: 'mois' },
  interestWarning: {
    ar: 'القسط الشهري لا يغطي الفائدة، وقد يزيد الدين بدلًا من أن ينقص.',
    en: 'The monthly payment does not cover interest, so the debt may increase instead of decrease.',
    fr: 'La mensualité ne couvre pas les intérêts, la dette peut donc augmenter au lieu de diminuer.',
  },
  unavailable: { ar: 'غير متاح', en: 'Unavailable', fr: 'Indisponible' },
  loading: { ar: 'جارٍ تحميل الديون...', en: 'Loading debts...', fr: 'Chargement des dettes...' },
  saved: { ar: 'تم حفظ الدين بنجاح.', en: 'Debt saved successfully.', fr: 'Dette enregistrée avec succès.' },
  deleted: { ar: 'تم حذف الدين.', en: 'Debt deleted.', fr: 'Dette supprimée.' },
  paymentRecorded: { ar: 'تم تسجيل الدفعة وتحديث الرصيد.', en: 'Payment recorded and balance updated.', fr: 'Paiement enregistré et solde mis à jour.' },
  generatedPayments: { ar: 'تمت إضافة الدفعات الشهرية المستحقة.', en: 'Due monthly payments were added.', fr: 'Les mensualités dues ont été ajoutées.' },
  updateDebtCalculations: { ar: 'تحديث حساب الديون', en: 'Update debt calculations', fr: 'Mettre à jour les calculs des dettes' },
  calculatingDebts: { ar: 'جارٍ تحديث الحساب...', en: 'Updating calculations...', fr: 'Mise à jour des calculs...' },
  debtCalculationUpdated: { ar: 'تم تحديث حساب الديون بنجاح.', en: 'Debt calculations updated successfully.', fr: 'Les calculs des dettes ont été mis à jour.' },
  noDueMonthlyPayments: { ar: 'لا توجد دفعات شهرية مستحقة حاليًا.', en: 'No monthly payments are currently due.', fr: 'Aucune mensualité n’est actuellement due.' },
  required: { ar: 'يرجى إكمال الحقول المطلوبة بقيم صحيحة.', en: 'Please complete required fields with valid values.', fr: 'Veuillez compléter les champs obligatoires avec des valeurs valides.' },
  completeRequired: { ar: 'يرجى إدخال الحقول المطلوبة قبل الحفظ.', en: 'Please complete the required fields before saving.', fr: 'Veuillez compléter les champs obligatoires avant l’enregistrement.' },
  completeRequiredButton: { ar: 'أكمل البيانات المطلوبة', en: 'Complete required fields', fr: 'Compléter les champs requis' },
  modalSubtitle: { ar: 'أدخل بيانات الدين لمتابعة السداد الشهري.', en: 'Enter debt details to track monthly repayment.', fr: 'Saisissez les données de la dette pour suivre le remboursement mensuel.' },
  saveErrorTitle: { ar: 'تعذر حفظ بيانات الدين', en: 'Could not save debt data', fr: 'Impossible d’enregistrer les données de la dette' },
  sectionDebtData: { ar: 'بيانات الدين', en: 'Debt details', fr: 'Détails de la dette' },
  sectionPaymentDetails: { ar: 'تفاصيل السداد', en: 'Repayment details', fr: 'Détails du remboursement' },
  sectionInterest: { ar: 'الفائدة', en: 'Interest', fr: 'Intérêt' },
  sectionSettings: { ar: 'الإعدادات والملاحظات', en: 'Settings and notes', fr: 'Paramètres et notes' },
  autoExpenseHelper: { ar: 'سيتم تسجيل الدفعة الشهرية ضمن المصروفات عند موعد الاستحقاق.', en: 'The monthly payment will be recorded as an expense when it becomes due.', fr: 'La mensualité sera enregistrée comme dépense à la date d’échéance.' },
  validationName: { ar: 'يرجى إدخال اسم الدين.', en: 'Please enter the debt name.', fr: 'Veuillez saisir le nom de la dette.' },
  validationCreditor: { ar: 'يرجى إدخال الجهة الدائنة.', en: 'Please enter the creditor.', fr: 'Veuillez saisir le créancier.' },
  validationOriginalAmount: { ar: 'يرجى إدخال مبلغ الدين الأصلي.', en: 'Please enter the original debt amount.', fr: 'Veuillez saisir le montant initial de la dette.' },
  validationRemainingAmount: { ar: 'يرجى إدخال المبلغ المتبقي.', en: 'Please enter the remaining amount.', fr: 'Veuillez saisir le montant restant.' },
  validationMonthlyPayment: { ar: 'يرجى إدخال قيمة الدفع الشهري.', en: 'Please enter the monthly payment amount.', fr: 'Veuillez saisir le montant de la mensualité.' },
  validationCurrency: { ar: 'يرجى اختيار العملة.', en: 'Please choose a currency.', fr: 'Veuillez choisir une devise.' },
  validationInterestRate: { ar: 'نسبة الفائدة يجب أن تكون بين 0 و100.', en: 'Interest rate must be between 0 and 100.', fr: 'Le taux d’intérêt doit être compris entre 0 et 100.' },
  validationPaymentDay: { ar: 'يوم الدفع الشهري يجب أن يكون بين 1 و31.', en: 'Monthly payment day must be between 1 and 31.', fr: 'Le jour de paiement mensuel doit être compris entre 1 et 31.' },
  validationStartDate: { ar: 'تاريخ بداية الدين غير صالح.', en: 'Debt start date is invalid.', fr: 'La date de début de la dette est invalide.' },
  validationFirstPaymentDate: { ar: 'تاريخ أول دفعة شهرية غير صالح.', en: 'First monthly payment date is invalid.', fr: 'La date de la première mensualité est invalide.' },
  debtCalculationError: { ar: 'تعذر تحديث بيانات الدين. يرجى مراجعة إعدادات قاعدة البيانات.', en: 'Could not update debt data. Please review database settings.', fr: 'Impossible de mettre à jour les données de la dette. Veuillez vérifier les paramètres de la base de données.' },
  authSaveError: { ar: 'يجب تسجيل الدخول لحفظ بيانات الدين.', en: 'You must sign in to save debt data.', fr: 'Vous devez vous connecter pour enregistrer les données de la dette.' },
  rlsSaveError: { ar: 'تعذر حفظ الدين بسبب صلاحيات الوصول. يرجى مراجعة إعدادات قاعدة البيانات.', en: 'Debt could not be saved because of access permissions. Please review database settings.', fr: 'La dette n’a pas pu être enregistrée en raison des autorisations d’accès. Veuillez vérifier les paramètres de la base de données.' },
  databaseSaveError: { ar: 'تعذر حفظ بيانات الدين. يرجى مراجعة إعدادات قاعدة البيانات والمحاولة مرة أخرى.', en: 'Debt data could not be saved. Please review the database settings and try again.', fr: 'Les données de la dette n’ont pas pu être enregistrées. Veuillez vérifier les paramètres de la base de données puis réessayer.' },
  networkSaveError: { ar: 'تعذر الاتصال بالخادم. يرجى المحاولة لاحقًا.', en: 'Could not connect to the server. Please try again later.', fr: 'Impossible de se connecter au serveur. Veuillez réessayer plus tard.' },
  duplicatePayment: { ar: 'تم تسجيل دفعة لهذا الدين في هذا التاريخ مسبقًا.', en: 'A payment for this debt already exists on this date.', fr: 'Un paiement pour cette dette existe déjà à cette date.' },
  error: { ar: 'تعذر إكمال العملية. حاول مرة أخرى لاحقًا.', en: 'Could not complete the action. Please try again later.', fr: 'Impossible de terminer l’action. Réessayez plus tard.' },
  yes: { ar: 'نعم', en: 'Yes', fr: 'Oui' },
  no: { ar: 'لا', en: 'No', fr: 'Non' },
  dueToday: { ar: 'مستحق اليوم', en: 'Due today', fr: 'Dû aujourd’hui' },
  tableView: { ar: 'جدول الديون', en: 'Debts table', fr: 'Tableau des dettes' },
  // Payoff strategies
  payoffDate: { ar: 'تاريخ السداد المتوقع', en: 'Est. payoff date', fr: 'Date de remboursement estimée' },
  payoffStrategies: { ar: 'اقتراحات طريقة السداد', en: 'Payoff strategies', fr: 'Stratégies de remboursement' },
  payoffStrategiesBody: {
    ar: 'أدخل أي مبلغ إضافي تستطيع دفعه شهريًا واكتشف الفرق بين طريقة الكرة الثلجية وطريقة الانهيار الجليدي.',
    en: 'Enter any extra monthly amount and see the difference between the snowball and avalanche methods.',
    fr: 'Entrez un montant mensuel supplémentaire et découvrez la différence entre la méthode boule de neige et la méthode avalanche.',
  },
  snowballTitle: { ar: 'الكرة الثلجية', en: 'Snowball', fr: 'Boule de neige' },
  snowballDesc: {
    ar: 'سدِّد أصغر الديون أولًا، ثم أضف دفعتها إلى الدين التالي — تكسب زخمًا نفسيًا وتشعر بالتقدم بسرعة.',
    en: 'Pay off the smallest debts first, then roll that payment to the next — you build momentum and see quick wins.',
    fr: `Remboursez d'abord les plus petites dettes, puis cumulez ce paiement sur la suivante — vous gagnez en motivation.`,
  },
  avalancheTitle: { ar: 'الانهيار الجليدي', en: 'Avalanche', fr: 'Avalanche' },
  avalancheDesc: {
    ar: 'سدِّد الدين الأعلى فائدة أولًا — توفر أكبر قدر من المال على المدى الطويل.',
    en: 'Pay off the highest-interest debt first — you save the most money over time.',
    fr: `Remboursez d'abord la dette au taux le plus élevé — vous économisez le plus d'argent à long terme.`,
  },
  extraPaymentLabel: { ar: 'دفعة إضافية شهرية', en: 'Extra monthly payment', fr: 'Versement mensuel supplémentaire' },
  extraPaymentPlaceholder: { ar: 'مثال: 50', en: 'e.g. 50', fr: 'ex. 50' },
  totalInterestLabel: { ar: 'إجمالي الفائدة', en: 'Total interest', fr: 'Total des intérêts' },
  interestSaved: { ar: 'فائدة موفَّرة', en: 'Interest saved', fr: 'Intérêts économisés' },
  payoffInMonths: { ar: 'مدة السداد الكلية', en: 'Total payoff time', fr: 'Durée totale de remboursement' },
  debtOrderLabel: { ar: 'ترتيب السداد', en: 'Payoff order', fr: 'Ordre de remboursement' },
  payoffMonth: { ar: 'الشهر', en: 'Month', fr: 'Mois' },
  noActiveDebts: { ar: 'لا توجد ديون نشطة لحساب الاستراتيجية.', en: 'No active debts to calculate strategy.', fr: 'Aucune dette active pour calculer la stratégie.' },
  interestSavedVsSnowball: { ar: 'وفر مقارنةً بالكرة الثلجية', en: 'saved vs. snowball', fr: 'économisé vs. boule de neige' },
  fastestMethod: { ar: 'أسرع بـ', en: 'faster by', fr: 'plus rapide de' },
  sameSpeed: { ar: 'نفس المدة', en: 'Same duration', fr: 'Même durée' },
  recommended: { ar: 'الأفضل لتوفير المال', en: 'Best to save money', fr: 'Meilleure économie' },
  bestMomentum: { ar: 'الأفضل نفسيًا', en: 'Best for momentum', fr: 'Meilleure motivation' },
};

