'use client';
import { useState } from 'react';
import Link from 'next/link';
import { Languages } from 'lucide-react';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
type Language = 'ar' | 'en' | 'fr' | 'zh';
const content = {
  ar: { back: 'العودة للرئيسية', title: 'أنواع الإستثمار', intro: 'الإستثمار يعني تشغيل المال أو الوقت في أصل أو مهارة بهدف تحقيق نمو مستقبلي. الأفضل دائماً توزيع المخاطر وعدم وضع كل المال في خيار واحد.', tipsTitle: 'نصائح مهمة', tips: ['ابدأ بمبلغ صغير وتعلم قبل زيادة المبلغ.', 'نوّع بين أكثر من نوع استثمار لتقليل المخاطر.', 'لا تستثمر مال الطوارئ أو المال الذي تحتاجه قريباً.', 'قارن الرسوم والمخاطر قبل الاختيار.'], items: [['الأسهم', 'شراء حصة في شركة. قد تربح من ارتفاع السعر أو توزيعات الأرباح.', ['أسهم البنوك', 'أسهم الاتصالات', 'أسهم الطاقة', 'أسهم الشركات القيادية']], ['الصناديق الاستثمارية', 'محفظة يديرها مختصون وتجمع أموال عدة مستثمرين.', ['صناديق الأسهم', 'صناديق الدخل', 'صناديق متوازنة', 'صناديق مؤشرات']], ['الصكوك والسندات', 'أدوات دخل ثابت أو شبه ثابت تناسب من يريد مخاطرة أقل من الأسهم.', ['صكوك حكومية', 'صكوك شركات', 'سندات قصيرة الأجل']], ['العقار', 'شراء أصل عقاري للاستفادة من الإيجار أو ارتفاع القيمة.', ['شقة للإيجار', 'أرض', 'محل تجاري', 'صناديق عقارية']], ['الذهب والمعادن', 'أصول تستخدم غالباً للحماية وتنويع المحفظة.', ['ذهب عيار 24', 'سبائك', 'صناديق ذهب', 'فضة']], ['المشاريع الصغيرة', 'استثمار مباشر في نشاط تجاري أو خدمة.', ['متجر إلكتروني', 'مطعم صغير', 'خدمات رقمية', 'تجارة منزلية']], ['التعليم والمهارات', 'استثمار في نفسك لزيادة الدخل مستقبلاً.', ['دورات مهنية', 'لغات', 'برمجة', 'تسويق ومبيعات']], ['العملات الرقمية', 'أصول عالية التذبذب وتحتاج حذراً ومعرفة قبل الدخول.', ['بيتكوين', 'إيثريوم', 'صناديق مرتبطة بالعملات الرقمية']]] },
  en: { back: 'Back to home', title: 'Investment Types', intro: 'Investing means using money or time in an asset or skill to achieve future growth. It is better to diversify risks and avoid putting everything in one option.', tipsTitle: 'Important tips', tips: ['Start small and learn before increasing the amount.', 'Diversify across more than one investment type.', 'Do not invest emergency money or money you need soon.', 'Compare fees and risks before choosing.'], items: [['Stocks', 'Buying a share in a company. You may profit from price growth or dividends.', ['Bank stocks', 'Telecom stocks', 'Energy stocks', 'Blue-chip companies']], ['Investment funds', 'A portfolio managed by specialists that combines money from many investors.', ['Equity funds', 'Income funds', 'Balanced funds', 'Index funds']], ['Sukuk and bonds', 'Fixed or semi-fixed income instruments for lower risk than stocks.', ['Government sukuk', 'Corporate sukuk', 'Short-term bonds']], ['Real estate', 'Buying property to benefit from rent or value growth.', ['Rental apartment', 'Land', 'Commercial shop', 'Real estate funds']], ['Gold and metals', 'Assets often used for protection and portfolio diversification.', ['24K gold', 'Bullion', 'Gold funds', 'Silver']], ['Small businesses', 'Direct investment in a business or service.', ['Online store', 'Small restaurant', 'Digital services', 'Home business']], ['Education and skills', 'Investing in yourself to increase future income.', ['Professional courses', 'Languages', 'Programming', 'Sales and marketing']], ['Digital assets', 'High-volatility assets that require caution and knowledge.', ['Bitcoin', 'Ethereum', 'Crypto-linked funds']]] },
  fr: { back: 'Retour à l\'accueil', title: "Types d'investissement", intro: "Investir signifie utiliser de l'argent ou du temps dans un actif ou une compétence pour obtenir une croissance future. Il vaut mieux diversifier les risques.", tipsTitle: 'Conseils importants', tips: ['Commencez petit et apprenez avant d\'augmenter.', 'Diversifiez entre plusieurs types d\'investissement.', 'N\'investissez pas votre fonds d\'urgence.', 'Comparez les frais et les risques avant de choisir.'], items: [['Actions', 'Acheter une part d\'une entreprise avec profit possible via prix ou dividendes.', ['Banques', 'Télécoms', 'Énergie', 'Grandes sociétés']], ['Fonds d\'investissement', 'Portefeuille géré par des spécialistes pour plusieurs investisseurs.', ['Fonds actions', 'Fonds revenus', 'Fonds équilibrés', 'Fonds indiciels']], ['Sukuk et obligations', 'Instruments de revenu fixe ou semi-fixe avec moins de risque que les actions.', ['Sukuk publics', 'Sukuk sociétés', 'Obligations courtes']], ['Immobilier', 'Acheter un bien pour le loyer ou la hausse de valeur.', ['Appartement locatif', 'Terrain', 'Local commercial', 'Fonds immobiliers']], ['Or et métaux', 'Actifs utilisés pour protéger et diversifier le portefeuille.', ['Or 24K', 'Lingots', 'Fonds or', 'Argent']], ['Petites entreprises', 'Investissement direct dans une activité ou un service.', ['Boutique en ligne', 'Petit restaurant', 'Services numériques', 'Commerce à domicile']], ['Éducation et compétences', 'Investir en soi pour augmenter les revenus futurs.', ['Formations', 'Langues', 'Programmation', 'Vente et marketing']], ['Actifs numériques', 'Actifs très volatils qui nécessitent prudence et connaissance.', ['Bitcoin', 'Ethereum', 'Fonds liés aux cryptos']]] },
  zh: { back: '返回首页', title: '投资类型', intro: '投资是把金钱或时间投入资产或技能，以获得未来增长。最好分散风险，不要把所有资金放在一个选择里。', tipsTitle: '重要建议', tips: ['从小金额开始，先学习再增加投入。', '分散到多种投资类型以降低风险。', '不要投资应急资金或近期需要的钱。', '选择前比较费用和风险。'], items: [['股票', '购买公司的股份，可能通过价格上涨或分红获利。', ['银行股', '电信股', '能源股', '蓝筹公司']], ['投资基金', '由专业人士管理，汇集多位投资者资金的组合。', ['股票基金', '收益基金', '平衡基金', '指数基金']], ['伊斯兰债券和债券', '固定或半固定收益工具，风险通常低于股票。', ['政府债券', '公司债券', '短期债券']], ['房地产', '购买房产以获得租金或价值增长。', ['出租公寓', '土地', '商铺', '房地产基金']], ['黄金和金属', '常用于保护资产和分散投资组合。', ['24K黄金', '金条', '黄金基金', '白银']], ['小型企业', '直接投资商业活动或服务。', ['网店', '小餐厅', '数字服务', '家庭生意']], ['教育和技能', '投资自己以提高未来收入。', ['职业课程', '语言', '编程', '销售和营销']], ['数字资产', '波动较高，需要谨慎和知识。', ['比特币', '以太坊', '加密相关基金']]] },
};
export default function InvestmentEducationPage() {
  const [language, setLanguage] = useState<Language>('ar');
  const t = content[language];
  const isArabic = language === 'ar';
  return (
    <main dir={isArabic ? 'rtl' : 'ltr'} className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-blue-100 px-4 py-8 text-slate-900">
      <div className="mx-auto max-w-5xl space-y-6">
        <div className="rounded-3xl bg-blue-950 p-6 text-white shadow-xl">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <Link href="/" className="text-sm text-blue-100 hover:text-white">{t.back}</Link>
            <Select value={language} onValueChange={(value) => setLanguage(value as Language)}><SelectTrigger className="w-[150px] border-white/20 bg-white/10 text-white [&>span]:text-white"><Languages className="h-4 w-4 me-2" /><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ar">العربية</SelectItem><SelectItem value="en">English</SelectItem><SelectItem value="fr">Français</SelectItem><SelectItem value="zh">中文</SelectItem></SelectContent></Select>
          </div>
          <h1 className="mt-4 text-4xl font-bold">{t.title}</h1>
          <p className="mt-3 max-w-3xl text-blue-100">{t.intro}</p>
        </div>
        <section className="grid gap-4 md:grid-cols-2">{t.items.map(([title, desc, examples]) => (<article key={title as string} className="rounded-2xl border border-blue-100 bg-white p-5 shadow-sm"><h2 className="text-2xl font-bold text-blue-900">{title as string}</h2><p className="mt-2 text-slate-700">{desc as string}</p><div className="mt-4 flex flex-wrap gap-2">{(examples as string[]).map((example) => <span key={example} className="rounded-full bg-blue-50 px-3 py-1 text-sm font-medium text-blue-800">{example}</span>)}</div></article>))}</section>
        <div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-amber-900"><h2 className="text-xl font-bold">{t.tipsTitle}</h2><ul className="mt-3 list-disc space-y-2 ps-6">{t.tips.map((tip) => <li key={tip}>{tip}</li>)}</ul></div>
      </div>
    </main>
  );
}
