import type { Asset, CaseId, EventKind, Factor, Horizon, Regime, Template } from '../../domain/macro-simulator/engine';
export type Language = 'ar' | 'en' | 'fr';
type Label = Record<Language, string>;
export const copy = {
  title: { ar: 'مختبر المحاكاة الاقتصادية', en: 'Macro Simulation Lab', fr: 'Laboratoire de simulation macro' },
  subtitle: { ar: 'غيّر الافتراضات. تتبّع الأثر. اختبر قرارك.', en: 'Change assumptions. Trace the impact. Test your reasoning.', fr: 'Changez les hypothèses. Suivez les effets. Testez votre raisonnement.' },
  badge: { ar: 'نسخة تعليمية تجريبية', en: 'Educational beta', fr: 'Bêta pédagogique' },
  disclaimer: { ar: 'كل النتائج هنا افتراضية بمعاملات تعليمية غير معايرة. ليست أسعاراً حية أو توقعات أو توصيات استثمارية.', en: 'All outputs are hypothetical, using uncalibrated educational coefficients. No live prices, forecasts or investment recommendations.', fr: 'Résultats hypothétiques fondés sur des coefficients pédagogiques non calibrés. Ni cours en direct, ni prévisions, ni conseils d’investissement.' },
  lab: { ar: 'مختبر السيناريو', en: 'Scenario lab', fr: 'Scénarios' },
  challenge: { ar: 'تحدٍّ تعليمي', en: 'Learning challenge', fr: 'Défi pédagogique' },
  method: { ar: 'المنهجية والحدود', en: 'Method & limitations', fr: 'Méthode et limites' },
  save: { ar: 'حفظ في هذا التبويب', en: 'Save in this tab', fr: 'Enregistrer dans cet onglet' },
  load: { ar: 'استعادة المحفوظ', en: 'Restore saved scenario', fr: 'Restaurer le scénario' },
  export: { ar: 'تصدير السيناريو', en: 'Export scenario', fr: 'Exporter le scénario' },
  import: { ar: 'استيراد JSON', en: 'Import JSON', fr: 'Importer un JSON' },
  saved: { ar: 'حُفظت الافتراضات في هذا التبويب فقط، وليس في حسابك السحابي.', en: 'Assumptions saved in this tab only, not to your cloud account.', fr: 'Hypothèses enregistrées dans cet onglet seulement, pas dans votre compte cloud.' },
  loaded: { ar: 'تمت الاستعادة. شغّل المحاكاة لحساب النتائج من جديد.', en: 'Restored. Run the simulation to calculate fresh outputs.', fr: 'Restauré. Lancez la simulation pour recalculer les résultats.' },
  noSave: { ar: 'لا يوجد سيناريو محفوظ في هذا التبويب.', en: 'No saved scenario in this tab.', fr: 'Aucun scénario enregistré dans cet onglet.' },
  invalid: { ar: 'تحقق من القيم وحدودها ومجموع الأوزان. للاستيراد استخدم ملفاً صالحاً من هذا الإصدار.', en: 'Check values, limits and weights. Imports must be valid files from this model version.', fr: 'Vérifiez les valeurs, limites et pondérations. Le fichier doit correspondre à cette version du modèle.' },
  storageError: { ar: 'تعذر الحفظ أو التصدير في المتصفح. لم تُغيّر بيانات حسابك.', en: 'Browser storage or export failed. Your account data is unchanged.', fr: 'Échec du stockage ou de l’export. Les données de votre compte sont inchangées.' },
  presets: { ar: 'ابدأ بتمرين جاهز', en: 'Start with an exercise', fr: 'Choisissez un exercice' },
  builder: { ar: 'ابنِ الحدث', en: 'Build the event', fr: 'Construisez l’événement' },
  scenarioName: { ar: 'اسم السيناريو', en: 'Scenario name', fr: 'Nom du scénario' },
  untitled: { ar: 'سيناريو مخصص', en: 'Custom scenario', fr: 'Scénario personnalisé' },
  time: { ar: 'وقت الحدث الافتراضي — الكويت UTC+3', en: 'Hypothetical event time — Kuwait UTC+3', fr: 'Heure fictive — Koweït UTC+3' },
  timeNote: { ar: 'لترتيب السيناريو فقط؛ لا يضيف حدثاً حقيقياً أو تنبيهاً مجدولاً.', en: 'Scenario metadata only; this does not create a real event or scheduled alert.', fr: 'Métadonnée uniquement ; aucun événement réel ni alerte programmée.' },
  world: { ar: 'حالة العالم المفترضة', en: 'Assumed macro environment', fr: 'Environnement macro supposé' },
  worldNote: { ar: 'اختيارك افتراض للتمرين، وليس قراءة للاقتصاد الحالي.', en: 'Your choice is an exercise assumption, not a reading of today’s economy.', fr: 'Votre choix est une hypothèse, pas une mesure de l’économie actuelle.' },
  event: { ar: 'نوع الصدمة', en: 'Shock type', fr: 'Type de choc' },
  magnitude: { ar: 'حجم التغيّر المفترض', en: 'Assumed change', fr: 'Variation supposée' },
  expected: { ar: 'التغيّر الذي كان متوقعاً', en: 'Previously expected change', fr: 'Variation attendue avant l’annonce' },
  priced: { ar: 'النسبة المسعّرة مسبقاً', en: 'Already priced in', fr: 'Déjà intégré dans les cours' },
  rateNote: { ar: 'مفاجأة الفائدة = التغيّر المعلن ناقص المتوقع. 25 نقطة أساس = 0.25 نقطة مئوية.', en: 'Rate surprise = announced change minus expected change. 25 basis points = 0.25 percentage points.', fr: 'Surprise de taux = variation annoncée moins variation attendue. 25 points de base = 0,25 point de pourcentage.' },
  goldNote: { ar: 'رفع الذهب وحده لا يثبت سبباً لهبوط الدولار أو النفط؛ هذا التمرين لا يفرض عليهما حركة.', en: 'A gold price change alone does not establish a cause for USD or oil to move; this exercise imposes no such link.', fr: 'Un mouvement de l’or seul ne prouve aucun effet causal sur le dollar ou le pétrole ; cet exercice n’impose pas ce lien.' },
  add: { ar: 'أضف صدمة أخرى', en: 'Add another shock', fr: 'Ajouter un choc' },
  remove: { ar: 'إزالة', en: 'Remove', fr: 'Retirer' },
  notes: { ar: 'فرضيتك وملاحظاتك', en: 'Your thesis and notes', fr: 'Votre hypothèse et vos notes' },
  notesHelp: { ar: 'النص للتوثيق فقط. الحساب يعتمد على الحقول الرقمية، ولا يُحلّل النص بالذكاء الاصطناعي في هذه النسخة.', en: 'Notes are documentation only. Calculations use numeric controls; this version does not interpret text with AI.', fr: 'Notes documentaires uniquement. Les calculs utilisent les champs numériques, sans interprétation du texte par IA.' },
  horizon: { ar: 'الأفق الافتراضي', en: 'Hypothetical horizon', fr: 'Horizon hypothétique' },
  portfolio: { ar: 'محفظتك الافتراضية', en: 'Your virtual portfolio', fr: 'Votre portefeuille fictif' },
  capital: { ar: 'رأس المال الافتراضي — USD', en: 'Virtual capital — USD', fr: 'Capital fictif — USD' },
  total: { ar: 'مجموع الأوزان', en: 'Total allocation', fr: 'Allocation totale' },
  weights: { ar: 'يجب أن يكون مجموع الأوزان 100%. لا نعدّلها تلقائياً.', en: 'Weights must sum to 100%. They are never silently normalized.', fr: 'Les pondérations doivent totaliser 100 %. Aucun ajustement automatique.' },
  run: { ar: 'تشغيل المحاكاة', en: 'Run simulation', fr: 'Lancer la simulation' },
  reset: { ar: 'إعادة الضبط', en: 'Reset', fr: 'Réinitialiser' },
  empty: { ar: 'جاهز للتجربة؟ اختر الافتراضات ثم شغّل المحاكاة.', en: 'Ready to explore? Choose assumptions and run the simulation.', fr: 'Prêt à explorer ? Choisissez les hypothèses et lancez la simulation.' },
  stale: { ar: 'تغيّرت المدخلات. النتائج المعروضة تخص التشغيل السابق؛ أعد التشغيل لتحديثها.', en: 'Inputs changed. Displayed results belong to the previous run; rerun to update.', fr: 'Les entrées ont changé. Les résultats affichés sont ceux du calcul précédent ; relancez la simulation.' },
  results: { ar: 'مسارات بديلة، لا مستقبل مؤكد', en: 'Alternative paths, not a certain future', fr: 'Trajectoires alternatives, pas un avenir certain' },
  noProbability: { ar: 'لا تمثل هذه المسارات احتمالات أو فواصل ثقة؛ هي اختبارات حساسية مختلفة.', en: 'These paths are sensitivity tests, not probabilities or confidence intervals.', fr: 'Ces trajectoires sont des tests de sensibilité, pas des probabilités ni des intervalles de confiance.' },
  portfolioImpact: { ar: 'أثر افتراضي على المحفظة', en: 'Hypothetical portfolio impact', fr: 'Effet hypothétique sur le portefeuille' },
  markets: { ar: 'استجابة الأصول في المسار المرجعي', en: 'Reference-path asset responses', fr: 'Réactions des actifs : trajectoire de référence' },
  simulated: { ar: 'تغيّر افتراضي', en: 'Hypothetical change', fr: 'Variation hypothétique' },
  transmission: { ar: 'خريطة انتقال الصدمة', en: 'Shock transmission map', fr: 'Transmission du choc' },
  transmissionNote: { ar: 'اتجاهات مفترضة داخل النموذج، وليست علاقات سببية مثبتة أو قراءات حية.', en: 'Assumed model channels, not proven causal relationships or live readings.', fr: 'Canaux supposés du modèle, pas des relations causales prouvées ni des données en direct.' },
  positive: { ar: 'ضغط صعودي', en: 'Upward pressure', fr: 'Pression haussière' },
  negative: { ar: 'ضغط هبوطي', en: 'Downward pressure', fr: 'Pression baissière' },
  neutral: { ar: 'لا أثر صافٍ', en: 'No net effect', fr: 'Pas d’effet net' },
  timeline: { ar: 'مسار الأثر عبر الزمن', en: 'Impact through time', fr: 'Évolution de l’effet' },
  timelineNote: { ar: 'منحنيات تعليمية مُنشأة، لا تاريخ سعري ولا توقع. المحطات الزمنية فئات غير متساوية المدة.', en: 'Constructed teaching curves, not price history or forecasts. Time checkpoints are unequally spaced categories.', fr: 'Courbes pédagogiques construites, ni historique ni prévisions. Les étapes sont des catégories de durées inégales.' },
  chartAsset: { ar: 'الأصل المعروض', en: 'Displayed asset', fr: 'Actif affiché' },
  chartTable: { ar: 'عرض بيانات الرسم كجدول', en: 'View chart data as a table', fr: 'Afficher les données en tableau' },
  now: { ar: 'قبل الحدث', en: 'Before event', fr: 'Avant l’événement' },
  interpreter: { ar: 'مفسّر SFM التعليمي', en: 'SFM educational interpreter', fr: 'Interprète pédagogique SFM' },
  ruleBased: { ar: 'تفسير قائم على قواعد معلنة — ليس جواب ذكاء اصطناعي.', en: 'Explanation from disclosed rules — not an AI-generated answer.', fr: 'Explication fondée sur des règles déclarées — pas une réponse générée par IA.' },
  reversal: { ar: 'ما الذي قد يعكس النتيجة؟', en: 'What could reverse the result?', fr: 'Qu’est-ce qui pourrait inverser le résultat ?' },
  reversalText: { ar: 'اختلاف التوقعات السابقة، نبرة التصريحات، سبب الصدمة، السيولة، والتحوط قد يغيّر الاستجابة. اختبر افتراضاً بديلاً بدلاً من اعتبار المسار المرجعي يقيناً.', en: 'Prior expectations, communication, the cause of the shock, liquidity and hedging can change reactions. Test an alternative assumption rather than treating the reference path as certain.', fr: 'Attentes initiales, communication, cause du choc, liquidité et couverture peuvent modifier les réactions. Testez une autre hypothèse plutôt que de considérer la référence comme certaine.' },
  contribution: { ar: 'مساهمة الأصول في تغيّر المحفظة — نقاط مئوية', en: 'Contribution to portfolio change — percentage points', fr: 'Contribution à la variation du portefeuille — points de pourcentage' },
  pin: { ar: 'ثبّت التشغيل للمقارنة', en: 'Pin this run for comparison', fr: 'Épingler ce calcul pour comparaison' },
  comparison: { ar: 'مقارنة التشغيل المثبّت', en: 'Pinned-run comparison', fr: 'Comparaison avec le calcul épinglé' },
  incomparable: { ar: 'للمقارنة المباشرة، استخدم رأس المال والأوزان والأفق أنفسها.', en: 'Direct comparison requires identical capital, weights and horizon.', fr: 'Une comparaison directe exige les mêmes capital, pondérations et horizon.' },
  delta: { ar: 'فرق أثر المحفظة — نقاط مئوية', en: 'Portfolio impact difference — percentage points', fr: 'Écart d’effet sur le portefeuille — points de pourcentage' },
  challengeTitle: { ar: 'توقّع قبل كشف النتيجة', en: 'Reason before revealing', fr: 'Raisonnez avant de révéler' },
  challengeText: { ar: 'اختر اتجاه الذهب في النموذج، واكتب سببك ثم اكشف المسار. لا يوجد مال حقيقي أو تقييم لقدرتك على توقع السوق.', en: 'Choose the model’s gold direction, write your reasoning, then reveal. No real money or assessment of market-prediction skill.', fr: 'Choisissez le sens de l’or dans le modèle, justifiez puis révélez. Ni argent réel, ni évaluation de votre capacité à prévoir le marché.' },
  guess: { ar: 'توقّعي للذهب', en: 'My gold hypothesis', fr: 'Mon hypothèse pour l’or' },
  choose: { ar: 'اختر اتجاهًا', en: 'Choose a direction', fr: 'Choisissez un sens' },
  reveal: { ar: 'كشف النتيجة التعليمية', en: 'Reveal teaching outcome', fr: 'Révéler le résultat pédagogique' },
  matched: { ar: 'تطابق اختيارك مع اتجاه النموذج المرجعي. هذا ليس دليلاً على دقة توقع السوق.', en: 'Your choice matched the reference model. This is not evidence of market forecasting accuracy.', fr: 'Votre choix correspond au modèle de référence. Cela ne prouve pas une précision de prévision du marché.' },
  unmatched: { ar: 'اختلف اختيارك عن النموذج المرجعي. راجع افتراضات انتقال الأثر؛ النموذج ليس حكماً على صحة قرار حقيقي.', en: 'Your choice differed from the reference model. Review its transmission assumptions; it does not judge real-world decisions.', fr: 'Votre choix diffère du modèle de référence. Examinez ses hypothèses ; il ne juge pas une décision réelle.' },
  challengeRequired: { ar: 'اختر اتجاهاً واكتب سببك قبل كشف النتيجة.', en: 'Choose a direction and write your reasoning before revealing.', fr: 'Choisissez un sens et justifiez avant de révéler.' },
  noLive: { ar: 'البيانات الحية: غير مرتبطة', en: 'Live data: not connected', fr: 'Données en direct : non connectées' },
  noCalibration: { ar: 'المعايرة الإحصائية: غير متوفرة', en: 'Statistical calibration: unavailable', fr: 'Calibration statistique : indisponible' },
  noConfidence: { ar: 'احتمالات النتائج: لا تُحسب', en: 'Outcome probabilities: not calculated', fr: 'Probabilités : non calculées' },
  methodologyText: { ar: 'نحسب مفاجأة الحدث، ثم نجمعها عبر قنوات مفترضة، ثم نطبق معاملات حساسية الأصول. المسارات تغيّر قوة الأثر إلى 0.55 و1 و1.6 من المرجع؛ ليست متفائلة أو متشائمة لجميع المحافظ.', en: 'Event surprises feed assumed channels, then asset sensitivities. Paths scale impact by 0.55, 1 and 1.6; none is universally optimistic or pessimistic for every portfolio.', fr: 'Les surprises alimentent des canaux supposés puis des sensibilités d’actifs. Les trajectoires multiplient l’effet par 0.55, 1 et 1.6 ; aucune n’est optimiste ou pessimiste pour tous les portefeuilles.' },
  limitations: { ar: 'القيود: تقريب خطي، أوزان ثابتة، بلا رسوم أو ضرائب أو توزيعات أو رافعة. نقد USD ثابت اسمياً ولا يتبع مؤشر الدولار. السندات تمثل تغيّر السعر لا العائد. النواتج محدودة بين -95% و+200% كحاجز حسابي، لا كحد لخسارة السوق.', en: 'Limits: linear approximation, fixed weights, no fees, taxes, dividends or leverage. USD cash is nominally constant and does not track the dollar index. Bonds represent price returns, not yields. Outputs are clipped to -95%/+200% as a computational guard, not a market loss bound.', fr: 'Limites : approximation linéaire, pondérations fixes, sans frais, impôts, dividendes ni levier. Le cash USD reste constant et ne suit pas l’indice dollar. Les obligations représentent une variation de prix, non un rendement actuariel. Bornes -95 %/+200 % : garde-fou de calcul, pas limites du marché.' },
  coefficients: { ar: 'معاملات الحساسية التعليمية', en: 'Educational sensitivity coefficients', fr: 'Coefficients pédagogiques de sensibilité' },
  sourceNote: { ar: 'مرجع بحثي لفكرة فصل القرار عن مسار السياسة المتوقع؛ لا يثبت معاملات هذا النموذج.', en: 'Research background for distinguishing policy decisions from expected policy paths; it does not validate this model’s coefficients.', fr: 'Référence sur la distinction entre décision et trajectoire anticipée ; elle ne valide pas les coefficients du modèle.' },
  roadmap: { ar: 'المرحلة التالية — غير مفعّلة حالياً', en: 'Next stage — not enabled yet', fr: 'Prochaine étape — non activée' },
  roadmapText: { ar: 'إعادة أحداث تاريخية ببيانات مؤرخة، معايرة واختبار خارج العينة، ربط مصادر السوق، وتحليل النص بالذكاء الاصطناعي. لن تُعرض كميزات مكتملة قبل تنفيذها والتحقق منها.', en: 'Point-in-time historical replay, calibration and out-of-sample testing, market-data adapters and AI text interpretation. These are not complete features yet.', fr: 'Rejeu historique avec données disponibles à l’époque, calibration et tests hors échantillon, sources de marché et interprétation IA. Ces fonctions ne sont pas encore réalisées.' },
  engines: { ar: 'استكشف محركات SFM الحالية', en: 'Explore existing SFM engines', fr: 'Explorer les moteurs SFM existants' },
  goldEngine: { ar: 'محرك الذهب', en: 'Gold engine', fr: 'Moteur de l’or' },
  oilEngine: { ar: 'محرك النفط', en: 'Oil engine', fr: 'Moteur du pétrole' },
  connectionsNote: { ar: 'روابط انتقال فقط؛ هذه النسخة لا تستورد بيانات المحركين.', en: 'Navigation links only; this version does not import their data.', fr: 'Liens de navigation uniquement ; cette version n’importe pas leurs données.' },
} satisfies Record<string, Label>;
export type CopyKey = keyof typeof copy;
export const assetLabels: Record<Asset, Label> = {
  gold: { ar: 'الذهب', en: 'Gold', fr: 'Or' }, silver: { ar: 'الفضة', en: 'Silver', fr: 'Argent' },
  oil: { ar: 'النفط', en: 'Oil', fr: 'Pétrole' }, usd: { ar: 'مؤشر الدولار — تمثيلي', en: 'USD index — proxy', fr: 'Indice USD — proxy' },
  equities: { ar: 'الأسهم العالمية', en: 'Global equities', fr: 'Actions mondiales' }, bonds: { ar: 'سعر السندات', en: 'Bond prices', fr: 'Prix obligataires' },
  gcc: { ar: 'أسهم الخليج — تمثيلية', en: 'GCC equities — proxy', fr: 'Actions du Golfe — proxy' }, crypto: { ar: 'العملات الرقمية', en: 'Crypto', fr: 'Crypto' },
  cash: { ar: 'نقد بالدولار', en: 'USD cash', fr: 'Liquidités USD' },
};
export const eventLabels: Record<EventKind, Label> = {
  rates: { ar: 'قرار الفائدة', en: 'Rate decision', fr: 'Décision de taux' }, inflation: { ar: 'مفاجأة التضخم', en: 'Inflation surprise', fr: 'Surprise d’inflation' },
  oilSupply: { ar: 'صدمة نفط من جانب العرض', en: 'Supply-driven oil shock', fr: 'Choc pétrolier lié à l’offre' }, growth: { ar: 'مفاجأة النمو', en: 'Growth surprise', fr: 'Surprise de croissance' },
  risk: { ar: 'تغيّر النفور من المخاطرة', en: 'Risk-aversion shift', fr: 'Variation de l’aversion au risque' }, gold: { ar: 'تحريك الذهب فقط', en: 'Gold-only price exercise', fr: 'Exercice sur l’or seul' },
};
export const units: Record<EventKind, Label> = {
  rates: { ar: 'نقطة أساس', en: 'basis points', fr: 'points de base' }, inflation: { ar: 'نقطة مئوية', en: 'percentage points', fr: 'points de pourcentage' },
  oilSupply: { ar: '%', en: '%', fr: '%' }, growth: { ar: 'نقطة مئوية', en: 'percentage points', fr: 'points de pourcentage' },
  risk: { ar: 'وحدات افتراضية', en: 'stylized units', fr: 'unités fictives' }, gold: { ar: '%', en: '%', fr: '%' },
};
export const templateLabels: Record<Template, Label> = {
  hike: { ar: 'رفع الفائدة', en: 'Rate hike', fr: 'Hausse des taux' }, cut: { ar: 'خفض الفائدة', en: 'Rate cut', fr: 'Baisse des taux' },
  supply: { ar: 'صدمة النفط', en: 'Oil supply shock', fr: 'Choc pétrolier' }, inflation: { ar: 'تضخم مفاجئ', en: 'Inflation surprise', fr: 'Inflation surprise' },
  recession: { ar: 'تباطؤ النمو', en: 'Growth slowdown', fr: 'Ralentissement' }, risk: { ar: 'نفور من المخاطرة', en: 'Risk aversion', fr: 'Aversion au risque' },
  compound: { ar: 'اصنع أزمة مركّبة', en: 'Build a compound crisis', fr: 'Crise composée' }, gold: { ar: 'ماذا لو ارتفع الذهب؟', en: 'What if gold rises?', fr: 'Et si l’or montait ?' },
};
export const regimeLabels: Record<Regime, Label> = {
  balanced: { ar: 'بيئة متوازنة', en: 'Balanced environment', fr: 'Environnement équilibré' },
  inflationary: { ar: 'ضغط تضخمي', en: 'Inflationary pressure', fr: 'Pression inflationniste' },
  recessionary: { ar: 'تباطؤ اقتصادي', en: 'Economic slowdown', fr: 'Ralentissement économique' },
};
export const caseLabels: Record<CaseId, Label> = {
  contained: { ar: 'انتقال محدود', en: 'Contained transmission', fr: 'Transmission limitée' },
  reference: { ar: 'المسار المرجعي', en: 'Reference path', fr: 'Trajectoire de référence' },
  amplified: { ar: 'انتقال مضخّم', en: 'Amplified transmission', fr: 'Transmission amplifiée' },
};
export const factorLabels: Record<Factor, Label> = {
  yields: { ar: 'عوائد السندات', en: 'Bond yields', fr: 'Taux obligataires' }, prices: { ar: 'ضغط الأسعار', en: 'Price pressure', fr: 'Pression sur les prix' },
  demand: { ar: 'الطلب والنمو', en: 'Demand & growth', fr: 'Demande et croissance' }, risk: { ar: 'النفور من المخاطرة', en: 'Risk aversion', fr: 'Aversion au risque' },
  dollar: { ar: 'قناة الدولار', en: 'Dollar channel', fr: 'Canal du dollar' },
};
export const horizonLabels: Record<Horizon, Label> = {
  '5m': { ar: '5 دقائق', en: '5 min', fr: '5 min' }, '1h': { ar: 'ساعة', en: '1 hour', fr: '1 heure' }, '1d': { ar: 'يوم', en: '1 day', fr: '1 jour' },
  '1w': { ar: 'أسبوع', en: '1 week', fr: '1 semaine' }, '1m': { ar: 'شهر', en: '1 month', fr: '1 mois' }, '3m': { ar: '3 أشهر', en: '3 months', fr: '3 mois' }, '12m': { ar: '12 شهرًا', en: '12 months', fr: '12 mois' },
};
export const explanations: Record<EventKind, Label> = {
  rates: { ar: 'يفصل التمرين بين القرار والمتوقع: حتى رفع الفائدة قد يمثل مفاجأة تيسيرية إذا كان أقل من المتوقع. يمر الأثر المفترض بالعوائد والدولار والسيولة.', en: 'The exercise separates the decision from expectations: even a hike can be a dovish surprise if smaller than expected. Assumed effects pass through yields, USD and liquidity.', fr: 'L’exercice distingue décision et attentes : une hausse inférieure aux attentes peut surprendre dans un sens accommodant. Les canaux supposés incluent taux, dollar et liquidité.' },
  inflation: { ar: 'نفترض هنا أن مفاجأة التضخم تغيّر تسعير الفائدة وضغط الأسعار والطلب. غيّر البيئة الاقتصادية لترى حساسية النتيجة لهذا الافتراض.', en: 'Here we assume inflation surprises change rate pricing, price pressure and demand. Change the macro environment to inspect sensitivity to that assumption.', fr: 'Nous supposons ici que l’inflation modifie taux anticipés, pression des prix et demande. Changez l’environnement pour tester cette hypothèse.' },
  oilSupply: { ar: 'هذه صدمة نفط من جانب العرض، وليست زيادة طلب. نفترض أثراً مباشراً على النفط وأثراً ثانوياً على الأسعار والنمو؛ لا نفرض مكسباً مؤكداً لجميع أسواق الخليج.', en: 'This is an oil supply shock, not stronger demand. We assume direct oil effects and secondary price/growth effects; no guaranteed gain across all GCC markets.', fr: 'Choc d’offre pétrolière, non hausse de demande. Nous supposons des effets directs sur le pétrole et indirects sur prix et croissance, sans gain garanti dans tout le Golfe.' },
  growth: { ar: 'نختبر كيف يغيّر اختلاف النمو المفترض الطلب على الأصول والسلع. السبب والسياسات المصاحبة قد يبدّلان المسار الواقعي.', en: 'We test how an assumed growth surprise changes demand for assets and commodities. Its cause and accompanying policy may alter real-world paths.', fr: 'Nous testons une surprise de croissance et son effet supposé sur actifs et matières premières. Sa cause et les politiques associées peuvent modifier la trajectoire réelle.' },
  risk: { ar: 'النفور من المخاطرة هنا عامل افتراضي. لا نفترض تلقائياً تعطل إمدادات النفط؛ أضف صدمة عرض مستقلة لتجربة ذلك.', en: 'Risk aversion is a stylized factor here. We do not automatically assume disrupted oil supply; add a separate supply shock to test that.', fr: 'L’aversion au risque est un facteur fictif. Aucune perturbation pétrolière automatique ; ajoutez un choc d’offre séparé pour la tester.' },
  gold: { ar: 'هذا اختبار أثر الذهب على المحفظة فقط. لا ينتج عنه تلقائياً هبوط الدولار أو النفط، لأن تزامن الأسعار لا يثبت السببية.', en: 'This tests gold exposure in the portfolio only. USD and oil do not automatically fall; coincident price changes do not establish causation.', fr: 'Cet exercice teste seulement l’exposition à l’or. Dollar et pétrole ne baissent pas automatiquement ; la simultanéité ne prouve pas la causalité.' },
};
