export type GameLanguage = 'ar' | 'en' | 'fr';
export const modeCopy = {
  navigation: { ar: 'أوضاع المحاكاة', en: 'Simulation modes', fr: 'Modes de simulation' },
  lab: { ar: 'مختبر السيناريوهات', en: 'Scenario lab', fr: 'Laboratoire de scénarios' },
  game: { ar: 'لعبة القرارات', en: 'Decision game', fr: 'Jeu de décisions' },
} as const satisfies Record<string, Record<GameLanguage, string>>;
export const gameCopy = {
  title: { ar: 'قرارك قبل الحدث. تعلّم بعده.', en: 'Decide first. Reflect afterwards.', fr: 'Décidez, puis analysez.' },
  subtitle: { ar: '3 جولات تعليمية متتابعة: تثبيت القرار، كشف الأثر الافتراضي، ثم مراجعة السبب والمخاطر.', en: '3 sequential learning rounds: lock a decision, reveal the hypothetical impact, then review your reasoning and risks.', fr: '3 manches pédagogiques : figez une décision, révélez son effet hypothétique, puis examinez votre raisonnement et les risques.' },
  disclaimer: { ar: 'لعبة بنموذج تعليمي غير معاير. ليست أسعاراً حقيقية أو توقعات أو توصية استثمارية، ولا تقيس مهارتك في التداول.', en: 'An uncalibrated educational game. Not real prices, forecasts, investment advice or a measure of trading skill.', fr: 'Jeu pédagogique non calibré. Ni cours réels, ni prévisions, ni conseil financier, ni mesure de compétence en trading.' },
  local: { ar: 'الجلسة في ذاكرة هذه الصفحة فقط؛ الخروج أو التحديث أو تبديل الحساب يمسحها. لا توجد أوامر تداول أو رسوم أو حفظ سحابي.', en: 'This session lives in page memory only; leaving, reloading or changing account clears it. No trades, charges or cloud storage.', fr: 'Session en mémoire de cette page uniquement ; quitter, actualiser ou changer de compte l’efface. Aucun ordre, frais ou stockage cloud.' },
  capital: { ar: 'رأس المال الافتراضي (USD)', en: 'Virtual starting capital (USD)', fr: 'Capital initial virtuel (USD)' },
  start: { ar: 'ابدأ الجلسة', en: 'Start session', fr: 'Commencer la session' },
  round: { ar: 'الجولة', en: 'Round', fr: 'Manche' },
  known: { ar: 'الافتراضات المتاحة قبل قرارك', en: 'Assumptions available before your decision', fr: 'Hypothèses connues avant votre décision' },
  context: { ar: 'بيئة النموذج', en: 'Model context', fr: 'Contexte du modèle' },
  horizon: { ar: 'أفق كل صدمة: يوم واحد افتراضي', en: 'Each shock horizon: one hypothetical day', fr: 'Horizon de chaque choc : un jour hypothétique' },
  incremental: { ar: 'كل جولة صدمة جديدة مستقلة، وتتراكم قيمة الحيازات فقط. هذا ليس مساراً اقتصادياً مستمراً أو إعادة لحدث تاريخي.', en: 'Each round is a new independent shock; only holding values carry forward. This is not a continuous economic path or historical replay.', fr: 'Chaque manche est un nouveau choc indépendant ; seules les valeurs des positions sont reportées. Ce n’est ni une trajectoire économique continue ni une relecture historique.' },
  hold: { ar: 'احتفظ بالحيازات', en: 'Keep holdings', fr: 'Conserver les positions' },
  rebalance: { ar: 'عدّل التوزيع', en: 'Rebalance allocation', fr: 'Rééquilibrer' },
  action: { ar: 'قرار هذه الجولة', en: 'This round’s decision', fr: 'Décision de cette manche' },
  allocation: { ar: 'توزيع الأصول', en: 'Asset allocation', fr: 'Allocation des actifs' },
  allocationNote: { ar: 'نسب التحرير مقربة إلى 0.01%. لا تُطبّق إلا عند اختيار تعديل التوزيع. الاحتفاظ لا ينفذ إعادة موازنة.', en: 'Editable weights are rounded to 0.01% and apply only when rebalancing. Keeping holdings does not rebalance.', fr: 'Les poids modifiables sont arrondis à 0,01 % et ne s’appliquent qu’au rééquilibrage. Conserver les positions ne les rééquilibre pas.' },
  total: { ar: 'المجموع', en: 'Total', fr: 'Total' },
  rationale: { ar: 'سبب القرار والمخاطر التي تراقبها', en: 'Decision rationale and risks to watch', fr: 'Raisonnement et risques à surveiller' },
  rationaleHint: { ar: 'اكتب من 10 إلى 600 حرف قبل كشف النتيجة. هذا توثيق لتفكيرك، وليس تقييماً آلياً لجودته.', en: 'Write 10–600 characters before revealing. This records your reasoning; it does not automatically grade its quality.', fr: 'Écrivez 10 à 600 caractères avant la révélation. Votre raisonnement est consigné, sans notation automatique de sa qualité.' },
  reveal: { ar: 'ثبّت القرار واكشف النتيجة', en: 'Lock decision and reveal', fr: 'Figer la décision et révéler' },
  locked: { ar: 'القرار مثبت. لا يمكن تعديله بعد كشف هذه الجولة.', en: 'Decision locked. It cannot be edited after this round is revealed.', fr: 'Décision figée. Elle ne peut plus être modifiée après la révélation de cette manche.' },
  outcome: { ar: 'نتيجة الجولة الافتراضية', en: 'Hypothetical round result', fr: 'Résultat hypothétique de la manche' },
  pathNote: { ar: 'المسار المرجعي وحده يُضاف إلى الرصيد. المساران الآخران لاختبار الحساسية، بلا احتمالات أو ضمانات.', en: 'Only the reference path is credited to the balance. The other paths are sensitivity tests, without probabilities or guarantees.', fr: 'Seule la trajectoire de référence est créditée au solde. Les autres sont des tests de sensibilité, sans probabilités ni garanties.' },
  next: { ar: 'انتقل للجولة التالية', en: 'Next round', fr: 'Manche suivante' },
  finish: { ar: 'اعرض مراجعة الجلسة', en: 'Review session', fr: 'Bilan de la session' },
  finished: { ar: 'اكتملت الجلسة التعليمية', en: 'Learning session complete', fr: 'Session pédagogique terminée' },
  current: { ar: 'قيمة محفظتك الافتراضية', en: 'Your virtual portfolio value', fr: 'Valeur de votre portefeuille virtuel' },
  cumulative: { ar: 'التغير التراكمي في النموذج', en: 'Cumulative model change', fr: 'Variation cumulée du modèle' },
  benchmark: { ar: 'الاحتفاظ بالحيازات الأولية دون تداول', en: 'Initial holdings, without trading', fr: 'Positions initiales, sans transaction' },
  benchmarkNote: { ar: 'المقارنة تبدأ بالحيازات نفسها، ثم تحتفظ بها وتتغير أوزانها طبيعياً في كل جولة. لا تعيد الموازنة إلى النسب الأولى.', en: 'The comparator starts with identical holdings, then lets their weights drift each round. It never rebalances back to initial percentages.', fr: 'Le comparateur commence avec les mêmes positions, puis laisse leurs poids évoluer. Aucun rééquilibrage vers les pourcentages initiaux.' },
  difference: { ar: 'فرق القيمة عن الاحتفاظ (USD)', en: 'Value difference versus holding (USD)', fr: 'Écart de valeur avec la conservation (USD)' },
  drawdown: { ar: 'أكبر تراجع بين نهايات الجولات', en: 'Largest round-end drawdown', fr: 'Repli maximal entre fins de manche' },
  drawdownNote: { ar: 'مقاس من أرصدة نهايات الجولات فقط، وليس أدنى سعر داخل الجولة أو تقديراً للخسارة المستقبلية.', en: 'Measured only from round-end balances, not intraround lows or future loss estimates.', fr: 'Mesuré uniquement aux fins de manche, sans creux intermédiaires ni estimation de perte future.' },
  chart: { ar: 'مسار الرصيد الافتراضي', en: 'Virtual balance path', fr: 'Trajectoire du solde virtuel' },
  chartNote: { ar: 'بداية الجلسة ثم نتائج الجولات المكشوفة فقط. القيم التفصيلية في السجل أدناه.', en: 'Starting capital followed only by revealed round results. Exact values are in the journal below.', fr: 'Capital initial suivi uniquement des résultats révélés. Les valeurs détaillées figurent dans le journal ci-dessous.' },
  you: { ar: 'محفظتك', en: 'Your portfolio', fr: 'Votre portefeuille' },
  journal: { ar: 'سجل القرارات المثبتة', en: 'Locked decision journal', fr: 'Journal des décisions figées' },
  before: { ar: 'القيمة قبل الجولة', en: 'Value before round', fr: 'Valeur avant la manche' },
  after: { ar: 'القيمة بعد الجولة', en: 'Value after round', fr: 'Valeur après la manche' },
  contribution: { ar: 'مساهمة الأصل في التغير (USD)', en: 'Asset contribution to change (USD)', fr: 'Contribution de l’actif à la variation (USD)' },
  assetChange: { ar: 'تغير الأصل في النموذج', en: 'Asset change in model', fr: 'Variation de l’actif dans le modèle' },
  attribution: { ar: 'من أين جاءت النتيجة؟', en: 'Where did the result come from?', fr: 'D’où vient le résultat ?' },
  empty: { ar: 'لن تظهر نتيجة الجولة قبل تثبيت قرارك وسببه.', en: 'No round result appears before you lock your decision and rationale.', fr: 'Aucun résultat avant de figer votre décision et son raisonnement.' },
  reflection: { ar: 'قارن سبب قرارك بما افترضه النموذج، وحدد ما الذي قد يُبطل هذا الافتراض في الواقع. الربح في اللعبة لا يثبت صحة القرار خارجها.', en: 'Compare your rationale with the model assumptions and identify what could invalidate them in reality. A game profit does not validate a real-world decision.', fr: 'Comparez votre raisonnement aux hypothèses et identifiez ce qui pourrait les invalider dans la réalité. Un gain dans le jeu ne valide pas une décision réelle.' },
  reset: { ar: 'جلسة جديدة', en: 'New session', fr: 'Nouvelle session' },
  confirmReset: { ar: 'بدء جلسة جديدة يمسح سجل هذه الجلسة. هل تريد المتابعة؟', en: 'Starting a new session clears this journal. Continue?', fr: 'Une nouvelle session efface ce journal. Continuer ?' },
  confirm: { ar: 'امسح وابدأ من جديد', en: 'Clear and restart', fr: 'Effacer et recommencer' },
  cancel: { ar: 'إلغاء', en: 'Cancel', fr: 'Annuler' },
  weightsError: { ar: 'أدخل نسباً صالحة بين 0 و100 ومجموعها 100% تماماً؛ لا نعدلها تلقائياً.', en: 'Enter valid weights from 0 to 100 summing to exactly 100%; they are not adjusted automatically.', fr: 'Saisissez des poids de 0 à 100 totalisant exactement 100 % ; aucun ajustement automatique.' },
  rationaleError: { ar: 'سجّل سبباً من 10 إلى 600 حرف قبل الكشف.', en: 'Record a rationale of 10–600 characters before revealing.', fr: 'Consignez un raisonnement de 10 à 600 caractères avant la révélation.' },
  invalid: { ar: 'تعذر تنفيذ العملية. تحقق من المدخلات وحالة الجولة.', en: 'Action could not be completed. Check the inputs and round state.', fr: 'Action impossible. Vérifiez les données et l’état de la manche.' },
} as const satisfies Record<string, Record<GameLanguage, string>>;
export type GameCopyKey = keyof typeof gameCopy;
export const roundCopy = {
  tightening: {
    title: { ar: 'مفاجأة الفائدة', en: 'Rate surprise', fr: 'Surprise de taux' },
    intro: { ar: 'افتراض تدريبي: رفع بمقدار 50 نقطة أساس مقابل 25 متوقعة، في بيئة متوازنة.', en: 'Training assumption: a 50 bp increase versus 25 bp expected, in a balanced environment.', fr: 'Hypothèse : hausse de 50 points de base contre 25 attendus, dans un environnement équilibré.' },
    lesson: { ar: 'يستخدم النموذج الفرق بين الإعلان والتوقع، لا رقم الرفع وحده. راجع تعرضك للقنوات المفترضة للعوائد والدولار.', en: 'The model uses the announcement minus expectations, not the increase alone. Review exposure to its assumed yield and dollar channels.', fr: 'Le modèle utilise l’écart entre annonce et attentes. Examinez l’exposition aux canaux supposés des rendements et du dollar.' },
  },
  energy: {
    title: { ar: 'صدمة إمدادات الطاقة', en: 'Energy supply shock', fr: 'Choc d’offre énergétique' },
    intro: { ar: 'افتراض تدريبي: صدمة نفط مرتبطة بالإمدادات بمقدار +20%، غير مسعرة مسبقاً، في بيئة تضخمية.', en: 'Training assumption: a +20% supply-related oil shock, not priced in, in an inflationary environment.', fr: 'Hypothèse : choc pétrolier d’offre de +20 %, non anticipé, dans un environnement inflationniste.' },
    lesson: { ar: 'هذه صدمة إمدادات مفترضة، وليست استنتاجاً من ارتفاع النفط وحده. افصل مساهمة النفط المباشرة عن بقية الحيازات.', en: 'This assumes a supply shock; it is not inferred from an oil rise alone. Separate oil’s direct contribution from other holdings.', fr: 'Le choc d’offre est une hypothèse, non une déduction d’une simple hausse du pétrole. Distinguez sa contribution directe des autres positions.' },
  },
  slowdown: {
    title: { ar: 'تباطؤ الطلب', en: 'Demand slowdown', fr: 'Ralentissement de la demande' },
    intro: { ar: 'افتراض تدريبي: صدمة نمو -2 نقطة مئوية، غير مسعرة مسبقاً، في بيئة ركودية.', en: 'Training assumption: a -2 percentage-point growth shock, not priced in, in a recessionary environment.', fr: 'Hypothèse : choc de croissance de -2 points de pourcentage, non anticipé, dans un environnement récessif.' },
    lesson: { ar: 'قارن نتيجة الاحتفاظ بنتيجة أي إعادة توزيع، مع الانتباه إلى أن الرسوم والضرائب والتوزيعات غير محتسبة.', en: 'Compare holding with any reallocation, remembering that fees, taxes and distributions are excluded.', fr: 'Comparez conservation et réallocation, en rappelant que frais, fiscalité et distributions sont exclus.' },
  },
} as const;
