import type { Lang } from '@/lib/translations';

/**
 * Investor Experience copy (phase 2.9). Investor-friendly, concrete, and
 * free of promotional claims — no guaranteed returns, no invented traction.
 * English is the source shape; Arabic and French must cover every key.
 */

const en = {
  eyebrow: 'Investor workspace built from your real project data',
  title: 'Investment Offers',
  subtitle: 'Prepare, review, and share your project with investors: readiness, financials, documents, risks, and secure sharing in one place.',
  loading: 'Loading your investor workspace…',
  partialLoad: 'Some records could not be loaded. Figures shown come only from the data that did load.',
  signInTitle: 'Sign in to open your investor workspace.',
  signInBody: 'Investor materials require an account and saved project data.',
  signIn: 'Sign in',
  noProjectsTitle: 'Add a project first to prepare an investor offer.',
  noProjectsBody: 'The workspace builds everything from a real saved project — nothing is generated from thin air.',
  openProjects: 'Open my projects',
  selectProject: 'Project',
  selectProjectHint: 'Choose the project to prepare for investors.',
  noFakeData: 'No fake investors, offers, or activity are ever shown. Everything here reflects your saved data only.',

  /* Tabs */
  tabOverview: 'Overview',
  tabReadiness: 'Investment Readiness',
  tabFinancials: 'Financials',
  tabDocuments: 'Documents',
  tabPitchDeck: 'Pitch Deck',
  tabRisks: 'Risks',
  tabSharing: 'Sharing',
  tabActivity: 'Investor Activity',

  /* Statuses */
  statusComplete: 'Complete',
  statusPartial: 'Partial',
  statusMissing: 'Missing',
  statusBlocked: 'Blocked',
  statusNeedsReview: 'Needs review',
  statusApproved: 'Approved',
  statusPendingReview: 'Pending review',
  statusExpired: 'Expired',
  statusNeedsUpdate: 'Needs update',
  statusPrivate: 'Private',
  statusShared: 'Shared with investors',
  statusOpen: 'Open',
  statusMitigated: 'Mitigated',
  statusAccepted: 'Accepted',
  statusAnswered: 'Answered',
  statusActive: 'Active',
  statusRevoked: 'Revoked',

  /* Overview */
  overviewReadiness: 'Investment readiness',
  overviewScoreOf: 'of 100',
  overviewFundingTarget: 'Funding target',
  overviewFundingType: 'Funding type',
  overviewMissingItems: 'Missing requirements',
  overviewBlockers: 'Critical blockers',
  overviewLatestActivity: 'Latest investor activity',
  overviewNoActivity: 'No investor activity data is available yet.',
  overviewNextAction: 'Next recommended step',
  overviewAllReady: 'All required investor materials are complete. Review them, then share the offer.',
  overviewValueProposition: 'Value proposition',
  overviewNoValueProposition: 'No project summary has been written yet. A short, clear value proposition is the first thing investors read.',
  overviewProjectStage: 'Project stage',
  overviewLastUpdated: 'Last updated',
  overviewComputedAt: 'Score computed',
  overviewHighlights: 'Key financial figures',

  /* Readiness */
  readinessTitle: 'Project readiness for investment',
  readinessSubtitle: 'A deterministic score computed from your validated data — every point traces back to a named requirement. Nothing is estimated by AI.',
  readinessScore: 'Readiness score',
  readinessBreakdown: 'Category breakdown',
  readinessWeight: 'Weight',
  readinessMissing: 'Missing requirements',
  readinessBlockers: 'Blocking requirements',
  readinessOptional: 'Optional improvements',
  readinessNextAction: 'Recommended next step',
  readinessComplete: 'Complete the missing requirements',
  readinessNoBlockers: 'No blocking requirements.',
  readinessFormulaTitle: 'How this score is calculated',
  readinessFormulaBody: 'Each category has a fixed weight; its completion equals the share of its required checks that pass against saved data. The total is the weighted average, rounded down. The score never reaches 100 unless every required item is genuinely complete.',
  categoryProfile: 'Project profile',
  categoryBusinessModel: 'Business model',
  categoryMarket: 'Market opportunity',
  categoryFinancials: 'Financial data',
  categoryPitchDeck: 'Pitch Deck',
  categoryDocuments: 'Core investor documents',
  categoryRisks: 'Risks',
  categoryFundingRequest: 'Funding request',
  categoryInvestorContact: 'Investor contact readiness',

  /* Check labels (mirror readiness engine check ids) */
  check_profile_name: 'Project name',
  check_profile_description: 'Project description and value',
  check_profile_stage: 'Project stage or status',
  check_profile_sector: 'Project sector',
  check_business_model_value: 'Business model and value proposition',
  check_business_model_revenue_streams: 'Revenue streams',
  check_business_model_operations: 'Operating plan',
  check_market_target_customers: 'Target customers',
  check_market_size: 'Market size',
  check_market_competition: 'Competition and advantage',
  check_financials_model: 'Financial model',
  check_financials_revenue: 'Revenue data',
  check_financials_costs: 'Cost data',
  check_financials_forecast: 'Financial forecast',
  check_financials_assumptions: 'Financial assumptions',
  check_pitch_deck_exists: 'Saved pitch deck',
  check_pitch_deck_half_complete: 'At least half of the slides complete',
  check_pitch_deck_fully_complete: 'All slides complete',
  check_documents_any: 'At least one document',
  check_documents_legal: 'Legal or registration document',
  check_documents_financial: 'Financial statements',
  check_risks_recorded: 'Recorded risks',
  check_risks_mitigation: 'Mitigation for every risk',
  check_funding_amount: 'Requested funding amount',
  check_funding_currency: 'Funding currency',
  check_funding_use_of_funds: 'Use of funds',
  check_funding_type: 'Funding type',
  check_contact_email: 'Investor contact email',
  check_contact_share_link: 'Active investor link',

  /* Financials */
  financialsTitle: 'Financial indicators',
  financialsSubtitle: 'Only figures you saved are shown, each labeled with its source. Nothing is projected on your behalf.',
  financialsEmpty: 'No financial data has been added yet.',
  financialsEmptyBody: 'Add a financial model to your project so investors can review revenue, costs, and forecasts.',
  financialsOpenModel: 'Update financial data',
  financialsRevenueStreams: 'Revenue streams',
  financialsCostItems: 'Cost items',
  financialsForecast: 'Forecast',
  financialsForecastPeriods: 'Forecast periods',
  financialsAssumptions: 'Assumptions',
  financialsKpis: 'Saved indicators',
  financialsFundingTarget: 'Funding target',
  financialsUseOfFunds: 'Use of funds',
  financialsAllocation: 'Allocation',
  financialsAmount: 'Amount',
  financialsCurrency: 'Currency',
  financialsReportingPeriod: 'Reporting period',
  financialsDataSource: 'Source',
  financialsLastUpdate: 'Last update',
  sourceUserEntered: 'User-entered',
  sourceForecast: 'Forecast',
  sourceActual: 'Actual',
  sourceAiAssisted: 'AI-assisted',
  sourceUnavailable: 'Unavailable',
  metricPlannedRevenue: 'Planned monthly revenue',
  metricPlannedCosts: 'Planned monthly costs',
  metricPlannedNet: 'Planned monthly net',
  fundsProduct: 'Product development',
  fundsMarketing: 'Marketing',
  fundsOperations: 'Operations',
  fundsHiring: 'Hiring',
  fundsLicensesLegal: 'Licenses & legal',
  fundsEmergencyReserve: 'Emergency reserve',
  fundsOther: 'Other',

  /* Documents */
  documentsTitle: 'Core investor files',
  documentsSubtitle: 'Documents investors will ask for, organized by category with review status and sharing visibility.',
  documentsEmpty: 'No documents uploaded yet.',
  documentsEmptyBody: 'Upload company, legal, and financial documents from the Business Hub so investors can review them.',
  documentsAdd: 'Add missing documents',
  documentsName: 'File',
  documentsCategory: 'Category',
  documentsUpdated: 'Updated',
  documentsVisibility: 'Visibility',
  documentsOpen: 'Open',
  documentsNoLegal: 'No legal documents uploaded.',
  docCategoryCompany: 'Company documents',
  docCategoryLegal: 'Legal',
  docCategoryFinancial: 'Financial',
  docCategoryMarket: 'Market research',
  docCategoryPitch: 'Pitch Deck',
  docCategoryContracts: 'Contracts',
  docCategoryDiligence: 'Due diligence',
  docCategoryOther: 'Supporting files',

  /* Due diligence */
  diligenceTitle: 'Due-diligence checklist',
  diligenceSubtitle: 'Marked complete only when real evidence exists — a linked document or a written review note.',
  diligenceRequired: 'Required',
  diligenceOptional: 'Optional',
  diligenceEvidence: 'Evidence',
  diligenceNoEvidence: 'No evidence yet',
  diligenceMarkReviewed: 'Mark reviewed',
  diligenceNotePlaceholder: 'Where is the evidence? (document, registry, contract…)',
  diligenceNoteRequired: 'A review note or linked document is required before marking this item reviewed.',
  diligenceLastReview: 'Last review',
  diligenceSaveFailed: 'The checklist item could not be saved.',
  ddGroupIdentity: 'Company identity',
  ddGroupOwnership: 'Ownership',
  ddGroupLegal: 'Legal registration',
  ddGroupFinancialStatements: 'Financial statements',
  ddGroupTax: 'Tax & regulatory',
  ddGroupContracts: 'Contracts',
  ddGroupIp: 'Intellectual property',
  ddGroupLiabilities: 'Liabilities',
  ddGroupRisks: 'Key risks',
  ddGroupFunding: 'Funding structure',

  /* Pitch deck */
  pitchTitle: 'Pitch Deck',
  pitchSubtitle: 'The investor presentation built from your saved project data.',
  pitchStatus: 'Deck status',
  pitchCompletion: 'Completion',
  pitchLanguage: 'Language',
  pitchUpdated: 'Last updated',
  pitchSlides: 'Slides',
  pitchMissingSections: 'Sections needing data',
  pitchOpenBuilder: 'Open the Pitch Deck builder',
  pitchCreate: 'Create the Pitch Deck',
  pitchEmpty: 'The pitch deck has not been created yet.',
  pitchEmptyBody: 'Generate it from your project page — every slide is built from saved data and stays reviewable before saving.',
  pitchAiNote: 'AI-assisted content is always shown for review before it is saved. Nothing is published silently.',

  /* Risks */
  risksTitle: 'Project risks',
  risksSubtitle: 'A transparent risk register with severity, probability, and mitigation. Investors expect honesty here.',
  risksEmpty: 'No risks recorded yet.',
  risksEmptyBody: 'Record the real risks of the project with a mitigation plan for each. A project with no acknowledged risks reads as unprepared.',
  risksAdd: 'Add a risk',
  risksEdit: 'Edit risk',
  risksDelete: 'Delete risk',
  risksTitleField: 'Risk title',
  risksCategory: 'Category',
  risksSeverity: 'Severity',
  risksProbability: 'Probability',
  risksImpact: 'Impact',
  risksMitigation: 'Mitigation plan',
  risksStatus: 'Status',
  risksLastReview: 'Last review',
  risksSave: 'Save risk',
  risksSaving: 'Saving…',
  risksMissingTitle: 'Enter a risk title.',
  risksMissingMitigation: 'No mitigation recorded',
  risksSaveFailed: 'The risk could not be saved.',
  risksDeleteFailed: 'The risk could not be deleted.',
  risksUpdateAction: 'Update project risks',
  riskCategoryMarket: 'Market',
  riskCategoryFinancial: 'Financial',
  riskCategoryOperational: 'Operational',
  riskCategoryLegal: 'Legal',
  riskCategoryRegulatory: 'Regulatory',
  riskCategoryCompetition: 'Competition',
  riskCategoryLiquidity: 'Liquidity',
  riskCategoryTechnology: 'Technology',
  riskCategoryExecution: 'Execution',
  riskCategoryConcentration: 'Concentration',
  severityLow: 'Low',
  severityMedium: 'Medium',
  severityHigh: 'High',
  severityCritical: 'Critical',

  /* Sharing */
  sharingTitle: 'Share with investors',
  sharingSubtitle: 'Create a controlled link: choose what investors see, protect it with a password, set an expiry, and revoke it at any time.',
  sharingCreate: 'Create an investor link',
  sharingLabel: 'Link label',
  sharingLabelPlaceholder: 'e.g. Angel round — first meeting',
  sharingExpiry: 'Expiration date',
  sharingNoExpiry: 'No expiry set',
  sharingPassword: 'Password (optional)',
  sharingPasswordHint: 'At least 6 characters. Investors will need it to open the link.',
  sharingSections: 'Visible sections',
  sharingAllowDownloads: 'Allow document downloads',
  sharingMessage: 'Message to the investor (optional)',
  sharingMessagePlaceholder: 'A short welcome or context for the reviewer.',
  sharingGenerate: 'Create the link',
  sharingGenerating: 'Creating…',
  sharingSectionsRequired: 'Select at least one section to share.',
  sharingCreateFailed: 'The link could not be created.',
  sharingCreated: 'Investor link created. Copy it now — it will not be shown again.',
  sharingCopy: 'Copy link',
  sharingCopied: 'Copied.',
  sharingActiveLinks: 'Investor links',
  sharingNoLinks: 'No investor links created yet.',
  sharingRevoke: 'Revoke access',
  sharingRevokeFailed: 'The link could not be revoked.',
  sharingAccessCount: 'Opens',
  sharingLastAccess: 'Last access',
  sharingExpiresAt: 'Expires',
  sharingPrivateNote: 'Internal notes and private documents are never included in an investor link.',
  sectionOverview: 'Overview',
  sectionReadiness: 'Readiness',
  sectionFinancials: 'Financials',
  sectionDocuments: 'Documents',
  sectionPitchDeck: 'Pitch Deck',
  sectionRisks: 'Risks',

  /* Activity */
  activityTitle: 'Investor activity',
  activitySubtitle: 'Real access events from your investor links. Nothing here is simulated.',
  activityEmpty: 'No investor activity data is available yet.',
  activityEmptyBody: 'Events appear once an investor opens one of your links.',
  activityEventOfferOpened: 'Offer opened',
  activityEventDeckViewed: 'Pitch Deck viewed',
  activityEventDocumentDownloaded: 'Document downloaded',
  activityEventQuestionSubmitted: 'Question submitted',
  activityEventAccessDenied: 'Access denied',
  activityEventLinkRevoked: 'Link revoked',
  activityVia: 'via',
  questionsTitle: 'Investor questions',
  questionsEmpty: 'No investor questions yet.',
  questionsRespond: 'Response',
  questionsInternalNote: 'Internal note (never shown to investors)',
  questionsSave: 'Save response',
  questionsSaveFailed: 'The response could not be saved.',
  questionsAskedBy: 'From',
  questionsStatusLabel: 'Status',

  /* Public viewer */
  viewerLoading: 'Opening the investor offer…',
  viewerPasswordTitle: 'This offer is password-protected',
  viewerPasswordBody: 'Enter the password you received from the project owner.',
  viewerPasswordField: 'Password',
  viewerPasswordSubmit: 'Open the offer',
  viewerPasswordWrong: 'Incorrect password. Try again.',
  viewerExpired: 'This investor link has expired.',
  viewerRevoked: 'Access to this investor link has been revoked.',
  viewerNotFound: 'This investor link does not exist.',
  viewerUnavailable: 'The investor offer could not be loaded right now.',
  viewerMessageTitle: 'Message from the project owner',
  viewerAskTitle: 'Ask the project owner',
  viewerAskField: 'Your question',
  viewerAskName: 'Your name (optional)',
  viewerAskSubmit: 'Send the question',
  viewerAskSent: 'Your question was sent to the project owner.',
  viewerAskFailed: 'The question could not be sent.',
  viewerDisclaimer: 'This page shows project data shared by its owner for review purposes. It is not investment advice and makes no return guarantees.',
  viewerDownload: 'Download',
  viewerNoDownloads: 'Downloads are disabled for this link.',

  /* Generic */
  notRecorded: 'Not recorded',
  updated: 'Updated',
  cancel: 'Cancel',
  close: 'Close',
  confirmDelete: 'Confirm deletion',
  retry: 'Retry',
  loadFailedDocuments: 'The documents could not be loaded.',
  staleData: 'Some data is over a year old and should be reviewed.',
};

export type InvestorCopy = typeof en;

const ar: InvestorCopy = {
  eyebrow: 'مساحة عمل للمستثمرين مبنية من بيانات مشروعك الفعلية',
  title: 'العروض الاستثمارية',
  subtitle: 'جهّز مشروعك وراجعه وشاركه مع المستثمرين: الجاهزية، البيانات المالية، المستندات، المخاطر، والمشاركة الآمنة في مكان واحد.',
  loading: 'جاري تحميل مساحة عمل المستثمر…',
  partialLoad: 'تعذر تحميل بعض السجلات. الأرقام المعروضة مبنية فقط على البيانات التي تم تحميلها.',
  signInTitle: 'سجّل الدخول لفتح مساحة عمل المستثمر.',
  signInBody: 'تتطلب مواد المستثمرين حساباً وبيانات مشاريع محفوظة.',
  signIn: 'تسجيل الدخول',
  noProjectsTitle: 'أضف مشروعاً أولاً لتجهيز عرض استثماري.',
  noProjectsBody: 'تُبنى هذه المساحة بالكامل من مشروع حقيقي محفوظ — لا يُنشأ أي محتوى من فراغ.',
  openProjects: 'فتح مشاريعي',
  selectProject: 'المشروع',
  selectProjectHint: 'اختر المشروع الذي تريد تجهيزه للمستثمرين.',
  noFakeData: 'لا يتم عرض مستثمرين أو عروض أو نشاط وهمي إطلاقاً. كل ما هنا يعكس بياناتك المحفوظة فقط.',

  tabOverview: 'نظرة عامة',
  tabReadiness: 'جاهزية الاستثمار',
  tabFinancials: 'البيانات المالية',
  tabDocuments: 'المستندات',
  tabPitchDeck: 'العرض الاستثماري',
  tabRisks: 'المخاطر',
  tabSharing: 'المشاركة',
  tabActivity: 'نشاط المستثمرين',

  statusComplete: 'مكتمل',
  statusPartial: 'جزئي',
  statusMissing: 'مفقود',
  statusBlocked: 'متوقف على متطلب',
  statusNeedsReview: 'يحتاج مراجعة',
  statusApproved: 'معتمد',
  statusPendingReview: 'بانتظار المراجعة',
  statusExpired: 'منتهي الصلاحية',
  statusNeedsUpdate: 'يحتاج تحديثاً',
  statusPrivate: 'خاص',
  statusShared: 'مشارك مع المستثمرين',
  statusOpen: 'مفتوح',
  statusMitigated: 'تمت معالجته',
  statusAccepted: 'مقبول',
  statusAnswered: 'تمت الإجابة',
  statusActive: 'نشط',
  statusRevoked: 'ملغى',

  overviewReadiness: 'جاهزية المشروع للاستثمار',
  overviewScoreOf: 'من 100',
  overviewFundingTarget: 'التمويل المطلوب',
  overviewFundingType: 'نوع التمويل',
  overviewMissingItems: 'متطلبات ناقصة',
  overviewBlockers: 'عوائق أساسية',
  overviewLatestActivity: 'آخر نشاط للمستثمرين',
  overviewNoActivity: 'لا توجد بيانات نشاط مستثمرين متاحة حالياً',
  overviewNextAction: 'الخطوة التالية الموصى بها',
  overviewAllReady: 'جميع مواد المستثمر المطلوبة مكتملة. راجعها ثم شارك العرض.',
  overviewValueProposition: 'عرض القيمة',
  overviewNoValueProposition: 'لم يُكتب ملخص للمشروع بعد. عرض القيمة القصير والواضح هو أول ما يقرؤه المستثمر.',
  overviewProjectStage: 'مرحلة المشروع',
  overviewLastUpdated: 'آخر تحديث',
  overviewComputedAt: 'وقت احتساب النتيجة',
  overviewHighlights: 'أبرز الأرقام المالية',

  readinessTitle: 'جاهزية المشروع للاستثمار',
  readinessSubtitle: 'نتيجة محسوبة بشكل حتمي من بياناتك المتحقق منها — كل نقطة تعود إلى متطلب محدد بالاسم. لا يقدّر الذكاء الاصطناعي أي جزء منها.',
  readinessScore: 'نتيجة الجاهزية',
  readinessBreakdown: 'تفصيل الفئات',
  readinessWeight: 'الوزن',
  readinessMissing: 'متطلبات ناقصة',
  readinessBlockers: 'متطلبات معطِّلة',
  readinessOptional: 'تحسينات اختيارية',
  readinessNextAction: 'الخطوة التالية الموصى بها',
  readinessComplete: 'أكمل المتطلبات الناقصة',
  readinessNoBlockers: 'لا توجد متطلبات معطِّلة.',
  readinessFormulaTitle: 'كيف تُحسب هذه النتيجة',
  readinessFormulaBody: 'لكل فئة وزن ثابت، ونسبة اكتمالها تساوي نسبة متطلباتها الإلزامية المستوفاة من البيانات المحفوظة. النتيجة الكلية هي المتوسط الموزون مقرّباً للأسفل، ولا تصل إلى 100 إلا إذا اكتمل كل متطلب إلزامي فعلاً.',
  categoryProfile: 'الملف التعريفي للمشروع',
  categoryBusinessModel: 'نموذج العمل',
  categoryMarket: 'فرصة السوق',
  categoryFinancials: 'البيانات المالية',
  categoryPitchDeck: 'العرض الاستثماري',
  categoryDocuments: 'ملفات المستثمر الأساسية',
  categoryRisks: 'المخاطر',
  categoryFundingRequest: 'طلب التمويل',
  categoryInvestorContact: 'جاهزية التواصل مع المستثمر',

  check_profile_name: 'اسم المشروع',
  check_profile_description: 'وصف المشروع وقيمته',
  check_profile_stage: 'مرحلة أو حالة المشروع',
  check_profile_sector: 'قطاع المشروع',
  check_business_model_value: 'نموذج العمل وعرض القيمة',
  check_business_model_revenue_streams: 'مصادر الإيراد',
  check_business_model_operations: 'خطة التشغيل',
  check_market_target_customers: 'العملاء المستهدفون',
  check_market_size: 'حجم السوق',
  check_market_competition: 'المنافسة والميزة التنافسية',
  check_financials_model: 'النموذج المالي',
  check_financials_revenue: 'بيانات الإيرادات',
  check_financials_costs: 'بيانات التكاليف',
  check_financials_forecast: 'التوقعات المالية',
  check_financials_assumptions: 'الافتراضات المالية',
  check_pitch_deck_exists: 'عرض استثماري محفوظ',
  check_pitch_deck_half_complete: 'اكتمال نصف الشرائح على الأقل',
  check_pitch_deck_fully_complete: 'اكتمال جميع الشرائح',
  check_documents_any: 'مستند واحد على الأقل',
  check_documents_legal: 'مستند قانوني أو ترخيص',
  check_documents_financial: 'قوائم مالية',
  check_risks_recorded: 'مخاطر مسجلة',
  check_risks_mitigation: 'خطة تخفيف لكل خطر',
  check_funding_amount: 'مبلغ التمويل المطلوب',
  check_funding_currency: 'عملة التمويل',
  check_funding_use_of_funds: 'استخدام التمويل',
  check_funding_type: 'نوع التمويل',
  check_contact_email: 'بريد تواصل للمستثمرين',
  check_contact_share_link: 'رابط مستثمر نشط',

  financialsTitle: 'المؤشرات المالية',
  financialsSubtitle: 'تُعرض الأرقام التي حفظتها فقط، وكل رقم موسوم بمصدره. لا تُنشأ أي توقعات نيابة عنك.',
  financialsEmpty: 'لم تُضف بيانات مالية بعد',
  financialsEmptyBody: 'أضف نموذجاً مالياً لمشروعك ليتمكن المستثمرون من مراجعة الإيرادات والتكاليف والتوقعات.',
  financialsOpenModel: 'حدّث البيانات المالية',
  financialsRevenueStreams: 'مصادر الإيراد',
  financialsCostItems: 'بنود التكاليف',
  financialsForecast: 'التوقعات',
  financialsForecastPeriods: 'فترات التوقع',
  financialsAssumptions: 'الافتراضات',
  financialsKpis: 'مؤشرات محفوظة',
  financialsFundingTarget: 'التمويل المطلوب',
  financialsUseOfFunds: 'استخدام التمويل',
  financialsAllocation: 'التخصيص',
  financialsAmount: 'المبلغ',
  financialsCurrency: 'العملة',
  financialsReportingPeriod: 'فترة التقرير',
  financialsDataSource: 'المصدر',
  financialsLastUpdate: 'آخر تحديث',
  sourceUserEntered: 'مدخل من المستخدم',
  sourceForecast: 'توقع',
  sourceActual: 'فعلي',
  sourceAiAssisted: 'بمساعدة الذكاء الاصطناعي',
  sourceUnavailable: 'غير متوفر',
  metricPlannedRevenue: 'الإيراد الشهري المخطط',
  metricPlannedCosts: 'التكاليف الشهرية المخططة',
  metricPlannedNet: 'الصافي الشهري المخطط',
  fundsProduct: 'تطوير المنتج',
  fundsMarketing: 'التسويق',
  fundsOperations: 'التشغيل',
  fundsHiring: 'التوظيف',
  fundsLicensesLegal: 'التراخيص والقانوني',
  fundsEmergencyReserve: 'احتياطي الطوارئ',
  fundsOther: 'أخرى',

  documentsTitle: 'ملفات المستثمر الأساسية',
  documentsSubtitle: 'المستندات التي سيطلبها المستثمرون، منظمة حسب الفئة مع حالة المراجعة ومستوى المشاركة.',
  documentsEmpty: 'لا توجد مستندات مرفوعة بعد',
  documentsEmptyBody: 'ارفع مستندات الشركة والمستندات القانونية والمالية من مركز الأعمال ليتمكن المستثمرون من مراجعتها.',
  documentsAdd: 'أضف المستندات الناقصة',
  documentsName: 'الملف',
  documentsCategory: 'الفئة',
  documentsUpdated: 'آخر تحديث',
  documentsVisibility: 'مستوى المشاركة',
  documentsOpen: 'فتح',
  documentsNoLegal: 'لا توجد مستندات قانونية مرفوعة',
  docCategoryCompany: 'مستندات الشركة',
  docCategoryLegal: 'قانونية',
  docCategoryFinancial: 'مالية',
  docCategoryMarket: 'أبحاث السوق',
  docCategoryPitch: 'العرض الاستثماري',
  docCategoryContracts: 'العقود',
  docCategoryDiligence: 'الفحص النافي للجهالة',
  docCategoryOther: 'ملفات مساندة',

  diligenceTitle: 'قائمة الفحص النافي للجهالة',
  diligenceSubtitle: 'لا يُعتبر أي بند مكتملاً إلا بدليل فعلي — مستند مرتبط أو ملاحظة مراجعة مكتوبة.',
  diligenceRequired: 'إلزامي',
  diligenceOptional: 'اختياري',
  diligenceEvidence: 'الدليل',
  diligenceNoEvidence: 'لا يوجد دليل بعد',
  diligenceMarkReviewed: 'تأكيد المراجعة',
  diligenceNotePlaceholder: 'أين الدليل؟ (مستند، سجل رسمي، عقد…)',
  diligenceNoteRequired: 'مطلوب ملاحظة مراجعة أو مستند مرتبط قبل تأكيد مراجعة هذا البند.',
  diligenceLastReview: 'آخر مراجعة',
  diligenceSaveFailed: 'تعذر حفظ بند الفحص.',
  ddGroupIdentity: 'هوية الشركة',
  ddGroupOwnership: 'الملكية',
  ddGroupLegal: 'التسجيل القانوني',
  ddGroupFinancialStatements: 'القوائم المالية',
  ddGroupTax: 'الضرائب والجهات الرقابية',
  ddGroupContracts: 'العقود',
  ddGroupIp: 'الملكية الفكرية',
  ddGroupLiabilities: 'الالتزامات',
  ddGroupRisks: 'المخاطر الرئيسية',
  ddGroupFunding: 'هيكل التمويل',

  pitchTitle: 'العرض الاستثماري',
  pitchSubtitle: 'عرض المستثمرين المبني من بيانات مشروعك المحفوظة.',
  pitchStatus: 'حالة العرض',
  pitchCompletion: 'نسبة الاكتمال',
  pitchLanguage: 'اللغة',
  pitchUpdated: 'آخر تحديث',
  pitchSlides: 'الشرائح',
  pitchMissingSections: 'أقسام تحتاج بيانات',
  pitchOpenBuilder: 'افتح منشئ العرض الاستثماري',
  pitchCreate: 'أنشئ العرض الاستثماري',
  pitchEmpty: 'العرض الاستثماري غير مكتمل',
  pitchEmptyBody: 'أنشئه من صفحة المشروع — كل شريحة تُبنى من بيانات محفوظة وتبقى قابلة للمراجعة قبل الحفظ.',
  pitchAiNote: 'أي محتوى مُنشأ بمساعدة الذكاء الاصطناعي يُعرض للمراجعة دائماً قبل حفظه. لا يُنشر شيء بصمت.',

  risksTitle: 'مخاطر المشروع',
  risksSubtitle: 'سجل شفاف للمخاطر مع الشدة والاحتمالية وخطة التخفيف. يتوقع المستثمرون صراحة كاملة هنا.',
  risksEmpty: 'لا توجد مخاطر مسجلة',
  risksEmptyBody: 'سجّل المخاطر الحقيقية للمشروع مع خطة تخفيف لكل منها. المشروع الذي لا يعترف بأي مخاطر يبدو غير جاهز.',
  risksAdd: 'إضافة خطر',
  risksEdit: 'تعديل الخطر',
  risksDelete: 'حذف الخطر',
  risksTitleField: 'عنوان الخطر',
  risksCategory: 'الفئة',
  risksSeverity: 'الشدة',
  risksProbability: 'الاحتمالية',
  risksImpact: 'الأثر',
  risksMitigation: 'خطة التخفيف',
  risksStatus: 'الحالة',
  risksLastReview: 'آخر مراجعة',
  risksSave: 'حفظ الخطر',
  risksSaving: 'جاري الحفظ…',
  risksMissingTitle: 'أدخل عنواناً للخطر.',
  risksMissingMitigation: 'لا توجد خطة تخفيف مسجلة',
  risksSaveFailed: 'تعذر حفظ الخطر.',
  risksDeleteFailed: 'تعذر حذف الخطر.',
  risksUpdateAction: 'حدّث مخاطر المشروع',
  riskCategoryMarket: 'السوق',
  riskCategoryFinancial: 'مالية',
  riskCategoryOperational: 'تشغيلية',
  riskCategoryLegal: 'قانونية',
  riskCategoryRegulatory: 'تنظيمية',
  riskCategoryCompetition: 'المنافسة',
  riskCategoryLiquidity: 'السيولة',
  riskCategoryTechnology: 'التقنية',
  riskCategoryExecution: 'التنفيذ',
  riskCategoryConcentration: 'التركّز',
  severityLow: 'منخفضة',
  severityMedium: 'متوسطة',
  severityHigh: 'عالية',
  severityCritical: 'حرجة',

  sharingTitle: 'شارك العرض مع المستثمر',
  sharingSubtitle: 'أنشئ رابطاً مضبوطاً: اختر ما يراه المستثمر، واحمِه بكلمة مرور، وحدد تاريخ انتهاء، وألغِه في أي وقت.',
  sharingCreate: 'إنشاء رابط مستثمر',
  sharingLabel: 'اسم الرابط',
  sharingLabelPlaceholder: 'مثال: جولة تمويل أولى — الاجتماع الأول',
  sharingExpiry: 'تاريخ الانتهاء',
  sharingNoExpiry: 'بدون تاريخ انتهاء',
  sharingPassword: 'كلمة المرور (اختياري)',
  sharingPasswordHint: '6 أحرف على الأقل. سيحتاجها المستثمر لفتح الرابط.',
  sharingSections: 'الأقسام الظاهرة',
  sharingAllowDownloads: 'السماح بتنزيل المستندات',
  sharingMessage: 'رسالة للمستثمر (اختياري)',
  sharingMessagePlaceholder: 'ترحيب قصير أو سياق للمراجع.',
  sharingGenerate: 'إنشاء الرابط',
  sharingGenerating: 'جاري الإنشاء…',
  sharingSectionsRequired: 'اختر قسماً واحداً على الأقل للمشاركة.',
  sharingCreateFailed: 'تعذر إنشاء الرابط.',
  sharingCreated: 'تم إنشاء رابط المستثمر. انسخه الآن — لن يظهر مرة أخرى.',
  sharingCopy: 'نسخ الرابط',
  sharingCopied: 'تم النسخ.',
  sharingActiveLinks: 'روابط المستثمرين',
  sharingNoLinks: 'لم تُنشأ روابط مستثمرين بعد.',
  sharingRevoke: 'إلغاء الوصول',
  sharingRevokeFailed: 'تعذر إلغاء الرابط.',
  sharingAccessCount: 'مرات الفتح',
  sharingLastAccess: 'آخر وصول',
  sharingExpiresAt: 'ينتهي',
  sharingPrivateNote: 'الملاحظات الداخلية والمستندات الخاصة لا تُدرج أبداً في رابط المستثمر.',
  sectionOverview: 'نظرة عامة',
  sectionReadiness: 'الجاهزية',
  sectionFinancials: 'البيانات المالية',
  sectionDocuments: 'المستندات',
  sectionPitchDeck: 'العرض الاستثماري',
  sectionRisks: 'المخاطر',

  activityTitle: 'نشاط المستثمرين',
  activitySubtitle: 'أحداث وصول حقيقية من روابط المستثمرين الخاصة بك. لا شيء هنا مُحاكى.',
  activityEmpty: 'لا توجد بيانات نشاط مستثمرين متاحة حالياً',
  activityEmptyBody: 'تظهر الأحداث بمجرد أن يفتح مستثمر أحد روابطك.',
  activityEventOfferOpened: 'تم فتح العرض',
  activityEventDeckViewed: 'تمت مشاهدة العرض الاستثماري',
  activityEventDocumentDownloaded: 'تم تنزيل مستند',
  activityEventQuestionSubmitted: 'تم إرسال سؤال',
  activityEventAccessDenied: 'تم رفض الوصول',
  activityEventLinkRevoked: 'تم إلغاء الرابط',
  activityVia: 'عبر',
  questionsTitle: 'أسئلة المستثمرين',
  questionsEmpty: 'لا توجد أسئلة من المستثمرين بعد.',
  questionsRespond: 'الرد',
  questionsInternalNote: 'ملاحظة داخلية (لا تظهر للمستثمرين أبداً)',
  questionsSave: 'حفظ الرد',
  questionsSaveFailed: 'تعذر حفظ الرد.',
  questionsAskedBy: 'من',
  questionsStatusLabel: 'الحالة',

  viewerLoading: 'جاري فتح العرض الاستثماري…',
  viewerPasswordTitle: 'هذا العرض محمي بكلمة مرور',
  viewerPasswordBody: 'أدخل كلمة المرور التي استلمتها من مالك المشروع.',
  viewerPasswordField: 'كلمة المرور',
  viewerPasswordSubmit: 'فتح العرض',
  viewerPasswordWrong: 'كلمة المرور غير صحيحة. حاول مرة أخرى.',
  viewerExpired: 'انتهت صلاحية رابط المستثمر هذا.',
  viewerRevoked: 'تم إلغاء الوصول عبر رابط المستثمر هذا.',
  viewerNotFound: 'رابط المستثمر هذا غير موجود.',
  viewerUnavailable: 'تعذر تحميل العرض الاستثماري حالياً.',
  viewerMessageTitle: 'رسالة من مالك المشروع',
  viewerAskTitle: 'اسأل مالك المشروع',
  viewerAskField: 'سؤالك',
  viewerAskName: 'اسمك (اختياري)',
  viewerAskSubmit: 'إرسال السؤال',
  viewerAskSent: 'تم إرسال سؤالك إلى مالك المشروع.',
  viewerAskFailed: 'تعذر إرسال السؤال.',
  viewerDisclaimer: 'تعرض هذه الصفحة بيانات مشروع شاركها مالكها لغرض المراجعة، وهي ليست نصيحة استثمارية ولا تتضمن أي ضمان للعوائد.',
  viewerDownload: 'تنزيل',
  viewerNoDownloads: 'التنزيل معطل لهذا الرابط.',

  notRecorded: 'غير مسجل',
  updated: 'آخر تحديث',
  cancel: 'إلغاء',
  close: 'إغلاق',
  confirmDelete: 'تأكيد الحذف',
  retry: 'إعادة المحاولة',
  loadFailedDocuments: 'تعذر تحميل المستندات',
  staleData: 'بعض البيانات أقدم من سنة وتحتاج مراجعة.',
};

const fr: InvestorCopy = {
  eyebrow: 'Espace investisseur construit à partir de vos données projet réelles',
  title: 'Offres d’investissement',
  subtitle: 'Préparez, vérifiez et partagez votre projet avec les investisseurs : préparation, finances, documents, risques et partage sécurisé au même endroit.',
  loading: 'Chargement de votre espace investisseur…',
  partialLoad: 'Certains enregistrements n’ont pas pu être chargés. Les chiffres affichés proviennent uniquement des données chargées.',
  signInTitle: 'Connectez-vous pour ouvrir votre espace investisseur.',
  signInBody: 'Les éléments investisseurs nécessitent un compte et des données projet enregistrées.',
  signIn: 'Se connecter',
  noProjectsTitle: 'Ajoutez d’abord un projet pour préparer une offre.',
  noProjectsBody: 'L’espace se construit entièrement à partir d’un projet réel enregistré — rien n’est inventé.',
  openProjects: 'Ouvrir mes projets',
  selectProject: 'Projet',
  selectProjectHint: 'Choisissez le projet à préparer pour les investisseurs.',
  noFakeData: 'Aucun investisseur, offre ou activité fictive n’est affiché. Tout reflète uniquement vos données enregistrées.',

  tabOverview: 'Vue d’ensemble',
  tabReadiness: 'Préparation à l’investissement',
  tabFinancials: 'Finances',
  tabDocuments: 'Documents',
  tabPitchDeck: 'Pitch Deck',
  tabRisks: 'Risques',
  tabSharing: 'Partage',
  tabActivity: 'Activité investisseurs',

  statusComplete: 'Complet',
  statusPartial: 'Partiel',
  statusMissing: 'Manquant',
  statusBlocked: 'Bloqué',
  statusNeedsReview: 'À revoir',
  statusApproved: 'Approuvé',
  statusPendingReview: 'En attente de revue',
  statusExpired: 'Expiré',
  statusNeedsUpdate: 'À mettre à jour',
  statusPrivate: 'Privé',
  statusShared: 'Partagé avec les investisseurs',
  statusOpen: 'Ouvert',
  statusMitigated: 'Atténué',
  statusAccepted: 'Accepté',
  statusAnswered: 'Répondu',
  statusActive: 'Actif',
  statusRevoked: 'Révoqué',

  overviewReadiness: 'Préparation à l’investissement',
  overviewScoreOf: 'sur 100',
  overviewFundingTarget: 'Financement recherché',
  overviewFundingType: 'Type de financement',
  overviewMissingItems: 'Exigences manquantes',
  overviewBlockers: 'Blocages critiques',
  overviewLatestActivity: 'Dernière activité investisseur',
  overviewNoActivity: 'Aucune donnée d’activité investisseur disponible pour le moment.',
  overviewNextAction: 'Prochaine étape recommandée',
  overviewAllReady: 'Tous les éléments requis sont complets. Vérifiez-les, puis partagez l’offre.',
  overviewValueProposition: 'Proposition de valeur',
  overviewNoValueProposition: 'Aucun résumé du projet n’a encore été rédigé. Une proposition de valeur courte et claire est la première chose qu’un investisseur lit.',
  overviewProjectStage: 'Stade du projet',
  overviewLastUpdated: 'Dernière mise à jour',
  overviewComputedAt: 'Score calculé',
  overviewHighlights: 'Chiffres financiers clés',

  readinessTitle: 'Préparation du projet à l’investissement',
  readinessSubtitle: 'Un score déterministe calculé à partir de vos données validées — chaque point renvoie à une exigence nommée. Rien n’est estimé par l’IA.',
  readinessScore: 'Score de préparation',
  readinessBreakdown: 'Détail par catégorie',
  readinessWeight: 'Poids',
  readinessMissing: 'Exigences manquantes',
  readinessBlockers: 'Exigences bloquantes',
  readinessOptional: 'Améliorations optionnelles',
  readinessNextAction: 'Prochaine étape recommandée',
  readinessComplete: 'Complétez les exigences manquantes',
  readinessNoBlockers: 'Aucune exigence bloquante.',
  readinessFormulaTitle: 'Comment ce score est calculé',
  readinessFormulaBody: 'Chaque catégorie a un poids fixe ; son avancement correspond à la part de ses contrôles obligatoires validés par les données enregistrées. Le total est la moyenne pondérée, arrondie à l’inférieur. Le score n’atteint 100 que si chaque exigence est réellement complète.',
  categoryProfile: 'Profil du projet',
  categoryBusinessModel: 'Modèle économique',
  categoryMarket: 'Opportunité de marché',
  categoryFinancials: 'Données financières',
  categoryPitchDeck: 'Pitch Deck',
  categoryDocuments: 'Documents investisseurs essentiels',
  categoryRisks: 'Risques',
  categoryFundingRequest: 'Demande de financement',
  categoryInvestorContact: 'Contact investisseur',

  check_profile_name: 'Nom du projet',
  check_profile_description: 'Description et valeur du projet',
  check_profile_stage: 'Stade ou statut du projet',
  check_profile_sector: 'Secteur du projet',
  check_business_model_value: 'Modèle économique et proposition de valeur',
  check_business_model_revenue_streams: 'Sources de revenus',
  check_business_model_operations: 'Plan opérationnel',
  check_market_target_customers: 'Clients cibles',
  check_market_size: 'Taille du marché',
  check_market_competition: 'Concurrence et avantage',
  check_financials_model: 'Modèle financier',
  check_financials_revenue: 'Données de revenus',
  check_financials_costs: 'Données de coûts',
  check_financials_forecast: 'Prévisions financières',
  check_financials_assumptions: 'Hypothèses financières',
  check_pitch_deck_exists: 'Pitch deck enregistré',
  check_pitch_deck_half_complete: 'Au moins la moitié des diapositives complètes',
  check_pitch_deck_fully_complete: 'Toutes les diapositives complètes',
  check_documents_any: 'Au moins un document',
  check_documents_legal: 'Document légal ou d’immatriculation',
  check_documents_financial: 'États financiers',
  check_risks_recorded: 'Risques enregistrés',
  check_risks_mitigation: 'Atténuation pour chaque risque',
  check_funding_amount: 'Montant de financement demandé',
  check_funding_currency: 'Devise du financement',
  check_funding_use_of_funds: 'Utilisation des fonds',
  check_funding_type: 'Type de financement',
  check_contact_email: 'E-mail de contact investisseur',
  check_contact_share_link: 'Lien investisseur actif',

  financialsTitle: 'Indicateurs financiers',
  financialsSubtitle: 'Seuls les chiffres que vous avez enregistrés sont affichés, chacun avec sa source. Aucune projection n’est créée à votre place.',
  financialsEmpty: 'Aucune donnée financière ajoutée pour le moment.',
  financialsEmptyBody: 'Ajoutez un modèle financier à votre projet pour que les investisseurs puissent examiner revenus, coûts et prévisions.',
  financialsOpenModel: 'Mettre à jour les données financières',
  financialsRevenueStreams: 'Sources de revenus',
  financialsCostItems: 'Postes de coûts',
  financialsForecast: 'Prévisions',
  financialsForecastPeriods: 'Périodes de prévision',
  financialsAssumptions: 'Hypothèses',
  financialsKpis: 'Indicateurs enregistrés',
  financialsFundingTarget: 'Financement recherché',
  financialsUseOfFunds: 'Utilisation des fonds',
  financialsAllocation: 'Allocation',
  financialsAmount: 'Montant',
  financialsCurrency: 'Devise',
  financialsReportingPeriod: 'Période de référence',
  financialsDataSource: 'Source',
  financialsLastUpdate: 'Dernière mise à jour',
  sourceUserEntered: 'Saisi par l’utilisateur',
  sourceForecast: 'Prévision',
  sourceActual: 'Réel',
  sourceAiAssisted: 'Assisté par IA',
  sourceUnavailable: 'Indisponible',
  metricPlannedRevenue: 'Revenu mensuel prévu',
  metricPlannedCosts: 'Coûts mensuels prévus',
  metricPlannedNet: 'Net mensuel prévu',
  fundsProduct: 'Développement produit',
  fundsMarketing: 'Marketing',
  fundsOperations: 'Exploitation',
  fundsHiring: 'Recrutement',
  fundsLicensesLegal: 'Licences et juridique',
  fundsEmergencyReserve: 'Réserve d’urgence',
  fundsOther: 'Autre',

  documentsTitle: 'Documents investisseurs essentiels',
  documentsSubtitle: 'Les documents que les investisseurs demanderont, classés par catégorie avec statut de revue et visibilité de partage.',
  documentsEmpty: 'Aucun document téléversé pour le moment.',
  documentsEmptyBody: 'Téléversez les documents d’entreprise, juridiques et financiers depuis le Centre d’affaires pour que les investisseurs puissent les examiner.',
  documentsAdd: 'Ajouter les documents manquants',
  documentsName: 'Fichier',
  documentsCategory: 'Catégorie',
  documentsUpdated: 'Mis à jour',
  documentsVisibility: 'Visibilité',
  documentsOpen: 'Ouvrir',
  documentsNoLegal: 'Aucun document juridique téléversé.',
  docCategoryCompany: 'Documents d’entreprise',
  docCategoryLegal: 'Juridique',
  docCategoryFinancial: 'Financier',
  docCategoryMarket: 'Études de marché',
  docCategoryPitch: 'Pitch Deck',
  docCategoryContracts: 'Contrats',
  docCategoryDiligence: 'Due diligence',
  docCategoryOther: 'Fichiers annexes',

  diligenceTitle: 'Liste de due diligence',
  diligenceSubtitle: 'Un élément n’est complet qu’avec une preuve réelle — un document lié ou une note de revue écrite.',
  diligenceRequired: 'Obligatoire',
  diligenceOptional: 'Optionnel',
  diligenceEvidence: 'Preuve',
  diligenceNoEvidence: 'Pas encore de preuve',
  diligenceMarkReviewed: 'Marquer comme revu',
  diligenceNotePlaceholder: 'Où est la preuve ? (document, registre, contrat…)',
  diligenceNoteRequired: 'Une note de revue ou un document lié est requis avant de marquer cet élément comme revu.',
  diligenceLastReview: 'Dernière revue',
  diligenceSaveFailed: 'L’élément n’a pas pu être enregistré.',
  ddGroupIdentity: 'Identité de l’entreprise',
  ddGroupOwnership: 'Actionnariat',
  ddGroupLegal: 'Immatriculation légale',
  ddGroupFinancialStatements: 'États financiers',
  ddGroupTax: 'Fiscal et réglementaire',
  ddGroupContracts: 'Contrats',
  ddGroupIp: 'Propriété intellectuelle',
  ddGroupLiabilities: 'Passifs',
  ddGroupRisks: 'Risques majeurs',
  ddGroupFunding: 'Structure de financement',

  pitchTitle: 'Pitch Deck',
  pitchSubtitle: 'La présentation investisseur construite à partir de vos données projet enregistrées.',
  pitchStatus: 'Statut du deck',
  pitchCompletion: 'Avancement',
  pitchLanguage: 'Langue',
  pitchUpdated: 'Dernière mise à jour',
  pitchSlides: 'Diapositives',
  pitchMissingSections: 'Sections nécessitant des données',
  pitchOpenBuilder: 'Ouvrir l’éditeur de Pitch Deck',
  pitchCreate: 'Créer le Pitch Deck',
  pitchEmpty: 'Le Pitch Deck n’est pas encore créé.',
  pitchEmptyBody: 'Générez-le depuis la page projet — chaque diapositive est construite à partir de données enregistrées et reste vérifiable avant sauvegarde.',
  pitchAiNote: 'Le contenu assisté par IA est toujours présenté pour revue avant sauvegarde. Rien n’est publié en silence.',

  risksTitle: 'Risques du projet',
  risksSubtitle: 'Un registre transparent des risques avec gravité, probabilité et atténuation. Les investisseurs attendent de la franchise ici.',
  risksEmpty: 'Aucun risque enregistré pour le moment.',
  risksEmptyBody: 'Consignez les risques réels du projet avec un plan d’atténuation pour chacun. Un projet sans aucun risque reconnu paraît mal préparé.',
  risksAdd: 'Ajouter un risque',
  risksEdit: 'Modifier le risque',
  risksDelete: 'Supprimer le risque',
  risksTitleField: 'Intitulé du risque',
  risksCategory: 'Catégorie',
  risksSeverity: 'Gravité',
  risksProbability: 'Probabilité',
  risksImpact: 'Impact',
  risksMitigation: 'Plan d’atténuation',
  risksStatus: 'Statut',
  risksLastReview: 'Dernière revue',
  risksSave: 'Enregistrer le risque',
  risksSaving: 'Enregistrement…',
  risksMissingTitle: 'Saisissez un intitulé de risque.',
  risksMissingMitigation: 'Aucune atténuation enregistrée',
  risksSaveFailed: 'Le risque n’a pas pu être enregistré.',
  risksDeleteFailed: 'Le risque n’a pas pu être supprimé.',
  risksUpdateAction: 'Mettre à jour les risques du projet',
  riskCategoryMarket: 'Marché',
  riskCategoryFinancial: 'Financier',
  riskCategoryOperational: 'Opérationnel',
  riskCategoryLegal: 'Juridique',
  riskCategoryRegulatory: 'Réglementaire',
  riskCategoryCompetition: 'Concurrence',
  riskCategoryLiquidity: 'Liquidité',
  riskCategoryTechnology: 'Technologie',
  riskCategoryExecution: 'Exécution',
  riskCategoryConcentration: 'Concentration',
  severityLow: 'Faible',
  severityMedium: 'Moyenne',
  severityHigh: 'Élevée',
  severityCritical: 'Critique',

  sharingTitle: 'Partager avec les investisseurs',
  sharingSubtitle: 'Créez un lien contrôlé : choisissez ce que l’investisseur voit, protégez-le par mot de passe, fixez une expiration et révoquez-le à tout moment.',
  sharingCreate: 'Créer un lien investisseur',
  sharingLabel: 'Nom du lien',
  sharingLabelPlaceholder: 'ex. Tour d’amorçage — première réunion',
  sharingExpiry: 'Date d’expiration',
  sharingNoExpiry: 'Sans expiration',
  sharingPassword: 'Mot de passe (optionnel)',
  sharingPasswordHint: 'Au moins 6 caractères. L’investisseur en aura besoin pour ouvrir le lien.',
  sharingSections: 'Sections visibles',
  sharingAllowDownloads: 'Autoriser le téléchargement des documents',
  sharingMessage: 'Message à l’investisseur (optionnel)',
  sharingMessagePlaceholder: 'Un court mot d’accueil ou de contexte.',
  sharingGenerate: 'Créer le lien',
  sharingGenerating: 'Création…',
  sharingSectionsRequired: 'Sélectionnez au moins une section à partager.',
  sharingCreateFailed: 'Le lien n’a pas pu être créé.',
  sharingCreated: 'Lien investisseur créé. Copiez-le maintenant — il ne sera plus affiché.',
  sharingCopy: 'Copier le lien',
  sharingCopied: 'Copié.',
  sharingActiveLinks: 'Liens investisseurs',
  sharingNoLinks: 'Aucun lien investisseur créé pour le moment.',
  sharingRevoke: 'Révoquer l’accès',
  sharingRevokeFailed: 'Le lien n’a pas pu être révoqué.',
  sharingAccessCount: 'Ouvertures',
  sharingLastAccess: 'Dernier accès',
  sharingExpiresAt: 'Expire',
  sharingPrivateNote: 'Les notes internes et les documents privés ne sont jamais inclus dans un lien investisseur.',
  sectionOverview: 'Vue d’ensemble',
  sectionReadiness: 'Préparation',
  sectionFinancials: 'Finances',
  sectionDocuments: 'Documents',
  sectionPitchDeck: 'Pitch Deck',
  sectionRisks: 'Risques',

  activityTitle: 'Activité des investisseurs',
  activitySubtitle: 'Événements d’accès réels issus de vos liens investisseurs. Rien ici n’est simulé.',
  activityEmpty: 'Aucune donnée d’activité investisseur disponible pour le moment.',
  activityEmptyBody: 'Les événements apparaissent dès qu’un investisseur ouvre l’un de vos liens.',
  activityEventOfferOpened: 'Offre ouverte',
  activityEventDeckViewed: 'Pitch Deck consulté',
  activityEventDocumentDownloaded: 'Document téléchargé',
  activityEventQuestionSubmitted: 'Question envoyée',
  activityEventAccessDenied: 'Accès refusé',
  activityEventLinkRevoked: 'Lien révoqué',
  activityVia: 'via',
  questionsTitle: 'Questions des investisseurs',
  questionsEmpty: 'Aucune question d’investisseur pour le moment.',
  questionsRespond: 'Réponse',
  questionsInternalNote: 'Note interne (jamais visible par les investisseurs)',
  questionsSave: 'Enregistrer la réponse',
  questionsSaveFailed: 'La réponse n’a pas pu être enregistrée.',
  questionsAskedBy: 'De',
  questionsStatusLabel: 'Statut',

  viewerLoading: 'Ouverture de l’offre investisseur…',
  viewerPasswordTitle: 'Cette offre est protégée par mot de passe',
  viewerPasswordBody: 'Saisissez le mot de passe reçu du porteur de projet.',
  viewerPasswordField: 'Mot de passe',
  viewerPasswordSubmit: 'Ouvrir l’offre',
  viewerPasswordWrong: 'Mot de passe incorrect. Réessayez.',
  viewerExpired: 'Ce lien investisseur a expiré.',
  viewerRevoked: 'L’accès via ce lien investisseur a été révoqué.',
  viewerNotFound: 'Ce lien investisseur n’existe pas.',
  viewerUnavailable: 'L’offre investisseur n’a pas pu être chargée pour le moment.',
  viewerMessageTitle: 'Message du porteur de projet',
  viewerAskTitle: 'Poser une question au porteur de projet',
  viewerAskField: 'Votre question',
  viewerAskName: 'Votre nom (optionnel)',
  viewerAskSubmit: 'Envoyer la question',
  viewerAskSent: 'Votre question a été envoyée au porteur de projet.',
  viewerAskFailed: 'La question n’a pas pu être envoyée.',
  viewerDisclaimer: 'Cette page présente des données de projet partagées par son propriétaire à des fins de revue. Ce n’est pas un conseil en investissement et aucun rendement n’est garanti.',
  viewerDownload: 'Télécharger',
  viewerNoDownloads: 'Les téléchargements sont désactivés pour ce lien.',

  notRecorded: 'Non renseigné',
  updated: 'Mis à jour',
  cancel: 'Annuler',
  close: 'Fermer',
  confirmDelete: 'Confirmer la suppression',
  retry: 'Réessayer',
  loadFailedDocuments: 'Les documents n’ont pas pu être chargés.',
  staleData: 'Certaines données datent de plus d’un an et devraient être revues.',
};

export const INVESTOR_TEXT: Record<Lang, InvestorCopy> = { ar, en, fr };
