// TEXT translations for charity-projects/page

const RAW_TEXT = {
  ar: {
    title: 'المشاريع الخيرية',
    subtitle: 'خطط للزكاة، الخمس، الكفالات، الصدقات، والمشاريع الخيرية طويلة الأمد بذكاء.',
    breadcrumb: 'THE SFM / المشاريع الخيرية',
    newProject: 'مشروع خيري جديد',
    zakatCalculator: 'حاسبة الزكاة',
    activeProjects: 'إجمالي المشاريع النشطة',
    totalDonations: 'إجمالي التبرعات',
    commitments: 'الالتزامات الخيرية المتوقعة',
    estimatedZakat: 'زكاة المال المتوقعة',
    nextZakat: 'أقرب موعد زكاة',
    noDueDate: 'لا يوجد موعد',
    nextDueDateKpi: 'أقرب موعد',
    beneficiariesCountKpi: 'عدد المستفيدين',
    upcomingRemindersKpi: 'التذكيرات القادمة',
    unavailable: 'غير متاح',
    smartZakat: 'حاسبة الزكاة الذكية',
    cash: 'المدخرات النقدية',
    investments: 'الاستثمارات',
    gold: 'الذهب',
    silver: 'الفضة',
    debts: 'الديون المستحقة',
    nonZakat: 'أصول غير خاضعة للزكاة',
    goldPrice: 'سعر غرام الذهب',
    silverPrice: 'سعر غرام الفضة',
    zakatableAmount: 'المبلغ الخاضع للزكاة',
    zakatAmount: 'قيمة الزكاة 2.5%',
    zakatDisclaimer: 'هذه الحاسبة تقديرية لأغراض تنظيمية، ويُفضّل مراجعة جهة شرعية مختصة للحالات الخاصة.',
    nisabNote: 'سيتم ربط أسعار الذهب والفضة لاحقاً لحساب النصاب تلقائياً. الإدخال اليدوي متاح حالياً.',
    hawlTracking: 'تتبع الحول الهجري',
    assetName: 'اسم الأصل',
    assetType: 'نوع الأصل',
    ownershipDate: 'تاريخ التملك',
    dueDate: 'موعد الزكاة المتوقع',
    reminder: 'تذكير قبل 30 يوماً',
    addAsset: 'حفظ أصل الزكاة',
    projects: 'المشاريع الخيرية',
    projectListDesc: 'تابع المشاريع الخيرية وحالتها والتبرعات المرتبطة بها من مكان واحد.',
    searchProjects: 'بحث في المشاريع الخيرية',
    noFilteredProjects: 'لا توجد مشاريع مطابقة للفلاتر الحالية.',
    noFilteredProjectsBody: 'جرّب تغيير البحث أو الفلاتر لعرض مشاريع أخرى.',
    templates: 'قوالب المشاريع',
    forecast: 'التزاماتك الخيرية المتوقعة للسنة',
    forecastEmpty: 'أضف الزكاة أو الكفالات أو المشاريع الخيرية لحساب الالتزامات المتوقعة.',
    impact: 'تحليل أثر التبرع',
    donationAmount: 'مبلغ التبرع',
    incomeMissing: 'أضف بيانات الدخل لعرض تحليل أثر التبرع على الميزانية.',
    donationPercent: 'هذا التبرع يعادل {pct}% من دخلك الشهري.',
    remainingNet: 'بعد هذا التبرع، صافي ميزانيتك الشهرية المتوقع: {amount}.',
    highWarning: 'تنبيه: هذا التبرع مرتفع مقارنة بدخلك هذا الشهر.',
    emptyTitle: 'لا توجد مشاريع خيرية حالياً',
    emptyBody: 'ابدأ بإضافة مشروع خيري لتتبع التبرعات والمواعيد والأثر.',
    target: 'الهدف المالي',
    collected: 'المحصّل',
    remaining: 'المتبقي',
    organization: 'الجهة المنفذة',
    category: 'الفئة',
    status: 'الحالة',
    startDate: 'تاريخ البداية',
    endDate: 'تاريخ النهاية',
    notes: 'ملاحظات',
    linkedDonations: 'التبرعات المرتبطة',
    view: 'عرض التفاصيل',
    addDonation: 'إضافة تبرع',
    edit: 'تعديل',
    archive: 'أرشفة',
    saveProject: 'حفظ المشروع',
    cancel: 'إلغاء',
    projectName: 'اسم المشروع',
    comingSoon: 'قريباً',
    futureTitle: 'ميزات قادمة',
    reports: 'التقارير',
    reportsDesc: 'أنشئ تقارير سنوية وتقارير للتبرعات والمستفيدين، ثم صدّرها بصيغ مناسبة للمتابعة.',
    annualPdfReport: 'تقرير الأعمال الخيرية السنوي PDF',
    generateReport: 'إنشاء التقرير',
    reportYear: 'سنة التقرير',
    exportPdf: 'تصدير PDF',
    exportExcel: 'تصدير Excel',
    preparingExcel: 'جاري تجهيز ملف Excel...',
    excelExported: 'تم تصدير ملف Excel بنجاح.',
    excelExportFailed: 'تعذر تصدير ملف Excel.',
    emptyReportExported: 'لا توجد بيانات كافية، سيتم تصدير تقرير فارغ.',
    notEnoughReportData: 'لا توجد بيانات كافية لإنشاء تقرير حالياً.',
    emptyReportsBody: 'أضف مشاريع أو تبرعات لبدء إنشاء التقارير.',
    yearlyCharityReport: 'التقرير الخيري السنوي',
    yearlyReportDesc: 'ملخص سنوي للمشاريع والتبرعات والمستفيدين والأثر.',
    donationsReport: 'تقرير التبرعات',
    donationsReportDesc: 'تحليل للتبرعات المسجلة حسب السنة والمشروع.',
    zakatKhumsReport: 'تقرير الزكاة والخمس',
    zakatKhumsReportDesc: 'يعرض بيانات الزكاة والخمس المرتبطة بهذه الوحدة عند توفرها.',
    beneficiariesReport: 'تقرير المستفيدين',
    beneficiariesReportDesc: 'ملخص للمستفيدين والكفالات والتجديدات القادمة.',
    documentsEmptyBody: 'احفظ إيصالات التبرعات، شهادات الجمعيات، وتقارير المشاريع في مكان واحد.',
    beneficiariesEmptyBody: 'أضف المستفيدين المرتبطين بمشاريعك لتنظيم الحالات والكفالات.',
    contributorsEmptyBody: 'أضف أفراد العائلة أو المساهمين لتتبع مساهماتهم ونسبة التغطية.',
    noContributors: 'لم تتم إضافة مساهمين بعد',
    documentVault: 'خزانة المستندات',
    documentVaultDesc: 'احفظ إيصالات التبرعات، شهادات الجمعيات، وتقارير المشاريع الخيرية في مكان واحد.',
    documentsCenter: 'خزانة المستندات',
    uploadDocument: 'رفع مستند',
    documentTitle: 'عنوان المستند',
    documentCategory: 'التصنيف',
    linkProject: 'ربط بمشروع',
    linkDonation: 'ربط بتبرع',
    linkZakatAsset: 'ربط بأصل زكاة',
    linkCommitment: 'ربط بالتزام',
    chooseFile: 'اختر الملف',
    searchDocuments: 'بحث في المستندات',
    allCategories: 'كل التصنيفات',
    noDocuments: 'لا توجد مستندات محفوظة حتى الآن',
    fileTooLarge: 'حجم الملف كبير جداً.',
    unsupportedFileType: 'نوع الملف غير مدعوم.',
    uploadFailed: 'تعذر رفع المستند.',
    documentUploaded: 'تم رفع المستند بنجاح.',
    documentDeleted: 'تم حذف المستند بنجاح.',
    openDocumentFailed: 'تعذر فتح المستند حالياً.',
    confirmDeleteDocument: 'هل تريد حذف هذا المستند؟',
    viewDocument: 'عرض',
    downloadDocument: 'تحميل',
    deleteDocument: 'حذف',
    documentsCount: 'المستندات: {count}',
    searchInsideSoon: 'البحث داخل الملفات قريباً.',
    donation_receipt: 'إيصال تبرع',
    charity_certificate: 'شهادة جمعية',
    project_report: 'تقرير مشروع',
    zakat_document: 'مستند زكاة',
    beneficiary_report: 'تقرير مستفيد',
    hijriCalendar: 'التقويم الخيري الهجري',
    hijriCalendarDesc: 'تابع الزكاة، الحول، رمضان، ذي الحجة، الأضحية، الكفالات، ومواعيد المشاريع من مكان واحد.',
    upcomingReminders: 'التذكيرات القادمة',
    addReminder: 'إضافة تذكير',
    editReminders: 'تعديل التذكيرات',
    reminderTitle: 'عنوان التذكير',
    reminderType: 'نوع التذكير',
    hijriDate: 'التاريخ الهجري',
    remindBefore: 'ذكرني قبل',
    priority: 'الأولوية',
    hijriEstimated: 'التاريخ الهجري تقديري',
    preciseHijriLater: 'سيتم تفعيل التاريخ الهجري الدقيق لاحقاً.',
    completedAction: 'تم',
    dismissAction: 'تجاهل',
    deleteAction: 'حذف',
    noReminders: 'لا توجد تذكيرات قادمة حالياً.',
    reminderEmptyBody: 'أضف تذكيراً للزكاة أو رمضان أو المشاريع الخيرية.',
    reminderSaved: 'تم حفظ التذكير بنجاح.',
    reminderUpdated: 'تم تحديث التذكير.',
    reminderDeleted: 'تم حذف التذكير.',
    confirmDeleteReminder: 'هل تريد حذف هذا التذكير؟',
    daysBefore: 'قبل {days} يوم',
    daysRemaining: 'باقي {days} يوم',
    dueToday: 'مستحق اليوم',
    overdue: 'متأخر {days} يوم',
    smartAlerts: 'تنبيهات ذكية',
    noUrgentAlerts: 'لا توجد تنبيهات عاجلة حالياً.',
    seasonalReminders: 'مواسم خيرية',
    notificationNote: 'هذه التذكيرات تظهر داخل صفحة المشاريع الخيرية حالياً، ولم يتم تفعيل الإشعارات الخارجية بعد.',
    ramadanPlanning: 'رمضان',
    ramadanPlanningDesc: 'جهّز خطة الصدقات، الإفطار، والكفالات قبل بداية الشهر.',
    lastTenNights: 'العشر الأواخر',
    lastTenNightsDesc: 'رتّب تذكيرات قيام الليل، الصدقة اليومية، وزكاة الفطر.',
    arafahDay: 'يوم عرفة',
    eidAdha: 'الأضحية',
    eidAdhaDesc: 'تابع موعد الأضحية وسدادها وربطها بالمستندات.',
    zakatAnnualReview: 'مراجعة الزكاة السنوية',
    nextZakatDue: 'موعد الزكاة القادم',
    monthlyCharity: 'صدقة شهرية',
    monthlyCharityDesc: 'ثبّت تذكيراً شهرياً للصدقات والكفالات المستمرة.',
    charityReminders: 'تذكيرات خيرية',
    zakatCalendarEmptyHint: 'أضف أصل زكاة أو تذكيراً لعرض الموعد القادم.',
    low: 'منخفضة',
    normal: 'عادية',
    high: 'عالية',
    active: 'نشط',
    dismissed: 'متجاهل',
    hawl: 'الحول',
    ramadan: 'رمضان',
    dhul_hijjah: 'ذو الحجة',
    arafah: 'عرفة',
    project_milestone: 'مرحلة مشروع',
    goldNisab: 'النصاب حسب الذهب',
    silverNisab: 'النصاب حسب الفضة',
    reachedNisabQuestion: 'هل بلغت النصاب؟',
    reachedNisab: 'أنت بلغت النصاب',
    notReachedNisab: 'لم تبلغ النصاب بعد',
    automaticPrice: 'السعر التلقائي',
    manualPrice: 'السعر اليدوي',
    nisabMethod: 'طريقة حساب النصاب',
    goldBased: 'حسب الذهب',
    silverBased: 'حسب الفضة',
    conservative: 'الأكثر احتياطاً',
    metalsStatus: 'حالة أسعار الذهب والفضة',
    lastUpdated: 'آخر تحديث',
    priceSource: 'مصدر السعر',
    apiNotConfigured: 'واجهة أسعار المعادن غير مفعّلة حالياً. أدخل السعر يدوياً.',
    metalsConversionWarning: 'تعذر تحويل أسعار الذهب إلى الدينار الكويتي تلقائياً. أدخل السعر يدوياً.',
    enterPriceManually: 'أدخل السعر يدوياً',
    refreshPrices: 'تحديث الأسعار',
    metalsDisclaimer: 'أسعار الذهب والفضة تقديرية وقد تختلف حسب العيار والمصدر وسعر السوق المحلي. استخدم الأسعار كمرجع، وراجع جهة مختصة للحالات الشرعية الخاصة.',
    zakatInputs: 'بيانات الزكاة',
    zakatSummaryTitle: 'ملخص الزكاة',
    zakatGuidanceTitle: 'التوضيح الشرعي والتنظيمي',
    cashSavings: 'النقد والمدخرات',
    zakatableInvestments: 'الاستثمارات القابلة للزكاة',
    goldHoldings: 'الذهب',
    goldWeight: 'وزن الذهب بالغرام',
    goldKarat: 'عيار الذهب',
    directGoldValue: 'أو أدخل القيمة مباشرة',
    silverHoldings: 'الفضة',
    silverWeight: 'وزن الفضة بالغرام',
    directSilverValue: 'أو أدخل القيمة مباشرة',
    nonZakatableAssets: 'أصول غير خاضعة للزكاة',
    personalHome: 'السكن الشخصي',
    personalCar: 'سيارة خاصة',
    householdFurniture: 'أثاث المنزل',
    personalTools: 'أدوات شخصية',
    residentialLand: 'أرض للسكن',
    personalUseAssets: 'أصول للاستخدام الشخصي',
    otherNonZakatAsset: 'وصف الأصل غير الخاضع للزكاة',
    nonZakatHelper: 'استبعد الأصول غير الخاضعة للزكاة مثل السكن الشخصي والسيارة الخاصة والأثاث المستخدم.',
    goldPriceToday: 'سعر الذهب اليوم',
    silverPriceToday: 'سعر الفضة اليوم',
    liveStatus: 'مباشر',
    manualStatus: 'يدوي',
    failedStatus: 'تعذر التحديث',
    manualFallback: 'تعذر تحميل أسعار الذهب والفضة. يمكنك إدخال السعر يدوياً مؤقتاً.',
    usedNisab: 'النصاب المستخدم في الحساب',
    netZakatBase: 'صافي الوعاء الزكوي',
    zakatDue: 'قيمة الزكاة المستحقة',
    zakatRate: 'نسبة الزكاة 2.5%',
    dueSummary: 'بلغت النصاب، والزكاة التقديرية المستحقة هي:',
    notDueSummary: 'لم تبلغ النصاب حسب البيانات المدخلة حالياً.',
    incompleteZakat: 'أكمل بيانات الأسعار أو الأصول لحساب الزكاة بدقة.',
    differenceFromNisab: 'الفرق عن النصاب',
    calculationMethod: 'طريقة الحساب',
    saveZakatCalculation: 'حفظ حساب الزكاة',
    zakatHistory: 'سجل حسابات الزكاة',
    noZakatHistory: 'لا توجد حسابات زكاة محفوظة حتى الآن.',
    calculationSaved: 'تم حفظ حساب الزكاة.',
    calculationDeleted: 'تم حذف حساب الزكاة.',
    completedHawl: 'اكتمل الحول',
    upcomingHawl: 'الحول قادم',
    missingOwnershipDate: 'تاريخ التملك غير مكتمل',
    closeToNisabNote: 'أنت قريب من النصاب. راقب المدخرات والاستثمارات خلال الفترة القادمة.',
    aboveNisabNote: 'الزكاة التقديرية ظاهرة بناءً على البيانات المدخلة. راجع الحالات الخاصة مع جهة مختصة.',
    missingPricesNote: 'تعذر حساب النصاب تلقائياً بسبب عدم توفر أسعار الذهب والفضة.',
    highDebtsNote: 'الديون المستحقة أثرت على صافي الوعاء الزكوي.',
    zakatEstimateDisclaimer: 'هذه الحاسبة تقديرية لأغراض التنظيم والمتابعة، ولا تعتبر فتوى شرعية. للحالات الخاصة، راجع جهة شرعية مختصة.',
    organizationDirectory: 'دليل الجهات الخيرية',
    organizationDirectoryDesc: 'اختر جهة خيرية موثوقة واربطها بمشاريعك وتبرعاتك لمتابعة الشفافية والتنظيم.',
    searchOrganization: 'بحث عن جهة خيرية',
    allOrganizations: 'كل الجهات',
    verifiedOrganizations: 'الجهات الموثقة',
    pendingReview: 'قيد المراجعة',
    unverified: 'غير موثقة',
    verified: 'موثقة',
    rejected: 'مرفوضة',
    organizationType: 'نوع الجهة',
    viewDetails: 'عرض التفاصيل',
    selectOrganization: 'اختيار الجهة',
    licenseNumber: 'رقم الترخيص',
    trustIndicators: 'مؤشرات الثقة',
    transparency: 'الشفافية',
    efficiency: 'الكفاءة',
    trackRecord: 'السجل السابق',
    notReviewedYet: 'لم يتم تقييم الجهة بعد',
    manualOrganizationEntry: 'لم أجد الجهة، إدخال يدوي',
    selectExecutingOrganization: 'اختيار الجهة المنفذة',
    verificationDisclaimer: 'حالة التوثيق في هذا الدليل لأغراض تنظيمية داخل التطبيق، ولا تغني عن التحقق من المصادر الرسمية قبل التبرع.',
    noOrganizationsAvailable: 'لا توجد جهات خيرية محفوظة في الدليل حالياً. يمكن إضافة الجهات لاحقاً من خلال لوحة إدارة أو ملف استيراد موثوق.',
    dataSource: 'مصدر البيانات',
    unverifiedOrganizationWarning: 'هذه الجهة غير موثقة داخل التطبيق. تحقق من المصدر الرسمي قبل التبرع.',
    charity: 'جمعية خيرية',
    zakat_house: 'بيت زكاة',
    humanitarian: 'إنسانية',
    waqf: 'وقف',
    impactDashboard: 'لوحة الأثر',
    impactDashboardDesc: 'شاهد أثر تبرعاتك ومشاريعك الخيرية بناءً على بياناتك المسجلة.',
    notEnoughImpactData: 'لا توجد بيانات كافية لعرض الأثر حالياً.',
    impactEmptyBody: 'أضف مشاريع خيرية أو تبرعات لبدء تتبع الأثر.',
    totalDonated: 'إجمالي التبرعات',
    activeCharityProjects: 'المشاريع النشطة',
    completedProjects: 'المشاريع المكتملة',
    beneficiariesSupported: 'المستفيدون المدعومون',
    monthlySponsorships: 'الكفالات الشهرية',
    estimatedZakatImpact: 'الزكاة المقدرة',
    projectImpactProgress: 'تقدم أثر المشاريع',
    completionRate: 'نسبة الإنجاز',
    givingIncomeRatio: 'نسبة العطاء من الدخل',
    impactOverTime: 'تطور الأثر خلال السنة',
    impactByCategory: 'توزيع الأثر حسب النوع',
    beneficiaryImpact: 'أثر المستفيدين',
    yearlyImpactSummary: 'ملخص أثر السنة',
    customImpactIndicators: 'مؤشرات أثر مخصصة',
    addImpactMetric: 'إضافة مؤشر أثر',
    metricName: 'اسم المؤشر',
    metricValue: 'قيمة المؤشر',
    metricUnit: 'وحدة المؤشر',
    referenceBenchmark: 'مؤشر مرجعي',
    addIncomeForGivingRatio: 'أضف بيانات الدخل لحساب نسبة العطاء من الدخل.',
    customImpactHint: 'يمكنك إضافة مؤشرات أثر مخصصة لكل مشروع لعرض نتائج أدق.',
    projectContributions: 'مساهمات المشاريع',
    sponsorshipAmount: 'مبلغ الكفالات',
    currentMonth: 'الشهر الحالي',
    thisYear: 'هذا العام',
    metricSaved: 'تم حفظ مؤشر الأثر.',
    beneficiaryTracking: 'إدارة المستفيدين',
    beneficiaryDesc: 'تابع الكفالات والحالات الخيرية والمستفيدين المرتبطين بمشاريعك الخيرية بشكل منظم وآمن.',
    privacyNote: 'استخدم رقماً مرجعياً أو اسماً مختصراً بدلاً من البيانات الشخصية الحساسة.',
    addBeneficiary: 'إضافة مستفيد',
    shortName: 'الاسم المختصر / المرجع',
    referenceNumber: 'الرقم المرجعي',
    beneficiaryType: 'نوع المستفيد',
    linkedProject: 'المشروع المرتبط',
    responsibleOrg: 'الجهة المسؤولة',
    country: 'الدولة',
    city: 'المدينة',
    monthlySupport: 'مبلغ الكفالة الشهري',
    currency: 'العملة',
    sponsorshipStart: 'تاريخ بداية الكفالة',
    sponsorshipEnd: 'تاريخ نهاية الكفالة',
    nextRenewal: 'تاريخ التجديد القادم',
    totalBeneficiaries: 'إجمالي المستفيدين',
    activeSponsorships: 'الكفالات النشطة',
    monthlySupportTotal: 'الدعم الشهري',
    upcomingRenewals: 'تجديدات قادمة',
    searchBeneficiaries: 'بحث في المستفيدين',
    allStatuses: 'كل الحالات',
    allTypes: 'كل الفئات',
    noBeneficiaries: 'لا توجد مستفيدين حتى الآن',
    addSupport: 'إضافة دعم',
    linkedDocuments: 'المستندات المرتبطة',
    beneficiariesCount: 'المستفيدون: {count}',
    beneficiarySaved: 'تم حفظ المستفيد بنجاح.',
    beneficiaryDeleted: 'تم حذف المستفيد.',
    confirmDeleteBeneficiary: 'هل تريد حذف هذا المستفيد؟',
    renewalReminderCreated: 'تم إنشاء تذكير التجديد.',
    familyCollaboration: 'المساهمون',
    collaborationDesc: 'أضف المساهمين إلى المشاريع الخيرية وتابع تعهدات كل مساهم والمدفوعات المسجلة.',
    addContributor: 'إضافة مساهم',
    contributorName: 'اسم المساهم',
    emailOptional: 'البريد الإلكتروني اختياري',
    role: 'الدور',
    pledgedAmount: 'المبلغ المتعهد به',
    paidAmount: 'المبلغ المدفوع',
    paymentStatus: 'حالة الدفع',
    markPaid: 'تحديد كمدفوع',
    totalPledged: 'إجمالي التعهدات',
    totalPaid: 'إجمالي المدفوع',
    contributors: 'المساهمون',
    projectCoverage: 'نسبة تغطية المشروع',
    contributorSummary: 'ملخص المساهمين',
    contributorPayments: 'مساهمات المساهمين',
    recordedDonations: 'التبرعات المسجلة',
    invitationsSoon: 'إرسال الدعوات قريباً',
    emailSaved: 'تم حفظ البريد للمتابعة. إرسال الدعوات سيكون متاحاً لاحقاً.',
    contributorSaved: 'تم حفظ المساهم بنجاح.',
    contributorDeleted: 'تم حذف المساهم.',
    contributorPaid: 'تم تحديث مساهمة المساهم.',
    confirmDeleteContributor: 'هل تريد حذف هذا المساهم؟',
    lateContribution: 'مساهمة متأخرة',
    contributorsCount: 'المساهمون: {count}',
    topContributor: 'أعلى مساهم',
    owner: 'مالك',
    contributor: 'مساهم',
    viewer: 'مشاهد',
    pending: 'بانتظار',
    paid: 'مدفوع',
    partial: 'جزئي',
    late: 'متأخر',
    cancelled: 'ملغي',
    needs_review: 'يحتاج مراجعة',
    orphan: 'يتيم',
    family: 'أسرة',
    student: 'طالب',
    medical: 'حالة طبية',
    elderly: 'كبار السن',
    refugee: 'لاجئ',
    project_group: 'مجموعة مشروع',
    saved: 'تم الحفظ بنجاح.',
    error: 'تعذر تنفيذ العملية حالياً.',
    planning: 'تخطيط',
    fundraising: 'جاري الجمع',
    in_progress: 'قيد التنفيذ',
    completed: 'مكتمل',
    paused: 'متوقف',
    ongoing: 'صدقة جارية',
    sponsorship: 'كفالة',
    zakat: 'زكاة',
    sacrifice: 'أضحية',
    endowment: 'وقف',
    mosque: 'بناء مسجد',
    water_well: 'بئر ماء',
    education: 'تعليم',
    relief: 'إغاثة',
    other: 'أخرى',
    monthly: 'شهري',
    annual: 'سنوي',
    once: 'مرة واحدة',
    projectDetails: 'بيانات المشروع',
    financialDetails: 'البيانات المالية',
    organizationDetails: 'بيانات الجهة المنفذة',
    additionalDetails: 'تفاصيل إضافية',
    reminderDetails: 'بيانات التذكير',
    reminderLinks: 'روابط التذكير',
    documentDetails: 'بيانات المستند',
    documentLinks: 'روابط المستند',
    beneficiaryIdentity: 'بيانات المستفيد',
    sponsorshipDetails: 'بيانات الكفالة',
    contributorDetails: 'بيانات المساهم',
    contributionDetails: 'بيانات المساهمة',
  },
  en: {
    title: 'Charity Projects',
    subtitle: 'Plan zakat, khums, sponsorships, donations, and long-term charity projects intelligently.',
    breadcrumb: 'THE SFM / Charity Projects',
    newProject: 'New Charity Project',
    zakatCalculator: 'Zakat Calculator',
    activeProjects: 'Active Projects',
    totalDonations: 'Total Donations',
    commitments: 'Expected Charity Commitments',
    estimatedZakat: 'Estimated Zakat',
    nextZakat: 'Next Zakat Due Date',
    noDueDate: 'No due date',
    nextDueDateKpi: 'Nearest Due Date',
    beneficiariesCountKpi: 'Beneficiaries',
    upcomingRemindersKpi: 'Upcoming Reminders',
    unavailable: 'Unavailable',
    smartZakat: 'Smart Zakat Calculator',
    cash: 'Cash savings',
    investments: 'Investments',
    gold: 'Gold',
    silver: 'Silver',
    debts: 'Deductible debts',
    nonZakat: 'Non-zakat assets',
    goldPrice: 'Gold price per gram',
    silverPrice: 'Silver price per gram',
    zakatableAmount: 'Zakatable amount',
    zakatAmount: 'Zakat amount 2.5%',
    zakatDisclaimer: 'This calculator is an estimate for planning purposes. Please consult a qualified religious authority for special cases.',
    nisabNote: 'Gold and silver prices will be connected later to calculate nisab automatically. Manual input is available now.',
    hawlTracking: 'Hijri Hawl Tracking',
    assetName: 'Asset name',
    assetType: 'Asset type',
    ownershipDate: 'Ownership date',
    dueDate: 'Expected zakat due date',
    reminder: 'Reminder 30 days before due date',
    addAsset: 'Save zakat asset',
    projects: 'Charity Projects',
    templates: 'Project Templates',
    forecast: 'Expected Charity Commitments This Year',
    forecastEmpty: 'Add zakat, sponsorships, or projects to calculate expected commitments.',
    impact: 'Impact Analysis',
    donationAmount: 'Donation amount',
    incomeMissing: 'Add income data to analyze donation impact on your budget.',
    donationPercent: 'This donation equals {pct}% of your monthly income.',
    remainingNet: 'After this donation, expected monthly net is {amount}.',
    highWarning: 'Warning: this donation is high compared with your income this month.',
    emptyTitle: 'No charity projects yet.',
    emptyBody: 'Start by adding a charity project to track donations, due dates, and impact.',
    target: 'Financial target',
    collected: 'Collected',
    remaining: 'Remaining',
    organization: 'Executing organization',
    category: 'Category',
    status: 'Status',
    startDate: 'Start date',
    endDate: 'End date',
    notes: 'Notes',
    linkedDonations: 'Linked donations',
    view: 'View details',
    addDonation: 'Add donation',
    edit: 'Edit',
    archive: 'Archive',
    saveProject: 'Save project',
    cancel: 'Cancel',
    projectName: 'Project name',
    comingSoon: 'Coming soon',
    futureTitle: 'Future features',
    reports: 'Reports',
    annualPdfReport: 'Annual Charity PDF Report',
    generateReport: 'Generate Report',
    reportYear: 'Report year',
    exportExcel: 'Export Excel',
    preparingExcel: 'Preparing Excel file...',
    excelExported: 'Excel file exported successfully.',
    excelExportFailed: 'Could not export Excel file.',
    emptyReportExported: 'Not enough data. An empty report will be exported.',
    emptyReportsBody: 'No saved reports yet. Open the reports tab to generate or export an annual charity summary.',
    projectListDesc: 'Manage charity projects, donations, documents, beneficiaries, contributors, and reports from one organized workspace.',
    searchProjects: 'Search projects',
    noFilteredProjects: 'No projects match the current filters.',
    noFilteredProjectsBody: 'Adjust search or filters to see matching charity projects.',
    reportsDesc: 'Generate annual summaries from your saved charity projects, donations, zakat records, beneficiaries, and documents.',
    yearlyCharityReport: 'Annual charity report',
    yearlyReportDesc: 'A structured yearly overview of donations, projects, impact, documents, and reminders.',
    donationsReport: 'Donations report',
    donationsReportDesc: 'Review recorded donations by project, date, contributor, and currency.',
    zakatKhumsReport: 'Zakat and dues report',
    zakatKhumsReportDesc: 'Summarize saved zakat calculations and related obligations for the selected year.',
    beneficiariesReport: 'Beneficiaries report',
    beneficiariesReportDesc: 'Summarize active beneficiaries, sponsorships, renewals, and linked projects.',
    exportPdf: 'Export PDF',
    notEnoughReportData: 'Not enough saved data to generate this report yet.',
    documentsEmptyBody: 'Upload receipts, certificates, or reports to keep the document vault organized.',
    beneficiariesEmptyBody: 'Add beneficiaries or sponsorship cases to start tracking support and renewals.',
    contributorsEmptyBody: 'Add contributors to coordinate pledged and paid amounts by project.',
    noContributors: 'No contributors saved yet.',
    documentVault: 'Document Vault',
    documentVaultDesc: 'Store donation receipts, charity certificates, and project reports in one place.',
    documentsCenter: 'Documents Center',
    uploadDocument: 'Upload Document',
    documentTitle: 'Document title',
    documentCategory: 'Category',
    linkProject: 'Link to project',
    linkDonation: 'Link to donation',
    linkZakatAsset: 'Link to zakat asset',
    linkCommitment: 'Link to commitment',
    chooseFile: 'Choose file',
    searchDocuments: 'Search documents',
    allCategories: 'All categories',
    noDocuments: 'No documents saved yet.',
    fileTooLarge: 'File is too large.',
    unsupportedFileType: 'Unsupported file type.',
    uploadFailed: 'Upload failed.',
    documentUploaded: 'Document uploaded successfully.',
    documentDeleted: 'Document deleted successfully.',
    openDocumentFailed: 'Could not open the document right now.',
    confirmDeleteDocument: 'Do you want to delete this document?',
    viewDocument: 'View',
    downloadDocument: 'Download',
    deleteDocument: 'Delete',
    documentsCount: 'Documents: {count}',
    searchInsideSoon: 'Search inside files coming soon.',
    donation_receipt: 'Donation receipt',
    charity_certificate: 'Charity certificate',
    project_report: 'Project report',
    zakat_document: 'Zakat document',
    beneficiary_report: 'Beneficiary report',
    hijriCalendar: 'Hijri Charity Calendar',
    hijriCalendarDesc: 'Track zakat, hawl, Ramadan, Dhul Hijjah, sacrifice, sponsorships, and project deadlines in one place.',
    upcomingReminders: 'Upcoming Reminders',
    addReminder: 'Add Reminder',
    editReminders: 'Edit reminders',
    reminderTitle: 'Reminder title',
    reminderType: 'Reminder type',
    hijriDate: 'Hijri date',
    remindBefore: 'Remind me before',
    priority: 'Priority',
    hijriEstimated: 'Hijri date is estimated',
    preciseHijriLater: 'Precise Hijri dates will be enabled later.',
    completedAction: 'Completed',
    dismissAction: 'Dismiss',
    deleteAction: 'Delete',
    noReminders: 'No upcoming reminders right now',
    reminderEmptyBody: 'Add a reminder for zakat, Ramadan, or charity projects.',
    reminderSaved: 'Reminder saved successfully.',
    reminderUpdated: 'Reminder updated.',
    reminderDeleted: 'Reminder deleted.',
    confirmDeleteReminder: 'Do you want to delete this reminder?',
    daysBefore: '{days} days before',
    daysRemaining: '{days} days remaining',
    dueToday: 'Due today',
    overdue: '{days} days overdue',
    smartAlerts: 'Smart Alerts',
    noUrgentAlerts: 'No urgent alerts right now.',
    seasonalReminders: 'Islamic charity seasons',
    notificationNote: 'These reminders appear inside Charity Projects for now. External notifications are not enabled yet.',
    ramadanPlanning: 'Ramadan planning',
    ramadanPlanningDesc: 'Prepare giving, iftar, and sponsorship plans before the month begins.',
    lastTenNights: 'Last 10 nights',
    lastTenNightsDesc: 'Plan nightly giving, worship reminders, and zakat al-fitr.',
    arafahDay: 'Arafah day',
    eidAdha: 'Eid Al-Adha / sacrifice',
    eidAdhaDesc: 'Track sacrifice timing, payment, and related documents.',
    zakatAnnualReview: 'Annual zakat review',
    nextZakatDue: 'Next zakat due',
    monthlyCharity: 'Monthly charity',
    monthlyCharityDesc: 'Keep a monthly reminder for ongoing charity and sponsorships.',
    charityReminders: 'Charity reminders',
    zakatCalendarEmptyHint: 'Add a zakat asset or reminder to show the next date.',
    low: 'Low',
    normal: 'Normal',
    high: 'High',
    active: 'Active',
    dismissed: 'Dismissed',
    hawl: 'Hawl',
    ramadan: 'Ramadan',
    dhul_hijjah: 'Dhul Hijjah',
    arafah: 'Arafah',
    project_milestone: 'Project milestone',
    goldNisab: 'Gold-based Nisab',
    silverNisab: 'Silver-based Nisab',
    reachedNisabQuestion: 'Have you reached Nisab?',
    reachedNisab: 'You have reached Nisab',
    notReachedNisab: 'You have not reached Nisab yet',
    automaticPrice: 'Automatic price',
    manualPrice: 'Manual price',
    nisabMethod: 'Nisab calculation method',
    goldBased: 'Gold-based',
    silverBased: 'Silver-based',
    conservative: 'More conservative',
    metalsStatus: 'Gold and Silver Price Status',
    lastUpdated: 'Last updated',
    priceSource: 'Price source',
    apiNotConfigured: 'Metals price API is not configured. Please enter prices manually.',
    metalsConversionWarning: 'Could not automatically convert metal prices to KWD. Please enter the price manually.',
    enterPriceManually: 'Enter price manually',
    refreshPrices: 'Refresh prices',
    metalsDisclaimer: 'Gold and silver prices are estimates and may vary by purity, source, and local market price. Use these prices as a reference and consult a qualified authority for specific religious cases.',
    zakatInputs: 'Zakat Inputs',
    zakatSummaryTitle: 'Zakat Summary',
    zakatGuidanceTitle: 'Religious & Planning Notes',
    cashSavings: 'Cash / Savings',
    zakatableInvestments: 'Zakatable investments',
    goldHoldings: 'Gold holdings',
    goldWeight: 'Gold weight in grams',
    goldKarat: 'Gold karat',
    directGoldValue: 'Or enter value directly',
    silverHoldings: 'Silver holdings',
    silverWeight: 'Silver weight in grams',
    directSilverValue: 'Or enter value directly',
    nonZakatableAssets: 'Non-zakatable assets',
    personalHome: 'Personal home',
    personalCar: 'Personal car',
    householdFurniture: 'Household furniture',
    personalTools: 'Personal tools',
    residentialLand: 'Residential land',
    personalUseAssets: 'Personal-use assets',
    otherNonZakatAsset: 'Describe other non-zakatable asset',
    nonZakatHelper: 'Exclude non-zakatable assets such as a personal home, private car, and used household furniture.',
    goldPriceToday: 'Gold price today',
    silverPriceToday: 'Silver price today',
    liveStatus: 'Live',
    manualStatus: 'Manual',
    failedStatus: 'Update failed',
    manualFallback: 'Could not load gold and silver prices. You can enter prices manually temporarily.',
    usedNisab: 'Selected Nisab',
    netZakatBase: 'Net zakat base',
    zakatDue: 'Zakat due',
    zakatRate: 'Zakat rate 2.5%',
    dueSummary: 'You have reached Nisab. Estimated zakat due is:',
    notDueSummary: 'You have not reached Nisab based on the current inputs.',
    incompleteZakat: 'Complete price or asset data to calculate zakat accurately.',
    differenceFromNisab: 'Difference from Nisab',
    calculationMethod: 'Calculation method',
    saveZakatCalculation: 'Save Zakat Calculation',
    zakatHistory: 'Zakat History',
    noZakatHistory: 'No saved zakat calculations yet.',
    calculationSaved: 'Zakat calculation saved.',
    calculationDeleted: 'Zakat calculation deleted.',
    completedHawl: 'Hawl completed',
    upcomingHawl: 'Hawl upcoming',
    missingOwnershipDate: 'Ownership date incomplete',
    closeToNisabNote: 'You are close to Nisab. Monitor savings and investments in the coming period.',
    aboveNisabNote: 'The estimated zakat is based on your inputs. Consult a qualified authority for special cases.',
    missingPricesNote: 'Nisab could not be calculated automatically because gold and silver prices are unavailable.',
    highDebtsNote: 'Deductible debts affected the net zakat base.',
    zakatEstimateDisclaimer: 'This calculator is an estimate for planning and tracking. It is not a religious ruling. For special cases, consult a qualified authority.',
    organizationDirectory: 'Charity Organization Directory',
    organizationDirectoryDesc: 'Choose a trusted charity organization and link it to your projects and donations for better transparency and organization.',
    searchOrganization: 'Search charity organization',
    allOrganizations: 'All organizations',
    verifiedOrganizations: 'Verified organizations',
    pendingReview: 'Pending review',
    unverified: 'Unverified',
    verified: 'Verified',
    rejected: 'Rejected',
    organizationType: 'Organization type',
    viewDetails: 'View details',
    selectOrganization: 'Select organization',
    licenseNumber: 'License number',
    trustIndicators: 'Trust Indicators',
    transparency: 'Transparency',
    efficiency: 'Efficiency',
    trackRecord: 'Track record',
    notReviewedYet: 'Not reviewed yet',
    manualOrganizationEntry: 'I cannot find the organization, enter manually',
    selectExecutingOrganization: 'Select executing organization',
    verificationDisclaimer: 'The verification status in this directory is for in-app organization purposes and does not replace checking official sources before donating.',
    noOrganizationsAvailable: 'No charity organizations are currently available in the directory. Organizations can be added later through an admin panel or trusted import file.',
    dataSource: 'Data source',
    unverifiedOrganizationWarning: 'This organization is not verified inside the app. Check the official source before donating.',
    charity: 'Charity',
    zakat_house: 'Zakat house',
    humanitarian: 'Humanitarian',
    waqf: 'Waqf',
    impactDashboard: 'Impact Dashboard',
    impactDashboardDesc: 'See the impact of your donations and charity projects based on your recorded data.',
    notEnoughImpactData: 'Not enough data to show impact right now.',
    impactEmptyBody: 'Add charity projects or donations to start tracking impact.',
    totalDonated: 'Total donated',
    activeCharityProjects: 'Active charity projects',
    completedProjects: 'Completed projects',
    beneficiariesSupported: 'Beneficiaries supported',
    monthlySponsorships: 'Monthly sponsorships',
    estimatedZakatImpact: 'Estimated zakat',
    projectImpactProgress: 'Project impact progress',
    completionRate: 'Completion rate',
    givingIncomeRatio: 'Giving-to-Income Ratio',
    impactOverTime: 'Impact Over Time',
    impactByCategory: 'Impact by Category',
    beneficiaryImpact: 'Beneficiary impact',
    yearlyImpactSummary: 'Yearly impact summary',
    customImpactIndicators: 'Custom impact indicators',
    addImpactMetric: 'Add impact metric',
    metricName: 'Metric name',
    metricValue: 'Metric value',
    metricUnit: 'Metric unit',
    referenceBenchmark: 'Reference benchmark',
    addIncomeForGivingRatio: 'Add income data to calculate your giving-to-income ratio.',
    customImpactHint: 'You can add custom impact indicators to each project for more accurate results.',
    projectContributions: 'Project contributions',
    sponsorshipAmount: 'Sponsorship amount',
    currentMonth: 'Current month',
    thisYear: 'This year',
    metricSaved: 'Impact metric saved.',
    beneficiaryTracking: 'Beneficiary Tracking',
    beneficiaryDesc: 'Track sponsorships, charity cases, and beneficiaries linked to your projects in an organized and secure way.',
    privacyNote: 'Use a reference number or short label instead of sensitive personal information.',
    addBeneficiary: 'Add Beneficiary',
    shortName: 'Short name / label',
    referenceNumber: 'Reference number',
    beneficiaryType: 'Beneficiary type',
    linkedProject: 'Linked project',
    responsibleOrg: 'Responsible organization',
    country: 'Country',
    city: 'City',
    monthlySupport: 'Monthly support amount',
    currency: 'Currency',
    sponsorshipStart: 'Sponsorship start date',
    sponsorshipEnd: 'Sponsorship end date',
    nextRenewal: 'Next renewal date',
    totalBeneficiaries: 'Total Beneficiaries',
    activeSponsorships: 'Active Sponsorships',
    monthlySupportTotal: 'Monthly Support',
    upcomingRenewals: 'Upcoming Renewals',
    searchBeneficiaries: 'Search beneficiaries',
    allStatuses: 'All statuses',
    allTypes: 'All categories',
    noBeneficiaries: 'No beneficiaries yet.',
    addSupport: 'Add support',
    linkedDocuments: 'Linked documents',
    beneficiariesCount: 'Beneficiaries: {count}',
    beneficiarySaved: 'Beneficiary saved successfully.',
    beneficiaryDeleted: 'Beneficiary deleted.',
    confirmDeleteBeneficiary: 'Do you want to delete this beneficiary?',
    renewalReminderCreated: 'Renewal reminder created.',
    familyCollaboration: 'Contributors',
    collaborationDesc: 'Add family members or contributors to a project and track each person’s contribution and coverage percentage.',
    addContributor: 'Add Contributor',
    contributorName: 'Contributor name',
    emailOptional: 'Email optional',
    role: 'Role',
    pledgedAmount: 'Pledged amount',
    paidAmount: 'Paid amount',
    paymentStatus: 'Payment status',
    markPaid: 'Mark as Paid',
    totalPledged: 'Total pledged',
    totalPaid: 'Total paid',
    contributors: 'Contributors',
    projectCoverage: 'Project coverage',
    contributorSummary: 'Contributors Summary',
    contributorPayments: 'Contributor payments',
    recordedDonations: 'Recorded donations',
    invitationsSoon: 'Invitations coming soon',
    emailSaved: 'Email saved for follow-up. Sending invitations will be available later.',
    contributorSaved: 'Contributor saved successfully.',
    contributorDeleted: 'Contributor deleted.',
    contributorPaid: 'Contributor payment updated.',
    confirmDeleteContributor: 'Do you want to delete this contributor?',
    lateContribution: 'Late contribution',
    contributorsCount: 'Contributors: {count}',
    topContributor: 'Top contributor',
    owner: 'Owner',
    contributor: 'Contributor',
    viewer: 'Viewer',
    pending: 'Pending',
    paid: 'Paid',
    partial: 'Partial',
    late: 'Late',
    cancelled: 'Cancelled',
    needs_review: 'Needs review',
    orphan: 'Orphan',
    family: 'Family',
    student: 'Student',
    medical: 'Medical',
    elderly: 'Elderly',
    refugee: 'Refugee',
    project_group: 'Project group',
    saved: 'Saved successfully.',
    error: 'This action could not be completed right now.',
    planning: 'Planning',
    fundraising: 'Fundraising',
    in_progress: 'In progress',
    completed: 'Completed',
    paused: 'Paused',
    ongoing: 'Ongoing charity',
    sponsorship: 'Sponsorship',
    zakat: 'Zakat',
    sacrifice: 'Sacrifice',
    endowment: 'Endowment',
    mosque: 'Mosque construction',
    water_well: 'Water well',
    education: 'Education',
    relief: 'Relief',
    other: 'Other',
    monthly: 'Monthly',
    annual: 'Annual',
    once: 'One-time',
    projectDetails: 'Project details',
    financialDetails: 'Financial details',
    organizationDetails: 'Organization details',
    additionalDetails: 'Additional details',
    reminderDetails: 'Reminder details',
    reminderLinks: 'Reminder links',
    documentDetails: 'Document details',
    documentLinks: 'Document links',
    beneficiaryIdentity: 'Beneficiary details',
    sponsorshipDetails: 'Sponsorship details',
    contributorDetails: 'Contributor details',
    contributionDetails: 'Contribution details',
  },
  fr: {
    title: 'Projets caritatifs',
    subtitle: 'Planifiez la zakat, le khums, les parrainages, les dons et les projets caritatifs à long terme.',
    breadcrumb: 'THE SFM / Projets caritatifs',
    newProject: 'Nouveau projet caritatif',
    zakatCalculator: 'Calculateur de zakat',
    activeProjects: 'Projets actifs',
    totalDonations: 'Total des dons',
    commitments: 'Engagements caritatifs prévus',
    estimatedZakat: 'Zakat estimée',
    nextZakat: 'Prochaine échéance de zakat',
    noDueDate: 'Aucune échéance',
    nextDueDateKpi: 'Prochaine échéance',
    beneficiariesCountKpi: 'Bénéficiaires',
    upcomingRemindersKpi: 'Rappels à venir',
    unavailable: 'Indisponible',
    smartZakat: 'Calculateur intelligent de zakat',
    cash: 'Épargne en espèces',
    investments: 'Investissements',
    gold: 'Or',
    silver: 'Argent',
    debts: 'Dettes déductibles',
    nonZakat: 'Actifs non soumis à la zakat',
    goldPrice: "Prix de l'or par gramme",
    silverPrice: "Prix de l'argent par gramme",
    zakatableAmount: 'Montant soumis à la zakat',
    zakatAmount: 'Montant de zakat 2,5 %',
    zakatDisclaimer: 'Ce calculateur fournit une estimation à des fins d’organisation. Consultez une autorité religieuse qualifiée pour les cas particuliers.',
    nisabNote: "Les prix de l’or et de l’argent seront connectés plus tard pour calculer le nisab automatiquement. La saisie manuelle est disponible.",
    hawlTracking: 'Suivi du hawl hijri',
    assetName: "Nom de l'actif",
    assetType: "Type d'actif",
    ownershipDate: "Date d'acquisition",
    dueDate: 'Date de zakat prévue',
    reminder: "Rappel 30 jours avant l'échéance",
    addAsset: "Enregistrer l'actif",
    projects: 'Projets caritatifs',
    templates: 'Modèles de projets',
    forecast: 'Engagements caritatifs prévus cette année',
    forecastEmpty: 'Ajoutez la zakat, les parrainages ou les projets pour calculer les engagements prévus.',
    impact: "Analyse d'impact",
    donationAmount: 'Montant du don',
    incomeMissing: 'Ajoutez vos revenus pour analyser l’impact du don sur votre budget.',
    donationPercent: 'Ce don représente {pct}% de votre revenu mensuel.',
    remainingNet: 'Après ce don, le net mensuel prévu est {amount}.',
    highWarning: 'Attention : ce don est élevé par rapport à votre revenu ce mois-ci.',
    emptyTitle: 'Aucun projet caritatif pour le moment.',
    emptyBody: 'Ajoutez un projet caritatif pour suivre les dons, les échéances et l’impact.',
    target: 'Objectif financier',
    collected: 'Collecté',
    remaining: 'Restant',
    organization: 'Organisation exécutante',
    category: 'Catégorie',
    status: 'Statut',
    startDate: 'Date de début',
    endDate: 'Date de fin',
    notes: 'Notes',
    linkedDonations: 'Dons liés',
    view: 'Voir les détails',
    addDonation: 'Ajouter un don',
    edit: 'Modifier',
    archive: 'Archiver',
    saveProject: 'Enregistrer le projet',
    cancel: 'Annuler',
    projectName: 'Nom du projet',
    comingSoon: 'Bientôt',
    futureTitle: 'Fonctionnalités à venir',
    reports: 'Rapports',
    annualPdfReport: 'Rapport annuel caritatif PDF',
    generateReport: 'Générer le rapport',
    reportYear: 'Année du rapport',
    exportExcel: 'Exporter Excel',
    preparingExcel: 'Préparation du fichier Excel...',
    excelExported: 'Fichier Excel exporté avec succès.',
    excelExportFailed: 'Impossible d’exporter le fichier Excel.',
    emptyReportExported: 'Données insuffisantes. Un rapport vide sera exporté.',
    emptyReportsBody: 'Ajoutez des projets ou des dons pour commencer à créer des rapports.',
    projectListDesc: 'Gérez les projets caritatifs, les dons, les documents, les bénéficiaires, les contributeurs et les rapports au même endroit.',
    searchProjects: 'Rechercher des projets',
    noFilteredProjects: 'Aucun projet ne correspond aux filtres actuels.',
    noFilteredProjectsBody: 'Modifiez la recherche ou les filtres pour afficher d’autres projets.',
    reportsDesc: 'Générez des synthèses annuelles à partir de vos projets, dons, données de zakat, bénéficiaires et documents.',
    yearlyCharityReport: 'Rapport caritatif annuel',
    yearlyReportDesc: 'Vue annuelle structurée des dons, projets, bénéficiaires et de l’impact.',
    donationsReport: 'Rapport des dons',
    donationsReportDesc: 'Analyse des dons enregistrés par année et par projet.',
    zakatKhumsReport: 'Rapport zakat et khums',
    zakatKhumsReportDesc: 'Affiche les données de zakat et de khums liées à ce module lorsqu’elles sont disponibles.',
    beneficiariesReport: 'Rapport des bénéficiaires',
    beneficiariesReportDesc: 'Résumé des bénéficiaires, parrainages et renouvellements à venir.',
    exportPdf: 'Exporter PDF',
    notEnoughReportData: 'Données insuffisantes pour générer un rapport pour le moment.',
    documentsEmptyBody: 'Conservez les reçus de dons, certificats d’associations et rapports de projets au même endroit.',
    beneficiariesEmptyBody: 'Ajoutez les bénéficiaires liés à vos projets pour organiser les cas et les parrainages.',
    contributorsEmptyBody: 'Ajoutez les membres de la famille ou contributeurs pour suivre leurs contributions et la couverture.',
    noContributors: 'Aucun contributeur ajouté pour le moment.',
    documentVault: 'Coffre de documents',
    documentVaultDesc: 'Conservez les reçus de dons, les certificats d’associations et les rapports de projets au même endroit.',
    documentsCenter: 'Centre des documents',
    uploadDocument: 'Téléverser un document',
    documentTitle: 'Titre du document',
    documentCategory: 'Catégorie',
    linkProject: 'Lier à un projet',
    linkDonation: 'Lier à un don',
    linkZakatAsset: 'Lier à un actif de zakat',
    linkCommitment: 'Lier à un engagement',
    chooseFile: 'Choisir un fichier',
    searchDocuments: 'Rechercher des documents',
    allCategories: 'Toutes les catégories',
    noDocuments: 'Aucun document enregistré pour le moment.',
    fileTooLarge: 'Le fichier est trop volumineux.',
    unsupportedFileType: 'Type de fichier non pris en charge.',
    uploadFailed: 'Impossible de téléverser le fichier.',
    documentUploaded: 'Document téléversé avec succès.',
    documentDeleted: 'Document supprimé avec succès.',
    openDocumentFailed: 'Impossible d’ouvrir le document pour le moment.',
    confirmDeleteDocument: 'Voulez-vous supprimer ce document ?',
    viewDocument: 'Voir',
    downloadDocument: 'Télécharger',
    deleteDocument: 'Supprimer',
    documentsCount: 'Documents : {count}',
    searchInsideSoon: 'Recherche dans les fichiers bientôt disponible.',
    donation_receipt: 'Reçu de don',
    charity_certificate: 'Certificat d’association',
    project_report: 'Rapport de projet',
    zakat_document: 'Document de zakat',
    beneficiary_report: 'Rapport de bénéficiaire',
    hijriCalendar: 'Calendrier caritatif hijri',
    hijriCalendarDesc: 'Suivez la zakat, le hawl, Ramadan, Dhul Hijjah, le sacrifice, les parrainages et les échéances de projets.',
    upcomingReminders: 'Rappels à venir',
    addReminder: 'Ajouter un rappel',
    editReminders: 'Modifier les rappels',
    reminderTitle: 'Titre du rappel',
    reminderType: 'Type de rappel',
    hijriDate: 'Date hijri',
    remindBefore: 'Me rappeler avant',
    priority: 'Priorité',
    hijriEstimated: 'La date hijri est estimée',
    preciseHijriLater: 'Les dates hijri précises seront activées ultérieurement.',
    completedAction: 'Terminé',
    dismissAction: 'Ignorer',
    deleteAction: 'Supprimer',
    noReminders: 'Aucun rappel à venir pour le moment',
    reminderEmptyBody: 'Ajoutez un rappel pour la zakat, Ramadan ou les projets caritatifs.',
    reminderSaved: 'Rappel enregistré avec succès.',
    reminderUpdated: 'Rappel mis à jour.',
    reminderDeleted: 'Rappel supprimé.',
    confirmDeleteReminder: 'Voulez-vous supprimer ce rappel ?',
    daysBefore: '{days} jours avant',
    daysRemaining: '{days} jours restants',
    dueToday: "Échéance aujourd'hui",
    overdue: 'En retard de {days} jours',
    smartAlerts: 'Alertes intelligentes',
    noUrgentAlerts: 'Aucune alerte urgente pour le moment.',
    seasonalReminders: 'Saisons caritatives islamiques',
    notificationNote: 'Ces rappels apparaissent dans Projets caritatifs pour le moment. Les notifications externes ne sont pas encore activées.',
    ramadanPlanning: 'Ramadan',
    ramadanPlanningDesc: 'Préparez les dons, iftars et parrainages avant le début du mois.',
    lastTenNights: 'Les 10 dernières nuits',
    lastTenNightsDesc: 'Planifiez les dons nocturnes, les rappels de culte et la zakat al-fitr.',
    arafahDay: 'Jour de Arafah',
    eidAdha: 'Aïd Al-Adha / sacrifice',
    eidAdhaDesc: 'Suivez la date du sacrifice, le paiement et les documents liés.',
    zakatAnnualReview: 'Révision annuelle de la zakat',
    nextZakatDue: 'Prochaine zakat',
    monthlyCharity: 'Don mensuel',
    monthlyCharityDesc: 'Gardez un rappel mensuel pour les dons continus et les parrainages.',
    charityReminders: 'Rappels caritatifs',
    zakatCalendarEmptyHint: 'Ajoutez un actif de zakat ou un rappel pour afficher la prochaine date.',
    low: 'Faible',
    normal: 'Normale',
    high: 'Élevée',
    active: 'Actif',
    dismissed: 'Ignoré',
    hawl: 'Hawl',
    ramadan: 'Ramadan',
    dhul_hijjah: 'Dhul Hijjah',
    arafah: 'Arafah',
    project_milestone: 'Jalon de projet',
    goldNisab: 'Nisab basé sur l’or',
    silverNisab: 'Nisab basé sur l’argent',
    reachedNisabQuestion: 'Avez-vous atteint le nisab ?',
    reachedNisab: 'Vous avez atteint le nisab',
    notReachedNisab: 'Vous n’avez pas encore atteint le nisab',
    automaticPrice: 'Prix automatique',
    manualPrice: 'Prix manuel',
    nisabMethod: 'Méthode de calcul du nisab',
    goldBased: 'Basé sur l’or',
    silverBased: 'Basé sur l’argent',
    conservative: 'Plus prudent',
    metalsStatus: 'État des prix de l’or et de l’argent',
    lastUpdated: 'Dernière mise à jour',
    priceSource: 'Source du prix',
    apiNotConfigured: 'L’API des prix des métaux n’est pas configurée. Veuillez saisir les prix manuellement.',
    metalsConversionWarning: 'Impossible de convertir automatiquement les prix des métaux en KWD. Veuillez saisir le prix manuellement.',
    enterPriceManually: 'Saisir le prix manuellement',
    refreshPrices: 'Actualiser les prix',
    metalsDisclaimer: 'Les prix de l’or et de l’argent sont estimatifs et peuvent varier selon la pureté, la source et le marché local. Utilisez-les comme référence et consultez une autorité qualifiée pour les cas religieux spécifiques.',
    zakatInputs: 'Données de zakat',
    zakatSummaryTitle: 'Résumé de la zakat',
    zakatGuidanceTitle: 'Notes religieuses et d’organisation',
    cashSavings: 'Espèces / épargne',
    zakatableInvestments: 'Investissements soumis à la zakat',
    goldHoldings: 'Or',
    goldWeight: 'Poids de l’or en grammes',
    goldKarat: 'Carat de l’or',
    directGoldValue: 'Ou saisir la valeur directement',
    silverHoldings: 'Argent',
    silverWeight: 'Poids de l’argent en grammes',
    directSilverValue: 'Ou saisir la valeur directement',
    nonZakatableAssets: 'Actifs non soumis à la zakat',
    personalHome: 'Résidence personnelle',
    personalCar: 'Voiture personnelle',
    householdFurniture: 'Mobilier du foyer',
    personalTools: 'Objets personnels',
    residentialLand: 'Terrain résidentiel',
    personalUseAssets: 'Actifs à usage personnel',
    otherNonZakatAsset: 'Décrire un autre actif non soumis à la zakat',
    nonZakatHelper: 'Excluez les actifs non soumis à la zakat comme la résidence personnelle, la voiture privée et le mobilier utilisé.',
    goldPriceToday: 'Prix de l’or aujourd’hui',
    silverPriceToday: 'Prix de l’argent aujourd’hui',
    liveStatus: 'Direct',
    manualStatus: 'Manuel',
    failedStatus: 'Échec de mise à jour',
    manualFallback: 'Impossible de charger les prix de l’or et de l’argent. Vous pouvez saisir les prix manuellement temporairement.',
    usedNisab: 'Nisab utilisé',
    netZakatBase: 'Base nette de zakat',
    zakatDue: 'Zakat due',
    zakatRate: 'Taux de zakat 2,5 %',
    dueSummary: 'Vous avez atteint le nisab. La zakat estimée due est :',
    notDueSummary: 'Vous n’avez pas atteint le nisab selon les données actuelles.',
    incompleteZakat: 'Complétez les prix ou les actifs pour calculer la zakat avec précision.',
    differenceFromNisab: 'Écart par rapport au nisab',
    calculationMethod: 'Méthode de calcul',
    saveZakatCalculation: 'Enregistrer le calcul de zakat',
    zakatHistory: 'Historique des calculs de zakat',
    noZakatHistory: 'Aucun calcul de zakat enregistré pour le moment.',
    calculationSaved: 'Calcul de zakat enregistré.',
    calculationDeleted: 'Calcul de zakat supprimé.',
    completedHawl: 'Hawl terminé',
    upcomingHawl: 'Hawl à venir',
    missingOwnershipDate: 'Date d’acquisition incomplète',
    closeToNisabNote: 'Vous êtes proche du nisab. Surveillez l’épargne et les investissements prochainement.',
    aboveNisabNote: 'La zakat estimée est basée sur vos données. Consultez une autorité qualifiée pour les cas particuliers.',
    missingPricesNote: 'Le nisab ne peut pas être calculé automatiquement car les prix de l’or et de l’argent sont indisponibles.',
    highDebtsNote: 'Les dettes déductibles ont affecté la base nette de zakat.',
    zakatEstimateDisclaimer: 'Ce calculateur fournit une estimation à des fins d’organisation et de suivi. Il ne constitue pas un avis religieux. Pour les cas particuliers, consultez une autorité qualifiée.',
    organizationDirectory: 'Répertoire des organisations caritatives',
    organizationDirectoryDesc: 'Choisissez une organisation caritative fiable et liez-la à vos projets et dons pour plus de transparence et d’organisation.',
    searchOrganization: 'Rechercher une organisation caritative',
    allOrganizations: 'Toutes les organisations',
    verifiedOrganizations: 'Organisations vérifiées',
    pendingReview: 'En cours d’examen',
    unverified: 'Non vérifiée',
    verified: 'Vérifiée',
    rejected: 'Rejetée',
    organizationType: 'Type d’organisation',
    viewDetails: 'Voir les détails',
    selectOrganization: 'Sélectionner l’organisation',
    licenseNumber: 'Numéro de licence',
    trustIndicators: 'Indicateurs de confiance',
    transparency: 'Transparence',
    efficiency: 'Efficacité',
    trackRecord: 'Historique',
    notReviewedYet: 'Pas encore évaluée',
    manualOrganizationEntry: 'Je ne trouve pas l’organisation, saisie manuelle',
    selectExecutingOrganization: 'Sélectionner l’organisation exécutante',
    verificationDisclaimer: 'Le statut de vérification dans ce répertoire sert à l’organisation dans l’application et ne remplace pas la vérification auprès des sources officielles avant de faire un don.',
    noOrganizationsAvailable: 'Aucune organisation caritative n’est actuellement disponible dans le répertoire. Les organisations pourront être ajoutées plus tard via un panneau d’administration ou un fichier d’import fiable.',
    dataSource: 'Source des données',
    unverifiedOrganizationWarning: 'Cette organisation n’est pas vérifiée dans l’application. Vérifiez la source officielle avant de faire un don.',
    charity: 'Association caritative',
    zakat_house: 'Maison de zakat',
    humanitarian: 'Humanitaire',
    waqf: 'Waqf',
    impactDashboard: 'Tableau d’impact',
    impactDashboardDesc: 'Visualisez l’impact de vos dons et projets caritatifs à partir de vos données enregistrées.',
    notEnoughImpactData: 'Données insuffisantes pour afficher l’impact pour le moment.',
    impactEmptyBody: 'Ajoutez des projets caritatifs ou des dons pour commencer le suivi de l’impact.',
    totalDonated: 'Total donné',
    activeCharityProjects: 'Projets actifs',
    completedProjects: 'Projets terminés',
    beneficiariesSupported: 'Bénéficiaires soutenus',
    monthlySponsorships: 'Parrainages mensuels',
    estimatedZakatImpact: 'Zakat estimée',
    projectImpactProgress: 'Progression de l’impact des projets',
    completionRate: 'Taux d’achèvement',
    givingIncomeRatio: 'Ratio dons / revenus',
    impactOverTime: 'Évolution de l’impact',
    impactByCategory: 'Impact par catégorie',
    beneficiaryImpact: 'Impact des bénéficiaires',
    yearlyImpactSummary: 'Résumé annuel de l’impact',
    customImpactIndicators: 'Indicateurs d’impact personnalisés',
    addImpactMetric: 'Ajouter un indicateur d’impact',
    metricName: 'Nom de l’indicateur',
    metricValue: 'Valeur de l’indicateur',
    metricUnit: 'Unité de l’indicateur',
    referenceBenchmark: 'Indicateur de référence',
    addIncomeForGivingRatio: 'Ajoutez vos revenus pour calculer le ratio dons / revenus.',
    customImpactHint: 'Vous pouvez ajouter des indicateurs d’impact personnalisés à chaque projet pour des résultats plus précis.',
    projectContributions: 'Contributions aux projets',
    sponsorshipAmount: 'Montant des parrainages',
    currentMonth: 'Mois en cours',
    thisYear: 'Cette année',
    metricSaved: 'Indicateur d’impact enregistré.',
    beneficiaryTracking: 'Suivi des bénéficiaires',
    beneficiaryDesc: 'Suivez les parrainages, les cas caritatifs et les bénéficiaires liés à vos projets de manière organisée et sécurisée.',
    privacyNote: 'Utilisez un numéro de référence ou un libellé court au lieu de données personnelles sensibles.',
    addBeneficiary: 'Ajouter un bénéficiaire',
    shortName: 'Nom court / libellé',
    referenceNumber: 'Numéro de référence',
    beneficiaryType: 'Type de bénéficiaire',
    linkedProject: 'Projet lié',
    responsibleOrg: 'Organisation responsable',
    country: 'Pays',
    city: 'Ville',
    monthlySupport: 'Montant du soutien mensuel',
    currency: 'Devise',
    sponsorshipStart: 'Date de début du parrainage',
    sponsorshipEnd: 'Date de fin du parrainage',
    nextRenewal: 'Prochaine date de renouvellement',
    totalBeneficiaries: 'Total des bénéficiaires',
    activeSponsorships: 'Parrainages actifs',
    monthlySupportTotal: 'Soutien mensuel',
    upcomingRenewals: 'Renouvellements à venir',
    searchBeneficiaries: 'Rechercher des bénéficiaires',
    allStatuses: 'Tous les statuts',
    allTypes: 'Toutes les catégories',
    noBeneficiaries: 'Aucun bénéficiaire pour le moment.',
    addSupport: 'Ajouter un soutien',
    linkedDocuments: 'Documents liés',
    beneficiariesCount: 'Bénéficiaires : {count}',
    beneficiarySaved: 'Bénéficiaire enregistré avec succès.',
    beneficiaryDeleted: 'Bénéficiaire supprimé.',
    confirmDeleteBeneficiary: 'Voulez-vous supprimer ce bénéficiaire ?',
    renewalReminderCreated: 'Rappel de renouvellement créé.',
    familyCollaboration: 'Contributeurs',
    collaborationDesc: 'Ajoutez des membres de la famille ou des contributeurs à un projet et suivez la contribution de chacun.',
    addContributor: 'Ajouter un contributeur',
    contributorName: 'Nom du contributeur',
    emailOptional: 'E-mail facultatif',
    role: 'Rôle',
    pledgedAmount: 'Montant promis',
    paidAmount: 'Montant payé',
    paymentStatus: 'Statut du paiement',
    markPaid: 'Marquer comme payé',
    totalPledged: 'Total promis',
    totalPaid: 'Total payé',
    contributors: 'Contributeurs',
    projectCoverage: 'Couverture du projet',
    contributorSummary: 'Résumé des contributeurs',
    contributorPayments: 'Paiements des contributeurs',
    recordedDonations: 'Dons enregistrés',
    invitationsSoon: 'Invitations bientôt disponibles',
    emailSaved: 'E-mail enregistré pour le suivi. L’envoi d’invitations sera disponible plus tard.',
    contributorSaved: 'Contributeur enregistré avec succès.',
    contributorDeleted: 'Contributeur supprimé.',
    contributorPaid: 'Paiement du contributeur mis à jour.',
    confirmDeleteContributor: 'Voulez-vous supprimer ce contributeur ?',
    lateContribution: 'Contribution en retard',
    contributorsCount: 'Contributeurs : {count}',
    topContributor: 'Meilleur contributeur',
    owner: 'Propriétaire',
    contributor: 'Contributeur',
    viewer: 'Lecteur',
    pending: 'En attente',
    paid: 'Payé',
    partial: 'Partiel',
    late: 'En retard',
    cancelled: 'Annulé',
    needs_review: 'À réviser',
    orphan: 'Orphelin',
    family: 'Famille',
    student: 'Étudiant',
    medical: 'Médical',
    elderly: 'Personne âgée',
    refugee: 'Réfugié',
    project_group: 'Groupe de projet',
    saved: 'Enregistré avec succès.',
    error: "Impossible d'effectuer cette action pour le moment.",
    planning: 'Planification',
    fundraising: 'Collecte',
    in_progress: 'En cours',
    completed: 'Terminé',
    paused: 'En pause',
    ongoing: 'Aumône continue',
    sponsorship: 'Parrainage',
    zakat: 'Zakat',
    sacrifice: 'Sacrifice',
    endowment: 'Waqf',
    mosque: 'Construction de mosquée',
    water_well: "Puits d'eau",
    education: 'Éducation',
    relief: 'Secours',
    other: 'Autre',
    monthly: 'Mensuel',
    annual: 'Annuel',
    once: 'Unique',
    projectDetails: 'Détails du projet',
    financialDetails: 'Détails financiers',
    organizationDetails: 'Détails de l’organisation',
    additionalDetails: 'Détails supplémentaires',
    reminderDetails: 'Détails du rappel',
    reminderLinks: 'Liens du rappel',
    documentDetails: 'Détails du document',
    documentLinks: 'Liens du document',
    beneficiaryIdentity: 'Détails du bénéficiaire',
    sponsorshipDetails: 'Détails du parrainage',
    contributorDetails: 'Détails du contributeur',
    contributionDetails: 'Détails de la contribution',
  },
} as const;

const WINDOWS_1252_REVERSE: Record<string, number> = {
  '€': 0x80,
  '‚': 0x82,
  'ƒ': 0x83,
  '„': 0x84,
  '…': 0x85,
  '†': 0x86,
  '‡': 0x87,
  'ˆ': 0x88,
  '‰': 0x89,
  'Š': 0x8a,
  '‹': 0x8b,
  'Œ': 0x8c,
  'Ž': 0x8e,
  '‘': 0x91,
  '’': 0x92,
  '“': 0x93,
  '”': 0x94,
  '•': 0x95,
  '–': 0x96,
  '—': 0x97,
  '˜': 0x98,
  '™': 0x99,
  'š': 0x9a,
  '›': 0x9b,
  'œ': 0x9c,
  'ž': 0x9e,
  'Ÿ': 0x9f,
};

function repairMojibakeText(value: string) {
  if (!/[ÃÂØÙ]/.test(value)) return value;

  const bytes = Array.from(value, char => {
    const code = char.codePointAt(0) ?? 0;
    return WINDOWS_1252_REVERSE[char] ?? (code <= 0xff ? code : null);
  });

  if (bytes.some(byte => byte === null)) return value;

  try {
    const repaired = new TextDecoder('utf-8').decode(new Uint8Array(bytes as number[]));
    return /[\u0600-\u06ffÀ-ÿ]/.test(repaired) ? repaired : value;
  } catch {
    return value;
  }
}

function repairTextDictionary<T>(value: T): T {
  if (typeof value === 'string') return repairMojibakeText(value) as T;
  if (Array.isArray(value)) return value.map(item => repairTextDictionary(item)) as T;
  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>).map(([key, item]) => [key, repairTextDictionary(item)]),
    ) as T;
  }
  return value;
}

const ARABIC_COPY_OVERRIDES = {
  title: 'المشاريع الخيرية',
  subtitle: 'خطط للزكاة، الخمس، الكفالات، الصدقات، والمشاريع الخيرية طويلة الأمد بذكاء.',
  breadcrumb: 'THE SFM / المشاريع الخيرية',
  newProject: 'مشروع خيري جديد',
  addReminder: 'إضافة تذكير',
  uploadDocument: 'رفع مستند',
  reports: 'التقارير',
  activeProjects: 'إجمالي المشاريع النشطة',
  totalDonations: 'إجمالي التبرعات',
  nextDueDateKpi: 'أقرب موعد',
  beneficiariesCountKpi: 'عدد المستفيدين',
  upcomingRemindersKpi: 'التذكيرات القادمة',
  unavailable: 'غير متاح',
  projects: 'المشاريع الخيرية',
  projectListDesc: 'تابع المشاريع الخيرية وحالتها والتبرعات والمواعيد والأثر من مكان واحد.',
  searchProjects: 'ابحث في المشاريع الخيرية',
  emptyTitle: 'لا توجد مشاريع خيرية حالياً',
  emptyBody: 'ابدأ بإضافة مشروع خيري لتتبع التبرعات والمواعيد والأثر.',
  beneficiaryTracking: 'إدارة المستفيدين',
  beneficiaryDesc: 'نظم المستفيدين المرتبطين بالمشاريع والكفالات مع بيانات مختصرة ومحترمة.',
  noBeneficiaries: 'لا توجد مستفيدين حتى الآن',
  beneficiariesEmptyBody: 'أضف المستفيدين المرتبطين بمشاريعك لتنظيم الحالات والكفالات.',
  addBeneficiary: 'إضافة مستفيد',
  contributors: 'المساهمون',
  familyCollaboration: 'المساهمون',
  collaborationDesc: 'أضف أفراد العائلة أو المساهمين لتتبع مساهماتهم ونسبة التغطية.',
  noContributors: 'لم تتم إضافة مساهمين بعد',
  contributorsEmptyBody: 'أضف أفراد العائلة أو المساهمين لتتبع مساهماتهم ونسبة التغطية.',
  addContributor: 'إضافة مساهم',
  documentVault: 'خزانة المستندات',
  documentVaultDesc: 'احفظ إيصالات التبرعات، شهادات الجمعيات، وتقارير المشاريع في مكان واحد.',
  noDocuments: 'لا توجد مستندات محفوظة حتى الآن',
  documentsEmptyBody: 'احفظ إيصالات التبرعات، شهادات الجمعيات، وتقارير المشاريع في مكان واحد.',
  impactDashboard: 'لوحة الأثر',
  impactDashboardDesc: 'اعرض أثر التبرعات والمشاريع والمستفيدين بصورة عملية قابلة للمتابعة.',
  notEnoughImpactData: 'لا توجد بيانات كافية لعرض الأثر حالياً',
  impactEmptyBody: 'يمكنك إضافة مشاريع خيرية أو تبرعات لبدء تتبع الأثر.',
  reportsDesc: 'أنشئ تقارير خيرية مختصرة للتبرعات والمستفيدين والزكاة والخمس.',
  notEnoughReportData: 'لا توجد بيانات كافية لإنشاء تقرير حالياً',
  emptyReportsBody: 'أضف مشاريع أو تبرعات لبدء إنشاء التقارير.',
  yearlyCharityReport: 'التقرير الخيري السنوي',
  zakatKhumsReport: 'تقرير الزكاة والخمس',
  donationsReport: 'تقرير التبرعات',
  beneficiariesReport: 'تقرير المستفيدين',
  exportPdf: 'تصدير PDF',
  exportExcel: 'تصدير Excel',
  generateReport: 'إنشاء تقرير',
  smartZakat: 'حاسبة الزكاة',
  zakatInputs: 'الأموال النقدية والاستثمارات',
  cashSavings: 'الأموال النقدية',
  goldHoldings: 'الذهب',
  silverHoldings: 'الفضة',
  zakatableInvestments: 'الاستثمارات',
  debts: 'الديون',
  zakatSummaryTitle: 'الملخص',
  zakatGuidanceTitle: 'التذكيرات والتنبيهات',
  zakatEstimateDisclaimer: 'هذه الحاسبة تقديرية ولا تُعد فتوى شرعية.',
  metalsDisclaimer: 'هذه الحاسبة تقديرية ولا تُعد فتوى شرعية. راجع جهة شرعية مختصة للحالات الخاصة.',
  hijriCalendar: 'التقويم الخيري الهجري',
  hijriCalendarDesc: 'تابع مواسم العطاء ومواعيد الزكاة والكفالات والتذكيرات القادمة.',
  upcomingReminders: 'التذكيرات القادمة',
  charityReminders: 'التذكيرات الخيرية',
  addAsset: 'حفظ أصل الزكاة',
  projectName: 'اسم المشروع',
  organization: 'الجهة المنفذة',
  status: 'الحالة',
  target: 'الهدف المالي',
  collected: 'المحصّل',
  remaining: 'المتبقي',
  privacyNote: 'معلومات مختصرة ومحترمة',
  allStatuses: 'كل الحالات',
  allTypes: 'كل الأنواع',
  allCategories: 'كل التصنيفات',
  searchBeneficiaries: 'ابحث في المستفيدين',
  searchDocuments: 'ابحث في المستندات',
  searchOrganization: 'ابحث في الجهات',
  organizationDirectory: 'دليل الجهات الخيرية',
  organizationDirectoryDesc: 'اختر جهة منفذة موثوقة واربطها بالمشاريع والتقارير.',
  noOrganizationsAvailable: 'لا توجد جهات متاحة حالياً.',
  totalBeneficiaries: 'إجمالي المستفيدين',
  activeSponsorships: 'الكفالات النشطة',
  monthlySupportTotal: 'إجمالي الدعم الشهري',
  upcomingRenewals: 'التجديدات القادمة',
  totalPledged: 'إجمالي التعهدات',
  totalPaid: 'إجمالي المدفوع',
  contributorSummary: 'ملخص المساهمين',
  contributorPayments: 'مدفوعات المساهمين',
  recordedDonations: 'التبرعات المسجلة',
  pending: 'قيد الانتظار',
  paid: 'مدفوع',
  partial: 'جزئي',
  late: 'متأخر',
  cancelled: 'ملغى',
  planning: 'قيد التخطيط',
  fundraising: 'جمع التبرعات',
  in_progress: 'قيد التنفيذ',
  completed: 'مكتمل',
  paused: 'متوقف مؤقتاً',
  active: 'نشط',
  dismissed: 'مؤجل',
  needs_review: 'تحتاج مراجعة',
  orphan: 'يتيم',
  family: 'أسرة',
  student: 'طالب',
  medical: 'حالة علاجية',
  elderly: 'كبار السن',
  refugee: 'لاجئ',
  project_group: 'مجموعة مشروع',
  ongoing: 'صدقة جارية',
  sponsorship: 'كفالة',
  zakat: 'الزكاة',
  sacrifice: 'أضحية',
  endowment: 'وقف',
  mosque: 'مسجد',
  water_well: 'بئر ماء',
  education: 'تعليم',
  relief: 'إغاثة',
  other: 'أخرى',
} as const;

const REPAIRED_TEXT = repairTextDictionary(RAW_TEXT);

export const TEXT = {
  ...REPAIRED_TEXT,
  ar: {
    ...REPAIRED_TEXT.ar,
    ...ARABIC_COPY_OVERRIDES,
  },
} as const;

