import type { DirectionalBias, IntelligenceFactorKey, IntelligenceRecommendation, IntelligenceRisk } from '@/domain/intelligence/contracts';

export const DASHBOARD_COPY = {
  ar: {
    analysis: 'تحليل', subtitle: 'قراءة السوق وأهم الأدلة في مكان واحد', price: 'السعر الحالي', trend: 'الاتجاه الفني',
    confidence: 'درجة الثقة', confidenceNote: 'جودة الأدلة واتساقها، وليست احتمالاً للربح', recommendation: 'قراءة المحرك', horizon: 'الأفق الزمني', risk: 'مستوى المخاطر', sharia: 'التوافق الشرعي',
    chart: 'الرسم البياني للسعر', summary: 'ملخص التحليل الذكي', keyPoints: 'أبرز الأدلة', fullAnalysis: 'عرض التحليل الكامل',
    news: 'آخر الأخبار والأحداث المؤثرة', allNews: 'عرض جميع الأخبار', headline: 'الخبر', date: 'التاريخ والوقت', source: 'المصدر', impact: 'التأثير', read: 'قراءة الخبر', unclassified: 'غير مصنف',
    levels: 'مستويات السعر المرجعية', rangeHigh: 'أعلى النطاق المرصود', rangeLow: 'أدنى النطاق المرصود', rangeNote: 'نطاق مشتق من الأسعار التاريخية، وليس هدفاً مضموناً أو وقف خسارة.',
    forecasts: 'قراءة النموذج', allHorizons: 'تحليل الآفاق الزمنية', currentHorizon: 'الأفق المحدد', noOtherHorizons: 'افتح تحليل الآفاق للحصول على قراءة مستقلة لكل أفق زمني.',
    asset: 'معلومات الأصل', symbol: 'الرمز', name: 'الاسم', type: 'فئة الأصل', currency: 'عملة التسعير', exchange: 'السوق', provider: 'مزود بيانات السوق',
    watchlist: 'قائمة المتابعة', share: 'مشاركة', copied: 'تم نسخ الرابط', copyFailed: 'تعذر نسخ الرابط', assistant: 'اسأل المساعد عن هذا الأصل',
    unavailable: 'غير متاح', noEvidence: 'لا تتوفر أدلة موثقة حديثة لهذا القسم.', noNews: 'لا تتوفر أخبار موثقة حديثة لهذا الأصل.',
    periodChange: 'تغير الفترة المختارة', periodHigh: 'أعلى إغلاق في الفترة', periodLow: 'أدنى إغلاق في الفترة', periodStart: 'أول إغلاق في الفترة',
    updated: 'بيانات السعر حتى', generated: 'وقت إنشاء التحليل', version: 'إصدار المحرك', engine: 'محرك التحليل', engineNote: 'تحليل SFM مبني على الأدلة. يظهر مزود بيانات السوق بصورة مستقلة عن المحرك التحليلي.',
    evidence: 'سجل الأدلة والتفسير التفصيلي', history: 'الدقة التاريخية والسجل', timeline: 'المسار الزمني للقرار', tools: 'أدوات التحليل', details: 'تفاصيل الأصل',
    score: 'درجة العامل', coverage: 'تغطية البيانات', limitations: 'القيود وشروط الإبطال', notAdvice: 'قراءة تحليلية وليست نصيحة استثمارية شخصية.',
    live: 'مباشر من المصدر', delayed: 'بيانات متأخرة', cached: 'بيانات محفوظة', stale: 'بيانات قديمة', current: 'متاح',
    compliant: 'متوافق', non_compliant: 'غير متوافق', needs_review: 'يحتاج مراجعة',
    readingNote: 'هذه قراءة المحرك للأفق المحدد، وفق الأدلة الموضحة أدناه. راجع اكتمال البيانات وحداثتها قبل اتخاذ القرار.',
    insufficientNote: 'الأدلة الحالية لا تكفي لقراءة اتجاهية موثوقة. لا يتم اختلاق توصية أو أسعار بديلة.',
    partial: 'بيانات جزئية', sourceTime: 'وقت المصدر',
  },
  en: {
    analysis: 'Analysis', subtitle: 'The market reading and essential evidence, in one place', price: 'Current price', trend: 'Technical direction',
    confidence: 'Analysis confidence', confidenceNote: 'Evidence quality and consistency, not a probability of profit', recommendation: 'Engine reading', horizon: 'Time horizon', risk: 'Risk level', sharia: 'Sharia compliance',
    chart: 'Price chart', summary: 'Intelligence summary', keyPoints: 'Key evidence', fullAnalysis: 'View full analysis',
    news: 'Latest news and events', allNews: 'View all news', headline: 'Headline', date: 'Date and time', source: 'Source', impact: 'Impact', read: 'Read article', unclassified: 'Unclassified',
    levels: 'Reference price levels', rangeHigh: 'Observed range high', rangeLow: 'Observed range low', rangeNote: 'A range derived from historical prices, not a guaranteed target or stop-loss.',
    forecasts: 'Model reading', allHorizons: 'Analyze time horizons', currentHorizon: 'Selected horizon', noOtherHorizons: 'Open horizon analysis to obtain an independent reading for each time horizon.',
    asset: 'Asset information', symbol: 'Symbol', name: 'Name', type: 'Asset class', currency: 'Quote currency', exchange: 'Market', provider: 'Market-data provider',
    watchlist: 'Watchlist', share: 'Share', copied: 'Link copied', copyFailed: 'Unable to copy link', assistant: 'Ask the assistant about this asset',
    unavailable: 'Unavailable', noEvidence: 'No current verified evidence is available for this section.', noNews: 'No current verified news is available for this asset.',
    periodChange: 'Selected-period change', periodHigh: 'Highest close in period', periodLow: 'Lowest close in period', periodStart: 'First close in period',
    updated: 'Price data as of', generated: 'Analysis generated', version: 'Engine version', engine: 'Analysis engine', engineNote: 'SFM analysis is evidence-based. The upstream market-data provider is identified separately.',
    evidence: 'Evidence ledger and explanation', history: 'Historical accuracy and history', timeline: 'Decision timeline', tools: 'Analysis tools', details: 'Asset details',
    score: 'Factor score', coverage: 'Data coverage', limitations: 'Limitations and invalidation', notAdvice: 'An analytical reading, not personal investment advice.',
    live: 'Live from source', delayed: 'Delayed', cached: 'Cached', stale: 'Stale data', current: 'Available',
    compliant: 'Compliant', non_compliant: 'Non-compliant', needs_review: 'Needs review',
    readingNote: 'This is the engine reading for the selected horizon, based on the evidence below. Check data coverage and freshness before making a decision.',
    insufficientNote: 'Current evidence is insufficient for a reliable directional reading. No recommendation or replacement prices are invented.',
    partial: 'Partial data', sourceTime: 'Source time',
  },
  fr: {
    analysis: 'Analyse', subtitle: 'La lecture du marché et les preuves essentielles, au même endroit', price: 'Cours actuel', trend: 'Direction technique',
    confidence: 'Confiance', confidenceNote: 'Qualité et cohérence des preuves, pas une probabilité de gain', recommendation: 'Lecture du moteur', horizon: 'Horizon temporel', risk: 'Niveau de risque', sharia: 'Conformité charia',
    chart: 'Graphique du cours', summary: 'Synthèse intelligente', keyPoints: 'Preuves essentielles', fullAnalysis: 'Voir l’analyse complète',
    news: 'Dernières actualités et événements', allNews: 'Toutes les actualités', headline: 'Titre', date: 'Date et heure', source: 'Source', impact: 'Impact', read: 'Lire l’article', unclassified: 'Non classé',
    levels: 'Niveaux de prix de référence', rangeHigh: 'Haut de la plage observée', rangeLow: 'Bas de la plage observée', rangeNote: 'Plage issue des cours historiques ; ni objectif garanti ni stop-loss.',
    forecasts: 'Lecture du modèle', allHorizons: 'Analyser les horizons', currentHorizon: 'Horizon sélectionné', noOtherHorizons: 'Ouvrez l’analyse des horizons pour obtenir une lecture indépendante à chaque horizon.',
    asset: 'Informations sur l’actif', symbol: 'Symbole', name: 'Nom', type: 'Classe d’actifs', currency: 'Devise de cotation', exchange: 'Marché', provider: 'Fournisseur de données de marché',
    watchlist: 'Liste de suivi', share: 'Partager', copied: 'Lien copié', copyFailed: 'Copie du lien impossible', assistant: 'Interroger l’assistant sur cet actif',
    unavailable: 'Indisponible', noEvidence: 'Aucune preuve vérifiée récente n’est disponible pour cette section.', noNews: 'Aucune actualité vérifiée récente pour cet actif.',
    periodChange: 'Variation de la période', periodHigh: 'Clôture la plus haute', periodLow: 'Clôture la plus basse', periodStart: 'Première clôture',
    updated: 'Cours observé le', generated: 'Analyse générée le', version: 'Version du moteur', engine: 'Moteur d’analyse', engineNote: 'L’analyse SFM repose sur des preuves. Le fournisseur de données est identifié séparément.',
    evidence: 'Registre des preuves et explication', history: 'Précision historique et historique', timeline: 'Chronologie des décisions', tools: 'Outils d’analyse', details: 'Détails de l’actif',
    score: 'Score du facteur', coverage: 'Couverture des données', limitations: 'Limites et invalidation', notAdvice: 'Lecture analytique, pas un conseil en investissement personnalisé.',
    live: 'Direct de la source', delayed: 'Différé', cached: 'En cache', stale: 'Données anciennes', current: 'Disponible',
    compliant: 'Conforme', non_compliant: 'Non conforme', needs_review: 'À vérifier',
    readingNote: 'Lecture du moteur pour l’horizon sélectionné, fondée sur les preuves ci-dessous. Vérifiez la couverture et la fraîcheur des données avant toute décision.',
    insufficientNote: 'Les preuves actuelles ne permettent pas une lecture directionnelle fiable. Aucune recommandation ni valeur de remplacement n’est inventée.',
    partial: 'Données partielles', sourceTime: 'Date de la source',
  },
} as const;

export const DASHBOARD_ENUMS = {
  ar: {
    direction: { BULLISH: 'صاعد', BEARISH: 'هابط', NEUTRAL: 'محايد', MIXED: 'متباين', UNAVAILABLE: 'غير محسوم' },
    recommendation: { BUY: 'شراء', SELL: 'بيع', WAIT: 'انتظار', INSUFFICIENT_DATA: 'بيانات غير كافية' },
    risk: { LOW: 'منخفضة', MEDIUM: 'متوسطة', HIGH: 'مرتفعة', VERY_HIGH: 'مرتفعة جداً', UNAVAILABLE: 'غير متاح' },
    factors: { TECHNICAL: 'التحليل الفني', FUNDAMENTAL: 'التحليل الأساسي', MACRO: 'التحليل الكلي', SENTIMENT: 'مؤشرات المعنويات', NEWS: 'الأخبار', MOMENTUM: 'الزخم', LIQUIDITY: 'السيولة', VOLATILITY: 'التذبذب', RISK: 'المخاطر', SHARIA: 'الحالة الشرعية' },
  },
  en: {
    direction: { BULLISH: 'Bullish', BEARISH: 'Bearish', NEUTRAL: 'Neutral', MIXED: 'Mixed', UNAVAILABLE: 'Undetermined' },
    recommendation: { BUY: 'Buy', SELL: 'Sell', WAIT: 'Wait', INSUFFICIENT_DATA: 'Insufficient data' },
    risk: { LOW: 'Low', MEDIUM: 'Medium', HIGH: 'High', VERY_HIGH: 'Very high', UNAVAILABLE: 'Unavailable' },
    factors: { TECHNICAL: 'Technical analysis', FUNDAMENTAL: 'Fundamental analysis', MACRO: 'Macro analysis', SENTIMENT: 'Sentiment indicators', NEWS: 'News', MOMENTUM: 'Momentum', LIQUIDITY: 'Liquidity', VOLATILITY: 'Volatility', RISK: 'Risk', SHARIA: 'Sharia status' },
  },
  fr: {
    direction: { BULLISH: 'Haussier', BEARISH: 'Baissier', NEUTRAL: 'Neutre', MIXED: 'Mitigé', UNAVAILABLE: 'Indéterminé' },
    recommendation: { BUY: 'Acheter', SELL: 'Vendre', WAIT: 'Attendre', INSUFFICIENT_DATA: 'Données insuffisantes' },
    risk: { LOW: 'Faible', MEDIUM: 'Moyen', HIGH: 'Élevé', VERY_HIGH: 'Très élevé', UNAVAILABLE: 'Indisponible' },
    factors: { TECHNICAL: 'Analyse technique', FUNDAMENTAL: 'Analyse fondamentale', MACRO: 'Analyse macro', SENTIMENT: 'Indicateurs de sentiment', NEWS: 'Actualités', MOMENTUM: 'Dynamique', LIQUIDITY: 'Liquidité', VOLATILITY: 'Volatilité', RISK: 'Risque', SHARIA: 'Statut charia' },
  },
} satisfies Record<'ar' | 'en' | 'fr', { direction: Record<DirectionalBias, string>; recommendation: Record<IntelligenceRecommendation, string>; risk: Record<IntelligenceRisk, string>; factors: Record<IntelligenceFactorKey, string> }>;

export const DASHBOARD_EVIDENCE_LABELS: Record<'ar' | 'en' | 'fr', Record<string, string>> = {
  ar: { rsi14: 'مؤشر القوة النسبية RSI', price_vs_sma20: 'السعر مقابل متوسط 20', sma20_vs_sma50: 'متوسط 20 مقابل 50', change_5_period: 'تغير 5 فترات', change_20_period: 'تغير 20 فترة', annualized_volatility: 'التذبذب السنوي', recent_volume_ratio: 'نسبة حجم التداول', earnings_per_share: 'ربحية السهم', revenue_growth: 'نمو الإيرادات', earnings_growth: 'نمو الأرباح', debt_to_equity: 'الدين إلى حقوق الملكية', price_earnings_ratio: 'مضاعف الربحية', positive_sentiment_percent: 'نسبة المعنويات الإيجابية', negative_sentiment_percent: 'نسبة المعنويات السلبية', sentiment_sample_size: 'حجم العينة', macro_event_count: 'الأحداث الاقتصادية', next_macro_event: 'الحدث القادم', macro_observation_sofr: 'الفائدة الفعلية SOFR', macro_observation_effr: 'الفائدة الفعلية EFFR', macro_observation_cpi_yoy: 'التضخم السنوي CPI', macro_observation_core_cpi_yoy: 'التضخم الأساسي السنوي', macro_observation_gdp_growth: 'نمو الناتج المحلي', macro_observation_cpi: 'التضخم CPI', macro_observation_unemployment: 'البطالة', macro_observation_gdp: 'الناتج المحلي GDP', reported_risk_level: 'المخاطر المبلغ عنها', volatility_risk: 'مخاطر التذبذب' },
  en: { rsi14: 'Relative strength index RSI', price_vs_sma20: 'Price vs SMA 20', sma20_vs_sma50: 'SMA 20 vs SMA 50', change_5_period: '5-period change', change_20_period: '20-period change', annualized_volatility: 'Annualized volatility', recent_volume_ratio: 'Volume ratio', earnings_per_share: 'Earnings per share', revenue_growth: 'Revenue growth', earnings_growth: 'Earnings growth', debt_to_equity: 'Debt to equity', price_earnings_ratio: 'Price/earnings ratio', positive_sentiment_percent: 'Positive sentiment share', negative_sentiment_percent: 'Negative sentiment share', sentiment_sample_size: 'Sample size', macro_event_count: 'Economic events', next_macro_event: 'Next event', macro_observation_sofr: 'Effective rate SOFR', macro_observation_effr: 'Effective rate EFFR', macro_observation_cpi_yoy: 'CPI annual inflation', macro_observation_core_cpi_yoy: 'Core CPI annual inflation', macro_observation_gdp_growth: 'GDP growth', macro_observation_cpi: 'Inflation CPI', macro_observation_unemployment: 'Unemployment', macro_observation_gdp: 'GDP', reported_risk_level: 'Reported risk', volatility_risk: 'Volatility risk' },
  fr: { rsi14: 'Indice de force relative RSI', price_vs_sma20: 'Prix vs MM 20', sma20_vs_sma50: 'MM 20 vs MM 50', change_5_period: 'Variation sur 5 périodes', change_20_period: 'Variation sur 20 périodes', annualized_volatility: 'Volatilité annualisée', recent_volume_ratio: 'Ratio de volume', earnings_per_share: 'Bénéfice par action', revenue_growth: 'Croissance du chiffre d’affaires', earnings_growth: 'Croissance des bénéfices', debt_to_equity: 'Dette sur fonds propres', price_earnings_ratio: 'Ratio cours/bénéfice', positive_sentiment_percent: 'Part du sentiment positif', negative_sentiment_percent: 'Part du sentiment négatif', sentiment_sample_size: 'Taille de l’échantillon', macro_event_count: 'Événements économiques', next_macro_event: 'Prochain événement', macro_observation_sofr: 'Taux effectif SOFR', macro_observation_effr: 'Taux effectif EFFR', macro_observation_cpi_yoy: 'Inflation annuelle IPC', macro_observation_core_cpi_yoy: 'Inflation annuelle sous-jacente', macro_observation_gdp_growth: 'Croissance du PIB', macro_observation_cpi: 'Inflation IPC', macro_observation_unemployment: 'Chômage', macro_observation_gdp: 'PIB', reported_risk_level: 'Risque déclaré', volatility_risk: 'Risque de volatilité' },
};
