import type { EbookCategory, EbookLanguage, EbookLocale } from '@/data/ebooks';

export type FilterId = 'all' | EbookCategory | EbookLanguage;

export const UI_COPY: Record<EbookLocale, Record<string, string>> = {
  ar: {
    eyebrow: 'مكتبة تعليمية رقمية',
    title: 'كتب إلكترونية',
    heroTitle: 'مكتبة الكتب الإلكترونية',
    subtitle: 'مكتبة تعليمية تضم أدلة عملية في إدارة الأموال، التداول، ودراسة الجدوى.',
    searchPlaceholder: 'ابحث عن كتاب أو موضوع',
    searchLabel: 'البحث في الكتب الإلكترونية',
    all: 'الكل',
    booksCount: 'عدد الكتب',
    languagesCount: 'عدد اللغات',
    categoriesCount: 'عدد التصنيفات',
    latestAddition: 'أحدث إضافة',
    featuredBook: 'الكتاب المقترح',
    featuredReason: 'مناسب لمستخدمي صفحة تحليلات السوق والتداول.',
    allBooks: 'جميع الكتب',
    browseByCategory: 'تصفح حسب التصنيف',
    readingPath: 'مسار قراءة مقترح',
    readBook: 'قراءة الكتاب',
    downloadPdf: 'تحميل PDF',
    viewDetails: 'عرض التفاصيل',
    fileType: 'PDF',
    fileSize: 'حجم الملف',
    pages: 'صفحة',
    pageCount: 'عدد الصفحات',
    detailsTitle: 'تفاصيل الكتاب',
    whatYouWillLearn: 'ماذا ستتعلم؟',
    close: 'إغلاق',
    topics: 'الموضوعات',
    language: 'اللغة',
    category: 'التصنيف',
    emptyTitle: 'لا توجد كتب مطابقة لبحثك.',
    emptyBody: 'جرّب تغيير كلمات البحث أو الفلتر المحدد.',
    readingStepOne: 'ابدأ بكتاب المدخرات والاستثمار لبناء أساس مالي واضح.',
    readingStepTwo: 'ثم اقرأ قراءة شموع الأسهم وتحليلها لفهم حركة السعر ضمن سياق تداول منضبط.',
    readingStepThree: 'بعد ذلك اقرأ دراسة الجدوى: دليل عملي إذا كنت تخطط لمشروع أو قرار استثماري.',
    disclaimerTitle: 'تنبيه تعليمي',
    disclaimerBody: 'هذه الكتب لأغراض تعليمية وتثقيفية، ولا تُعد توصية مالية أو استثمارية.',
    relatedBooks: 'كتب مرتبطة',
    openReader: 'فتح القارئ',
    newest: 'إضافة حديثة',
    noPages: 'عدد الصفحات غير متاح',
  },
  en: {
    eyebrow: 'Digital education library',
    title: 'E-Books',
    heroTitle: 'E-Books Library',
    subtitle: 'An educational library with practical guides for personal finance, trading, and feasibility studies.',
    searchPlaceholder: 'Search for a book or topic',
    searchLabel: 'Search e-books',
    all: 'All',
    booksCount: 'Books',
    languagesCount: 'Languages',
    categoriesCount: 'Categories',
    latestAddition: 'Latest addition',
    featuredBook: 'Featured book',
    featuredReason: 'Suitable for Market Analysis and trading users.',
    allBooks: 'All books',
    browseByCategory: 'Browse by category',
    readingPath: 'Suggested reading path',
    readBook: 'Read book',
    downloadPdf: 'Download PDF',
    viewDetails: 'View details',
    fileType: 'PDF',
    fileSize: 'File size',
    pages: 'pages',
    pageCount: 'Pages',
    detailsTitle: 'Book details',
    whatYouWillLearn: 'What you will learn',
    close: 'Close',
    topics: 'Topics',
    language: 'Language',
    category: 'Category',
    emptyTitle: 'No books match your search.',
    emptyBody: 'Try changing the search terms or selected filter.',
    readingStepOne: 'Start with Savings and Investment to build a clear financial foundation.',
    readingStepTwo: 'Then read Reading and Analyzing Stock Candlesticks to understand price movement in a disciplined trading context.',
    readingStepThree: 'After that, read Feasibility Study: Practical Guide if you are planning a project or investment decision.',
    disclaimerTitle: 'Educational notice',
    disclaimerBody: 'These books are for educational purposes only and are not financial or investment advice.',
    relatedBooks: 'Related books',
    openReader: 'Open reader',
    newest: 'Recently added',
    noPages: 'Page count unavailable',
  },
  fr: {
    eyebrow: 'Bibliothèque éducative numérique',
    title: 'Livres électroniques',
    heroTitle: 'Bibliothèque de livres électroniques',
    subtitle: 'Une bibliothèque éducative avec des guides pratiques sur les finances personnelles, le trading et les études de faisabilité.',
    searchPlaceholder: 'Rechercher un livre ou un sujet',
    searchLabel: 'Rechercher dans les livres électroniques',
    all: 'Tout',
    booksCount: 'Livres',
    languagesCount: 'Langues',
    categoriesCount: 'Catégories',
    latestAddition: 'Dernier ajout',
    featuredBook: 'Livre recommandé',
    featuredReason: 'Adapté aux utilisateurs des analyses de marché et du trading.',
    allBooks: 'Tous les livres',
    browseByCategory: 'Parcourir par catégorie',
    readingPath: 'Parcours de lecture suggéré',
    readBook: 'Lire le livre',
    downloadPdf: 'Télécharger le PDF',
    viewDetails: 'Voir les détails',
    fileType: 'PDF',
    fileSize: 'Taille du fichier',
    pages: 'pages',
    pageCount: 'Pages',
    detailsTitle: 'Détails du livre',
    whatYouWillLearn: 'Ce que vous apprendrez',
    close: 'Fermer',
    topics: 'Sujets',
    language: 'Langue',
    category: 'Catégorie',
    emptyTitle: 'Aucun livre ne correspond à votre recherche.',
    emptyBody: 'Essayez de modifier les mots-clés ou le filtre sélectionné.',
    readingStepOne: 'Commencez par Épargne et investissement pour bâtir une base financière claire.',
    readingStepTwo: 'Lisez ensuite Lire et analyser les chandeliers des actions pour comprendre le mouvement des prix dans un cadre de trading discipliné.',
    readingStepThree: 'Lisez ensuite Étude de faisabilité : guide pratique si vous préparez un projet ou une décision d’investissement.',
    disclaimerTitle: 'Avis éducatif',
    disclaimerBody: 'Ces livres sont fournis à des fins éducatives et ne constituent pas un conseil financier ou d’investissement.',
    relatedBooks: 'Livres associés',
    openReader: 'Ouvrir le lecteur',
    newest: 'Ajout récent',
    noPages: 'Nombre de pages indisponible',
  },
};

export const FILTERS: Array<{ id: FilterId; label: Record<EbookLocale, string> }> = [
  { id: 'all', label: { ar: 'الكل', en: 'All', fr: 'Tout' } },
  { id: 'personal-finance', label: { ar: 'إدارة الأموال', en: 'Personal finance', fr: 'Finances personnelles' } },
  { id: 'investment', label: { ar: 'الاستثمار', en: 'Investment', fr: 'Investissement' } },
  { id: 'trading', label: { ar: 'التداول', en: 'Trading', fr: 'Trading' } },
  { id: 'feasibility', label: { ar: 'دراسة الجدوى', en: 'Feasibility studies', fr: 'Études de faisabilité' } },
  { id: 'ar', label: { ar: 'العربية', en: 'Arabic', fr: 'Arabe' } },
  { id: 'en', label: { ar: 'الإنجليزية', en: 'English', fr: 'Anglais' } },
  { id: 'fr', label: { ar: 'الفرنسية', en: 'French', fr: 'Français' } },
  { id: 'multilingual', label: { ar: 'متعدد اللغات', en: 'Multilingual', fr: 'Multilingue' } },
];
