export function PremiumLoginStyles() {
  return <style jsx global>{`
    .login-shell{--auth-page-background:var(--hero-gradient);--auth-page-grid:none;--auth-showcase-background:var(--hero-gradient);--auth-showcase-decoration:none;--auth-preview-background:color-mix(in srgb,var(--surface) 28%,transparent);--auth-allocation-chart:var(--accent);--auth-form-background:var(--surface-elevated);--auth-action-background:var(--primary);--auth-chart-accent:var(--accent);--auth-chart-fade:transparent;--auth-showcase-foreground:var(--hero-foreground);--auth-showcase-muted:var(--hero-foreground-muted);min-height:100dvh;padding:28px;isolation:isolate;background:var(--auth-page-background)}
    .login-shell:after{content:"";position:fixed;inset:0;z-index:-1;pointer-events:none;background:var(--auth-page-grid);background-size:44px 44px;opacity:.62}
    .login-stage{width:min(1500px,100%);grid-template-columns:minmax(0,3fr) minmax(390px,2fr);gap:28px;min-height:min(880px,calc(100dvh - 56px));align-items:stretch}
    [dir="rtl"] .login-stage{grid-template-columns:minmax(390px,2fr) minmax(0,3fr)}
    .login-showcase{min-height:0;padding:38px;border-radius:var(--radius-panel);border:1px solid color-mix(in srgb,var(--info) 44%,transparent);background:var(--auth-showcase-background);box-shadow:var(--shadow-lg);align-content:space-between;gap:22px}
    .login-showcase:before{background:var(--auth-showcase-decoration)}
    .showcase-brand{gap:15px}.showcase-brand img{width:72px;height:72px;border-radius:var(--radius-panel);box-shadow:var(--shadow-md)}
    .showcase-brand>div{display:grid;gap:3px}.showcase-brand strong{font-size:25px;letter-spacing:.04em}.showcase-brand span{font-size:15px;color:var(--accent)}
    .showcase-copy{gap:9px;max-width:700px}.showcase-copy h2{font-size:clamp(38px,4vw,67px);font-weight:600;letter-spacing:-.035em}.showcase-copy p{font-size:clamp(15px,1.25vw,19px);line-height:1.75;max-width:690px}.preview-label{font-size:11px;color:var(--auth-showcase-muted)}
    .showcase-dashboard{display:grid;grid-template-columns:minmax(0,1.7fr) minmax(220px,.9fr);grid-template-rows:1fr auto;gap:14px;min-width:0}
    .showcase-dashboard>section,.preview-metrics article{border:1px solid color-mix(in srgb,var(--info) 28%,transparent);background:var(--auth-preview-background);box-shadow:var(--shadow-sm);border-radius:var(--radius-panel)}
    .preview-chart-card{grid-row:1/3;padding:22px;min-width:0}.preview-card-heading{display:flex;justify-content:space-between;align-items:center;color:var(--auth-showcase-foreground)}.preview-card-heading strong{font-size:17px}.preview-card-heading span{color:var(--accent);border:1px solid color-mix(in srgb,var(--accent) 30%,transparent);border-radius:var(--radius-control);padding:4px 8px;background:color-mix(in srgb,var(--accent) 8%,transparent)}
    .preview-chart-card svg{width:100%;height:auto;margin-top:17px;overflow:visible}.chart-grid{fill:none;stroke:color-mix(in srgb,var(--info) 16%,transparent);stroke-dasharray:4 5}.chart-fill{fill:url(#sfmChartFill)}.chart-line{fill:none;stroke:var(--auth-chart-accent);stroke-width:5;stroke-linecap:round}
    .allocation-card{padding:18px;display:flex;align-items:center;gap:16px;color:var(--auth-showcase-foreground)}.allocation-card>div:last-child{display:grid;gap:6px}.allocation-card span{font-size:12px;color:var(--auth-showcase-muted)}
    .allocation-ring{flex:0 0 100px;aspect-ratio:1;border:16px solid var(--auth-allocation-chart);border-inline-end-color:var(--primary-2);border-radius:var(--radius-circle);display:grid;place-items:center;background:var(--surface-secondary);box-shadow:var(--shadow-md)}.allocation-ring span{font-size:19px;font-weight:600;color:var(--auth-showcase-foreground)}
    .preview-metrics{display:grid;gap:9px}.preview-metrics article{padding:11px 13px;display:grid;grid-template-columns:1fr auto;align-items:center;gap:3px 9px}.preview-metrics article>span{display:flex;align-items:center;gap:7px;font-size:11px;color:var(--auth-showcase-muted)}.preview-metrics article>span svg{color:var(--auth-chart-accent)}.preview-metrics strong{font-size:18px;color:var(--auth-showcase-foreground)}.preview-metrics small{grid-column:2;color:var(--success);font-size:10px}
    .showcase-benefits{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));border:1px solid color-mix(in srgb,var(--info) 24%,transparent);border-radius:var(--radius-panel);background:color-mix(in srgb,var(--surface) 38%,transparent);padding:17px 8px}.showcase-benefits article{display:flex;align-items:center;justify-content:center;gap:9px;padding:4px 12px;color:var(--auth-showcase-foreground);border-inline-end:1px solid color-mix(in srgb,var(--info) 18%,transparent)}.showcase-benefits article:last-child{border-inline-end:0}.showcase-benefits svg{color:var(--accent);flex:0 0 auto}.showcase-benefits div{display:grid;gap:2px}.showcase-benefits strong{font-size:12px}.showcase-benefits span{font-size:9px;line-height:1.4;color:var(--auth-showcase-muted)}
    .login-card{min-height:0;padding:30px clamp(25px,3vw,48px);gap:16px;justify-content:center;border-radius:var(--radius-panel);border:1px solid color-mix(in srgb,var(--info) 32%,var(--border));background:var(--auth-form-background);box-shadow:var(--shadow-lg);overflow:auto}
    .language-row{justify-content:space-between;align-items:center;margin-bottom:3px}.language-row>*{min-height:44px}.language-row .sfm-language-trigger{border-color:color-mix(in srgb,var(--primary) 24%,var(--border));background:color-mix(in srgb,var(--surface) 86%,var(--primary-soft));box-shadow:var(--shadow-sm)}
    .brand{gap:6px}.brand .mark{width:78px;height:78px;border-radius:var(--radius-panel);box-shadow:var(--shadow-md)}.brand h1{font-size:29px;font-weight:600;margin-top:8px}.brand p{font-size:13px;max-width:400px;line-height:1.65}
    .form{gap:13px}.auth-label{font-size:12px;font-weight:600}.auth-field input,.auth-field select{height:52px;border-radius:var(--radius-card);border-color:color-mix(in srgb,var(--primary) 25%,var(--border));background:color-mix(in srgb,var(--control-background) 92%,var(--primary-soft));padding-inline:15px;font-size:14px}.auth-field input:hover,.auth-field select:hover{border-color:color-mix(in srgb,var(--primary) 44%,var(--border))}.auth-field input:focus-visible,.auth-field select:focus-visible,.eye-btn:focus-visible,.link-btn:focus-visible,.social-btn:focus-visible,.submit-btn:focus-visible,.guest-action:focus-visible{outline:3px solid color-mix(in srgb,var(--focus-ring) 42%,transparent);outline-offset:2px}
    .login-inline-options{display:flex;align-items:center;justify-content:space-between;gap:14px;min-height:30px}.remember-row{display:flex;align-items:center;gap:8px;font-size:12px;color:var(--foreground-secondary);cursor:pointer}.remember-row input{inline-size:18px;block-size:18px;accent-color:var(--primary)}.login-inline-options .link-btn{font-size:12px}
    .submit-btn{height:54px;border:0;border-radius:var(--radius-card);background:var(--auth-action-background);box-shadow:var(--shadow-md);font-size:16px;color:var(--primary-foreground)}.submit-btn:hover:not(:disabled){opacity:1;filter:brightness(1.06);transform:translateY(-1px)}
    .social-divider span{font-size:11px}.social-btn{height:48px;border-radius:var(--radius-card);background:color-mix(in srgb,var(--surface) 92%,var(--primary-soft))}.google-btn svg{color:var(--foreground)}.guest-action{height:48px;display:flex;align-items:center;justify-content:center;gap:8px;border:1px solid color-mix(in srgb,var(--primary) 28%,var(--border));border-radius:var(--radius-card);background:transparent;color:var(--foreground);font:600 13px/1.4 var(--font-ui);cursor:pointer}.guest-action:hover:not(:disabled){background:var(--primary-soft)}
    .account-action{display:flex;align-items:center;justify-content:center;gap:8px;color:var(--foreground-muted);font-size:12px}.account-action .link-btn{font-weight:600}.actions{gap:7px 14px}.actions .guest-btn{border:1px solid var(--border);border-radius:var(--radius-control);padding:9px 13px}
    .auth-msg{min-height:42px;display:flex;align-items:center;border-radius:var(--radius-card)}.eye-btn{min-width:40px;min-height:40px;justify-content:center}.password-wrap input:-webkit-autofill,.auth-field input:-webkit-autofill{-webkit-text-fill-color:var(--foreground);box-shadow:var(--autofill-background-shadow)}
    @media(max-width:1180px){.login-stage,[dir="rtl"] .login-stage{grid-template-columns:minmax(0,1.35fr) minmax(370px,1fr)}.login-showcase{padding:28px}.showcase-benefits{grid-template-columns:1fr 1fr}.showcase-benefits article:nth-child(2){border-inline-end:0}.showcase-dashboard{grid-template-columns:1fr}.preview-chart-card{grid-row:auto}.allocation-card{display:none}.preview-metrics{grid-template-columns:repeat(3,1fr)}.preview-metrics article{display:grid;grid-template-columns:1fr}.preview-metrics small{grid-column:auto}}
    @media(max-width:900px){.login-shell{padding:18px}.login-stage,[dir="rtl"] .login-stage{grid-template-columns:1fr;max-width:680px;min-height:auto}.login-card,[dir="rtl"] .login-card{grid-column:1;grid-row:1}.login-showcase,[dir="rtl"] .login-showcase{display:grid;grid-column:1;grid-row:2;min-height:auto}.showcase-dashboard{display:none}.showcase-copy h2{font-size:34px}.showcase-benefits{grid-template-columns:repeat(4,minmax(0,1fr))}.showcase-benefits span{display:none}}
    @media(max-width:520px){.login-shell{padding:max(10px,env(safe-area-inset-top)) 10px max(14px,env(safe-area-inset-bottom));display:block}.login-stage,[dir="rtl"] .login-stage{margin:0;display:grid;gap:12px}.login-card{padding:18px 16px;border-radius:var(--radius-panel);gap:14px}.brand .mark{width:68px;height:68px}.brand h1{font-size:25px}.brand p{font-size:12px}.login-showcase{padding:20px;border-radius:var(--radius-panel);gap:16px}.showcase-brand img{width:54px;height:54px;border-radius:var(--radius-card)}.showcase-brand strong{font-size:20px}.showcase-copy h2{font-size:28px}.showcase-copy p{font-size:13px}.showcase-benefits{grid-template-columns:1fr 1fr;padding:12px 6px}.showcase-benefits article{justify-content:flex-start;padding:8px;border:0}.showcase-benefits strong{font-size:11px}.login-inline-options{align-items:flex-start}.auth-field input,.auth-field select{height:50px}.pref-row{grid-template-columns:1fr}.login-card.wide{max-width:none}}
    @media(max-width:340px){.login-shell{padding-inline:6px}.login-card{padding-inline:12px}.login-inline-options{flex-direction:column;gap:6px}.showcase-benefits{grid-template-columns:1fr}}
    @media(prefers-reduced-motion:reduce){.login-shell *{scroll-behavior:auto;animation-duration:.01ms;animation-iteration-count:1;transition-duration:.01ms}}
  `}</style>;
}
